### ISSUE TITLE
[取號報號][三合院] 請將alert改成popup

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1004]
[Scenario]
1. 客人取號/人數&電話沒有輸入完整/取號
2. alert跳出/客人按確定/alert消失
3. 客人再次執行步驟1.
4. alert跳出/客人勾選"防止此網頁跳出其他對話方塊"/客人按確定/alert消失

[Result] 一旦客人勾選後，alert再也不會跳出
[Expected Result] 我們要自己做一個popup提醒

![image](https://cloud.githubusercontent.com/assets/22789907/20509754/e5f9a708-b0a5-11e6-9e03-94fd339b5456.png)

**Comment by cyen1121** [comment]
bn store已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1585.12
[Result] Fixed
