### ISSUE TITLE
[取號報號][三合院] 建議輸入欄位focus時，該欄位就出現back icon

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1005]
1. 輸入中的欄位，顯示back icon (另一欄位就不出現)
2. 是避免有客人將enter位置當成back，順手按下去，就直接取號了

![image](https://cloud.githubusercontent.com/assets/22789907/20509904/2bb9a29c-b0a7-11e6-98d7-1f4b7de4ccb4.png)

**Comment by cyen1121** [comment]
bn store已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1585.12
[Result] Fixed
