### ISSUE TITLE
[取號報號][三合院] 請將取號密碼紀錄在local storage裡(店家取號機重開機後，可以直接進入取號畫面，不用再輸入密碼了)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1006]
[Scenario]
1. 店家第一次使用取號機/輸入取號密碼1****6/進入取號畫面
2. 店家將取號機關機，隔日再開機=>開機成功後可以直達取號畫面，不用再輸入密碼

**Comment by cyen1121** [comment]
已在bn store都修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1585.12
[Result] Fixed

[註] 還沒有完全關機完成，就急著再開機，則容易遇到"需要重新輸入密碼"的情形(但此情形店內人員可以在開店前就先重新輸入密碼)
