### ISSUE TITLE
[新版商店介面]編輯商品後，退出商店再重新進入，則商品沒有被load進來

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1007]
[Scenario]
1. 店主選一個至少有2個tag的商品/編輯/建立=>此時可以看到商品的位置改變&有邊框highlight
2. 退出商店再重新進入=>剛剛編輯的商品不見了
3. 再退出商店再重新進入=>還是不見
4. 點選至商品的另一tag=>商品出現了

**Comment by cmacma7** [comment]
fix in 1559.2
problem caused by cached item array fetch to wrong place (in the array), so cause problem.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1565
[Result] Fixed
