### ISSUE TITLE
操作 scan FB or Tagfans sync在FB留言後，容易發生頁面中"商品重複出現"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1009]
[Scenario]
1. 客人到FB社團下單
2. 老闆scan FB(不管有沒有成立訂單)/點左上"關閉"
3. 返回"推薦商品"的頁面，就可以看到商品重複出現

![image](https://cloud.githubusercontent.com/assets/22789907/20511767/e06744e8-b0b5-11e6-99b1-cd36d2dbafe3.png)
　　　

![image](https://cloud.githubusercontent.com/assets/22789907/20511772/e5573404-b0b5-11e6-853e-629457f1022b.png)

**Comment by cmacma7** [comment]
fix in 1559.2
problem caused by cached item array fetch to wrong place (in the array), so cause problem.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed
