### ISSUE TITLE
還沒有在tagfans登入過的FB帳號，無法直接發佈商品至Facebook

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1010]
[Scenario]
1. 店主的FB帳號，還沒有完成tagfans授權
2. 店主已建立新版店面 & 也另開分頁在FB登入(且已經是某社團的管理員)
3. 店主直接將商品範例發佈到FB

[Result]
1. popup"請確認你的FB是登入狀態"
2. 將FB重新登出再登入/店面重整/再次發布商品範例到FB=>仍跳出popup

**Comment by peichingliao** [comment]
r.1623、1624 已修正，bn已更新

複製步驟
0. Tagfans登出
1. 把FB>設定>應用程式>bn移除
2. 用FB登入Tagfans(僅登入)，授權使用
3. 登出Tagfans
4. 用Email登入Tagfans
5. 按發佈文章到Facebook，授權Facebook帳號
6. 授權完成，畫面重新載入 ---> 設定的帳號變成FB帳號

**Comment by peichingliao** [comment]
store已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed

---

[Scenario]
1. tagfans登出；把FB>設定>應用程式>store.tagfans.com移除
2. 用FB登入Tagfans(僅登入)，授權使用　　　
3. 登出Tagfans
4. 用Email登入Tagfans
5. 按發佈文章到Facebook，授權Facebook帳號
![image](https://cloud.githubusercontent.com/assets/22789907/21638123/e43e7e4a-d2a4-11e6-9f5d-8494836dbf9f.png)　![image](https://cloud.githubusercontent.com/assets/22789907/21638130/ed6adcac-d2a4-11e6-8747-394f98bbd7d7.png)　![image](https://cloud.githubusercontent.com/assets/22789907/21638136/f8e8fb7c-d2a4-11e6-8d75-75757299c40a.png)

6. 授權完成，畫面重新載入 ---> 回到email帳號的商店首頁，並可正常往下操作"發佈到FB"功能
