### ISSUE TITLE
新版商店架構-全店商品搜尋

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1011]
目前僅能搜尋單一類別或頁面的商品。

但在新架構頁面，使用者比較需要的其實是，直接搜尋全店商品。

**Comment by cmacma7** [comment]
Need to search in server side instead of client side because client side is load the products on demand for the speed issue.

**Comment by cmacma7** [comment]
enabled.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed
