### ISSUE TITLE
email登入Tagfans的用戶，第一次授權FB，會被系統誤認為是 FB登入Tagfans

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1012]
重現方法:
1.  Email登入Tagfans, 建好商店後。
2. 登出改用自己的FB帳號登入Tagfans。
3. 登出改回email登入Tagfans
4. 執行PO文到FB的功能，出現要求授權的程序，都按同意後，系統自動跳回Tagfans。此時此email帳號，被系統認為已經登出，自動以FB帳號登入。
    在此狀態下，使用者無法以店主身分操作該店。
5. 必須登出，再以email 登入，即可恢復正常，FB PO文程序。

**Comment by peichingliao** [comment]
node/facebook/publish_managedgroup 需特殊處理

**Comment by cmacma7** [comment]
Hi Peiching, please use the following two line to authenticate.
{
myLocalStorage.urlBeforeLogin = location.href;
window.location.href = '/node/facebook/publish_managedgroup';
}
then the problem should be fixed.

**Comment by peichingliao** [comment]
r.1623、1624 已修正，bn已更新

複製步驟
0. Tagfans登出
1. 把FB>設定>應用程式>bn移除
2. 用FB登入Tagfans(僅登入)，授權使用
3. 登出Tagfans
4. 用Email登入Tagfans
5. 按發佈文章到Facebook，授權Facebook帳號
6. 授權完成，畫面重新載入 ---> 設定的帳號變成FB帳號

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
---
　　　
[Scenario]
　
　0. Tagfans登出
1. 把FB>設定>應用程式>bn移除
2. 用FB登入Tagfans(僅登入)，授權使用
3. 登出Tagfans
4. 用Email登入Tagfans
5. 按發佈文章到Facebook，授權Facebook帳號
6. 授權完成，畫面重新載入
--->再點一次發布文章到facebook，就可以發布了

![image](https://cloud.githubusercontent.com/assets/22789907/20873231/6a868614-bae0-11e6-801b-11eb23aca3d8.png)

**Comment by peichingliao** [comment]
store已更新

**Comment by Iris926** [comment]
同 #1010 驗證步驟，Fixed.
