### ISSUE TITLE
[新版商店架構][分類列表] 不曾編輯過的分類列表，直接新增一個全新的tag，則畫面卡住

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1013]
[Scenario]
1. 商店的"分類列表"完全沒有編輯過
2. 編輯分類列表/新增一個還沒有列入auto complete的tag/建立

[Result] 畫面卡在"deploy"
![image](https://cloud.githubusercontent.com/assets/22789907/20549033/947cd102-b163-11e6-8bc3-fa1c5f871805.png)

**Comment by cmacma7** [comment]
fixed in version 1560.
problem caused by empty list. the N tag in list is empty, so we need to check the tags string is not empty and not "[]"

**Comment by Iris926** [comment]
[修改後發現的新問題]
1. 將所有分類列表裡的tag全部刪光/建立=>卡在deploy畫面(fixed)
2. 輸入含有" 的tag，將不會成功加入auto complete

**Comment by cmacma7** [comment]
fixed by accept " char as part of tag.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[修改後發現的新問題] 
1. 輸入含有" 的tag，會直接成功加入auto complete
2. 直接輸入含有" 的全新tag，到右側MENU裡點擊該tag，無作用

[Expected Result] 這個tag完全沒有被使用過，應顯示"沒有找到任何項目"的訊息

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1625.6
[Result] Fixed
