### ISSUE TITLE
[新版商店介面] 建議在左上MENU增加一個"商店首頁"的項目

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1014]
[客戶反應的真實情形]
1. 很多新客人是點選商品連結，直接進入某一商品頁的
2. 此時的新客人對於介面並不熟悉，可能會想要回首頁，但又還不清楚其實首頁就是"推薦商品"
3. 左上or右上MENU都沒有跟"首頁"相關的字眼出現，新客人在各頁面&各tag之間切換，若一不小心點回tagfans首頁，可能就忘記剛剛自己進到哪個商店
4. 客人必須重新回到一開始點的商品連結，再點一次

[建議] 在左上MENU的第一項，新增"商店首頁"：客人點了"商店首頁"，看到"推薦商品"，就會明白"首頁=推薦商品"

**Comment by cmacma7** [comment]
add 商店首頁 in left menu.
version 1585.11 and after.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1625
[Result] Fixed

---
[註]
1. "此店主頁"擺放的位置，暫不改動
2. "此店主頁"的行為，要改成固定顯示；當客人已經在此店主頁的時候，"此店主頁"就變灰色
3. "此店主頁"未來將開放讓店主自己設定成某個tag，不再寫死成"推薦商品"
4. "所有商品"這個詞目前有點爭議，因為不是每個店家都會放"商品"，也有資訊型的店家會進駐(ex.非凡大探索)
