### ISSUE TITLE
[統計總表] 老闆修改單一商品狀態，客人端沒有同步

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1017]
[Scenario]
1. 老闆跟客人都在統計總表
2. 老闆修改單一商品狀態

[Result] 客人端沒有同步

[註]
1. 客人若在訂單頁面，則單一商品狀態可同步
2. 訂單狀態可同步(both 訂單頁面&統計總表)

**Comment by cyen1121** [comment]
已修正上bn store

**Comment by cyen1121** [comment]
已修正上bn

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
---
