### ISSUE TITLE
[限量商品] 當下單數量大於庫存數量，則popup文案應調整

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1018]
[Scenario]
1. 庫存剩3，下單4
![image](https://cloud.githubusercontent.com/assets/22789907/20586171/7fb47ef8-b23c-11e6-9b76-f4a108cf71de.png)
　　　
2. 按"立即購買"

[Result] popup文案"商品已售完"
![image](https://cloud.githubusercontent.com/assets/22789907/20586175/909d9844-b23c-11e6-805a-1c44303bfa7b.png)

[建議]
1. 庫存數量=0，客人下單購買時，顯示"商品已售完"
2. 0<庫存數量<客人下單量，顯示"商品數量不足"

**Comment by cyen1121** [comment]
bn已修正

文字調整成商品數量不足

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed
