### ISSUE TITLE
[scan FB] 商品品項有#，則客人在FB下單後，老闆scan FB，會辨識失敗

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1020]
[Scenario]
1. 老闆刊登商品，商品品項有#(ex. ＃120)
2. 客人到FB下單，ex. 粉＃120+1
3. 老闆 scan FB

[Result] 辨識失敗
![image](https://cloud.githubusercontent.com/assets/22789907/20588265/c6d65380-b24e-11e6-919b-5b53561a5cf3.png)

**Comment by cmacma7** [comment]
fixed in version 1649. bug caused by ~!@#$%^& are note treat as word.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
