### ISSUE TITLE
[店內點餐][銅盤] 行動點餐時，填寫桌號改成點選桌號

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#1021]
涓豆腐反映服務生在填寫桌號時，容易產生錯誤。
因此希望改成用選取的方式（例如：選取口味的模式）

**Comment by gameflierHao** [comment]
Revision: 1568
Author: zhanghaowu
Date: 2016年11月24日 下午 12:30:46
Message:
新增取得店內座位表功能

POSMenu.getTableInfos
----
Modified : /nodejs/bn/POS/pos_porting.js
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by huangVic** [comment]
UI 選擇桌號的資料來源由此項目而來 
 #1029

**Comment by Iris926** [comment]
11/29 已驗證無誤。

1. 行動點餐時，可點選桌號
2. 若該桌號沒開桌，則popup"尚未開桌"
