### ISSUE TITLE
[統計總表]老闆在統計總表時有新進訂單，則新進訂單的時間排序應為 新->舊

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1023]
[Test Site] bn
[Scenario]
1. 老闆在統計總表
2. 有>1 的新進訂單/老闆點畫面上方的信封
3. 新進訂單直接匯入統計總表，時間排序為 舊->新
![image](https://cloud.githubusercontent.com/assets/22789907/20593967/509952d2-b26f-11e6-8f62-e5debc5f6370.png)
　　　
4. 退出統計總表，重新點"收件訂單"，再進一次統計總表，時間排序為 新->舊
![image](https://cloud.githubusercontent.com/assets/22789907/20593983/61551c8c-b26f-11e6-9f98-8bb8e9a2d906.png)

**Comment by cmacma7** [comment]
Problem caused by item push in old to new, so we reverse it again.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1806.2
[Result] Fixed
