### ISSUE TITLE
[店內點餐][銅盤] 行動點餐時，需要紀錄是哪台裝置點的

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#1025]
目前點餐時 POS會紀錄點餐人員都是 TAGFANS
未來需要加入點餐APP設定

**Comment by gameflierHao** [comment]
Revision: 1574
Author: zhanghaowu
Date: 2016年11月25日 上午 11:39:30
Message:
[店內點餐][銅盤] 行動點餐時，需要紀錄是哪台裝置點的

可由點餐APP新增SENDER
----
Modified : /nodejs/bn/POS/pos_porting.js
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by Iris926** [comment]
11/29 已驗證無誤：點餐系統/設定/已新增"點單人員"欄位，且可傳送至POS
![image](https://cloud.githubusercontent.com/assets/22789907/20700250/2a2fbc86-b647-11e6-97ae-0812c2bb8853.png)
