### ISSUE TITLE
[新版商店介面]複製widget並貼上/新增一個全新的widget，應直接帶入現在位置的tag(且會刪掉原有的tag)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1026]
[Scenario]
1. 老闆將舊店轉換成新店
2-1. 老闆從舊店page裡/複製一個widget/到新店底下選一個tag/貼上複製的widget
2-2. 老闆到新店底下選一個tag/新增一個widget
2-3. 老闆到新店底下複製一個widget/選一個tag/貼上複製的widget

[Expected Result] 直接帶入現在位置的tag，並刪除原有的tag

**Comment by cmacma7** [comment]
To move products from old platform to new platform, just choose the template style to product page template, then in the new product page, enter each old page, then edit each widget and apply a new tag to it. There is no need to copy and paste templates.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1649.3
[Result] Fixed

[新問題] 在不同tag下，編輯同一商品，則tag也會依目前所處的tag做更動
[Expected Result] 編輯時，應顯示商品原先被設定好的tag，不需依當前tag來做更動
