### ISSUE TITLE
[訂單頁面][統計總表] 老闆刪除訂單，客人端的訂單沒有被刪除

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1027]
[Scenario]
1. 老闆刪除訂單A
2. 客人點管理/清除瀏覽資料並重新載入/查看 我的訂單 =>訂單A還在(NG)
3. 客人登出再登入/查看 我的訂單=>訂單A還在(NG)

[Result] 客人端的訂單應與老闆同步

**Comment by cmacma7** [comment]
By design when store owner delete the order, the customer side should still see the order.
That is the customer must have a valid history, and cannot be modified by the store owner.
