### ISSUE TITLE
編輯已隱藏widget，則widget狀態會自動變成"未隱藏"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1030]
[Scenario]
1. 團媽/餐廳老闆編輯一個已隱藏的widget/建立

[Result] 該widget變成"未隱藏"
[Expected Result] 編輯已隱藏的widget，不應影響原隱藏狀態

**Comment by cmacma7** [comment]
I think if you edit, means open.... there is no need to modify a hidden widget. The one click less.
If she want to hide, then just click hide again.

**Comment by Iris926** [comment]
團媽的想法可能是這樣：
隱藏的範本widget，因為某些原因需要修改，但仍希望這個範本widget維持隱藏狀態
