### ISSUE TITLE
[搜尋] 搜尋後未清除關鍵字，關閉搜尋功能後再打開，關鍵字為空卻出現清空文字的btn

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1031]
[Test Site] store
[Version] v1.1.1570.8
[Scenario]
1. 進入任一商店/點 搜尋/輸入搜尋關鍵字/完成輸入/ENTER =>顯示搜尋結果
2. 點左側的X，關閉搜尋功能
![image](https://cloud.githubusercontent.com/assets/22789907/20642236/70e28c6c-b444-11e6-8680-ffaaa96f8cec.png)
　
　　　
3. 再點一次搜尋，叫出輸入關鍵字欄位

[Result] 輸入關鍵字欄位為空，但右側卻出現清空文字的X
![image](https://cloud.githubusercontent.com/assets/22789907/20642227/48ef64f0-b444-11e6-92a5-e34fbf4c72de.png)

**Comment by cmacma7** [comment]
Fix in store/debug 1585.7
problem caused by timeOut is set to 10ms, but input onchange happen before the toggleStoryBoardSearch happen. So we set search delay to 500ms, and the search will be cancelled within 500ms.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1625
[Scenario] 搜尋後未清除關鍵字/點search bar旁邊的取消/點右上icon再叫出search bar
[Result] 搜尋文字已經清空了，但還是可以看到"清空文字的X"
