### ISSUE TITLE
[新版商店介面][搜尋] 從搜尋結果點開小版商品變大版，並關閉搜尋欄位，則右上購物袋icon消失

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1032]
[Test Site] store
[Version] v1.1.1583.1
[Scenario]
1. 進入商店(須為新版介面)
2. 在推薦商品 or 任一tag下/點開搜尋欄位/輸入搜尋關鍵字/完成搜尋
3. 從搜尋結果裡點開小版商品變大版/將上方搜尋欄位按XX/畫面自動返回 推薦商品

[Result] 右上購物袋icon消失

**Comment by cmacma7** [comment]
fixed on 1585.5 bn and store/debug.
Problem cause by not show #joinPageMenu. Always show if EC mode.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1585.6
[Result] Fixed
