### ISSUE TITLE
[新版商店介面][新增商品] 若點擊分類列表裡的tag(第二層)，則新增商品時自動抓取的tag名稱有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1034]
[Test Site] store/debug
[Version] v1.1.1583.1
[Scenario]
1. 至新版商店，點右上購物袋icon
2. 在商品分類裡，點擊任一tag(ex. 附圖中的"配件")
![image](https://cloud.githubusercontent.com/assets/22789907/20649714/889e7dc2-b500-11e6-855b-9cf3757da252.png)
　　　
3. 在此tag下新增商品，查看自動生成的tag =>tag名稱為"配件"
![image](https://cloud.githubusercontent.com/assets/22789907/20649749/28c98f30-b501-11e6-8f3d-276701686e53.png)
　　　

4. 在步驟2中，點擊分類列表裡的tag(ex. 附圖中的"配件"---屬於"寶寶衣飾"底下的"配件")
![image](https://cloud.githubusercontent.com/assets/22789907/20649731/d6ead0f2-b500-11e6-917c-99b91014d379.png)
　　　
5. 在此tag下新增商品，查看自動生成的tag =>tag名稱為"寶寶衣飾_$配件"(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/20649743/0b8d1356-b501-11e6-9a62-8cf05e534761.png)

**Comment by cmacma7** [comment]
solved in version 1585 on both store and bn.
problem caused by AA_$BB should be parsed to AA,BB.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1585
[Result] Fixed
