### ISSUE TITLE
[新版商店介面][搜尋] 建議保留左上&右上的功能icon

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1035]
[Test Site] store/debug
[Version] v1.1.1585.6
[Scenario]
1. 在任一tag下，點標題的"搜尋"，叫出搜尋bar
2. 點擊任一商品，展開成大版，並叫出搜尋bar

[Expected Result] 建議將左上 & 右上的功能icon都保留

**Comment by cmacma7** [comment]
Fixed by hide search bar in fullscreen mode.
Fixed at version 1585.11 and after on bn and store.tagfans.com/debug

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed(目前已修改成最新版UI)

[客人]
![image](https://cloud.githubusercontent.com/assets/22789907/20788870/605e0b4e-b7ed-11e6-9495-15134ad3f47e.png)
　　　
[老闆]
![image](https://cloud.githubusercontent.com/assets/22789907/20788982/c268f358-b7ed-11e6-8291-8ac5ba79e348.png)
