### ISSUE TITLE
[統計總表] 批次修改訂單狀態，造成訂單總表關鍵字搜尋的tag消失

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1038]
[Scenario]
1. 進入統計總表/點右上"管理"/輸入關鍵字、進行訂單總表關鍵字搜尋
![image](https://cloud.githubusercontent.com/assets/22789907/20657741/368d432e-b573-11e6-9c70-3d73efca68cf.png)
　　　
2. 點擊任一欄位，進行篩選
![image](https://cloud.githubusercontent.com/assets/22789907/20657748/4c5410e8-b573-11e6-94da-fbf5a3204e4b.png)
　　　
3. 點選左上的批次修改訂單狀態 or 點開訂單修改單一商品狀態 or 修改任一訂單狀態
![image](https://cloud.githubusercontent.com/assets/22789907/20657759/5de1bc84-b573-11e6-8a57-473ea6c85b20.png)
　　　
[Result] 訂單總表關鍵字搜尋"上衣"消失了
![image](https://cloud.githubusercontent.com/assets/22789907/20657767/774050aa-b573-11e6-8310-d7c4354fabf0.png)

**Comment by cyen1121** [comment]
bn已修正，並且點選上方清除條件會清除全部的搜尋和過濾

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
