### ISSUE TITLE
新版商店架構-左邊menu，增加商店首頁功能

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1039]
使用者習慣上，隨時會有想回商店首頁的功能。
action: 在左邊menu，加上首頁項目==>跳到推薦商品，或是商品分類表的第一項。

**Comment by cmacma7** [comment]
added at version 1585.11 at store/debug and bn

**Comment by kevinyu75** [comment]
在bn或store/debug裡面，都沒看到這個首頁項目耶。已經清除瀏覽資料再載入過了。

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.1
[Result] Fixed
---

以下記錄今天LINE上面的討論：
1. "此店主頁"擺放的位置，暫不改動
2. "此店主頁"的行為，要改成固定顯示；當客人已經在此店主頁的時候，"此店主頁"就變灰色
3. "此店主頁"未來將開放讓店主自己設定成某個tag，不再寫死成"推薦商品"
4. "所有商品"這個詞目前有點爭議，因為不是每個店家都會放"商品"，也有資訊型的店家會進駐(ex.非凡大探索)
