### ISSUE TITLE
增加狀態改變的時間記錄欄位。

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1040]
取代POS的第一步，讓取貨點在收現金時，早晚班可以有依據進行交接。
舉例: 交接時，早班撈取特定時間段內被改變狀態的訂單，並結算現金。
(此功能為福利批發社所提出之需求，後續此用戶可協助轉介更多團媽)

**Comment by cyen1121** [comment]
bn已經加入此功能
只要在統計選日期下方選擇用訂單狀態改變日期查詢就可以查詢

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
