### ISSUE TITLE
[信用卡] 未完成信用卡付款，回到商品頁(顯示剛剛成立的訂單紀錄)，應該也要顯示"付款去"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1043]
[Scenario]
1. 至商品頁下單/成立訂單/付款去
![image](https://cloud.githubusercontent.com/assets/22789907/20698272/e34eecf8-b63a-11e6-9d6e-170867193f33.png)
　　　
2. 在popup點"信用卡付款"/點"取消"
![image](https://cloud.githubusercontent.com/assets/22789907/20698284/f8726b64-b63a-11e6-8b29-87b59145497e.png)
　　　
3. 會顯示大版訂單 & 有"付款去"的btn
![image](https://cloud.githubusercontent.com/assets/22789907/20698299/130190d6-b63b-11e6-9e76-082d04f9171b.png)
　　　
4. 點左上"瀏覽更多"/再次點進剛剛購買的商品頁 =>也應該要顯示"付款去"btn
![image](https://cloud.githubusercontent.com/assets/22789907/20698314/2dfec5de-b63b-11e6-8ae1-e5c135280136.png)

**Comment by peichingliao** [comment]
r.1600已修正, bn & store已上

**Comment by Iris926** [comment]
[Test Site] store
[Result] Fixed
