### ISSUE TITLE
[信用卡][重複綁定卡號] 建議可以跳出popup提醒，是否需要刪除同一卡號的舊有紀錄

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1044]
[Scenario]
1. 信用卡付款紀錄中，已有4筆重複綁定的卡號了(只有最新的第4筆才被認為是有效卡號)
![image](https://cloud.githubusercontent.com/assets/22789907/20698371/99b768d0-b63b-11e6-9660-bf54ba42788d.png)
　　　
2. 至商品頁下單購買/成立訂單/付款去
3. 在popup點"信用卡付款"/選歷史紀錄的卡號(選1/2/3都可以，不要選最新那一筆)
4. 確認付款(信用卡授權中只轉一下下)/顯示大版訂單&信用卡授權中btn
![image](https://cloud.githubusercontent.com/assets/22789907/20698409/d3cc97a2-b63b-11e6-9603-978022ad5e22.png)
　　　
[Expected Result] 在客人輸入重複卡號時，跳出popup來提醒客人，是否要刪除同一卡號的舊有紀錄

**Comment by cylee405** [comment]
在新增信用卡成功之後去檢查舊卡的狀態
無效卡的卡號會變成灰色
選到無效卡會顯示已失效
![image](https://cloud.githubusercontent.com/assets/23648277/21167307/a1daec56-c1e6-11e6-99d5-77d3d15411b9.png)

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1788.2
[Result] Fixed
