### ISSUE TITLE
[新版商店介面][建立商店] 選了範例想回上一步，找不到地方可以回去

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1047]
[Scenario]
1. 商店街/建立商店/快速建立/團購批發
2. 選 第一項快速開店(建議使用)
3. 想返回上一步，但找不到地方可以點

[註] 其實點開左上MENU，點tagfans icon就可以回去上一步，只是對使用者來說不夠直覺
![image](https://cloud.githubusercontent.com/assets/22789907/20703153/a792c2dc-b655-11e6-881e-7cdbceffb60d.png)

**Comment by cmacma7** [comment]
fixed by change to back button. version 1607.7 in store/debug

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1625
[Result] Fixed(點開左上三條線MENU後，可以看到back icon)

![image](https://cloud.githubusercontent.com/assets/22789907/20875511/4a73f26a-baf6-11e6-8eac-4d4b0e497a34.png)
