### ISSUE TITLE
成立訂單回覆留言方式，建議將"統一回復於文章最下方"的規則寫出來

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1054]
[Scenario]
1. 老闆第一次scan FB =>會看到"成立訂單回覆留言方式"的popup
![image](https://cloud.githubusercontent.com/assets/22789907/20785550/bbb58e98-b7db-11e6-846e-50da451c051c.png)
　　　
[Expected Result] 建議將"每10筆訂單留言一次"的規則寫出來

**Comment by peichingliao** [comment]
r.1675 已更新
store 已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
![image](https://cloud.githubusercontent.com/assets/22789907/21450217/a1b4a460-c92f-11e6-9121-ae158fbb5e64.png)
