### ISSUE TITLE
[統計總表][李小姐] 點擊任一欄位做篩選，再批次修改訂單狀態，則最下面一列的內容會跑位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1055]
[Scenario]
1. 老闆進入統計總表後，先篩選出需要整理的訂單
2. 點擊任一欄位來做篩選
3. 批次修改訂單狀態

[Result] 最下面一列的文字跑位：包含貨品狀態、訂單狀態、數量、金額
![image](https://cloud.githubusercontent.com/assets/22789907/20786661/45cdae5c-b7e2-11e6-8b69-30976a905fed.png)

**Comment by Iris926** [comment]
123

**Comment by cyen1121** [comment]
bn fixed.
調整欄位的檢查要設置在計算總價的地方

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
