### ISSUE TITLE
[分享]點進商品頁，直接複製網址列的網址分享出去，應可以直接打開商品頁

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1056]
[Scenario]
1. 舊版店面的商品，直接複製網址列---可以直接進入商品頁
http://store.tagfans.com/#page_join?o=4115&id=22403&viewType=station&fullscreen=1117505

2. 新版店面的商品，直接複製網址列---只能進到該tag下(NG)
http://store.tagfans.com/#page_join?o=3842&tag=%E7%94%9F%E6%B4%BB%E9%9B%9C%E8%B2%A8_%24%E6%94%B6%E7%B4%8D&viewType=station&mode=ec&fullscreen=1038779

3. 新/舊版店面，點了商品single URL後，再複製網址列的網址---看到小版商品，但無法點進去(NG)
http://store.tagfans.com/index.html?noteId=1173517&_stationId=x&_storeId=4378#page_join?fullscreen=1173517

http://store.tagfans.com/index.html?noteId=1118000&_stationId=22403&_storeId=4115#page_join?fullscreen=1118000
![image](https://cloud.githubusercontent.com/assets/22789907/20820112/cad7aa6c-b873-11e6-970a-6465278570e0.png)

**Comment by cmacma7** [comment]
cannot reproduce

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1788.2
[Result] Fixed

---

fullscreen 相關問題：
#913 
#1117
