### ISSUE TITLE
[訂單狀態] 在訂單狀態裡，編輯"狀態期限(天)"，建議修改訂單裡顯示的wording

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1063]
[Scenario]
1. 老闆編輯商品/點開訂單狀態 A /輸入"狀態期限(天)"的天數
2. 客人下單/老闆將此訂單狀態改成 A 

[Result] 訂單裡會看到 "取貨/狀態 期限 : 2016/12/3 上午10:13:22"
![image](https://cloud.githubusercontent.com/assets/22789907/20823646/fbe16892-b890-11e6-9fec-69f85aa9adf8.png)

[建議] 此項目的標題可以讓店主修改，以符合不同訂單狀態的描述

**Comment by cyen1121** [comment]
此為狀態時限
時間到了會自動將狀態設定為過期，因而關閉填寫欄位等相關資訊
