### ISSUE TITLE
[統計總表] 貨品狀態/訂單狀態 點了要可以編輯；filter功能放在下拉選單裡

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1065]
[Scenario]
1. 老闆進入訂單總表

![image](https://cloud.githubusercontent.com/assets/22789907/20827701/9e2cc2aa-b8ae-11e6-86b1-35fa4ab7d953.png)
　　　
[需求]
1. 紫色框：下拉狀態來過濾訂單(已OK)
2. 紅色/黃色框：點了之後就可以直接編輯狀態
3. 綠色框：該欄位可以直接移除

**Comment by cyen1121** [comment]
已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed
