### ISSUE TITLE
[總計總表] 請加上"訂單備註"的欄位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1066]
[Scenario]
1. 老闆進入訂單總表

[需求]
1. 訂單總表的最右側，加上"訂單備註"的欄位
2. 點擊訂單號碼，展開訂單，可以有欄位編輯"訂單備註"
3. 只有老闆可以看到，客人看不到

**Comment by cyen1121** [comment]
bn上已加入

限制字數英文45字長

**Comment by Iris926** [comment]
[Test Site] bn
[Scenario]
1. 進入訂單總表/點擊任一訂單號碼/開啟大版訂單
2. 在"管理者備註"欄位，編輯文字
![image](https://cloud.githubusercontent.com/assets/22789907/20910170/d0704e5a-bb9a-11e6-97b9-ecda2bca3176.png)

[建議]
1. 在大版訂單裡的"管理者備註"，字體可以縮小
2. 在大版訂單裡要輸入文字，建議要可以自動換行，不然輸入文字後都會被遮住，無法完整顯示
3. 在訂單總表哩，建議也要自動換行，不然"管理者備註"的欄位會被一直撐寬，過多的文字也會被遮住，無法完整顯示

---

[已完成] 訂單總表裡，點擊管理者備註的欄位，一樣有篩選功能

**Comment by cyen1121** [comment]
bn修正

由原先的input tag改成textarea

並且在檢查的時候會去除換行的文字，避免造成文字輸入過度複雜

**Comment by Iris926** [comment]
[Test Site] bn
[Scenario] 進入統計總表/點訂單號碼叫出大版訂單/編輯管理者備註/完成輸入
[Result] 統計總表的管理者備註欄位，會重複顯示出多個內容(重整頁面後，就只顯示一次)
[Expected Result] 一筆訂單顯示一次管理者備註的內容
![image](https://cloud.githubusercontent.com/assets/22789907/21132751/9d2b1f32-c150-11e6-9dbe-15560a9597b6.png)

**Comment by cyen1121** [comment]
bn已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
