### ISSUE TITLE
[新版商店介面] 點擊任一tag，可以在標題看到該tag下有多少商品數量

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1067]
[Scenario]
1. 老闆/客人，點擊任一tag

[需求] 可以在標題列看到該tag下有多少數量
![image](https://cloud.githubusercontent.com/assets/22789907/20828599/46b6976c-b8b3-11e6-8938-9ec665951005.png)
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/20828623/62507c72-b8b3-11e6-9290-5f90ba3bb6dd.png)

**Comment by cmacma7** [comment]
added in store/debug version 1607.4

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1625
[Result] 老闆若有隱藏商品時，客人端看到的商品數量應該要扣除

**Comment by cmacma7** [comment]
fixed by reduce the hidden widget in the counting.

**Comment by Iris926** [comment]
[Test Site] stor/debug
[Version] v1.1.1625.6
[Result] Fixed
