### ISSUE TITLE
[VIP價格] 編輯商品品項時，將category name清空，會造成VIP價格錯誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1072]
[Scenario]
1. 新增一個VIP價格商品
2. 將category name清空/編輯品項中的VIP價格
![image](https://cloud.githubusercontent.com/assets/22789907/20841284/39b5d22c-b8ee-11e6-926d-1ade73898cdc.png)
　　　
3. 對應的VIP客人查看此商品

[Result] 原設定好的VIP價格，會錯植到其他品項去
![image](https://cloud.githubusercontent.com/assets/22789907/20841362/7cab9d28-b8ee-11e6-8d2d-789eddef61e3.png)

**Comment by cyen1121** [comment]
bn fixed 

因category為空所以造成判斷上排列往前了

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
