### ISSUE TITLE
[VIP價格][規格組合] 編輯商品品項時，將category name清空，老闆端會看到某部分品項變成售完

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1080]
[refer to] #1072 
[Test Site] bn
[Scenario]
1. 老闆新增/編輯 VIP規格組合 的商品
2. 將某一商品品項的category name清空/建立

[Result]
1. 客人端查看此商品，品項&價格都正確(OK)
2. 老闆端查看此商品 =>發現很多商品品項都被自動改成"售完"(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/20875387/4e83897a-baf5-11e6-9b15-619cdf72ddb4.png)
　　　

[註] 商品連結 http://bn.tagfans.com/node/fb.html?noteId=15305_x_351

**Comment by peichingliao** [comment]
r.1362已修正, bn已更新

**Comment by peichingliao** [comment]
r.1632已修正, bn已更新

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
