### ISSUE TITLE
[入店審核] 將widget 分享連結裡的店號拿掉，無須審核就可以成功進入查看

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1081]
[Test Site] store
[Version] v1.1.1625
[Scenario]
1. 進入店號 1923 =>需要店主審核
2. http://store.tagfans.com/node/fb.html?noteId=489367_12612_1923 將此網址最後面的 _1923 去除

[Result] 可以成功進入該widget

**Comment by peichingliao** [comment]
請把後面那一串"489367_12612_1923"改hash

**Comment by cmacma7** [comment]
But, if you get into 489367_12612, without the store ID... then you cannot put the order to the store.
This means we got a useless note, and any operation on it will be no result.
