### ISSUE TITLE
[取號報號][三合院] 老闆網路斷線後恢復連線，要可以收到取號單；取號機網路斷線時，要可以取號成功

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1084]
[老闆/取號機 網路連線都正常]
1. 客人取號成功
2-1. 老闆在大版訂單頁面，點擊紅色信封，可成功載入該筆取號紀錄
2-2. 老闆在訂位總表頁面，點擊紅色信封，可成功載入該筆取號紀錄

---

[老闆網路斷線/取號機網路連線正常]
1. 客人取號成功
2. 老闆停留在大版訂單頁面，網路恢復連線 =>10秒內會收到紅色信封，但是按了無作用(NG)
3. 老闆退出後再重新進入 =>取號單已成功載入
　　　
1. 客人取號成功
2. 老闆停留在訂位總表頁面，網路恢復連線 =>10秒內會收到紅色信封，但是按了無作用(NG)
3. 老闆退出後再重新進入 =>取號單已成功載入，但是紅色信封還在(NG)

---

[老闆網路正常/取號機斷線]
1. 客人取號 =>會看到"已斷線"的訊息 (NG)
2. 取號機恢復連線 =>會看到"取號失敗"的popup (NG)

---

[Expected Result]
1. 不管網路是否正常連線，客人都要可以取號成功
*網路斷線時，需要依照當前號碼繼續往下計數
*網路斷線時，客人取號成功，背景會繼續往伺服器送單
2. 老闆停留在 大版訂單/訂位總表 頁面，恢復網路連線後，都要可以接收新訂單
*新訂單會以紅色信封的方式顯示在頁面上方
*點擊紅色信封要可以成功載入新訂單(且點擊後紅色信封要消失)

**Comment by cyen1121** [comment]
bn已修正
每個60秒會重新送單，或是下一位使用者點選完成時也會傳送整個列表

**Comment by Iris926** [comment]
[Test Site] bn
[發現新問題] 
1. 老闆在收件訂單(or統計總表)，收到新訂單(上方有紅色信封)
2. 不要點開紅色信封
3. 網路斷線
4. 客人持續取號
5. 老闆恢復連線，離開當前畫面，再重新進入收件訂單(or統計總表)

[Result] 上方的紅色信封還在

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.2115
[Result] Fixed
