### ISSUE TITLE
[統計總表] 建議加上"訂單狀態更新的時間" 的欄位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1088]
請協助加上一個欄位，紀錄"訂單狀態更新的時間"

1. 老闆/客人都可以看到
2. 最新狀態/最新更新時間 直接蓋掉前一筆紀錄

**Comment by Iris926** [comment]
Note：附上與kevin討論後，建議的MENU排版&wording
![image](https://cloud.githubusercontent.com/assets/22789907/21005152/a42916d0-bd6e-11e6-8947-90cd669102a7.png)

**Comment by Iris926** [comment]
[Test Site] bn
[Scenario]
*大版訂單改訂單狀態
*訂單總表改訂單狀態
*併單前後改訂單狀態
*設定日期區間，過濾 下訂時間/狀態更動時間

[註] 單頁訂單顯示筆數 拉進"設定"裡面

**Comment by cyen1121** [comment]
已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed
