### ISSUE TITLE
未登入狀態，進入店家後按"消費紀錄"並嘗試以FB登入，則畫面會一直呈現loading狀態

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1089]
[Scenario]
1. FB登出、tagfans登出
2. 到任何一個店家/消費紀錄 =>畫面下方會看到短暫顯示的提示"尚未登入"的訊息
![image](https://cloud.githubusercontent.com/assets/22789907/20919382/7e396d6a-bbd6-11e6-967a-3a14920ec9cb.png)
　　　
3. 點擊該提示訊息/在popup點確定/選擇以FB帳號登入/輸入FB帳密/登入

[Result] 畫面一直轉，無法成功進入tagfans
![image](https://cloud.githubusercontent.com/assets/22789907/20919595/9dcc1988-bbd7-11e6-8d90-0a9177911ed5.png)
　　　

[Expected Result]
1. 以FB帳號登入，應可成功回到店家裡面
2. 未登入狀態，建議畫面下方的提示訊息可以持續顯示，不消失
![image](https://cloud.githubusercontent.com/assets/22789907/20919382/7e396d6a-bbd6-11e6-967a-3a14920ec9cb.png)

**Comment by cmacma7** [comment]
Is this EC mode store only?

**Comment by cmacma7** [comment]
Fixed for both EC mode and normal mode.
1. normal mode cause by we return after location.href=url_before_login, and this return is not correct.
2. EC mode will return to main page of the store from page_personal directly.
Fixed in version 1635

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1635
[Result] Fixed
1. normal mode：登入成功後回到"消費紀錄"頁
2. EC mode：登入成功後回到店家首頁(推薦商品)

---

[發現新問題]
未登入狀態/進店家點消費紀錄/然後點"這是體驗帳號"來登入/在popup點"取消"，會跳出錯誤訊息

![image](https://cloud.githubusercontent.com/assets/22789907/20993677/d4799d8e-bd26-11e6-9e45-2d0beb079dcc.png)
