### ISSUE TITLE
[iOS] 瀏覽商品時，限時商品倒數時間的"秒"會跑版

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1090]
[Device] iPhone5
![image](https://cloud.githubusercontent.com/assets/22789907/20956277/df04abde-bc83-11e6-94a7-df145b681c88.png)

**Comment by cyen1121** [comment]
已修正上bn調整兼具與字型大小

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
---

App
![image](https://cloud.githubusercontent.com/assets/22789907/23778325/9526945c-0574-11e7-8b16-eeb2f4187c58.png)


Safari
![image](https://cloud.githubusercontent.com/assets/22789907/23778336/9fcb7026-0574-11e7-8ae4-598536d58b45.png)


Chrome
![image](https://cloud.githubusercontent.com/assets/22789907/23778344/a7c547c0-0574-11e7-8b80-bc9c6c4808c1.png)
