### ISSUE TITLE
當訂單狀態為"請匯款"，客人填寫個人資訊後，應可記錄下來，下次可以不用再填一次

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1091]
[Scenario]
1. 老闆將訂單A狀態改成"請匯款"
2. 客人至我的訂單，進行填寫
3. 老闆將訂單B狀態改成"請匯款"
4. 客人至我的訂單，進行填寫

[Expected Result] 應記錄姓名、電話、地址...等基本資料，客人就不用每次都要輸入

**Comment by cyen1121** [comment]
姓名(title)和信箱(email)無法做修改
在updateMyInfo會刪除這兩項資訊

**Comment by Iris926** [comment]
[Test Site] bn
[Result] 目前無法記錄電話與地址
