### ISSUE TITLE
[Scan FB] 第一層規格&第二層規格有相同的字出現時，容易造成scan誤判

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1092]
[Scenario]
1. 商品網址 http://store.tagfans.com/node/fb.html?noteId=1209391_15842_221
2. 客人在FB留言"小鹿 小"
3. 老闆scan FB

[Result] 會被誤判成"小鹿 大"

**Comment by cmacma7** [comment]
Try fix in version 1649 at store.tagfans.com/debug

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1649.6
[Result] Fixed

---

1. 當品項設定為兩層規格中，只有一個重複的地方
款式: **小**鹿 / 玫瑰花 / 五色彩點
尺寸: 大(58*39*23cm)、**小**(55*36*31cm)

　客人喊單 "小鹿 小"=>scan FB 正確

---

2. 當品項設定為兩層規格中，有兩個重複的地方
款式: **小**鹿 / **大**象 / 五色彩點
尺寸: **大**(58*39*23cm)、**小**(55*36*31cm)

　客人喊單 "小鹿 大" or "大象 小" 會辨識失敗，需要帶上數量
　ex. 小鹿 大*1、大象 小+2
