### ISSUE TITLE
[限量商品] 商品售完後，在商品頁直接F5重整，會看到品項數量又重新開啟(但是下單又會看到"商品數量不足")

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1094]
1. 商品網址 http://store.tagfans.com/node/fb.html?noteId=1210741_15842_221

2. 客人看到品項都顯示"售完"，按F5重整畫面，會看到錯誤訊息
![image](https://cloud.githubusercontent.com/assets/22789907/20962026/91dd32d0-bca2-11e6-9887-a62158ec9588.png)

3. 在錯誤訊息點"確定"，則會發現商品品項數量重置
![image](https://cloud.githubusercontent.com/assets/22789907/20962094/e0e8aada-bca2-11e6-9a51-06fa68cbde73.png)

4. 在數量已經重置的品項下單，卻又看到"商品數量不足"的訊息(然後該品項會重新變成售完)

**Comment by cyen1121** [comment]
bn已修正
因為大版還沒展開前找不到obj造成錯誤

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
