### ISSUE TITLE
[權哥]串連上下游~自動併單，拋單叫貨、自動對上游下單，自動更改下游貨品狀態為"已訂貨"

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1096]
MRS 內容編輯中

**Comment by VanessaHsu** [comment]
1. 下游商店自動併單 : 客戶、收件人地址、收件人電話、收件人地址、拋單(叫貨)者SID
2. 併單後，拋單(叫貨)者逐筆確認=> 寄發給不同廠商(store id)
   *終端售價不跟著拋單送出。
3. 寄發後，系統需確認限時、限量、VIP價錢、店號。
4. 自動下單: 
    *只針對可以下單的商品拋單叫貨。
    *警示: 提示不成功下單的項目數量。
    *下單成功，自動改變貨品狀態為"已訂貨"。
