### ISSUE TITLE
[新版商店介面] "消費紀錄"旁不應顯示商品數量的圓圈 & 返回tag瀏覽商品時，商品數量應可正常顯示

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1102]
[Scenario]
1. 進入店家瀏覽商品 =>tag旁都有一個圓圈會顯示商品數量
![image](https://cloud.githubusercontent.com/assets/22789907/20994847/00bc8120-bd2e-11e6-9079-cad5edede160.png)
　　　
2. 從左上MENU點進消費紀錄 =>消費紀錄旁有一個沒數字的圓圈(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/20994816/cd29cb38-bd2d-11e6-944b-6d1cc44928f1.png)
　　　
3. 點左上back回到剛剛的tag頁 =>tag旁的圓圈，數字也不見了(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/20994830/dff38948-bd2d-11e6-84a1-8acceb745526.png)

**Comment by cmacma7** [comment]
fix in version 1.1.1636.1. 
Caused by not check page==join_page in enhanceHeader.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1636.1
[Result] Fixed
