### ISSUE TITLE
精簡版商品上架 Widget優化與修正

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1104]
已與佩晴口頭討論，
精簡版過於精簡，需要把訂單狀態內的必要項目放上去。

**Comment by peichingliao** [comment]
r.1674 已修正
bn, store皆已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
1. 一般商品範本，建立新項目時，需要"分類標題" & "項目標題" 都可以新增出來
![image](https://cloud.githubusercontent.com/assets/22789907/21449948/554fb148-c92d-11e6-963e-79f44056ebf7.png)

2. 進階設定裡的 訂單狀態設定，預設的訂單狀態裡，需要有"插入表單"的功能(目的是希望每個訂單狀態點開，所擁有的功能都一致)

**Comment by peichingliao** [comment]
r.1745 已修正
bn已更新

1. 分開成 "建立新項目" & "建立新分類" 兩個按鈕
2. 已將表單復原

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
