### ISSUE TITLE
[Scan FB] 若點選上方的"再掃描一次"，則"回覆留言內容"的設定會跑掉

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1106]
[Test Site] bn
[Scenario]
1. 老闆 scan FB/點右上MENU選"推文回覆設定"
2. 在"回覆留言內容"選"自訂格式"，並輸入文字
3. 成功成立訂單，也正確以自訂格式回文

4. 老闆再次進入scan FB/點右上MENU選"推文回覆設定"
5. 在"回覆留言內容"，清除自訂格式的文字，並點選"預設格式"
6. 成功成立訂單，也正確以自動格式回文
7. 在畫面上方點"再掃描一次"/成功成立訂單

[Result] 以"自訂格式"回文

**Comment by peichingliao** [comment]
r.1654 已修正。
bn已更新，待測試

**Comment by peichingliao** [comment]
r.1659 已修正。
bn已更新，待測試

**Comment by peichingliao** [comment]
r.1675 已修正
store已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
