### ISSUE TITLE
[建店] 未登入狀態，進入建店流程，登入成功後，會被導到SAMPLE商店裡

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1110]
[Scenario]
1. 客人沒有登入tagfans
2. 點"我要開店"/快速建立/團購批發/快速開店/套用此範例，建立商店
3. 選擇用FB登入/輸入帳密/登入

[Result] 被導到SAMPLE商店去
![image](https://cloud.githubusercontent.com/assets/22789907/21093112/0e839fcc-c08b-11e6-979b-63cdabd7af18.png)
　　　
[Expected Result]
*成功登入後，畫面回到"套用此範例，建立商店"的步驟
*成功登入後，畫面回到tagfans首頁

**Comment by cmacma7** [comment]
fixed in store/debug and bn. 
problem caused by  $.mobile.changePage("#page_station") in ec mode, which take out the sample=true;
fixed by the following
$.mobile.changePage("#page_station", getParameterByName("sample")?{dataUrl:"page_station?sample=true"}:undefined);

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1705.15
[Result] Fixed
