### ISSUE TITLE
[訂單總表] 點選商品標題做篩選，應以對應的widget id 撈出結果，而不要直接用商品標題當字串來撈

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1111]
[Scenario]
1. 老闆進入訂單總表/進行併單
2. 老闆點擊商品標題做篩選

[Result] 發現只能撈出未併單的訂單 or 只撈出已併單的訂單

[root cause] 為了節省資料庫，商品標題過長的，會在併單的時候被截斷部分字

[Expected Result] 當老闆點任一商品標題做篩選時，應以該商品widget id 進行篩選，這樣就不會因為商品標題被截斷，而造成結果錯誤

**Comment by cyen1121** [comment]
已修正上bn和store

已經透過商品的id來做篩選

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] 相同品項，應該被統計在一起：
1. 訂單總表下方的"依商品統計"有錯
![image](https://cloud.githubusercontent.com/assets/22789907/21601869/d6ace1da-d1c9-11e6-9756-a53d662d5205.png)
　　　
2. 管理/依品項統計(OK)
![image](https://cloud.githubusercontent.com/assets/22789907/21601857/b97b2fcc-d1c9-11e6-8bf5-0eeac91b3841.png)

**Comment by cyen1121** [comment]
bn已修正可以驗證了

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
