### ISSUE TITLE
[李味鎂]使用bookmark來切換不同店面，造成瀏覽商品時店名錯誤，店主代客下訂單時，訂單也會錯植到其他店面

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1115]
[Scenario]
1. 老闆開了兩家店/分別將AB兩店加到browser bookmark
2. 老闆從bookmark點進A店/再從bookmark點進B店瀏覽商品 =>發現此時title顯示為A店(NG)
3. 在"A店標題+B店商品"的情形下，老闆代客下單買了B店商品 =>發現要到A店"我的訂單"才能查到訂單紀錄，B店完全查不到

**Comment by cmacma7** [comment]
fixed in store/debug 1658.1
cause by page actually not changed, so we force reload if gid != getParameterByName("o")

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
