### ISSUE TITLE
未登入狀態，購買商品並登入，不會直接回到商品頁

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1117]
[Version] v1.1.1637
[Test Site] store
[Scenario] 
1. 客人未登入
2-1. 進首頁/進入一間店/點開商品頁/購買/導至登入頁/選擇以FB or Email 登入
2-2. 點擊single widget URL/購買/導至登入頁/選擇以FB or Email 登入

[Result] 請參考附圖
![image](https://cloud.githubusercontent.com/assets/22789907/21135616/6c6fd6aa-c15d-11e6-98d8-77baf72d78b9.png)
　　　
[Expected Result]
1. 登入後，應回到商品頁，並可正常購買
2. 登入後回到商品頁，點back，應回到商品所處tag(EC mode) or 商品所處page(舊版)

---

[註] related to #913

**Comment by cmacma7** [comment]
fix at store/debug 1705.8. Problem caused by product widget toggle fullscreen mode, and because of the "fullscreen" parameter in the url, cause toggleFullscreen issue back(). Solved by filter out "fullscreen" parameter in the url by replaceState.

**Comment by Iris926** [comment]
[Test Site] bn
[Result]
1. 從商店裡點進一個商品頁/登入=>會回到該商品所在位置
2. 從single widget URL點進商品頁/登入=>會回到商品頁
![image](https://cloud.githubusercontent.com/assets/22789907/21403363/71e97186-c7f7-11e6-8775-0000224c917a.png)

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
