### ISSUE TITLE
[優惠活動widget] 訂單裡，優惠活動的項目，取消"修改貨品狀態"的功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1118]
[Scenario]
1. 老闆刊登 有優惠活動 的widget
2. 客人下單
3. 老闆查看大版訂單/點擊商品品項、優惠活動、運費

[Result]
1. 點擊商品品項名=>可以修改貨品狀態
2. 點擊優惠活動品項名=>可以修改貨品狀態(NG)
3. 點擊運費品項名=>無作用
![image](https://cloud.githubusercontent.com/assets/22789907/21168187/18cc62f8-c1ed-11e6-892a-6c6d33f7ce87.png) ![image](https://cloud.githubusercontent.com/assets/22789907/21168196/2644e662-c1ed-11e6-8ad9-ce539f24a480.png)
　　　

[Expected Result] 點擊優惠活動品項名，應無作用

**Comment by cyen1121** [comment]
item.e.sales_event=true
