### ISSUE TITLE
[優惠活動widget][匯入FB] 商品介紹裡，也需要自動帶入優惠活動的訊息

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1119]
[Scenario]
1. 老闆在系統新增一個 有優惠活動 的widget
2. 發布商品到facebook

[Expected Result] 商品 輸入描述 的欄位，需要自動帶入優惠活動的訊息
![image](https://cloud.githubusercontent.com/assets/22789907/21168929/d1ba58c4-c1f2-11e6-8f7f-0ba4b9c2916c.png)

**Comment by peichingliao** [comment]
r.1673 bn已更新, store已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
