### ISSUE TITLE
[優惠活動widget][scan FB] 客人在FB下單並達成優惠條件，老闆scan FB後也能自動成立正確訂單

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1120]
[Scenario]
1. 老闆在系統新增一個 有優惠活動 的widget
2. 發佈到facebook
3. 客人到FB下單，數量有達到優惠條件
4. 老闆scan FB

[Expected Result] 成立訂單時，也能判定已符合優惠活動，並將該優惠帶入訂單
![image](https://cloud.githubusercontent.com/assets/22789907/21168997/65e4a72a-c1f3-11e6-89b6-6291591e9faa.png)

**Comment by peichingliao** [comment]
r.1678 已修正
bn 已更新, store尚未

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed

**Comment by peichingliao** [comment]
r.1724 預先load優惠模組 for autoSend order
store已更新
