### ISSUE TITLE
[Scan FB] 留言尚未掃描完成 且 留言中包含非訂單留言，直接執行"成立訂單"，則訂單回文不會帶有[Tagfans Easy+]

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1128]
[Scenario]
1. 老闆設定推文為"多次統一回覆"
2. 商品的FB留言中，包含"非下單"留言(辨識失敗) or "已售完"(商品已售完)
3. 老闆點scan FB 後，趁掃描留言的黑圈圈還在轉，展開商品留言並全選，直接按下"成立訂單"
=>此時會看到畫面呈現 訂單剛掃描完就馬上被成立訂單(紅圈圈)

[Result] 查看FB訂單回文，則沒有帶[Tagfans Easy+]
![image](https://cloud.githubusercontent.com/assets/22789907/21294659/f8e526bc-c57c-11e6-8f36-791c06becb49.png)

**Comment by peichingliao** [comment]
1. 沒掃完之前，全選的勾、每個留言後面的勾不會出現
2. 沒掃完之前，成立訂單的按鈕無法按
3. 一開始的讀取中-->改成轉圈圈
4. 掃描完成後會有灰色框提示

r,1699 已修正
bn已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
