### ISSUE TITLE
The widget language can use <TL></TL> inside template instead of using context to carry the language

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#113]
To save bandwidth.

If you have a variable 
_widget_telephone_hint:聯絡電話  in context
you can use
_widget_telephone_hint = <TL>telephone</TL>;
and in <language>   telephone:聯絡電話

Then all the translation goes from context to template, so that widget download and changes will not send all the language words.

**Comment by gameflierHao** [comment]
As title

**Comment by cyen1121** [comment]
fixed
