### ISSUE TITLE
[訂單] 顧客回填資料需記住 姓名、電話、地址 三個欄位資訊

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1130]
團購的 "請匯款"表單
客人填過一次後
下次要再填資訊都沒有帶出來

**Comment by cyen1121** [comment]
姓名(title)和信箱(email)無法做修改
在updateMyInfo會刪除這兩項資訊

**Comment by peichingliao** [comment]
所以收件人姓名可以記嗎@@

**Comment by Iris926** [comment]
[Test Site] bn
[Result] 未成功存入電話、地址

**Comment by VanessaHsu** [comment]
[Test Site] store/debug
[Result]
*自動記憶]僅限帶有以下字眼的欄位:
  姓名/ 電話/ 手機/ 地址
*以下不自動記憶
  名字
