### ISSUE TITLE
[App][高雄Jessica] 建立商品widget時，連續點"建立"多次，應只建立一個商品

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1132]
[Test Site] store
[Scenario]
1. 老闆開啟APP/新增商品
2. 編輯商品/連續點"建立"多次

[Result] 建立出兩筆內容一樣、widget不同的商品
![image](https://cloud.githubusercontent.com/assets/22789907/21355658/d2d100f2-c709-11e6-83f7-2f805a1bdbb7.png)

---

[Note] PC無法複製此問題，目前只有在APP能複製

**Comment by cmacma7** [comment]
fixed by hide the button for 3 second then fadeIn the button.
fix on bn and store/debug.

**Comment by Iris926** [comment]
[Test Site] bn
[App version] BN v1.1.5
[Result] 有相同問題：在App上沒有看到"建立"被隱藏3秒
![image](https://cloud.githubusercontent.com/assets/22789907/21413348/85e16704-c831-11e6-8aad-6288bf322d92.png)

**Comment by cmacma7** [comment]
Hi Iris, I cannot reproduce. The button is hidden.

**Comment by Iris926** [comment]
[Test Site] bn
[App version] iOS/Android BN v1.1.11
[Result] Fixed
