### ISSUE TITLE
[團購]編輯商品時，將"敘述"的欄位拉大，則內文文字會與下方其他欄位重疊

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1133]
[Scenario]
1. 進入商品編輯頁(進階版or簡易版編輯器)
2. 在"敘述"的欄位右下角，調整欄位大小
![image](https://cloud.githubusercontent.com/assets/22789907/21383314/0ccf1ad2-c7a0-11e6-9883-fadf563d1265.png)
　　　

[Result] 將欄位拉大，則下方其他欄位沒有往下推，造成重疊

**Comment by cmacma7** [comment]
This is the behavior of teaxarea, hard to fix right now. So we just let it be for now.
