### ISSUE TITLE
[高雄Jessica]同一browser開啟兩個分頁，分別登入不同帳號，會造成新增商品時，誤判owner身分

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1134]
[Scenario]
1. 先到第一個分頁用A帳號登入(店主)
2. 再到第二個分頁用B帳號登入
3. 回到第一個分頁，複製商品並貼上

[Result] 新增商品的owner為B=>造成A帳號覺得在自己的商店裡，原來的商品可編輯，但新增的商品卻無法再次編輯

**Comment by cmacma7** [comment]
fixed in version 1746. 
fix by use storage event to detect loginMyth cvhange. If change, show popup to allow user to refresh the page.

**Comment by Iris926** [comment]
[Test Site] store/debug
[Version] v1.1.1746.1
[Result] 開啟分頁/進行登入or登出=>其他分頁都會顯示"重整頁面"的提醒，重整後，所有分頁的登入or登出狀態會一致

![image](https://cloud.githubusercontent.com/assets/22789907/21491408/83a07430-cc37-11e6-9ea7-692348d66d6d.png)
