### ISSUE TITLE
Map to do List

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#1139]
Mark definition
1. (action) callback(original info) 
2. (popup) 
3. (ads) need to add favorite star if user add favorite of ads

**Comment by huangVic** [comment]
1. action callback
    - 跟 map 註冊 callback:
      `map_module.subscribe('StoreAction', callback(data) )`  

    - 事件callback
       * 前往商店: 
          `data = { type: 'goToStore', data:  storeData }`

       * 接近商店:
          `data = { type: 'distanceTrigger', data:  storeData }` 
      
       * 收藏優惠卷: 
          `data = { type: 'addToFavorites', data: storeData }`

2. 讓地圖上的店家顯示 popup:  `map_module.openStoreInfo(data)`

     * 顯示店家資訊:
        `data = { type: 'popup',   lat: 123456, lng: 123456 }`  
     * 顯示店家優惠卷:  
        `data = { type: 'coupon' , lat: 123456, lng: 123456,  ........ }`
