### ISSUE TITLE
Need to enable create new items in array of menu order and other widgets.

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#114]
http://bn.tagfans.com/public/jqm.html#page_join?o=247&id=505&viewType=station
as example

**Comment by cmacma7** [comment]
Refer to #97 
Use schema to add the prototype of the array items.
schema.object.appendItems
// appendItems is an array and used by the editor to add items to array. Declare the items you put inside context to form an array here. If user delete all the items in an array, he can only use the create new item button in the editor to create new items. The items you want user to see when he click the create button should list under appendItems. You can have multiple items.

**Comment by cyen1121** [comment]
已修正
