### ISSUE TITLE
[Scan FB] 掃描介面刪除/修改訂單，需要判斷是否為併單

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1145]
併單就不給 刪除/修改，提示老闆先拆單

**Comment by peichingliao** [comment]
r.1802 已更新，bn已更新

**Comment by Iris926** [comment]
[Test Site] bn
[Scenario]
1. 從來沒有併單過的訂單/取消or修改 =>可正確操作
2. 併單/取消or修改 =>popup提示訊息
3. 曾經併過單又回復併單前的訂單/取消or修改 =>可正確操作
