### ISSUE TITLE
FB留言回覆設定

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#1146]
目前訂單回覆留言，已可自行勾選，決定內容。在各項目均為勾選的狀態下，系統仍會推送[Tagfans Easy+]字樣，但後面沒有任何說明。綜合用戶需求回饋，推文方式更改如下:
1. 全部不勾選時，不推送任何內容出去。
2. 勾選任一項時，留言內容前，還是要加上[Tagfans Easy+]

**Comment by peichingliao** [comment]
r.1749

bn已更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed
