### ISSUE TITLE
[widget更新機制] 一個browser新增/隱藏Widget,另一個browser未即時更新

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1147]
[widget更新機制] 一個browser新增/隱藏Widget,另一個browser未即時更新

F5重新整理之後才更新

**Comment by cmacma7** [comment]
in EC this is default behavior, because all product is filter result, not in a "page" that can listen for change.

**Comment by cmacma7** [comment]
Not a bug.
