### ISSUE TITLE
[用戶必須登入] 分享商品single widget URL到LINE，以LINE 直接開啟連結，則直接看到空白商品

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1150]
[Scenario]
1. 商店設定為"用戶必須登入"才能觀看
2. 分享此商品任一商品的網址到LINE
3. 客人從LINE直接點開此網址
http://store.tagfans.com/node/fb.html?noteId=1361866_x_4636
http://store.tagfans.com/node/fb.html?noteId=1118000_22403_4115

[Result] 看到空白商品，沒有任何提示popup
![image](https://cloud.githubusercontent.com/assets/22789907/21569558/d67b2272-cef8-11e6-81f2-8554162bba25.png)
　　　
[備註]
1. 舊版店面&EC 都會發生
2. 同樣的網址分享到messenager再點開，則會跳出提示popup
![image](https://cloud.githubusercontent.com/assets/22789907/21569579/faebc9d6-cef8-11e6-9342-02e5f4187fc0.png)

**Comment by cmacma7** [comment]
Fixed in version 1759, 
Problem caused by FB inApp browser does not allow prompt and alert if that prompt or alert is not trigger by human click.
Change to not using prompt, instead use javascript home-made popup.

**Comment by cmacma7** [comment]
The actually problem is we treat "" wrong, the actual fix is in version 1758.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed(android & iOS 手機都OK)
