### ISSUE TITLE
[管理][更改商店設定][EC] 更改商店設定並儲存，要點回tagfans首頁時，畫面錯亂

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1151]
[Scenario]
1. 進入EC商店/點左上MENU/管理
2. 進入 商店設定/點右上儲存 =>看到"設定已更改+[OK] btn" 的popup閃過去，畫面直接回到EC商店
3. 點左上MENU/點tagfans =>跳回 編輯商店 的畫面
4. 點左上完成 =>回到EC商店
5. 點左上MENU/點tagfans =>在EC商店又重整一次
6. 再點一次左上MENU/點tagfans =>此時才成功回到tagfans首頁

[備註] 
1. 進入舊版商店/設定/更改商店設定/商店設定/儲存 =>會看到"設定已更新"的popup
![image](https://cloud.githubusercontent.com/assets/22789907/21569692/30dc43a8-cefa-11e6-9405-32a87e7854d1.png)
　　　
2. 在popup點OK/再點左上完成 =>畫面回到設定頁，之後的操作也都正常

**Comment by cmacma7** [comment]
1803.1 fixed. 
Problem caused by model_favoriteList is fetched and drawed, cause the EC page in page station reload.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1803.1
[Result] Fixed
