### ISSUE TITLE
[EC][查詢本商品購買紀錄] 離開"查詢本商品購買紀錄"後，title的"商品數量"會變成0

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1152]
[Scenario]
1. 老闆or客人，進入EC商店/點開任一商品，進入商品頁
2. 點"查詢本商品購買紀錄"
3. 點左上back

[Result] title的商品數量會變成0 (畫面重整就會正常了)
![image](https://cloud.githubusercontent.com/assets/22789907/21570875/08ca3cac-cf05-11e6-92e7-50f3cb6842c4.png)　
![image](https://cloud.githubusercontent.com/assets/22789907/21570889/1b34cc5e-cf05-11e6-88b1-9e7b16454125.png)

**Comment by cmacma7** [comment]
fix in BN. 
problem cause by storyBoard after handleKeepAlive is null.

**Comment by Iris926** [comment]
[Test Site] bn
[Scenario]
1. 點進任一商品頁=>title仍會顯示該tag下的商品數量
![image](https://cloud.githubusercontent.com/assets/22789907/21603633/b424ca82-d1d9-11e6-98f0-ff779d258036.png)
　　　
2. 點了"查詢本商品購買數量"，再點左上back=>title只剩下tag名稱，沒有顯示數量
![image](https://cloud.githubusercontent.com/assets/22789907/21603644/c6b49402-d1d9-11e6-9269-3f4181c965ca.png)
　　　
---

Ｑ：請問這兩個地方的title顯示需要一致嗎? (目前行為沒有影響功能)

**Comment by cmacma7** [comment]
No, there is not need because it is single item full screen, not need to have count
