### ISSUE TITLE
[EC][查詢本商品購買紀錄] 被併單的訂單，點擊"前往主要訂單>>"無作用

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1153]
[Test Site] store
[Version] v1.1.1743
[Scenario]
1. 店主進入EC商店/點擊任一商品進入商品頁/點 查詢本商品購買紀錄
2. 找到任一被併單的訂單/展開成大版訂單/點"前往主要訂單>>"

[Result] 無作用
![image](https://cloud.githubusercontent.com/assets/22789907/21570944/8a89c1fe-cf05-11e6-98c5-0fc6452fbab2.png)

**Comment by cyen1121** [comment]
已修正，
getAction設置錯誤

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed
