### ISSUE TITLE
[發佈商品到FB] 改掉confirm -- 偵測到多張圖

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1156]
1. 偵測到有多張商品圖片，請按 [確定] 繼續將圖片上傳到留言處 或按 [取消] 不繼續傳圖
--> 不用confirm，改用div視窗詢問

2. 關聯儲存設定之後，需顯示轉圈圈，避免使用者以為沒有按下去

bn已修正

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
