### ISSUE TITLE
[限量商品] 購買限量商品，再點繼續購買，則剛剛買的商品數量沒有被扣掉

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1159]
#1094 
---
[Test Site] bn
[Widget single URL] http://bn.tagfans.com/node/fb.html?noteId=21359_x_351

**Comment by cyen1121** [comment]
bn已修正
購買完後會重新計算數量

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
