### ISSUE TITLE
[團購]商品 內容/圖片 處，要加上一個"去購買"btn，以免客人找不到下單購買的地方(或是可考慮將btn fixed 置底)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1162]

**Comment by cyen1121** [comment]
bn 上已經加入
需要打開商店管理設定的消費記錄欄位

**Comment by Iris926** [comment]
[Test Site] bn
[Result]
1. 當客人直接按"Buy"btn時(沒有選擇任何商品or運送方式)，則畫面直接捲到可以選購商品的地方

2. 當客人只選了商品or只選了運送方式，按"Buy"btn，則畫面直接捲到還沒選的運送方式or商品選項

3. 當店家沒有開啟"顯示購物紀錄"，則客人會看不到"Buy"btn
=>Fixed by Cma
=>不管店家有沒有開啟"顯示購物紀錄"，客人只要打開fullscreen商品頁，就可以在頁面置底右側看到"Buy"btn

**Comment by cyen1121** [comment]
fixed自動focus到正確的區域

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed

---

1. 沒有將商品加到購物清單，直接按"立即購買" or "Buy" =>popup"請選擇商品數量"，並自動將畫面捲到商品規格處
2. 沒有選擇運送方式，直接按"立即購買" or "Buy" =>popup"請選擇運送方式"，並自動將畫面捲到運送方式處
