### ISSUE TITLE
[拆單] 客人查看"我的訂單"時，不該看到拆單相關功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1163]
![image](https://cloud.githubusercontent.com/assets/22789907/21703909/6dcf3338-d3f0-11e6-8198-39da8feae721.png)

**Comment by cyen1121** [comment]
已修正上bn和store

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1788.2
[Result] 訂單已併單 or 併單後又回復到併單前，則又可看到拆單相關功能

**Comment by cyen1121** [comment]
已修正

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
