### ISSUE TITLE
[iOS app] EC mode選單開起關閉時，會導致App Crash (iphone 6 only)

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#1167]
如題

**Comment by gameflierHao** [comment]
目前測試:
使用SAFARI 將網頁存到桌面使用
執行同樣行為也會產生此BUG
因此認定為IOS的問題

解決方式:
開啟panel時加入delay(setTimeout)

**Comment by gameflierHao** [comment]
store version 1794

**Comment by Iris926** [comment]
1. 已請Howard協助測試，目前都沒再次發生問題
2. 已向團媽(君)回報，請她使用新版本，看看還會遇到問題嗎
