### ISSUE TITLE
[iOS App][EC] 點開左上MENU，滑動MENU or 商品列，造成MENU顯示有問題

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1168]
[App version] 1.1.10
[Test Site] store
[Version] v1.1.1788.2
[Scenario]
1. 進入EC商店
2. 點開左上MENU
3. 滑動MENU or 滑動底下的商品列

[Result] MENU顯示破版、跑位
![image](https://cloud.githubusercontent.com/assets/22789907/21831855/035718fe-d7e2-11e6-88f5-1b5cfb8559a5.png)

**Comment by cmacma7** [comment]
Safari bug....
