### ISSUE TITLE
[林皇宮花園] 進"婚禮預約"，點任一欄位，造成畫面當掉

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1169]
[Test Site] store
[Version] v1.1.1788.2
[Browser] Chrome 55.0.2883.87 m

**Comment by gameflierHao** [comment]
Store version: 1.1.1803.1

Revision: 1717
Author: zhanghaowu
Date: 2016年12月22日 上午 09:57:18
Message:
更新滿意度調查表qrcode內容改用短網址
----
Modified : /nodejs/bn/widgets/Widget/Opinions Collection/customerForm#FullSinglePage.js

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1803.1
[Result] Fixed

---

針對電腦fullscreen填寫預約單，視覺上會覺得欄位往上移的問題，暫不修改。
