### ISSUE TITLE
[統計總結] 清除瀏覽資料並重新下載，在統計總結的設定值不能被清掉

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1173]
* 不能被清掉的項目有：
1. 設定裡面的：單頁訂單顯示筆數、商品表單顯示運送、商品表單顯示欄位、商品表單Excel顯示欄位、單張『訂單狀態』修改是否推文通知
2. 日期區間
![image](https://cloud.githubusercontent.com/assets/22789907/21878372/d04bd2ec-d8cc-11e6-8ed1-6c4eb941af07.png)

**Comment by cyen1121** [comment]
myLocalStorage.module_showSummaryBeta_setting

是統計專門設定用的，要避免被清除

**Comment by cmacma7** [comment]
Fix in version 1083.1

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1828
[Result] 仍有項目會再清除瀏覽資料重新載入後，設定值變回預設
1. 單頁訂單顯示筆數
2. 單張『訂單狀態』修改是否推文通知
3. 日期區間

**Comment by cmacma7** [comment]
already fixed in system, David need to check whether he put all data under module_showSummaryBeta_setting.

**Comment by cyen1121** [comment]
module_showSummaryBeta_pageNumber

module_showSummaryBeta_replay_messagetable

也需要避免被清除

**Comment by cmacma7** [comment]
key.indexOf("module_showSummaryBeta_")==0  then do not clean.

**Comment by cmacma7** [comment]
fix in store.tagfans.com/debug/ version 1835.5

**Comment by cyen1121** [comment]
bn已加入日期紀錄功能

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed

---

1. 訂單排序設定 & 訂單時間區間設定
2. 設定：單頁訂單顯示筆數、商品表單顯示運送、商品表單顯示欄位、商品表單Excel顯示欄位、單張『訂單狀態』修改是否推文通知

**Comment by Iris926** [comment]
[Test Site] bn
[Result] 因造成多位團媽的操作不便，目前將"訂單排序設定 & 訂單時間區間設定" 回復為原邏輯

---

已更新至store
