### ISSUE TITLE
[EC] 商店選單需要加入 "登入/登出" 選項

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1174]

**Comment by cmacma7** [comment]
added in BN and store.tagfans.com/debug/  version 1835.2

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
---

1. 登出狀態進入EC商店=>選單最下方可以看到"登入"
2. 登入狀態進入EC商店=>選單不變(不會有"登出")
