### ISSUE TITLE
[Scan FB] 匯入FB文章，需要可以預覽社團文章的區塊

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1176]
匯入FB文章，需要可以預覽社團文章的區塊，以便加快匯入速度

電腦版：左邊為社團文章內容，右邊為匯入設定
手機版：上方為社團文章內容(預設)隱藏，下方為匯入設定

r.1802 已修正，bn已更新

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
