### ISSUE TITLE
[EC]點選 非推薦商品 的任一tag A，並F5重整畫面，則tag A會變成商店首頁

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1186]
[Test Site] store
[Version] v1.1.186
[Scenario]
 1. 進入EC商店，ex.本丸麻麻，首頁是"推薦商品"
 2. 點左上MENU/點tag [女]配件
![image](https://cloud.githubusercontent.com/assets/22789907/22095391/4897d6e2-de4f-11e6-89bc-e70919375cc1.png)

 3. 按F5重整畫面 =>上方title多了 $ 字號、MENU的"商城首頁"被置灰了
![image](https://cloud.githubusercontent.com/assets/22789907/22095404/61267506-de4f-11e6-8701-28ec23217107.png)
![image](https://cloud.githubusercontent.com/assets/22789907/22095417/7bfd767c-de4f-11e6-9a60-3fb7d9ef7c18.png)

4. 點其他tag，再點"商城首頁" =>跑到 [女]配件，而不是 推薦商品

**Comment by cmacma7** [comment]
Fixed on BN. Problem caused by not handling setMainPageTag correct if tag already exist in the url. We will set the tag on url becomes the mainPageTag.

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
