### ISSUE TITLE
需設計類似showWidgetPage的API，提供給EC首頁的推薦widget

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1187]
原因：showWidgetPage開啟的widget，最下方無法顯示購物車按鈕
且url沒有帶正確note資訊，直接copy url分享出去會有問題

**Comment by cmacma7** [comment]
Please use the API
showWidgetPage(url, showPopup, style, complete, showShoppingFooter).
The last parameter set to true, then the footer will show up. Available on BN.

**Comment by cmacma7** [comment]
url沒有帶正確note資訊，直接copy url分享出去會有問題.... this problem cannot resolve at this moment.
