### ISSUE TITLE
[福利批發] 發布商品到FB，商品連結少了store id，造成客人點連結下單後，找不到訂單

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1190]
[Test Site] store
[Version] v1.1.1806
[Scenario]
1. 店主在tagfans刊登商品，並發布商品到FB
2. FB PO商品時，商品的分享連結，少了店號
ex. http://store.tagfans.com/node/fb.html?noteId=1480144_x_
3. 客人從FB社團點了這個連結，到系統下單

[Result]
1. 下單成功，客人查看訂單，發現找不到訂單
2. 店主也看不到這張訂單

**Comment by cmacma7** [comment]
The link is not complete. No store ID so cannot send to the store owner!
