### ISSUE TITLE
[統計總表] 過濾後的訂單結果，仍需套用 "50 筆/頁"的設定

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1191]
[Scenario]
1. 店主進入收件匣(ex. 收件訂單、收件預約訂位...等)
2. 進入設定，設定單頁訂單顯示數量為 50 筆/頁
3. 回到訂單總表，進行過濾，ex. 點擊商品標題

[Result] 過濾後的訂單結果，單頁不足50筆，就已經換頁了
![image](https://cloud.githubusercontent.com/assets/22789907/22193334/94cb15c8-e175-11e6-970a-0300e0af25fc.png)

[Expected Result] 過濾結果仍依照 50筆/頁 的顯示規則，超過50筆才開始換頁

**Comment by cyen1121** [comment]
bn store已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1835
[Result] Fixed
