### ISSUE TITLE
[收件匣][統計總結] 收到紅色信封後不要點開，離開收件匣再重新進入，則紅色信封沒有消失

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1192]
[Scenario]
1. 餐廳老闆到 "收件 預約訂位"畫面 or 統計總結 畫面
2. 此時收到新進訂單，畫面上方會顯示 紅色信封+數量
3. 不要點紅色信封，直接離開收件匣，然後再重新進入收件匣

[Result] 新進訂單已經自動載入，但是紅色信封卻沒有消失

**Comment by cmacma7** [comment]
Problem caused by not re-calculate the new coming mail count.
Fixed at BN and store.tagfans.com/debug/  version 1835.1

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1871
[Result] Fixed
