### ISSUE TITLE
[購物車]當運送方式為"開啟"時，則不顯示"加入購物車"btn

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1193]
[Expected Result]
1. 店主新增一個購物車商品widget
2. 將運送方式"關閉"，則客人購買時，可以選擇要"加入購物車" or "立即購買"
3. 將運送方式"開啟"，則客人只能"立即購買"

---

[目前行為] 不管運送方式開or關，客人都可以"加入購物車" or "立即購買"

**Comment by cyen1121** [comment]
fixed 購物車模式不會跳出運費選項

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed (購物車商品，無論運送方式有無開啟，user購買時，都強制隱藏運送方式)
