### ISSUE TITLE
[購物車] 店主新增ATM匯款，user選擇後，匯款資訊顯示有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1197]
[Scenario]
1. 店主至管理/設定購物車/訂單狀態設定(統一設定處)
2. 新增付款方式"ATM匯款(郵局)"，並輸入相關資訊
3. user購買商品，完成訂單，至寄件備份點選"付款去"
4. 選擇"ATM匯款(郵局)"
![image](https://cloud.githubusercontent.com/assets/22789907/22322752/1f713b8e-e3d9-11e6-8d7b-f7eb5ee28ee6.png)

[Result] 顯示成中國信託
￼￼￼￼￼￼￼
![image](https://cloud.githubusercontent.com/assets/22789907/22322790/5b554a0a-e3d9-11e6-90d6-0f9dc17437d8.png)

**Comment by peichingliao** [comment]
store已更新
可測試
http://store.tagfans.com/node/fb.html?noteId=622742_16403_221

**Comment by peichingliao** [comment]
r.1912

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
