### ISSUE TITLE
修改template station的widget，cache不會更新

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#120]
(1)第一部電腦修改template station的widget內容或是新增widget
(2)第二部電腦在station內選擇新增widget看到的widget還是先前版本或是找不到新增進來的widget

**Comment by cmacma7** [comment]
In tempate station delete/move/
if (global.pageData && parseStationId(global.pageData.id)==130){
            bnsql.touchInfo("user", "widgetVersion");}
In template click operation_template bnsql.touchInfo("user", "widgetVersion");

Page need to refresh to reflect the changes
