### ISSUE TITLE
[購物清單] 填入商品數量產生購物清單，退出商品頁後再度進入，則購物清單未正常顯示

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1201]
[Scenario]
1. user在A商品填入數量=>畫面下方自動產生購物清單
2. 點左上back離開商品頁，再點擊商品進入 =>下方的購物清單沒有顯示(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/22539815/7e96880c-e957-11e6-8cb7-208d5314d7a2.png)

3. 繼續購買其他商品 =>下方的購物清單還是沒有顯示(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/22539825/8f3e9b36-e957-11e6-97f1-3138d941e35f.png)

[Note] 點擊"查看購物清單" 兩次，才能成功展開購物清單

**Comment by cyen1121** [comment]
fixed強迫有東西就展開

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
