### ISSUE TITLE
[優惠模組][Vanessa] 設定優惠模組後，更動商品金額，應設置檢查機制

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1202]
[Test Site] store
[Version] v1.1.1835
[Scenario] 測試widget 連結：http://store.tagfans.com/node/fb.html?noteId=1319968_x_3842
1. 建立一個有優惠模組的widget
2. 設定商品價格均=100
3. 設定優惠條件為"買3個，共299元"
4. 成功建立商品
5. 編輯商品，將商品價格改為120，儲存
6. user購買3個商品

[Result] 扣項為1元，沒有達成"買3個，共299元"
![image](https://cloud.githubusercontent.com/assets/22789907/22574959/77ae202c-e9ed-11e6-9db1-3597d668348f.png)

**Comment by peichingliao** [comment]
bn已更新 r.1903

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
---

買N個 共M元 or 買N個以上 每個M元 ，設定後再修改商品價格，會跳出popup
![image](https://cloud.githubusercontent.com/assets/22789907/23762581/54b12dee-0531-11e7-9245-5c211ecfe45b.png)
