### ISSUE TITLE
[FB私訊功能][Sunny] 增加 標題 & 標尾 兩個共用欄位，讓店主可以輸入後，直接套用至每個客人的私訊內容

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1203]
1. 增加 "開頭" & "結尾" 兩個欄位(已上bn)
2. 移除私訊內容的連結
![image](https://cloud.githubusercontent.com/assets/22789907/22582675/22d20a74-ea23-11e6-8e1b-27d56d67143d.png)

3. 移除 "日期區間+消費總金額" 的文字
![image](https://cloud.githubusercontent.com/assets/22789907/22582701/4e7fc544-ea23-11e6-8e34-f98f3bdbef1f.png)

**Comment by cyen1121** [comment]
bn已修正

**Comment by Iris926** [comment]
1. 移除私訊內容的連結 =>仍有一個"消費紀錄"的連結在
![image](https://cloud.githubusercontent.com/assets/22789907/22634180/6b9df9fc-ec62-11e6-9b42-c90dfc93c0a1.png)

2. 商品清單內容，需移除"運送方式"的統計

**Comment by cyen1121** [comment]
已修正上bn避免連結空白

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1856
[Result] Fixed

---

1. 私訊內容的連結無法移除，放"消費紀錄"
2. user名稱有排序：大寫字母>小寫字母>中文
