### ISSUE TITLE
[統計總結] 將confirm alert視窗，改為自己刻的視窗

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1204]
[Scenario]
1. 店主至收件訂單/統計總結/批次修改訂單狀態
2. 點"套用"/顯示confirm
![image](https://cloud.githubusercontent.com/assets/22789907/22584397/2482aa7c-ea2d-11e6-8ef0-5bc4131eb94f.png)

3. 若店主誤勾選了confirm裡的選項"防止此網頁產生其他對話方塊"，則之後再執行批次功能時，造成批次功能無作用

[建議] 將confirm 改成自己刻的視窗

**Comment by cyen1121** [comment]
doOKCancelModal("hello", function(data){console.log(data)});   this is not using system alert or confirm.

If you want to show message box then fadeout the message box, please use
$("#progress p").html(TL("no item found"));
$("#progress").fadeIn().delay(1000).fadeOut();

this is two lines of code, first line assign the text, second line decide thow to show the message

**Comment by cyen1121** [comment]
批量的部分都改成系統顯示，貨品狀態．併單．訂單狀態

保留合併單中間檢查彈出資訊使用瀏覽器樣式，因字數較多無法一瞬間閱讀完成，所以保留原本的樣式

**Comment by Iris926** [comment]
[Test Site] bn
刪除勾選訂單 的流程中，顯示的兩個popup，也需要套用系統的視窗
![image](https://cloud.githubusercontent.com/assets/22789907/22965448/9b46ada6-f398-11e6-9419-3f64b38c0189.png)
![image](https://cloud.githubusercontent.com/assets/22789907/22965464/ace7155a-f398-11e6-807b-f6c9a7c8fdfd.png)
![image](https://cloud.githubusercontent.com/assets/22789907/22965483/bec2ae7e-f398-11e6-9c07-df2eec7d9f0a.png)
