### ISSUE TITLE
[拆單] 取消拆單 or 品項數量=1時進行拆單，應可繼續使用改量改價功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1208]
[Scenario]
1. 店主進入收件訂單
2-1. 對品項數量>1的商品，進行拆單/在輸入"要拆開的數量"時按"取消"
2-2. 對品項數量=1的商品，進行拆單 =>會popup"商品數量需大於1"
2. 接著在這張訂單，進行改量改價 =>popup "拆單或併單後，無法再修改價格/數量" (NG)

[Expected Result] 拆單沒有成功，應可讓店主使用改量改價功能

**Comment by cyen1121** [comment]
已修正上bn
同步修正不是輸入數字造成錯誤拆分的問題

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
