### ISSUE TITLE
[iOS] 商品名稱較長，在iOS app/safari/chrome 上會發生文字被截斷

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1209]
[Scenario] 在不同device上查看商品：

(iPhone 6S+、iPhone5 確定都會發生)
**iOS app** 
![image](https://cloud.githubusercontent.com/assets/22789907/22633692/9db45926-ec5e-11e6-8afd-e55fac9e96b5.png)

**iOS safari**
![image](https://cloud.githubusercontent.com/assets/22789907/22633707/cf36a31e-ec5e-11e6-8417-5b21f6d0b4fa.png)

**iOS chrome**
![image](https://cloud.githubusercontent.com/assets/22789907/22633705/ca870fd4-ec5e-11e6-8acf-34e4349ecc18.png)

---

**PC chrome**
![image](https://cloud.githubusercontent.com/assets/22789907/22633647/3d72f810-ec5e-11e6-92a5-42a630968464.png)

**Andriod app**
![image](https://cloud.githubusercontent.com/assets/22789907/22633649/4ba8709a-ec5e-11e6-8da1-a2e155f72551.png)

**Android chrome**
![image](https://cloud.githubusercontent.com/assets/22789907/22633681/903bdc2e-ec5e-11e6-9fa4-cc616ea47bc1.png)

**Comment by cyen1121** [comment]
行高統一設定在1.8
已修正上bn

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed
