### ISSUE TITLE
[統計總結][刪除訂單] 建議改為"刪除勾選之訂單"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1210]
[Expected Result]
1. 進入統計總結
2. 點右上管理/批量修改狀態與刪除
3. 勾選欲刪除訂單/按"刪除勾選之訂單"
![image](https://cloud.githubusercontent.com/assets/22789907/22682795/c7fa7304-ed4f-11e6-9174-721a54409049.png)

**Comment by cyen1121** [comment]
已修正上bn

**Comment by Iris926** [comment]
Hi  @cmacma7 ~
要請你幫忙改這個popup裡面的文字，改成：確認刪除已勾選訂單？
![image](https://cloud.githubusercontent.com/assets/22789907/22721586/9c760dc2-edec-11e6-9334-d436a2f82884.png)
