### ISSUE TITLE
[統計總結][天使媽] 將較舊訂單的A品項的貨品狀態改成"售完"，再與較新訂單合併，則較新訂單的A品項被自動改成"售完"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1216]
[Scenario]
1. 有兩張訂單，都包含A品項
2. 將較舊訂單的A品項的貨品狀態改成"售完"、較新訂單的A品項維持空白
3. 合併這兩張訂單

[Result] 併單後，較新訂單的A品項被自動改成"售完"

**Comment by cyen1121** [comment]
已修正上bn和store

再判斷貨品狀態需加上subIndex

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1856
[Result] Fixed
