### ISSUE TITLE
[EC][隱藏] 店主將第一頁能顯示的商品，全部隱藏，造成user看到全白的畫面

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1219]
[Scenario]
1. user瀏覽店家，將第一頁商品滑到底，會自動載入第二頁(或更多)的商品
2. 店主將第一頁商品全部隱藏
3. user再次瀏覽店家

[Result] 因為沒有第一頁商品可以滑到底，造成後面幾頁的商品都無法load出來，畫面全白

**Comment by cmacma7** [comment]
fixed by remove disabled widget in EC mode, version 1870

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1871
[Result] Fixed
