### ISSUE TITLE
[購物車商品] 不顯示 "已有n人購買" 

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1228]
[Scenario]
1. 客人從系統購買商品並加入購物車，成立訂單
2. 客人從FB+1，店主經由scan FB 成立訂單

[Result] 經由scan FB 成立訂單，則在小版商品可以看到"已有n人購買"

[Expected Result] 只要是購物車商品，一律隱藏"已有n人購買"

**Comment by cyen1121** [comment]
bn已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
