### ISSUE TITLE
[EC][Scan FB] 點擊widget 欄位，直接開啟該widget，則網址&標題，不應該顯示"0"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1232]
*若店主將此網址分享出去，則客人點左上的"瀏覽更多"，會看到白畫面
*舊版店面無此問題

![image](https://cloud.githubusercontent.com/assets/22789907/23013168/86b4593e-f464-11e6-9160-bdb7c1432918.png)

![image](https://cloud.githubusercontent.com/assets/22789907/23013173/8c0f13c4-f464-11e6-84dc-b54a56127b71.png)

![image](https://cloud.githubusercontent.com/assets/22789907/23013181/902e52da-f464-11e6-8949-7aecb593f92d.png)

**Comment by peichingliao** [comment]
bn 已更新 r.1899
待部分掃描驗證完畢一起更新store

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1894.1
[Result] Fixed
