### ISSUE TITLE
[Scan FB] 成立訂單時按略過訂單，會造成要成立的留言被略過

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1236]
應防呆

**Comment by peichingliao** [comment]
r.1912 ,  bn已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed ：勾選留言並成立訂單中，店主若誤按了"略過留言"，則跳出提示視窗

![image](https://cloud.githubusercontent.com/assets/22789907/23733463/0bd14e6a-04b4-11e7-8ad4-4be7d31586b1.png)
