### ISSUE TITLE
統一設定：訂單狀態、取貨付款方式

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1240]
[設定全店訂單狀態Scenario]
1. 管理/購物設定/訂單狀態設定(統一設定處)/"套用"統一設定(新商品直接套用、舊商品要重新編輯並建立)
2. 新增商品=>此時就會套用統一設定
3. 新店預設"套用"統一設定；舊店讓老闆自己決定要不要"套用"

---

1. 舊訂單也需同步修改
*訂單直接拿global設定(default)
*保留單一商品可以設定訂單狀態的功能(客人平常看不到，真的有需求再來客服提)

2. 舊商品的訂單狀態編輯區塊?
*直接套用統一設定
*原有的訂單狀態編輯區塊直接隱藏(不刪、但隱藏)=>要給一個"請到統一設定處設定"的連結
*複製原有範本生成新商品，則context會升級；只要舊商品走過"建立"流程，也會升級(已有git #1214 )
*套用統一設定後，初始的訂單狀態要給系統預設值

**Comment by Iris926** [comment]
#721 
![image](https://cloud.githubusercontent.com/assets/22789907/23115177/2215d4ae-f77e-11e6-83d9-3fa6a853f281.png)

**Comment by cyen1121** [comment]
須將getShoppingContext在scan fb之前要確保從DB下載回local端
