### ISSUE TITLE
一鍵併單(已有此功能，需要打開)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1250]
[Scenario]
1. 選好日期
2. 篩選好狀態
3. 按[一鍵併單] =>popup"自動將所有客人的訂單合併"

[Result] 自動將所有客人的單全部合併

**Comment by cyen1121** [comment]
已在bn上打開

**Comment by peichingliao** [comment]
建議增加篩選功能：合併全部 or 所選訂單狀態為XXX的訂單(可多選)

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1935
[Result] Fixed
---
可依店主篩選結果，直接執行一鍵併單
