### ISSUE TITLE
[統一設定] 版本更新後，第一次進入商店管理/購物設定，則看不到統一設定的開關

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1255]
![image](https://cloud.githubusercontent.com/assets/22789907/23206403/82c2f998-f928-11e6-8956-b93ce5adcc5f.png)

**Comment by cmacma7** [comment]
the on/off button will appear only after user has create the 統一設定, that means he/she need to press 統一設定 button, and create the 統一設定.
