### ISSUE TITLE
page mode 的商店，快速切換至EC mode

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1270]

**Comment by cmacma7** [comment]
function added. In console, use
createTags(storeId, pageId, tagName); to create tags for the whole page.
for example.  (!note, this function can be used by store owner only);
createTags(569,4097,"超值票卷");
createTags(569,4082,"家用好物");
createTags(569,5216,"餐廚精選");

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1977
[Result] Fixed
