### ISSUE TITLE
[統計總結] 不同電腦使用loginmyth進入查看訂單，看到的訂單狀態修改時間不一致

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1291]
![image](https://cloud.githubusercontent.com/assets/22789907/24484962/aaf237a4-1533-11e7-994e-a933c3ad657b.png)

![image](https://cloud.githubusercontent.com/assets/22789907/24484971/b7755aa6-1533-11e7-88d8-c20012b385ab.png)

**Comment by cmacma7** [comment]
Hi David, which time you are using? Do you adjust the time to NTP time? If want to fix the time, then there is no need to adjust NTP time
