### ISSUE TITLE
[權哥] 一鍵轉發功能

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#1292]
一鍵轉發動作
1. 分享 -  cma
2. 複製圖片、標題、商品項目、終端價格、標註上一層來源store (widget duplicate function) - David
2. 選擇商店、選擇社團、選擇標籤(有預設)、選擇範本ID、設定價格  - cma/sylvia
3. 進入進階編輯or直接發佈  - cma

Context
1. 設定可否轉發到別人商店(不可被轉發、可被轉發一次、可被轉發無限次) - David
2. 設定鎖終端價格 - David

其他
1. 需記錄轉發路徑 - cma
2. 商店設定可否轉發(不可被轉發、可被轉發一次、可被轉發無限次) - cma

註
已被轉發出去的，源頭改動轉發設定，無法套用到其他複本

**Comment by cmacma7** [comment]
Feature updated to BN. 

orderTree programming guide.

To enable a widget as the root to orderTree, set the context of the widget copyRight to 1 for copy once, and 2 for copy free. 
The other people will have the ability to copy the copy-right-enalbed widget to its own store. If the widget is copy once, it can only be copied by its direct child, and other people cannot copy this widget again from its child node. If it is copy free, then this widget can be copied recursively. 

The orderTree maintains the relation of child to parent node. When increment the count of a child node, all its parent node's count will be increased. 
When calculate the count of a node, we just need to sum the count of all rows who's parentId is the target node Id.   
  
link a node to parent. when generate a node without parent, the parentNode will fill with the id of itself, then means, if the top most node is created, the noteId_in=parentId_in 
createOrderTree(noteId_in, parentId_in);
	SQL: call createNodeToOrderTree(noteId_in, parentId_in);
	BN:  bn.execSql({'fun':'createOrderTree', 'nid':noteId_in, 'parentId':parentId_in}, function(data){ console.log(data);
});
 
increase referenceCount to a node 
incOrderTree(noteId_in, inc_in);
	SQL: update orderTree set count=count+inc_in where nid=noteId_in;
	BN:  bn.execSql({'fun':'incOrderTree', 'nid':noteId_in, 'inc':inc_in}, function(data){ console.log(data);});
	 
delete a note from tree
delete all rows of orderTree whose parentId is the deleted noteId. In such condition, the original links will not break if any of the node in the middle is deleted. And all exist order will not deleted if nid is the deleted noteId. 
  BN:  bn.execSql({'fun':'deleteOrderTree', 'nid':noteId_in}, function(data){ console.log(data);});
  
calculate sum of a node, get the total refCount to this noteId
getOrderTree(noteId_in, callback)
	SQL: select parentid,sum(count) as count from orderTree where parentid in (1483479, 1483477) group by parentid;
	BN:  bn.execSql({'fun':'getOrderTree', 'nid':noteId_in}, function(data){ console.log(data);});
	BN: getOrderTree(noteId_in, callback) is a helper function that will combine function called into a single one to server. Use getOrderTree(noteId_in, callback) is prefered.

**Comment by VanessaHsu** [comment]
震鈺新需求(尚待確認)
*一鍵轉發時，需清空價錢。
*向上游叫貨時，需要確認限時、限量、批發價、店號
