### ISSUE TITLE
store.tagfans.com 上一頁出錯

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#130]
(1)在一個商店的頁面中隨便加一個widget
(2)新增完後按兩次back跳出商店
(3)title bar 會先轉紅在跳過頭

*BN站沒有看到相同問題

**Comment by cyen1121** [comment]
新的flow造成錯誤
(1)選擇一間商店
(2)修改商店Template
(3)修改完後(不能選取消要不然沒有錯誤發生)
(4)一直back回首頁List就會出現錯誤

**Comment by cmacma7** [comment]
Cannot reproduce the problem... maybe fixed as side effect. Please close if fixed.
