### ISSUE TITLE
[店內點餐][林酒店] 餐期修改需求

### ISSUE THREAD

**Issue by huangVic** [cmacma7/bn#1315]
- [x] 3. 點餐時間原為碼表, 改為進單時間
- [x] 4. 餐期平日午餐與晚餐為單點, 下午茶為吃到飽, 庫存需依每天每餐分開計算
- [x] 7. KDS 新增餐期的時段
- [x] 11. 平板電腦所螢幕只供點餐使用
- [x] 12. 平板電腦設定頁面鎖密碼 (預設 54768562)

**Comment by Iris926** [comment]
[Test Result] PASS!!
---

註：目前設定的密碼為系統預設(請詢問Howard/Iris)
