### ISSUE TITLE
[店內點餐][銅盤] 新增輸入來客數需求

### ISSUE THREAD

**Issue by huangVic** [cmacma7/bn#1317]
- [x]  點餐介面再更換桌號頁面能輸入來客人數 
- [x]  來客人數設定後要進入葆光系統

**Comment by Iris926** [comment]
[Test Result] PASS!!
---

[註]
1. 平板編輯人數/送出點餐單=>人數成功更新到POS
2. 平板每次切換桌號，服務人員要先編輯人數，再送出點餐單
