### ISSUE TITLE
[餐廳系統] 林酒店限量需求

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#1325]
依照餐期不同而有不同的限量設定

- [x] 葆光將在POS提供設定介面
- [x] 我方需要將原單一限量設定改為依照POS餐期限量新增的介面更改的限量設定
- [x] 平板新增非用餐時間警告 
- [x] KDS 餐期資料介接

**Comment by Iris926** [comment]
[Test Result] PASS!!
