### ISSUE TITLE
[匯入facebook社團文章] 機器人留言要改成"推文小幫手"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#1358]
![image](https://user-images.githubusercontent.com/22789907/28863475-af32f3d8-779b-11e7-9918-cdf20622f059.png)

**Comment by peichingliao** [comment]
r.2281 已修正
store已更新

**Comment by Iris926** [comment]
[Test Result] Fixed

![image](https://user-images.githubusercontent.com/22789907/28865976-2a581446-77a4-11e7-93a5-4e09e9fba449.png)
