### ISSUE TITLE
編輯商店後，返回商店畫面不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#138]
1. 進入商店頁面->右上角按鈕選編輯->編輯商店內容(修改標題) -> 完成後返回商店畫面
   a. 標題是舊的，必須重新整理才生效
   b. 商店畫面不完整，頁面列表不見了(如圖)
2. 進入分頁->右上角按鈕選編輯->編輯分頁內容(修改標題) -> 完成後返回分頁畫面，標題是舊的，必須重新整理才生效

![screenshot_2015-03-13-11-21-16](https://cloud.githubusercontent.com/assets/10726049/6632619/2a21784a-c974-11e4-93a3-8f2929a8377d.png)

**Comment by cmacma7** [comment]
The model_officialStationList is not mark as changed() in saveGroupInfo. Fixed
