### ISSUE TITLE
商店的首圖無法調整

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#139]
首圖與列表的方形圖示是同一張，比例卻差很多
建議
1. 分開兩張圖
2. 或讓商店首圖可以調整位置

**Comment by cmacma7** [comment]
Need to have two images, one for 1:1 as the cover thumbnail, and the other one is the store picture, for example, 16:9, so that the picture looks good.

**Comment by peichingliao** [comment]
用電腦版開的畫，首圖cover比例也是很奇怪
可否固定首圖尺寸比例呢?
![cover](https://cloud.githubusercontent.com/assets/10726049/7178218/b9c1d548-e45f-11e4-9a27-eba03cc1531f.png)

**Comment by cyen1121** [comment]
fixed

**Comment by peichingliao** [comment]
請問分兩張商店首圖的設定在哪兒
![2015-11-16 3 07 25](https://cloud.githubusercontent.com/assets/10726049/11176007/a65d8f62-8c73-11e5-8ae4-c5a6c4f073e6.png)

**Comment by cyen1121** [comment]
商店樣式都已經會對大螢幕調整圖片的顯示範圍，不會再有瘦長的圖片問題
