### ISSUE TITLE
取號 ios 手機無法操作

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1410]
測試機：iPhone7
問題一、使用Tagfans APP開啟樂麵屋板橋店「候位取號」頁面時，「確認」按鈕被跑馬燈遮住，無法點擊。如圖1。
![image](https://user-images.githubusercontent.com/35478230/35614294-88923f8e-06a9-11e8-871f-307173e6c543.png)

問題二、使用Safari開始樂麵屋板橋店無請洽管理者/服務人員，頁面是空的，只有跑馬燈，如圖2。
(http://store.tagfans.com/#page_join?o=5950&id=27985&viewType=station)
![image](https://user-images.githubusercontent.com/35478230/35614540-660395c0-06aa-11e8-85c5-464e0055107d.png)

**Comment by cmacma7** [comment]
fixed.
