### ISSUE TITLE
[訂位服務]空值，建議不允許儲存。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1412]
[訂位服務]
管理訂位規則
1.時間：「時」為空值時，請阻擋，不允許儲存。
2.桌子張數：「位」為空值時，請阻擋，不允許儲存。

**Comment by gameflierHao** [comment]
Revision: 3018
Author: zhanghaowu
Date: 2018年7月16日 下午 05:15:57
Message:
FIXED [訂位服務]空值，建議不允許儲存#1412
----
Modified : /nodejs/bn/widgets/Widget/orderTemplate/BookingTableSchedule/BookingTableSchedule2.js
