### ISSUE TITLE
[訂位服務]日期回饋判讀有問題

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1416]
日期回饋訊息請更正，為什麼選2016/3/24會顯示，1天內？？？

建議過去的日期就擋掉，不要給使用者選了。

今天是3/2，還差20多天。

![image](https://user-images.githubusercontent.com/35478230/36888286-bf843946-1e2f-11e8-831a-8b268888fbfa.png)

**Comment by gameflierHao** [comment]
因為"年"是2016
已經超過了預訂時間
