### ISSUE TITLE
[訂位服務]訂位後，於查詢，查無資料。如影片。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1417]
1.於查詢查無資料。
2.回到主頁面，在回到訂位服務，卻出現3/2的訂位資訊。非常詭異。

https://drive.google.com/open?id=1vump7gFi2isEXsH7sMRqx3loyIQo6l6K

**Comment by gameflierHao** [comment]
影片為編輯閃動
已修正該影片之現象

Revision: 2697
Author: zhanghaowu
Date: 2018年3月19日 下午 05:01:40
Message:
編輯時->點選左上方選單按鈕->發生選單閃爍問題

修正: 在編輯模式下無法使用全版面選單
----
Added : /nodejs/bn/widgets/Store Template/template_134_FullScreenStyle1.js
