### ISSUE TITLE
[預訂位]完成畫面需區別手機與電腦，顯示不同的資訊。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1423]
如果是手機的話就只要展現到Line的連結不需要QR Code。
但是如果是電腦的話就不需要連結，只要QR Code。

![image](https://user-images.githubusercontent.com/35478230/37443065-c0aceaec-2844-11e8-8b40-0724d191fbc7.png)

**Comment by gameflierHao** [comment]
Done

Revision: 2694
Author: zhanghaowu
Date: 2018年3月19日 下午 02:49:21
Message:
如果使用account kit登入 
1. 電腦版顯示Line QRCode
2. 手機版顯示Line 連結

Fixed Github issue#1423
----
Modified : /nodejs/bn/widgets/Widget/orderTemplate/BookingTableSchedule/BookingTableSchedule2.js

**Comment by anitalo73** [comment]
測試OK
