### ISSUE TITLE
[預訂位]凡變更人數，點預約時間第二次才會跳下一頁。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1425]
1.沒有變更人數，點預約時間一下，會直接跳下一頁。
2.但只要有變更人數，例如改成5，點預約時間第一下網頁不動，點第二下，才會跳下一頁。請修正此問題。

**Comment by gameflierHao** [comment]
1.沒有變更人數，點預約時間一下，會直接跳下一頁。
-目前預設行為是如此沒錯(預設會去搜尋2人位, 以及最近可接受預訂之日期)

2.但只要有變更人數，例如改成5，點預約時間第一下網頁不動，點第二下，才會跳下一頁。請修正此問題。
人數變更事件改成keyup
預約時間變更事件使用onchange
當重新搜尋時會將可預約時間列表隱藏


Revision: 2696
Author: zhanghaowu
Date: 2018年3月19日 下午 04:00:28
Message:
人數變更事件改成keyup
預約時間變更事件使用onchange
當重新搜尋時會將可預約時間列表隱藏

----
Modified : /nodejs/bn/widgets/Widget/orderTemplate/BookingTableSchedule/BookingTableSchedule2.js

**Comment by anitalo73** [comment]
測試OK
