### ISSUE TITLE
[預訂位]訂位人名為何沒有秀？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1426]
鐵粉絲後台商店，LINE有帶訂位人
http://store.tagfans.com/index.html#page_station?o=6898

鐵粉絲餐飲，LINE沒帶訂位人。
http://store.tagfans.com/#page_join?o=5392&id=29046&viewType=station

![image](https://user-images.githubusercontent.com/35478230/37443421-01f1f6ee-2847-11e8-90d4-3b9dc77c81c7.png)

![image](https://user-images.githubusercontent.com/35478230/37443429-0e1ef908-2847-11e8-80b0-ed95d2b66606.png)

**![image](https://user-images.githubusercontent.com/35478230/37443499-82b40736-2847-11e8-8307-3ec291f70a75.png)**

**Comment by gameflierHao** [comment]
Fixed

Revision: 2695
Author: zhanghaowu
Date: 2018年3月19日 下午 02:53:31
Message:
訂位人不換行(避免畫面過窄裝置Line無法顯示訂位人)

----
Modified : /nodejs/bn/widgets/Widget/orderTemplate/BookingTableSchedule/BookingTableScheduleForm2.js

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/41850675-faa03010-78b7-11e8-90f5-05776cfd97fb.png)
測試OK
