### ISSUE TITLE
[點餐]iphone手機，營業時間跨午夜，預定時間若為非營業時間，仍可成功送單。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1429]
Android平板、電腦會阻擋，是正確的。
![image](https://user-images.githubusercontent.com/35478230/38088178-780bae46-338d-11e8-9faa-416c3bcb3e96.png)

但iphoen沒有阻擋，預定時間選擇非營業時間，仍可成功送單。正確應該要阻擋。

**Comment by huangVic** [comment]
版號 SVN 2724
解決IOS系統 Date錯誤問題

**Comment by anitalo73** [comment]
測試OK
