### ISSUE TITLE
[點餐]選擇辣度，加入購物車，數量會亂跳，不正常。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1430]
http://store.tagfans.com/?o=7303#page_join?o=7303&id=31943&viewType=station

問題一、選擇辣度，再加入購物車，畫面應該要收下來。
問題二、一直點加入購物車，購物車上的數字會倍數成長，不正常。

![image](https://user-images.githubusercontent.com/35478230/38088987-79c58fce-3390-11e8-8e4f-a0ae8981c874.png)

![image](https://user-images.githubusercontent.com/35478230/38089038-aa190098-3390-11e8-8772-d9b9b16f8554.png)

**Comment by huangVic** [comment]
解決版號 SVN 2724
問題一、選擇辣度，再加入購物車，畫面應該要收下來。
> 解決口味後台設定沒有填寫金額與數量的問題。

問題二、一直點加入購物車，購物車上的數字會倍數成長，不正常
> 因問題一產生程式碼錯誤導致畫面沒有正常收起來，所以才可以一直點加入購物車

**Comment by anitalo73** [comment]
測試OK
