### ISSUE TITLE
[LINE機器人]未顯示排隊取號訂單資訊，我的候位資訊也是空的。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1433]
排隊取號後→收到加入LINE ROBOT簡訊→送出驗證碼，未顯示取號資訊。點我的候位資訊，也是空的。

商店：http://store.tagfans.com/#page_station?o=7313

![image](https://user-images.githubusercontent.com/35478230/38137774-532b735a-3459-11e8-99a5-0179ea72cd3a.png)

**Comment by cmacma7** [comment]
fixed.
