### ISSUE TITLE
[點餐]連續上傳多張菜單圖片，按儲存回到菜單頁loading不停

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1435]

**Comment by anitalo73** [comment]
上傳菜單圖片，連續選擇2~3道菜色圖片，儲存後，手機已看到更新的菜單圖片，但電腦網頁loading不停，須關閉瀏覽器，重開網站重新登入，才有辦法繼續編輯菜單。

![image](https://user-images.githubusercontent.com/35478230/38535830-21498c48-3cb8-11e8-8cc2-01c4ad43eec2.png)

**Comment by huangVic** [comment]
@anitalo73 這問題還存在嗎？

**Comment by anitalo73** [comment]
不存在。
