### ISSUE TITLE
[鐵粉絲e訂通]老闆幫新客人點餐，於機器人送出驗證碼後，沒有推出訂單內容。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1438]
用老闆身分，幫客人點餐，填寫客人的電話號碼，送出訂單後，客人收到簡訊，點擊簡訊裡的連結，且到LINE鐵粉絲e訂通畫面送出驗證碼，沒有出現剛剛老闆幫客人點菜的訂單內容。

老闆變更Tagfans後台訂單狀態，客人在鐵粉絲e訂通有收到訂單狀態變更。

正確情況：當客人到鐵粉絲e訂通送出驗證碼後，鐵粉絲e訂通應該要推出剛剛老闆幫客人點餐的訂單內容。

![image](https://user-images.githubusercontent.com/35478230/38795233-20f98d34-418a-11e8-8fe8-acb74a8ce7c5.png)

**Comment by cmacma7** [comment]
currently only reservation and waiting can show the order status.
need to add this feature for ordering.

**Comment by anitalo73** [comment]
老闆幫客人點餐，已可收到LINE訊息。
