### ISSUE TITLE
[點餐]外送外帶，機器人沒有秀。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1441]
![image](https://user-images.githubusercontent.com/35478230/39226395-d537fb36-4884-11e8-84a7-355fab9c2f70.png)
![image](https://user-images.githubusercontent.com/35478230/39226400-dbbf5076-4884-11e8-9bf3-45f5614ca00e.png)

老馬麵食館有「外帶」文字，鐵粉絲餐飲目前沒有帶。

**Comment by gameflierHao** [comment]
Revision: 2796
Author: zhanghaowu
Date: 2018年4月25日 下午 05:18:49
Message:
修正:[點餐]外送外帶，機器人沒有秀。
----
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by anitalo73** [comment]
測試OK
