### ISSUE TITLE
[機器人]預先點餐連結，複製到外部瀏覽器，會自動產生兩筆訂單。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1448]
測試點餐1.10.0版時，於機器人中，複製泰美味這間店的「預先點餐」連結，到外面的瀏覽器chrome，貼上，並且改成debug，送出訂單時，等特別久，大約1分鐘，成功送出後，自動產生兩筆訂單，機器人也同時收到兩則點餐訂單訊息。

![image](https://user-images.githubusercontent.com/35478230/39347293-c290b922-4a24-11e8-864c-c4b51c8d078c.png)

![image](https://user-images.githubusercontent.com/35478230/39347313-cf01610c-4a24-11e8-88f5-d8ef6f991a89.png)

![image](https://user-images.githubusercontent.com/35478230/39347373-1a49537c-4a25-11e8-9607-b46b839e1028.png)

**Comment by cmacma7** [comment]
no need to trace, because this is not a user's usage case.
