### ISSUE TITLE
[機器人]訂單明細→左上瀏覽更多，點餐需重新驗證驗話號碼，應不需再次驗證才是。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1451]
由機器人，我的點餐訂單，點「訂單明細」，進入tagfasn畫面，點左上角「瀏覽更多」，點餐需要再重新驗證電話號碼。應不需再次驗證才是。
![image](https://user-images.githubusercontent.com/35478230/39741634-4194214a-52cd-11e8-9e86-0523f152e213.png)

![image](https://user-images.githubusercontent.com/35478230/39741651-4c691300-52cd-11e8-83de-4b760365f944.png)

**Comment by cmacma7** [comment]
fixed.  now you already login.

**Comment by anitalo73** [comment]
測試OK
