### ISSUE TITLE
[機器人]預先點餐→查詢訂單，查無透過電腦點餐的訂單。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1452]
電腦點餐後，手機成功收到推播，
搜尋商家→店卡片上的「預先點餐」→查詢訂單，沒有顯示電腦點餐的訂單。僅看到透過「預先點餐」連結訂的單。因有收到推播，理應查詢訂單內的與機器人收到推播的單，是對應的。

![image](https://user-images.githubusercontent.com/35478230/39741789-c9991334-52cd-11e8-8432-91f7ee7cf85e.png)

![image](https://user-images.githubusercontent.com/35478230/39741849-f97554fa-52cd-11e8-9469-49c9da3588f0.png)

**Comment by anitalo73** [comment]
test

**Comment by anitalo73** [comment]
test

**Comment by anitalo73** [comment]
test

**Comment by cmacma7** [comment]
hello

**Comment by cmacma7** [comment]
test

**Comment by cmacma7** [comment]
test

**Comment by cmacma7** [comment]
test1

**Comment by cmacma7** [comment]
test2

**Comment by cmacma7** [comment]
teast4

**Comment by anitalo73** [comment]
test

**Comment by anitalo73** [comment]
客人自己用點腦點餐，LINE機器人會收到訊息，且LINE→預先點餐→查詢訂單，查詢得到。

但

老闆幫客人點餐，LINE機器人會收到訊息，但客人的查詢訂單，查不到該筆訂單？

是否老闆幫客人點餐，客人的查詢訂單也應該要可以查得到該筆訂單才對。
