### ISSUE TITLE
[優惠券]兌換紀錄

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1456]
1.兌換握的，應要可以展開，無法使用，要可以查詢序號，事後去核對。
2.報表：兌換紀錄。

**Comment by anitalo73** [comment]
1.兌換握的，應要可以展開，無法使用，要可以查詢序號，事後去核對。
2.報表：兌換紀錄。

**Comment by gameflierHao** [comment]
已加入最後使用時間
並記錄使用次數
