### ISSUE TITLE
[雲端點餐]換菜單照片，更多功能第二次，多了更新葆光菜單，且一般設定無法操作。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1457]
更多功能→一般設定→換照片→編輯→4:3→儲存→更多功能第二次→多了「更新葆光菜單」→一般設定無法操作

![image](https://user-images.githubusercontent.com/35478230/41830172-eba6469e-7871-11e8-8734-109be95e013c.png)

**Comment by huangVic** [comment]
edit 編輯完儲存之後，為何畫面上會產生兩個 cloudMenu 的 div ? 這樣 click 的事件監聽會失效
