### ISSUE TITLE
[艾可國際]專案需求

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1458]
vic整理1~7點
1. 建立商城
2. 建立等一個人咖啡分店
3. 等一個人咖啡點餐介面加上廣告功能
4. 點餐串接點數＆寄杯功能
5. 商城需要建立可以寄杯及儲值的品項
6. 會員系統需顯示寄杯杯數及直接扣杯功能
7. membership 需新增寄杯api 供其他介面查詢跟扣杯

計劃書連結
https://drive.google.com/open?id=1Z1l0p4fQXi6VeQsVy39Vsb_bXOTBmSLd

艾可的商城：http://www.ikuk.com.tw/

**Comment by anitalo73** [comment]
請 CMA 與 Michael 先跟艾可簽約。

**Comment by cmacma7** [comment]
Their 商城 is pretty good, cannot find a good reason to change it.

**Comment by anitalo73** [comment]
艾可6/28會議討論CMA

1.商城。團媽的
2.菜單。
(1&2先試試看，兩種入口，看他們喜歡哪一種。)

3.等一個人咖啡的店面。

Luca已開好帳號密碼。

信用卡申請：2.3%
簽約：賣到一千萬或一億。手續費低一點。
淨銷存：換找偉盟的系統。

**Comment by anitalo73** [comment]
艾可的tiffy提出，希望有xls匯入建檔的功能。
馬成已回覆：

Execel匯入的功能因為每一家寫的格式都不一樣，我們只接受我們的標準格式。 如果要把你們的格式轉成我們的標準格式的話我們這邊有一個20,000塊錢的標準收費。 好處是以後你們都可以用你們自己的格式輸入， 如果有上千件商品的話，我建議讓我們工程師幫你們做這個客制化。 但是如果只有100件左右商品的話，手動輸入應該會快很多
