### ISSUE TITLE
預約訂位UI

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1469]
增加營業時段→設定「+」
增加座位資訊→設定「+」

目前的UI呈現，兩個button似乎是頁籤的概念，cma提可以用「+」的方式表示新增。

**Comment by gameflierHao** [comment]
Revision: 3023
Author: zhanghaowu
Date: 2018年7月17日 下午 04:33:13
Message:
Fixed issue # 預約訂位UI #1469
https://github.com/cmacma7/bn/issues/1469
----
Modified : /nodejs/bn/widgets/Widget/orderTemplate/BookingTableSchedule/BookingTableSchedule2.js
