### ISSUE TITLE
預約訂位：是不是每張桌應該用餐時間要一樣

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1477]
每張桌的用餐時間，如果都不一樣，會不會很混亂，就訂位的邏輯上，是不是每張桌應該用餐時間要一樣？(待討論)

桌數與用餐時間的設定分開

![](https://i.imgur.com/eb759vp.png)

**Comment by gameflierHao** [comment]
我覺得可以再討論
情境:
二樓區域過22點後不開放 只開放一樓區域
