### ISSUE TITLE
口味作法如何限制至少必選一種。 <1.12.0>

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1482]
口味作法如何限制至少必選一種。

**Comment by huangVic** [comment]
是否有必要老闆帳號或是 POS介面不需要限制？

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/42082929-edf502bc-7bbb-11e8-90c9-7a08872bc0d3.png)

現在口味無論如何都必須要選嗎？
我最多數量最少數量都改成0了，它還是要我必選一種。
我原本是想說，改成 1、1就必選，改成0、0，就可以不選。

你覺得呢？

**Comment by anitalo73** [comment]
vic回覆LINE。
![image](https://user-images.githubusercontent.com/35478230/42103852-00d29340-7bfd-11e8-9225-1c466c808362.png)


測試OK

**Comment by anitalo73** [comment]
OK
