### ISSUE TITLE
[套餐]改訂單成立後的呈現方式

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1487]
改訂單成立後的呈現方式
1.widget
2.進印表機
3.進line機器人：

**Comment by gameflierHao** [comment]
3.進line機器人：
Revision: 2993
Author: zhanghaowu
Date: 2018年6月27日 下午 07:00:58
Message:
Add item taste when send mail to line robot
----
Modified : /nodejs/bn/widgets/Modules/POSMenu.js
