### ISSUE TITLE
[涓豆腐機器人]新電話號碼，驗證後，總店有LINE驗證，分店無LINE驗證，因此分店無法發優惠券。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1488]
用新的電話號碼0988165024 (先電話驗證，再搜尋店→點餐。)
1.直接先做電話驗證→總店membership有LINE驗證紀錄。
2.分店點餐→分店membership無LINE驗證紀錄。
![image](https://user-images.githubusercontent.com/35478230/41975071-470560fc-7a4c-11e8-8a7c-58e87e043cf8.png)

----------------------------------------------
----------------------------------------------
0922196886：(未電話驗證，先搜尋店→點餐。)

1.新顧客→掃QRcode→搜尋店家→預先點餐→點完餐→涓豆腐機器人收到點餐訊息→
2.membership寫入此新客戶資料，
總店有LINE驗證，
分店無LINE驗證，無LINE驗證→優惠券無法發送。

3.回去再點驗證電話號碼，顯示已完成驗證。→正確。
但分店無LINE驗證無法發優惠券，是只能總店發嗎？還是？

![image](https://user-images.githubusercontent.com/35478230/41974983-0e45e534-7a4c-11e8-847d-9e513f855198.png)

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/42009952-200d15f8-7abf-11e8-9eaa-d991c4d5f2df.png)

我剛剛再找一個新的電話號碼來驗證，分店有LINE驗證了，所以可以發優惠券了。
(昨天是分店沒有LINE驗證，不能發優惠券，情況不太一樣)

只是，總店顯示的LINE驗證怪怪的.....7651在分店有LINE驗證，在總店沒有LINE驗證。

**Comment by cmacma7** [comment]
There is another problem that the row number is repeated. headquarter row number conflict with child store row number. Both need to fix.

**Comment by cmacma7** [comment]
fixed by not showing child store users.

**Comment by anitalo73** [comment]
總店現在看不到分店的會員了是嗎？

**Comment by cmacma7** [comment]
yes
