### ISSUE TITLE
LINE機器人點印用卡付款，轉不到信用卡付款頁面去。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1490]
LINE機器人點印用卡付款，轉不到信用卡付款頁面去。

涓豆腐LINE機器人裡，水美味，可試。

電腦開沒問題喔
是機器人Line browser不行

http://eat.tagfans.com/index.html?meid=w6zCvcOaVUvCssOqXinCnw7ChinCqHzDnsKkw5bCiMOvE8KmwqbCp8Olw6tPU8OYwofDkGA4Tx01JsKhYcKiw58nesOEARvCmXFawpbDqTLDmkXCpMOaJMOm#page_join?o=7313&id=31993&viewType=station

![image](https://user-images.githubusercontent.com/35478230/42081556-54938f38-7bb8-11e8-8ceb-220858feeeee.png)

**Comment by peichingliao** [comment]
請steve開通eat的信用卡付款

**Comment by peichingliao** [comment]
steve說已開通

**Comment by anitalo73** [comment]
測試OK
