### ISSUE TITLE
未開始的優惠券，仍可開啟核銷編號及核銷QRcode

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1491]
未開始的優惠券，仍可開啟核銷編號及核銷QRcode。

是否應該要整個鎖起來？

![image](https://user-images.githubusercontent.com/35478230/42101792-c5be80c6-7bf6-11e8-97ab-2f0f3e7c77d2.png)

![image](https://user-images.githubusercontent.com/35478230/42101799-cb380644-7bf6-11e8-8d28-9b6e67262e46.png)

**Comment by cmacma7** [comment]
目前只看有沒有過期，所以是核銷的部分必須拒絕核銷期限之外的。 應該是說在期限之外應該不准使用

**Comment by gameflierHao** [comment]
Revision: 3011
Author: zhanghaowu
Date: 2018年7月16日 上午 11:28:59
Message:
1. 修改優惠卷圖片
2. 新增log記錄
3. FIXED:未開始的優惠券，仍可開啟核銷編號及核銷QRcode

目前未開始和過期以及使用過的優惠卷 皆不會看到核銷編號及核銷QRcode
----
Modified : /nodejs/bn/widgets/Widget/Coupons/template_singleCoupon_basic.js

**Comment by anitalo73** [comment]
測試OK

![image](https://user-images.githubusercontent.com/35478230/42745669-94ce5bae-8906-11e8-95b9-810364528b87.png)

![image](https://user-images.githubusercontent.com/35478230/42745671-996049e8-8906-11e8-9e3a-1bb57411a4b5.png)
