### ISSUE TITLE
QRcode核銷優惠券，拍QRcod需登入電話號碼？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1493]
拍QRcod為什麼要登入電話號碼？
不是老闆手機有登入老闆帳號即可嗎？
safari  會有問題，
chrome 正常。

![image](https://user-images.githubusercontent.com/35478230/42758124-f5b38dd0-8934-11e8-8973-22ec6d0cbe6c.png)

![image](https://user-images.githubusercontent.com/35478230/42758132-fcebea52-8934-11e8-9aa7-2f6adea21c39.png)

![image](https://user-images.githubusercontent.com/35478230/42758141-03c42326-8935-11e8-91bd-ad04501a7f9a.png)

**Comment by gameflierHao** [comment]
無法重現問題
請確認網域是否登入正確

**Comment by anitalo73** [comment]
測試案例是，store的老闆，因此有次問題。
未來客人如果用fb帳號登入，皆需從eat登入，
