### ISSUE TITLE
優惠券過期，應該要不可發送。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1499]
![image](https://user-images.githubusercontent.com/35478230/42687865-cd595e2e-86cc-11e8-9802-603a50471054.png)

![image](https://user-images.githubusercontent.com/35478230/42687870-d1d5e062-86cc-11e8-8cdf-1a3df06b6969.png)

**Comment by cmacma7** [comment]
Fixed on version 3016. please try on store/debug to verify. Expired coupon will not show up in the lists.

**Comment by anitalo73** [comment]
測試確認OK，degbu環境，membership發送優惠券列表，看不到已過期的優惠券。
