### ISSUE TITLE
優惠券標題與核銷序號QRcode壓字

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1501]
![image](https://user-images.githubusercontent.com/35478230/42745610-50bb1a60-8906-11e8-8230-41cb9b628792.png)

**Comment by gameflierHao** [comment]
Revision: 3020
Author: zhanghaowu
Date: 2018年7月17日 下午 02:45:52
Message:
Fixed issue #1501 優惠券標題與核銷序號QRcode壓字
https://github.com/cmacma7/bn/issues/1501
----
Modified : /nodejs/bn/widgets/Widget/Coupons/template_singleCoupon_basic.js

**Comment by anitalo73** [comment]
測試OK
