### ISSUE TITLE
開發票/印發票API 

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1506]

**Comment by cmacma7** [comment]
When user pay by creditcard to purchase on-line, system will call sendMail( actions[pendingMQTTSendInvoice, ...])
When the boss want to issues or print invoice at store, system call sendMail ( actions[MQTTSendInvoice, ...])
When customer want to cancel the credit card payment, system call cancelOrder( oid, order), the oid will be used to cancel the credit card, and order is used to cancel order and cancel the points or credits.
Both pendingMQTTInvoice and MQTTInvoice are in the same format

if (actions.server[i].method == "MQTTSendInvoice" || actions.server[i].method == "pendingMQTTSendInvoice"){
  var orderContext ={
	gid: data.gid,
	stid:data.stid,
	noteId:data.noteId,
	srcId:data.srcId,
	cat: 100, // wish to receive notification
	uid: receivers[0], //  the id who receive the order (in general is the store owner)
	senderId: socket.sqlUid, // the id who put the order 
  }

  var clientData = actions.server[i].data; // this is the data section that contain order details 

  if (actions.server[i].method == "pendingMQTTSendInvoice"){
     // insert the action into DB, and wait for payment complete callback to execute the pending action using TBoxSendInvoice just as below 
  }
  else {
    TBoxSendInvoice(data.isIssue, data.isPrint, {gid:data.gid}, data.noteId /*uniqueId*/, JSON.stringify(orderContext), clientData);
  }
}
