### ISSUE TITLE
[menu] 某分類，前台顯示不完整。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1509]
![image](https://user-images.githubusercontent.com/35478230/42810642-fca003f6-89ea-11e8-8958-fb47d44b18c3.png)

**Comment by huangVic** [comment]
![111](https://user-images.githubusercontent.com/5910437/42840932-fc9e8648-8a3a-11e8-9fc8-3a59bbb1d219.jpg)
![2](https://user-images.githubusercontent.com/5910437/42840944-0683fe22-8a3b-11e8-869b-fedfa9c7a078.jpg)

品項序號重複導致，請修正！

**Comment by huangVic** [comment]
![2](https://user-images.githubusercontent.com/5910437/42864157-0f2a7eb8-8a98-11e8-9a22-62dc69a1a1f4.jpg)
![111](https://user-images.githubusercontent.com/5910437/42864158-0f6e23f2-8a98-11e8-9e93-ebc066d7cd78.jpg)

出現重複itemno
