### ISSUE TITLE
[membership] 發送/核銷點數，機器人沒有推訊息。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1512]
目前[membership] 發送/核銷點數，機器人沒有推訊息。

建議與會員前端系統同步

凡是發送及核銷優惠券、點數，發送文字訊息，機器人都會同步推出資訊。

http://store.tagfans.com/admin/index.html

![image](https://user-images.githubusercontent.com/35478230/42981849-02ea3bd2-8c11-11e8-9dc5-95aea2cd8ce0.png)

**Comment by anitalo73** [comment]
重新定義memebership給點數核銷點數不push LINE

**Comment by cmacma7** [comment]
I think we should not send line message to user for membership management page.
