### ISSUE TITLE
[取號]我要取新的號碼，預設有先幫客人輸入的按鈕，第二次取號沒有先幫客人先選好？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1513]
### 第一次取號
![image](https://user-images.githubusercontent.com/35478230/42984100-68633ae8-8c1d-11e8-81f4-6e14e2f80497.png)
---
---
### 我要取新的號碼
![image](https://user-images.githubusercontent.com/35478230/42984136-97fee7d4-8c1d-11e8-93fd-59c73cf61059.png)

**Comment by peichingliao** [comment]
r.3033已修正
store已上線

**Comment by anitalo73** [comment]
目前老闆取號頁面，沒有下半部的設定最新取號號碼喔，

設定取號號碼在另一個widget

![image](https://user-images.githubusercontent.com/35478230/42990609-afce3ab4-8c35-11e8-9fa3-b3677b7911a5.png)


---
---


設定取號號碼在另一個widget

![image](https://user-images.githubusercontent.com/35478230/42990645-cf477a5e-8c35-11e8-9c5c-04bdac7feaba.png)

**Comment by anitalo73** [comment]
取號設定功能先在老闆的取號介面打開來，帶樂麵屋取號完成，再一起隱藏，由另一個新的widget設定新的取號號碼。
