### ISSUE TITLE
[機器人]push訊息同步點餐系統文案修改，外帶→自取。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1514]
![image](https://user-images.githubusercontent.com/35478230/42987105-b0542b98-8c2a-11e8-9932-394d48f82c12.png)

![image](https://user-images.githubusercontent.com/35478230/42987166-e0eabf88-8c2a-11e8-9975-5eea452ddb67.png)

**Comment by gameflierHao** [comment]
Revision: 3031
Author: zhanghaowu
Date: 2018年7月20日 下午 02:38:55
Message:
1. Fixed issue #1514 [機器人]push訊息同步點餐系統文案修改，外帶→自取
2. Add lovecode,crno,crtype
----
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by anitalo73** [comment]
讚
![image](https://user-images.githubusercontent.com/35478230/42989310-fd53688a-8c31-11e8-8773-0ad00b4a2061.png)
