### ISSUE TITLE
[Membership] admin/index.html 發文字訊息，斷線控制。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1517]
網路斷線時，送出訊息，系統回應「信息已發出」，實際LINE無收到push。

![image](https://user-images.githubusercontent.com/35478230/42989992-f8db0572-8c33-11e8-9ec5-8a5240fc34e3.png)

**Comment by cmacma7** [comment]
Fixed by alert user on failed coupons, ask user to close the dialog then resend!
