### ISSUE TITLE
[Membership] admin/index.html 發優惠券，斷線控制。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1518]
選擇優惠券後→中斷連線→按確認扭無反應
停在此頁→恢復網路連線→按確認扭仍無反應。

是否應該恢復網路連線後，在原頁面，要可以繼續發出優惠券的動作？

![image](https://user-images.githubusercontent.com/35478230/42991197-7bdc6832-8c37-11e8-9848-1896943f0f16.png)

**Comment by cmacma7** [comment]
Fixed by alert user on failed coupons, ask user to close the dialog then resend!
