### ISSUE TITLE
[套餐]套餐內的飲品是以品項「原價」價格須加錢的，購物車金額與訂單金額不相同。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1524]
![image](https://user-images.githubusercontent.com/35478230/43514496-eea5c712-95b2-11e8-8541-8b183d158aea.png)

![image](https://user-images.githubusercontent.com/35478230/43514511-f68943be-95b2-11e8-9bb8-451a34ccc006.png)

![image](https://user-images.githubusercontent.com/35478230/43514533-02232ee2-95b3-11e8-8065-375a049576ce.png)

![image](https://user-images.githubusercontent.com/35478230/43514563-0b581f7c-95b3-11e8-921e-cadb3e2fb3e3.png)

![image](https://user-images.githubusercontent.com/35478230/43514576-0f58aaba-95b3-11e8-9ba2-345cc1bb70d8.png)

**Comment by huangVic** [comment]
cloud.menu.1.13.0 已修正
