### ISSUE TITLE
[cloud menu] 樂子直接寫入葆光，桌號為空白？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1528]
樂子直接寫入葆光，桌號為空白？

![image](https://user-images.githubusercontent.com/35478230/43577227-e1161f68-967d-11e8-94f0-0424f9428693.png)

**Comment by anitalo73** [comment]
應是連線讀取問題。
菜單port不經常切換，固定抓同一個位置菜單，再觀察看看有無此狀況。

**Comment by anitalo73** [comment]
8/3，
樂子這個桌號檔也很不穩定，我今天測又出現這樣，重新整理好幾次也是。
昨天以前也經常抓不到桌號，推論可能是昨天以前菜單一直切換導致抓不到的關係，
不過，今天都沒有再切換菜單了，仍然又抓不到桌號耶。

![image](https://user-images.githubusercontent.com/35478230/43621998-94109cfe-970c-11e8-919b-e149fa401a64.png)

**Comment by gameflierHao** [comment]
DONE
1. BNSERV開了2個
2. POSMenu收到空的座位表時 不寫入
