### ISSUE TITLE
[發票]老闆訂單已開立發票，客人訂單尚未開立發票。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1538]
![image](https://user-images.githubusercontent.com/35478230/43697528-66b335f6-9977-11e8-9117-af96ec9e6a1c.png)

老闆作廢發票，客人看到的仍是尚未開立。
![image](https://user-images.githubusercontent.com/35478230/43697702-78a24c74-9978-11e8-88a9-88bb368895ee.png)

**Comment by cylee405** [comment]
fixed on debug

**Comment by anitalo73** [comment]
測試OK

![image](https://user-images.githubusercontent.com/35478230/43705792-2ee6580a-9996-11e8-8dad-0b0026d2593c.png)
