### ISSUE TITLE
[銷售分析] 客戶摘要，只有顯示「姓」，「名」沒有顯示喔。(除了老馬麵食館以外的店)

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1550]
http://store.tagfans.com/debug/admin/menu.html

客戶摘要，只有顯示「姓」，「名」目前沒有顯示，「名」也應該要顯示喔。因大部分LINE抓回來的名字都是寫在「名」這個欄位。

另問，目前membership有名字是經過LINE機器人驗證的，是否membership可以增加一個欄位是客人在訂單上輸入的名字。(據觀察，客人下訂單會寫真名、真姓，但LINE裡會用小名或英文名字，通常餐廳老闆記得的是訂單上的真名，不認識LINE抓回來的小名。)

![image](https://user-images.githubusercontent.com/35478230/43828521-549846f4-9b2f-11e8-8cb8-4f415173787b.png)

---
---
涓豆腐分店，只有顯示「姓」，「名」目前沒有顯示。
![image](https://user-images.githubusercontent.com/35478230/43832816-3c600548-9b3b-11e8-82c6-847db83ef772.png)
-----------------------------------------------------------------
-----------------------------------------------------------------

老馬麵食館，抓的是顧客的「名」。
![image](https://user-images.githubusercontent.com/35478230/43821546-10a15b2e-9b1c-11e8-9c8a-d1a31606343b.png)

**Comment by cmacma7** [comment]
fixed by reference root store names. Originally we didn't refer to root store user names
