### ISSUE TITLE
[新版Tbox] 點餐預設圖片未顯示

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1552]
點餐預設圖片未顯示

/uploads/1523552981597.png
/uploads/1523553019511.png
/uploads/1523552950623.png

/uploads/1523553854392.png

![image](https://user-images.githubusercontent.com/35478230/43873543-88bd22b2-9bb9-11e8-9c76-25572b4021ea.png)

**Comment by cmacma7** [comment]
Need to have link to the pictures.

**Comment by anitalo73** [comment]
/uploads/1523552981597.png
/uploads/1523553019511.png
/uploads/1523552950623.png
/uploads/1523553854392.png
