### ISSUE TITLE
[發票] 老闆帳號下的訂單，有印發票，但是查詢訂單，沒有發票資訊。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1553]
老闆帳號下的訂單，有印發票，但是查詢訂單，沒有發票資訊。
![image](https://user-images.githubusercontent.com/35478230/43877419-3c793842-9bcc-11e8-8177-a387203dd49f.png)

**Comment by anitalo73** [comment]
因老闆帳號不需要選擇付款資訊，

所以發票資訊跑起來。

**Comment by peichingliao** [comment]
debug已修正

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/43887353-2e581c4a-9bf1-11e8-9d67-92f206ca6fd3.png)
測試OK

**Comment by anitalo73** [comment]
老闆代客下單，老闆看到的訂單，應該不需要有「付款去」的按鈕吧？

![image](https://user-images.githubusercontent.com/35478230/43948990-eb75866e-9cbe-11e8-8054-b6d4b242f84f.png)
