### ISSUE TITLE
[發票] 前端，個人載具，格式需要check

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1557]
function isCrNoValid(crNo){return crNo.match(/^\/{1}[A-Z0-9\.\-\+]{7}$/)?true:false}

**Comment by huangVic** [comment]
cloud.menu.1.13.0 已增加此功能

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/43947965-0662d7a4-9cbc-11e8-9904-cfc5e506fd95.png)

**Comment by huangVic** [comment]
驗證與送出訂單時將自動轉成大寫
