### ISSUE TITLE
[點餐折扣] 選單文字顯示不完全。cloud.menu.1.13.0 

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1558]
選單文字顯示不完全。

![image](https://user-images.githubusercontent.com/35478230/43942886-455947be-9cac-11e8-817c-77cd908f271a.png)

**Comment by huangVic** [comment]
CSS 已修正

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/44130532-a1af2448-a080-11e8-9c2a-3e900ae41a73.png)
測試OK
