### ISSUE TITLE
[發票] 查詢訂單資訊，除了日期、發票號碼，需再顯示「載具編號、捐贈碼、統編」。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1559]
訂單資訊：目前有日期、發票號碼、

需再顯示「載具編號、捐贈碼、統編」

![image](https://user-images.githubusercontent.com/35478230/43944730-7f64623a-9cb2-11e8-85c4-26258c604c36.png)

**Comment by peichingliao** [comment]
r.3101 已修正
debug已更新
