### ISSUE TITLE
[發票] 捐贈發票，愛心碼格式需check。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1560]
捐贈發票，愛心碼格式需check。

![image](https://user-images.githubusercontent.com/35478230/43944913-28ff589a-9cb3-11e8-88ed-40b9a84d5da0.png)

**Comment by huangVic** [comment]
已加入驗證格式
-----------------
總長度為3至7碼字元
全部由數字組成

**Comment by huangVic** [comment]
已加入API查詢是否有此愛心捐贈碼
