### ISSUE TITLE
[cloud menu] 無法完整刪除菜單，重新複製別家菜單，會有原本的「品項序號」殘留。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1561]
水美味cloud menu原有菜單，逐一勾選分類，進行全部刪除。

再重新執行複製menu的程式： copyMenu(6254); 

發現有原來的菜單名稱共用「品項序號」殘留。

![image](https://user-images.githubusercontent.com/35478230/43946032-a1f65e8a-9cb6-11e8-9f6d-760fe4bbfa79.png)

**Comment by cmacma7** [comment]
use deleteMenu() before copyMenu() to make sure all items are deleted before you can copy from other stores.
