### ISSUE TITLE
[點餐] 老闆折扣功能，訂單成立後，沒有計算到折扣金額。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1563]
![image](https://user-images.githubusercontent.com/35478230/43948333-22c09304-9cbd-11e8-9410-c4d42986593e.png)

![image](https://user-images.githubusercontent.com/35478230/43948274-01345f7c-9cbd-11e8-9ba5-f14cb9a97b66.png)

**Comment by huangVic** [comment]
已修正
