### ISSUE TITLE
[點餐] 外帶，老闆代客下單，點「結帳」後，原本填好的「地址、公司」兩個欄位會被清空。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1564]
### **外帶，老闆代客下單，原本填好的所有欄位。**
![image](https://user-images.githubusercontent.com/35478230/43949170-51ec94aa-9cbf-11e8-8677-6b0e18d26eb4.png)

### **點「結帳」後，原本填好的「地址、公司」兩個欄位會被清空。**

![image](https://user-images.githubusercontent.com/35478230/43949207-713f1a62-9cbf-11e8-8763-9e9c1d33979c.png)

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
地址還是又被清掉囉！！

![image](https://user-images.githubusercontent.com/35478230/44131871-4add4ffc-a088-11e8-9d9f-c5cb61588f0b.png)

**Comment by huangVic** [comment]
新版本已修正

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/44138867-e3fbc834-a0a7-11e8-8aaa-9d9a535ec6f9.png)
檢測OK
