### ISSUE TITLE
[點餐折扣] 前一筆訂單成立後，折扣的快取沒有清除，新選擇下一筆訂單的商品，仍套用上一張單的折扣內容。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1565]
前一筆訂單成立後，折扣的快取沒有清除，

新選擇下一筆訂單的商品，仍套用上一張單的折扣內容。

![image](https://user-images.githubusercontent.com/35478230/43949654-be96514e-9cc0-11e8-8122-86273d9780db.png)

**Comment by huangVic** [comment]
已修正
