### ISSUE TITLE
[點餐訂單] 老闆代客下單，老闆看到的訂單，應該不需要有「付款去」的按鈕。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1566]
老闆代客下單，老闆看到的訂單，應該不需要有「付款去」的按鈕。

![image](https://user-images.githubusercontent.com/35478230/43950374-b810a8ea-9cc2-11e8-9375-b5b87a4a8d70.png)

**Comment by peichingliao** [comment]
r.3097已修正
debug已更新
