### ISSUE TITLE
[點餐] 串接葆光的顏色不見了。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1572]
![image](https://user-images.githubusercontent.com/35478230/44129004-b4f223f0-a078-11e8-84db-78ee3c2d6014.png)

**Comment by gameflierHao** [comment]
斷電造成 POS PORTING CODE REVERSE

**Comment by anitalo73** [comment]
上次更新沒壓CODE

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/44130638-08e7bc24-a081-11e8-88ab-876aa7eba507.png)
