### ISSUE TITLE
[點餐] 老闆折扣，於選折扣後所選的品項，以原價計算沒有打折。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1573]
![image](https://user-images.githubusercontent.com/35478230/44131730-7ed67f82-a087-11e8-8151-7d8a1d1b6f6f.png)

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
有品項的商品，折扣仍有問題。

**Comment by huangVic** [comment]
已修正口味品項需重新計算折扣
