### ISSUE TITLE
[發票] 菜名有「'」訂單成功送出後，發票皆開立失敗。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1575]
菜名是The Owner's Speciality，含有「'」。

訂單成功送出後，發票皆開立失敗。

重開發票，也失敗。

![image](https://user-images.githubusercontent.com/35478230/44190506-b96eae80-a159-11e8-8482-c27b3be8314a.png)

![image](https://user-images.githubusercontent.com/35478230/44190511-bffd2600-a159-11e8-8384-942f3ce6aba2.png)

![image](https://user-images.githubusercontent.com/35478230/44190514-c4294380-a159-11e8-98b3-b064912e9d34.png)

**Comment by cylee405** [comment]
fixed
