### ISSUE TITLE
[點餐] 美妙山平板acer 10吋，使用APP時，折扣、開錢箱按鈕被遮住了。(使用chrome瀏覽器正常)

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1579]
[點餐] 美妙山平板acer 10吋，使用APP時，折扣、開錢箱按鈕被遮住了。(使用chrome瀏覽器正常) 

![image](https://user-images.githubusercontent.com/35478230/44326175-66fcfd00-a48d-11e8-9b4b-79d4008cb2ff.png)

![image](https://user-images.githubusercontent.com/35478230/44326189-73815580-a48d-11e8-8339-cb570c8fcecd.png)

**Comment by huangVic** [comment]
cloud.menu.1.13.1 已修正
