### ISSUE TITLE
優惠券的注意事項，排版要如何會折行？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1585]
優惠券的注意事項，排版要如何會折行，我嘗試加<br>也沒有用。

![image](https://user-images.githubusercontent.com/35478230/45523987-bde0c280-b7fe-11e8-83da-5cf3f0f3b0a1.png)

馬成指導：Howard 如果你是用 ｛{ }} 在template裏， 改成｛｛｛ ｝｝｝ 就可以接受 html tag。

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/45532394-71a97880-b826-11e8-87cf-f3ac6d445b2d.png)


機器人也顯示<br>

**Comment by gameflierHao** [comment]
DONE
改用/n方式取代BR進行換行
