### ISSUE TITLE
[優惠券] 事件設定，check button與項目說明排版，請調整。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1586]
![image](https://user-images.githubusercontent.com/35478230/45524262-22505180-b800-11e8-82a4-9eb900123ccc.png)

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/45532442-aae1e880-b826-11e8-9752-1b35cc1c4007.png)

應該可以更好。

希望可以如下排版：
O滿意度調查表
O滿意度調查表
O滿意度調查表
O滿意度調查表

**Comment by gameflierHao** [comment]
DONE

**Comment by gameflierHao** [comment]
![1536917646163](https://user-images.githubusercontent.com/1106733/45542423-6c5b2680-b844-11e8-92cd-353e93f6e149.jpg)
