### ISSUE TITLE
[優惠券事件]填完滿意度調查表後，沒有送優惠券。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1589]
![image](https://user-images.githubusercontent.com/35478230/45528173-c098e300-b811-11e8-83a5-9aa670fbb4d0.png)

**Comment by gameflierHao** [comment]
http://store.tagfans.com/index.html#page_join?o=7523&id=32635&viewType=station

須配合新版滿意度CONTEXT

**Comment by anitalo73** [comment]
測試ＯＫ
