### ISSUE TITLE
[滿意度調查表]填完後，機器人回覆的訊息，「客戶名稱」請修正。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1590]
目前是抓取登入store的名稱，
如果客戶是登入電話，顯示名稱「+886電話號碼，且少三碼」很怪，請修正為客人在滿意度調查表填寫的姓名，若沒有填姓名，就不要在機器人顯示名稱。

![2018-09-14 11 32 02](https://user-images.githubusercontent.com/35478230/45528313-4157df00-b812-11e8-95c3-ec619f11cafe.png)

**Comment by gameflierHao** [comment]
更改為:
4230891-00036-問券調查表:感謝你的意見

**Comment by anitalo73** [comment]
測試ＯＫ
