### ISSUE TITLE
[座位設定]桌號設定相同，鎖住畫面，無法編輯。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1600]
![image](https://user-images.githubusercontent.com/35478230/46191757-3f6e3f80-c32b-11e8-865d-072e02e89df9.png)

**Comment by gameflierHao** [comment]
Revision: 3166
Author: zhanghaowu
Date: 2018年10月1日 上午 11:43:58
Message:
編輯context時,會檢查區域名稱是否重複.
fixed [座位設定]「區域」設定相同時，會鎖住，無法再修改。 #1599
fixed [座位設定]桌號設定相同，鎖住畫面，無法編輯。 #1600
----
Modified : /nodejs/bn/widgets/Widget/Order System/template_tagfansTable_editor.js
