### ISSUE TITLE
[平板點餐] 輪播廣告切回點餐的控制

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1603]
平板點餐，待機畫面進入輪播廣告時，點右半邊的區域，回到點餐頁面回跳兩下進入口味選擇，

點左半邊區域則不會有這樣的問題，會正常地停在點餐列表上。

正常情況，點右半邊區域，應該也要停在點餐列表上。

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
測試ＯＫ
