### ISSUE TITLE
[自動排位] 從自動排位系統叩客，報號系統的叫號號碼不會更新。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1610]
尚未找到原因。

**Comment by anitalo73** [comment]
只有阿水電腦有此問題。
vic howard電腦正常

**Comment by anitalo73** [comment]
真正原因，重新整理報號，報號會是舊的號碼。
僅有自動排位請顧客入座有此問題。
訂單報表叫好號，無此問題。

**Comment by anitalo73** [comment]
### Howard

![image](https://user-images.githubusercontent.com/35478230/46811480-715cb880-cda5-11e8-833e-8441f6e4c4a2.png)

這邊應該要放報號ID和下面POST的一樣。

還是上面那個是必要的,那下面還要upsertObject到報號一次,再請Vic再看一下~

**Comment by huangVic** [comment]
上面那張圖少了很多寫入內容, 版本 cloud.inline.1.0.1 已修正此問題。
# 主要問題是報號的時候沒有把號碼寫入DB 儲存，導致報號頁面雖然有收到 post 訊息，但重新整理頁面之後去DB 拿取號碼就還會是舊號碼。

**Comment by anitalo73** [comment]
測試OK
