### ISSUE TITLE
[debug membership] 無法手動新增會員

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1611]
點「新增」＋popup上的「新增」，一直停在此畫面。
重新整理，仍未見新增的會員資料。

![image](https://user-images.githubusercontent.com/35478230/46546594-0ec67100-c8fc-11e8-917f-6fbfaf3c9629.png)

**Comment by cmacma7** [comment]
To create a new member, you must enter the phone in the popup window. otherwise a new row cannot create.

**Comment by anitalo73** [comment]
test OK
