### ISSUE TITLE
[儲值扣點] 若後台有開啟折扣，客人選擇扣點消費時，應忽略context給予的折扣。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1620]
若後台有開啟折扣，客人選擇扣點消費時，應忽略context給予的折扣。

因扣點消費已享有admin/menu.html中Redeem欄位設定的credit。

![image](https://user-images.githubusercontent.com/35478230/47058603-4c7aa200-d1f8-11e8-96b4-2189f23ad49e.png)

**Comment by huangVic** [comment]
因品項在點數的制定上原本就可以和原價格有所不同, 例如 咖啡品項原價＄100元, 但點數設定上可以制定為 80點, 因此已經打折了, 故原本折扣上就不在需要打折一次

**Comment by anitalo73** [comment]
測試ｏｋ
