### ISSUE TITLE
[電子發票] 電腦版safari，用客人身份下單，選擇發票類型的排序，是老闆的排序。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1623]
電腦版safari，用客人身份下單，選擇發票類型的排序，是老闆的排序。

手機上的safari正常，發票類型選擇，是客人的排序。

![2018-10-17 11 21 37](https://user-images.githubusercontent.com/35478230/47060126-e0e80300-d1fe-11e8-9445-7b12c73e2a83.png)

**Comment by huangVic** [comment]
已改排序方式, 預設是紙本發票, 要存手機載具再讓客人自行切換
