### ISSUE TITLE
[直傳銷系統] 透過LINE機器人下單的訂單，沒有寫入membership的銷售分析。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1624]
vic和anita對應測試
在LINE機器人下單的訂單，沒有寫入membership的銷售分析。
透過手機外部瀏覽器，或電腦下單的訂單，都有正常寫入membership的銷售分析。

**Comment by cmacma7** [comment]
It is the GID and MEID problem. Fixed by change bn.js to handle meid case that will fetch order information from 226 db. Originally meid case does not fetch order info, so fail to send the order to robot DB.
