### ISSUE TITLE
[儲值]購物車列表上的點數，不會隨著商品數量增加喔。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1633]
購物車列表上的點數，不會隨著商品數量增加喔。

但購物車的總點數是有乘上商品數量的。

![image](https://user-images.githubusercontent.com/35478230/47285804-e25e6480-d61e-11e8-9e69-17e3799e89c2.png)

**Comment by huangVic** [comment]
已修正 cloud.menu.1.15.0

**Comment by anitalo73** [comment]
測試OK
