### ISSUE TITLE
[context客人自訂文字]對應訂單、LINE訊息也要相同。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1635]
![image](https://user-images.githubusercontent.com/35478230/47336583-f8256580-d6c2-11e8-9376-4b3b4da5dad7.png)

![image](https://user-images.githubusercontent.com/35478230/47336614-06738180-d6c3-11e8-84a4-73021292bf2a.png)

**Comment by huangVic** [comment]
「外送」文字：context.widget.context.deliveryService.deliveryTitle
「取餐時間」文字：context.widget.context.reserveText

請 @gameflierHao 在成立訂單時將文字部分修正

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/47493076-091bd580-d881-11e8-9ccc-5c9bba07fb7c.png)


![image](https://user-images.githubusercontent.com/35478230/47493112-1a64e200-d881-11e8-951c-b551bb0b8827.png)


測試OK
