### ISSUE TITLE
[LINE機器人] FER下單，正確應透過FER的LINE通知，目前會透過E訂通回覆給客人。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1639]
FER下單，目前會透過E訂通回覆給客人。

正確應透過FER的LINE通知回覆。

![image](https://user-images.githubusercontent.com/35478230/47472715-444ae400-d842-11e8-96ed-cfc4f060db49.png)

**Comment by anitalo73** [comment]
請到FER的LINE封鎖再重新加入，就會重新驗證電話號碼，再重新下單，就會是FER的LINE通知了，點「我的訂單」也會有資料。

**Comment by cmacma7** [comment]
so this is fixed?

**Comment by anitalo73** [comment]
yes, 這個是客戶操作問題，不是bug。
