### ISSUE TITLE
2015.04.16 UI bugs

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#164]
1. 主頁>管理>把User不應看到的選項隱藏
2. 主頁>"新增+"，我的手機顯示為 "新...+"
3. 快速建立的商店，在我的頁面區域，清單圖示不應為空白
4. 建立商店時，選擇分類 > 店家 > 連鎖商店 點擊之後看不出反應(建議變灰色,或是選擇區移除該項目)
5. 編輯商店內容頁面的標題，不應為 "編輯群組設定"
6. 編輯商店內容頁面，右上角 "儲存"，我的手機顯示為 "儲..."
7. 編輯頁面>給此頁選擇管理員>新增好友，顯示的popup不直覺，不知該如何進行
8. 編輯頁面>給此頁選擇管理員>右上角的"Change"，請改成"儲存"
9. 分享到line的網址沒有跟描述斷行

美國 Chic Rose Baby 超美蓬裙 : 每個小女孩都要有的夢幻蓬裙
腰圍可調整
從新生兒穿到4歲都沒問題唷！
保證正品，多色可選

※不包含髮帶 http://store.tagfans.com/index.html?noteId=7056&_stationId=899&_storeId=296

**Comment by cmacma7** [comment]
Fixed 1, 2, 5, 6, 7, 8
