### ISSUE TITLE
[membership]多筆資料使用 | 符號分隔篩選。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1641]
多筆資料使用 | 符號分隔篩選。

此功能目前尚未完善。

![image](https://user-images.githubusercontent.com/35478230/47480442-ff837500-d862-11e8-80a6-e85c7f4ac008.png)

**Comment by anitalo73** [comment]
於各欄位搜尋框內操作，測試OK

![image](https://user-images.githubusercontent.com/35478230/47541104-a1aa6800-d90a-11e8-945e-e6c3d54e5ffc.png)

**Comment by cmacma7** [comment]
Use Regex style to write conditions for each search. The search is call search(text, true, false), first true is regex enable, and the false is smart search disable

**Comment by anitalo73** [comment]
獨立欄位可使用|
全頁搜尋無法使用|
