### ISSUE TITLE
[menu.html] debug中，拖移換列的功能無法操作。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1646]
以下截圖是正式環境，測試環境無法操作。

![image](https://user-images.githubusercontent.com/35478230/47506806-72acdb80-d8a3-11e8-9a38-f6313f92459e.png)

**Comment by cmacma7** [comment]
Problem fixed by re-generate datatable js/css files with rowReorder and columnReorder features.

**Comment by anitalo73** [comment]
測試環境驗證正常

![image](https://user-images.githubusercontent.com/35478230/47580201-d5c07000-d980-11e8-92dd-35198c8c0dc7.png)
