### ISSUE TITLE
[點餐] 內用(是)開啟，自取(否)關閉，客人點餐畫面，仍會看到自取的選項。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1647]
[點餐] 內用(是)開啟，自取(否)關閉，客人點餐畫面，仍會看到自取的選項。
如下截圖，左側是客人畫面，右側是老闆context後台。
![image](https://user-images.githubusercontent.com/35478230/47510405-ab03e800-d8aa-11e8-89fc-9bb5ceed10f4.png)

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
測試OK
