### ISSUE TITLE
[membership]當客戶編號空白時，若其他會員的銷售人員編號也是空白時，從屬關係就成立，應特殊處理空白字元。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1653]
當客戶編號空白時，若其他會員的銷售人員編號也是空白時，從屬關係就成立，應特殊處理空白字元。

圖片中，電話號碼0975579002在FER這家店總部的membership把權限都清空了(如右圖)，該電話號碼登入後台也仍然看得到其他會員的資料(如左圖)。

![image](https://user-images.githubusercontent.com/35478230/47565460-173e2480-d95b-11e8-8232-33d1db19eb9e.png)

**Comment by cmacma7** [comment]
Fixed by change mysql select  SalesId!='' when filter the SalesId for each row of customers.

**Comment by anitalo73** [comment]
測試
我的電話號碼登入店號7887的membership
步驟1：原客戶編號空白，加上客戶編號後，可以看到管理的下級會員。→正確。
步驟2：將客戶編號清除(空白)，無法看到任何會員。→正確。
