### ISSUE TITLE
[點餐] context中「自取」開關設定，於舊版context的相容性控制有問題。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1654]
雅啤點餐context為舊版，沒有自取的開關設定選向，如下圖設定時，有如下描述之狀況：
正式環境前台顯示：雅啤，有內用，有自取。
測試環境前台顯示：雅啤，有內用，沒有自取。

![image](https://user-images.githubusercontent.com/35478230/47644535-5e215980-dba9-11e8-8c2f-36b0e11e1694.png)

**Comment by huangVic** [comment]
cloud.menu.1.15.0 已修正
