### ISSUE TITLE
[membership]銷售分析沒有顯示單位。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1657]
![image](https://user-images.githubusercontent.com/35478230/47782161-87bdba80-dd3a-11e8-9723-766705e400ca.png)

![image](https://user-images.githubusercontent.com/35478230/47782105-6230b100-dd3a-11e8-8705-10d7e5cad4f8.png)

**Comment by cmacma7** [comment]
added on items second line.

**Comment by anitalo73** [comment]
測試OK
