### ISSUE TITLE
[點餐負數]新舊版報表，需對應顯示。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1658]
![image](https://user-images.githubusercontent.com/35478230/47782389-1599a580-dd3b-11e8-8c0c-93fdb678b377.png)

![image](https://user-images.githubusercontent.com/35478230/47782503-5b566e00-dd3b-11e8-8493-438bf290b64a.png)

**Comment by cmacma7** [comment]
Howard need to change the code to allow q>0 and q<0

**Comment by anitalo73** [comment]
測試OK
