### ISSUE TITLE
[百八LINE機器人]百八編輯個人資料的欄位需求，另外，姓名欄位更新無效。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1659]
1.姓名欄位更新無效。
2.百八欄位需求如下圖。

![image](https://user-images.githubusercontent.com/35478230/47839190-d7f55500-ddec-11e8-8d2a-9ce92b79f7f4.png)

**Comment by cmacma7** [comment]
need to add the feature to this account.

**Comment by cmacma7** [comment]
fixed by enable 會員專屬 keyword, so that user can edit personal data by click 會員專屬 button

**Comment by anitalo73** [comment]
首次加入會員的地點：

[百八店別中文.txt](https://github.com/cmacma7/bn/files/2666282/default.txt)

之後有分店新增或關閉，由工程師修改。

**Comment by cmacma7** [comment]
added into userinfo.html as Store in meta data.
