### ISSUE TITLE
Android app需註冊domain name，方可點網址開啟app

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#166]
Android app需註冊domain name，方可點網址開啟app

**Comment by cmacma7** [comment]
Register tagfans App to system.

**Comment by cmacma7** [comment]
only iOS can directly jump to App, Android will go to browser, then re-direct to App. I think we need to popup app button when it is inside browser, which might be good enough instead of directly jump to App from Line or Facebook, or browser url.
