### ISSUE TITLE
[membership]銷售分析，品項名稱較長，金額排版需調整。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1662]
銷售分析中，品項名稱較長，金額排版無法正確檢視，需調整。

新版 membership報表
![image](https://user-images.githubusercontent.com/35478230/47843411-7fc54f80-ddfa-11e8-9b76-6093898fc9a2.png)

---
---
舊版報表
![image](https://user-images.githubusercontent.com/35478230/47843336-3c6ae100-ddfa-11e8-94ad-c2c6a537a704.png)

**Comment by anitalo73** [comment]
測試OK

![image](https://user-images.githubusercontent.com/35478230/47890130-7b477800-de88-11e8-8f2f-943c036d282e.png)

**Comment by cmacma7** [comment]
fixed by add a clear:right div at the end of each item.
