### ISSUE TITLE
[LINE機器人] [樂趣]電話驗證，究竟是驗證了沒？第一次進入顯示有驗證，第二是進入顯示未驗證。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1664]
[LINE機器人] [樂趣]

電話驗證，究竟是驗證了沒？

第一次進入顯示有驗證，第二是進入顯示未驗證。
第三次進入顯示有驗證，第日是進入顯示未驗證。

如下影片：
https://youtu.be/CmwrUrSTFjQ

**Comment by cmacma7** [comment]
Yes, this is by design.

**Comment by cmacma7** [comment]
We allow register again.
