### ISSUE TITLE
[LINE機器人] [樂趣] 編輯個人資訊，姓名欄位更新無效。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1665]
姓名欄位更新無效。
下次進來編輯個人資訊，姓名仍是舊的。

如下影片：
https://youtu.be/CmwrUrSTFjQ

**Comment by cmacma7** [comment]
cannot reproduce...

**Comment by cmacma7** [comment]
Problem caused by Name and FirstName. The LastName and FirstName is used in Line, and Name is used for system. So we need to show the Name, if not Name, show (FirstName+LastName) in admin.html

**Comment by anitalo73** [comment]
測試OK
