### ISSUE TITLE
[LINE機器人] [樂趣] 已完成電話驗證，報名課程正確流程，應不需要再次驗證電話？

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1666]
已完成電話驗證，報名課程正確流程，應不需要再次驗證電話？

如影片，加入LINE機器人好友初次已完成電話驗證，報名課程時，電話驗證的步驟應該要省略。

https://youtu.be/xz7VFhMi_-g

**Comment by cmacma7** [comment]
problem caused by the link of 報名課程 in line@ admin is set to https://store.tagfans.com....  and the register is using http://store.tagfans.com, so are in different domain, and this is the reason need to login again.

**Comment by anitalo73** [comment]
測試OK

![image](https://user-images.githubusercontent.com/35478230/47890012-cad97400-de87-11e8-8a46-372769f30c65.png)
