### ISSUE TITLE
[membership] membership刪除會員，若無重新驗證電話號碼，僅在LINE裡下單，後端並不會寫入LINE ID。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1667]
從membership刪除會員，
回到LINE機器人下單，membership有會員資料重新寫入，但實際後端視沒有LINE ID寫入，
導致，在外部瀏覽器下單，不會收到LINE通知。

必須在LINE機器人裡面，重新驗證電話號碼，後端才會有LINE ID寫入，
在外部瀏覽器下單後，才會收到LINE通知。

---
---
LINE外部的瀏覽器(手機或電腦)下單，成立訂單：
![image](https://user-images.githubusercontent.com/35478230/47892281-cb770800-de91-11e8-8d33-2280c29d78cb.png)
---
---
FER機器人，最後收到的訊息，沒有訂單 NO.4903081-00123
![image](https://user-images.githubusercontent.com/35478230/47892338-198c0b80-de92-11e8-8936-d8a413b95126.png)

---
---
E訂通，最後收到的訊息，沒有訂單 NO.4903081-00123
![image](https://user-images.githubusercontent.com/35478230/47892319-024d1e00-de92-11e8-90ad-84e0cfe3fd3e.png)

**Comment by cmacma7** [comment]
Problem caused by app.js of robot handle json.lineId typo, and it should be json.LineId. 
Fixed.

**Comment by anitalo73** [comment]
於正式環境membership刪除會員資料後，
到LINE下單，membership的資料會寫入
再到瀏覽器下單，LINE會正常收到通知。
測試OK
