### ISSUE TITLE
已隱藏的Tag，仍可直接連結觀看

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#167]
已透過分享連結出去的Tag
ex. http://store.tagfans.com/index.html?noteId=7056&_stationId=899&_storeId=296#page_join

就算管理者設定隱藏，只是在頁面看不到
但還是能從tag連結觀看

**Comment by cmacma7** [comment]
this suppose to be the default behavior. The logic is like ... if a mail is sent out, can you delete the mail by sender, or delete by sender is not allowed. 
Hide the widget prevent future customer see the widget, but should we also delete the share that already exist?

If you delete the widget, then all user should not see the widget anymore. But if you just hide, I guess the purpose of hide is only prevent user see it on the page.

**Comment by cmacma7** [comment]
This also means we should have a property to assign some widgets are not sharable, but can only save to favorite, so that this problem will be solved in different logic.
