### ISSUE TITLE
[艾可Android App] 進入點餐前，沒有電話驗證的流程。直接可以亂打電話號碼完成點餐。(7吋華碩平板)

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1674]
影片為客戶頁面，不需要電話驗證即可點餐。
https://youtu.be/CMUFTeTu4DU

以下為亂打三支電話號碼，完成點餐，再老闆帳號看到的訂單。
![image](https://user-images.githubusercontent.com/35478230/48105851-0a330680-e274-11e8-8f94-3c2fe87ad116.png)

**Comment by huangVic** [comment]
1.15.0出現的bug, 當 內用/外帶/自取選項在context 只保留一個項目時(外帶或自取), 則會跳過電話驗證.

cloud.menu.1.15.1 已修正

**Comment by anitalo73** [comment]
測試OK
已更新至正式站。
