### ISSUE TITLE
[menu]匯入功能，使用者在某分類下按匯入，請自動更新匯入檔案的TypeNo，讓資料新增在使用者按匯入的分類底下。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1675]
例如
匯入檔案的TypeNo是15
目前若在分類序號20底下按匯入，資料不會新增到分類序號20，而是會新增到分類序號15。

請修改為，當使用者在分類序號20底下按匯入，系統可自動更新匯入檔案的TypeNo為20，讓資料新增在使用者按匯入的分類底下。

**Comment by cmacma7** [comment]
Fixed by use TypeNo equal to TheTable.parameters.TypeNo for each row in the excel

**Comment by anitalo73** [comment]
測試OK
