### ISSUE TITLE
[menu]匯入功能不work

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1678]
匯入失敗
系統出現如下訊息

![image](https://user-images.githubusercontent.com/35478230/48338594-04d52200-e6a1-11e8-8fd5-7dd02a1206a1.png)

**Comment by cmacma7** [comment]
the statement is not correct. only rows with details that has extra web page will fail, not all the import fails.

**Comment by anitalo73** [comment]
OK
