### ISSUE TITLE
[點數]若使用點數消費，點數額度沒有超過免運額度，(因現金額度有超過免運額度)，目前沒有顯示運費，應該要顯示運費。請修改。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1680]
當數量x2時，總結金額超過免運額度，不顯示運費→正確。

但數量x2時，若使用點數消費，點數額度沒有超過免運額度，應該要顯示運費。請修改。

![image](https://user-images.githubusercontent.com/35478230/48401550-690cea00-e764-11e8-8797-3095f14c5494.png)

---

**Comment by huangVic** [comment]
cloud.menu.1.18.0 已修正
