### ISSUE TITLE
[會員前端介面] 做一筆現金消費，先前的累績金額會被歸零，前端介面累績金額只統計這筆新訂單的金額。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1684]
累積消費金額蠻多的，不只150元。

但只要做一筆現金消費，累積金額就會歸零，只統計這筆新的訂單金額。
---
![image](https://user-images.githubusercontent.com/35478230/48490050-7fe43700-e85f-11e8-8a8a-392680b94e4e.png)
---
![image](https://user-images.githubusercontent.com/35478230/48490149-bcb02e00-e85f-11e8-9556-c9ac30d86a8d.png)
--

**Comment by huangVic** [comment]
cloud.menu.1.18.0 已修正

**Comment by anitalo73** [comment]
正式環境正常。
