### ISSUE TITLE
[FER] 從購物車增加數量，舊金額(被槓掉的)不會變動?

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1689]
第一張圖是從購物車增加商品數量。被槓掉的舊金額，一直停在數量是1的情況下?
![image](https://user-images.githubusercontent.com/35478230/48695128-40c83400-ec19-11e8-8d9e-4b9a9fade653.png)

---
第二章圖示從選購畫面就先選好商品數量。被槓掉的舊金額，與新金額相同，有點奇妙??
![image](https://user-images.githubusercontent.com/35478230/48695140-4cb3f600-ec19-11e8-840b-f8be8bd07c77.png)

**Comment by huangVic** [comment]
cloud.menu.1.18.0 已修正

**Comment by anitalo73** [comment]
測試OK
