### ISSUE TITLE
[點餐] 外送自取文字顯示錯誤。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1690]
機器人顯示「外送」

![image](https://user-images.githubusercontent.com/35478230/48816710-38d5d480-ed7e-11e8-8661-fa78b04a5e25.png)
---
後台設定是「自取」，外送是關閉的喔。

![image](https://user-images.githubusercontent.com/35478230/48816726-4a1ee100-ed7e-11e8-912c-aeb0141e383c.png)

**Comment by huangVic** [comment]
<<< orderType: "3" (外送) >>>
----------------------------------------------
 if  (context.widget.context.deliveryService != undefined && context.widget.context.deliveryService.deliveryTitle != undefined) {
     console.log(context.widget.context.deliveryService.deliveryTitle)
} else {
     console.log('外送')
}


<<< orderType: "1" (外帶) >>>
----------------------------------------------
 if  (context.widget.context.takeOutService != undefined && context.widget.context.takeOutService.takeOutTitle != undefined) {
      console.log(context.widget.context.takeOutService.takeOutTitle)
} else {
      console.log('外帶')
}


<<< orderType: "2" (內用) >>>
----------------------------------------------
 if  (context.widget.context.insideService != undefined && context.widget.context.insideService.dineInTitle != undefined) {
      console.log(context.widget.context.insideService.dineInTitle)
} else {
      console.log('內用')
}

**Comment by anitalo73** [comment]
測試OK
