### ISSUE TITLE
[FER] 下單時選自取，機器人顯示宅配。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1691]
![image](https://user-images.githubusercontent.com/35478230/48823877-63835580-ed9d-11e8-8db1-0c205a8dc12a.png)

---

![image](https://user-images.githubusercontent.com/35478230/48823903-80b82400-ed9d-11e8-85c7-22767bfbd7d1.png)

**Comment by huangVic** [comment]
<<< orderType: "3" (外送) >>>
if (context.widget.context.deliveryService != undefined && context.widget.context.deliveryService.deliveryTitle != undefined) {
console.log(context.widget.context.deliveryService.deliveryTitle)
} else {
console.log('外送')
}

<<< orderType: "1" (外帶) >>>
if (context.widget.context.takeOutService != undefined && context.widget.context.takeOutService.takeOutTitle != undefined) {
console.log(context.widget.context.takeOutService.takeOutTitle)
} else {
console.log('外帶')
}

<<< orderType: "2" (內用) >>>
if (context.widget.context.insideService != undefined && context.widget.context.insideService.dineInTitle != undefined) {
console.log(context.widget.context.insideService.dineInTitle)
} else {
console.log('內用')
}

**Comment by anitalo73** [comment]
測試OK
