### ISSUE TITLE
[代客下單] 報表或備註多增加文字描述，此為[代客下單]

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1712]
![image](https://user-images.githubusercontent.com/35478230/49569766-cfee7f00-f96f-11e8-96b3-27631f444077.png)

目前訂單描述看不出來是業務代替下訂的。

建議增加描述。

**Comment by cmacma7** [comment]
Fixed by put [代客下單] after the name of customer.

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/51727701-2478c580-20a8-11e9-973b-8e9df831effa.png)

測試ＯＫ
