### ISSUE TITLE
[點數兌換優惠券] 發送數量沒檔。最高上限5張，可以一直兌換，客人點數被扣了，實際沒有發送優惠券。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1714]
[點數兌換優惠券] 發送數量沒檔。最高上限5張，可以一直兌換，客人點數被扣了，實際沒有發送優惠券。

超過兌換上限後，仍一直是兌換成功畫面，且繼續扣點數，但優惠券發超過上限後，沒有再繼續發。

![image](https://user-images.githubusercontent.com/35478230/49853326-bc389200-fe21-11e8-9f5d-c78f3adde7d0.png)

**Comment by gameflierHao** [comment]
Please use coupon.html
single coupon widget is only for old user

**Comment by anitalo73** [comment]
coupon.html中一直重複點兌換優惠券，會一直扣點數，但最多發到上限份數，就不會再發了，

客人停在這個頁面一直點兌換，沒有重新整理，也應該顯示售完。

不能讓客人一直點兌換，且一直扣點數卻沒有發送。

**Comment by anitalo73** [comment]
### **建議文案改為：
### **真可惜！本優惠券已經被兌換完畢囉！您可以選擇兌換其他的優惠券。
### **或
### **很抱歉，優惠卷已全數兌換完畢！您可以選擇兌換其他的優惠券。**

-------------------------------
這個文案會讓人誤以為「有兌換到」，但其實實際上沒有。
![image](https://user-images.githubusercontent.com/35478230/49988722-cd64d880-ffb2-11e8-9a06-7acb65eb66a7.png)
