### ISSUE TITLE
[menu.html]使用safari操作匯出功能時，無法直接下載檔案。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1726]
[menu.html]使用safari操作匯出功能時，無法直接下載檔案。

![image](https://user-images.githubusercontent.com/35478230/50803786-21e74380-1326-11e9-92e6-442b9eecf5d9.png)

**Comment by cmacma7** [comment]
We don't support Safari, I can force user to use Chrome for advanced features.
