### ISSUE TITLE
[平板點餐-可點時間]  可點時間結束後，餐點不顯示，應也要判斷不可送單。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1737]
可點時間結束後，餐點不顯示，應也要判斷不可送單。

若客戶在可點時間內，加入購物車，當可點時間結束後一或兩個小時，再將品項送出，目前沒有擋，應該要擋喔。

![image](https://user-images.githubusercontent.com/35478230/51012310-80ffbf00-1597-11e9-8b54-91075aa261ee.png)

**Comment by huangVic** [comment]
當可點時間結束後, 若購物車有點選此品項將自動移除此項目
