### ISSUE TITLE
[會員前端]分店的會員前端介面，沒有抓到總店的會員資料。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1750]
分店的會員前端介面，沒有抓到總店的會員資料。

![image](https://user-images.githubusercontent.com/35478230/51525356-18ec8b00-1e6b-11e9-873b-171e76a5cd24.png)

**Comment by huangVic** [comment]
新增 StoreCap 的判斷, 當 bit 為 1 表示取總店資訊

**Comment by anitalo73** [comment]
艾可這家店老闆帳號call api 取得客戶資料會顯示失敗。

![image](https://user-images.githubusercontent.com/35478230/51659723-6e997280-1fe6-11e9-9e30-41061fef043d.png)

**Comment by anitalo73** [comment]
會員前端介面要用分店自己的頁面
例如店號8039
應該要用 http://store.tagfans.com/#page_join?o=8039&id=35001&viewType=station

---
---

點數應該要抓credit_root這個才是總店7677的點數

![image](https://user-images.githubusercontent.com/35478230/51725890-93055580-209f-11e9-922b-6a8a1cf723d1.png)

**Comment by huangVic** [comment]
點數來自總店, 已改抓 Credit_root 和 Amount_root 這兩個欄位

**Comment by anitalo73** [comment]
問題一，新分店的會員點數抓對了，是7677的點數，但沒有抓到7677的優惠券資料？？
問題二，總店7677的會員資料抓錯？？

![image](https://user-images.githubusercontent.com/35478230/51736911-4aad5e00-20c6-11e9-9375-89d23322aa7a.png)

**Comment by anitalo73** [comment]
艾可優惠券核銷需透過手機核銷，無法使用會員前端介面做核銷，因會員前端介面的優惠券是分店的資料，無總店的total優惠券。
