### ISSUE TITLE
[cloudmenu]ATM匯款頁面文案調整，把「通知已匯款」文字改成「確認結帳」。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1754]
艾可新零售兩位客戶，在這個頁面，以為訂購完成，就跑去匯款，回來這找不到這個頁面，導致沒有走完下訂單的流程，艾可希望我們把「通知已匯款」文字改成「確認結帳」。

![image](https://user-images.githubusercontent.com/35478230/51669974-95fd3900-2000-11e9-8896-ab2bb7894550.png)

**Comment by gameflierHao** [comment]
Revision: 3355
Author: zhanghaowu
Date: 2019年1月31日 下午 12:23:49
Message:
[cloudmenu]ATM匯款頁面文案調整，把「通知已匯款」文字改成「確認結帳」。 #1754
----
Modified : /nodejs/bn/widgets/Modules/template_111_paymentMethodSetting.js

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/52044814-fb5fa580-257d-11e9-87f9-4ef8c0a29d74.png)
測試ＯＫ
