### ISSUE TITLE
新增widget分類，必須按清除快取，才看到新的內容

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#176]
新增widget分類，必須按清除快取，才看到新的內容

**Comment by cmacma7** [comment]
Got it!

**Comment by cmacma7** [comment]
It is cause by use the wrong update variable. create a globalinfo table to remember such variables. Originally use userinfo, which is wrong.

**Comment by peichingliao** [comment]
我的電腦(macbook air, chrome browser) 看不到新的分類
版本 1.1.750.1

![2015-06-16 10 45 48](https://cloud.githubusercontent.com/assets/10726049/8185996/19acba6e-147a-11e5-8eb1-8321f9d95c2a.png)

**Comment by cyen1121** [comment]
移除category 裡的package
fixed
