### ISSUE TITLE
[membership銷售分析] 分店編輯功能有錯誤訊息。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1761]
![image](https://user-images.githubusercontent.com/35478230/52611138-0213e400-2ebf-11e9-8491-62ab3784173e.png)

![image](https://user-images.githubusercontent.com/35478230/52611693-ab5bd980-2ec1-11e9-8671-f37b22e677e9.png)

**Comment by cmacma7** [comment]
only happen at the first time press the edit store then create a new row.
