### ISSUE TITLE
[杓文字便當]運費問題

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1769]
1.在購物車選購11個商品，且距離在2.5公里內，顯示免運費，但訂單送出後仍有計入運費。

2.在購物車選購時有顯示運費，點送出，在選擇付款方式時，點返回，此時在購物車運費的項目消失囉。

如下影片。

https://youtu.be/vSt0Je7K8jo

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
在購物車看到運費0元，但訂單送出選擇付款畫面時，運費又跑出來了。
送出結帳，運費還是沒有減免喔。

（外送地址距離在2.5公里內喔）

![image](https://user-images.githubusercontent.com/35478230/53142667-bb656e80-35cf-11e9-9895-6305958ebe4f.png)
