### ISSUE TITLE
訂位widget文字&UI建議

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#177]
1.  "增加開店時段" & "增加座位配置"  
   (一個新增, 一個增加, 不太統一.  桌子部署...好另類的詞)
2. 訂位查詢的狀態顯示：未讀->店家尚未讀取 / 取消訂位->已取消
3. 訂位查詢的店家電話，按下去出現訂位人的手機號碼（store.tagfans.com尚未解）

**Comment by cyen1121** [comment]
統一用詞和改成桌子張數

store等更新就會同步了
