### ISSUE TITLE
[杓文字便當]於訂購頁面上變更地址，map api 需重算運費？（或是不要讓客人在訂購頁面變更地址）

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1770]
例如，客人在杓文字頁面選擇外送，填入地址是：台北市大安區永康街10巷7號

訂購11個便當可享有免運費。

但客人在cloud menu訂購頁面上變更地址，改為新北市淡金公路1號，那運費跟分配分店別的api是否會重新計算，

或是，根本不要讓客人在cloud menu訂購頁面上變更地址。

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
正式環境訂單，在購物車上，地址不可修改。正確。
