### ISSUE TITLE
[百八LINE]會員點數累積時的文字訊息。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1777]
發票作廢：
您有一筆消費 OOO 元的訂單已被取消，故從您的紅利集點扣除 OO 點，目前累計點數共 OO 點。 
---
---
---
交易完成：
感謝您此次單筆消費ＯＯＯ元，每100元即可換1點，您共獲得Ｏ點，累計目前點數為ＯＯ點。
---
---
---
下圖是現在的訊息，客戶希望文字可以修改。
![image](https://user-images.githubusercontent.com/35478230/53008774-13d42900-3475-11e9-88a1-80b9dea5a678.png)

**Comment by cmacma7** [comment]
changed to the suggested text, with some modification to make it more readible.

**Comment by cmacma7** [comment]
change to app4.js, need to use to replace app2.js for other stores.
