### ISSUE TITLE
[杓文字便當]訂單送出失敗

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1788]
https://youtu.be/pX2VARGoTuQ

![image](https://user-images.githubusercontent.com/35478230/53282720-a8d96980-3776-11e9-90ef-3f7c855bb4f0.png)

**Comment by anitalo73** [comment]
似乎是沒有設定庫存的日期跟店，就會這樣。

**Comment by gameflierHao** [comment]
菜單若未設定庫存時會發生這個情況
已修正
