### ISSUE TITLE
[杓文字便當]杓文字首頁「查詢訂單」，連結錯誤。http 要加「s」

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1789]
杓文字首頁「查詢訂單」，連結錯誤，

目前的連結是
http://store.tagfans.com/index.html#page_station?mail=true&o=7827&bg=null

http 要加「s」

不然客戶訂購完之後，到杓文字首頁點「查詢訂單」，會被要求再次登入。

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
已從主頁編輯器調整「查詢訂單」、「我的優惠券」的網址為http。
