### ISSUE TITLE
[杓文字便當]手機選擇的日期，不可選的日期，不要顯示。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1792]
今日是2/27，不可點2/27的便當，但仍可選擇2/27，選了無法往下一步走，使用者會不曉得發生什麼事。

在手機介面上，請直接將不可選擇的日期，直接擋掉，不要讓使用者選。

![image](https://user-images.githubusercontent.com/35478230/53465241-04159f80-3a88-11e9-8d2c-ebe5f5ae0fcc.png)

**Comment by huangVic** [comment]
已修正成為日期選擇器, 不使用原生日期介面

**Comment by anitalo73** [comment]
正式環境測試ＯＫ
