### ISSUE TITLE
[平板點餐][百八]外文菜單的帳單明細現在顯示中文菜名，應該要顯示外文菜名。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1797]
![image](https://user-images.githubusercontent.com/35478230/53706619-1ae03b80-3e66-11e9-82e8-203036c41f88.png)

**Comment by huangVic** [comment]
已更新，外文菜單將顯示外文與中文，方便服務人員查看

**Comment by anitalo73** [comment]
![image](https://user-images.githubusercontent.com/35478230/54013766-4b510e00-41b5-11e9-8848-bf26f3755d29.png)
測試ｏｋ

**Comment by anitalo73** [comment]
已經更新至百八個分店。
