### ISSUE TITLE
[平板點餐庫存][百八] 庫存前台顯示數量的位置可自訂。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1798]

**Comment by huangVic** [comment]
![1552277316969](https://user-images.githubusercontent.com/5910437/54099917-b4739400-43f6-11e9-8894-2f47bace56a6.jpg)

context 已增加可以設定庫存顯示位置（預設為左上）

**Comment by anitalo73** [comment]
已更新至百八各分店。
