### ISSUE TITLE
[平板點餐][庫存]加購項目若數量不足，但未售完的情況下，主餐仍會成功送出，系統應要將主餐擋下來。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1812]
紅茶庫存3
點選商品「百八丼數量1，加購紅茶數量4」
系統回覆訊息，紅茶數量不足，且訂購單清空，
查看結帳單，百八丼數量1，送出成功。

預期情況：百八丼應要無法送出，留在訂購單上。

**Comment by gameflierHao** [comment]
Fixed
