### ISSUE TITLE
[掃瞄槍]點餐頁面schema與context增加barcode掃描槍功能後，地址無法輸入，點擊地址輸入區塊，沒有出現輸入框。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1813]
問題描述：點餐頁面schema與context增加barcode掃描槍功能後，地址無法輸入，點擊地址輸入區塊，沒有出現輸入框。

測試載具
ASUS 7吋平板，chrome瀏覽器
mac 電腦，chrome瀏覽器

登入帳號，阿水的fb帳號（羅惠玲token）
store店號，8127
https://store.tagfans.com/debug/#page_join?o=8127&id=35357&viewType=station

![image](https://user-images.githubusercontent.com/35478230/54434618-aa8cc080-4769-11e9-967f-d063f678a07c.png)

**Comment by huangVic** [comment]
已修正

**Comment by anitalo73** [comment]
正式環境ＯＫ
