### ISSUE TITLE
[等一個人咖啡][membership]會員被建立多次，請協助刪除該會員資料。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1817]
會員前端介面新增會員，輸入資料後，點「建立」無反應。
分店測試人員測試多次，最後自己的電話號碼，在後台被建立多次，導致進入cloud menu頁面看到如下畫面，請協助刪除該會員資料。

0983118011

![image](https://user-images.githubusercontent.com/35478230/54666419-a32c3500-4b24-11e9-912d-241a4d6de5de.png)

**Comment by cmacma7** [comment]
fixed by not allow create by _unique by Vic
