### ISSUE TITLE
[平板點餐]同一個主餐，點同一種飲料，分兩次點單，一次點去冰，一次點正常冰，但送單會合併為同一種口味。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1819]
平板點餐
第一次點單：點百八丼數量1，紅茶數量1，正常冰，按確認，按確認，送到左側購物清單，尚未送出訂單。
第二次點單：點百八丼數量1，紅茶數量1，去冰，按確認，按確認，送到左側購物清單，
購物清單，只有顯示一列。
按送出訂單。
![image](https://user-images.githubusercontent.com/35478230/54801062-0e4e4680-4ca0-11e9-9e1c-2965e8c8aeb9.png)

結帳單及POS顯示：百八丼數量2，紅茶數量2，正常冰

預期情況：應該是，
百八丼數量2，
紅茶數量1，正常冰
紅茶數量1，去冰

**Comment by huangVic** [comment]
已修正,
