### ISSUE TITLE
[timeline]android pad點選日期時，會先跳出一般輸入鍵盤，擋住點選日期的選項。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1826]
android pad 橫式操作時，
點選輸入日期的文字框，會先跳出一般輸入鍵盤，必須關閉，才能點選日期，
進入月曆點選日期時，點一次日期，又會再跳出一次鍵盤。 （如下圖）

android pad 直式操作時，畫面較長，原生鍵盤就不會擋住日期輸入選項。

![image](https://user-images.githubusercontent.com/35478230/54898455-5de27b80-4f07-11e9-8cb1-7b78b33ef1a3.png)

華碩七吋平板

tagfans 開發票 debug app

**Comment by cmacma7** [comment]
change to use readonly for datetimepicker and change dialog to not to use scroll style, so that it will not have fix bottom header, the text will not push up.

**Comment by anitalo73** [comment]
測試ＯＫ
