### ISSUE TITLE
[cloud menu]在debug，加點套餐內的品項，且在購物車把數量增加大於一以上，送出訂單後，訂單總金額是錯誤的。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1831]
測試店：8127
店主或客人訂購，皆有同樣問題。

點餐，
在debug，
加點套餐內的品項，
且在購物車把數量增加大於一以上，
送出訂單後，
訂單總金額是錯誤的。
Ｅ訂通，LINE收到的金額，正式環境或debug訂購，送到LINE，總金額都是錯誤的。
(如下圖)

---

客人帳號點的
![image](https://user-images.githubusercontent.com/35478230/55229424-e8a0de80-5257-11e9-8af5-9579970e0053.png)

---
店主用pos介面點的
![image](https://user-images.githubusercontent.com/35478230/55229033-ca86ae80-5256-11e9-8798-d8c72a238b84.png)

**Comment by huangVic** [comment]
debug上已修正, 解決套餐金額計算錯誤問題！

**Comment by anitalo73** [comment]
就git上的例子，正確總金額是3438元，截圖，正式環境的金額是對的。

但（4/19測試）
現在debug是3438元，
現在正式環境式4434元。（錯誤）

**Comment by anitalo73** [comment]
正式環境確認正常。
