### ISSUE TITLE
[cloud menu]後台價格輸入千分位符號時，前台顯示錯誤金額。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1834]
正式環境中

admin/menu.html中，商品價格輸入千分位符號時，例如「1,399」。

前台購買時，該商品的訂購價格是1元。

預期結果：前台購買時，該商品的訂購價格是1399元。

系統應該要可以正確判讀包含千分位的價格資訊。

或，後台應要擋掉，不要讓客人在金額欄位輸入千分位符號。

![image](https://user-images.githubusercontent.com/35478230/55793189-e874ce80-5af4-11e9-84df-44deca929415.png)

**Comment by cmacma7** [comment]
fixed by show 
"invalid number" if user input a "1,000" like string

**Comment by anitalo73** [comment]
menu.html金額欄位輸入千分為符號，後台金額會顯示為Invalid Number，
前台金額仍會錯誤，若客人硬要使用，不能怪系統問題了。
測試ＯＫ

![image](https://user-images.githubusercontent.com/35478230/56706292-fce8d600-6746-11e9-8046-6bac8e40844b.png)
