### ISSUE TITLE
[杓文字][老闆確認退款才退貨]當老闆同意退款時，數量會加倍奉還。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1836]
環境：debug
店號：7827
庫存日期：4/16永康店

便當原始數量10個
客人下訂單完成刷卡，買3個便當，庫存變更為7個。
客人，請求退款，庫存數量不更動，庫存7個。
老闆同意退款，庫存數量變更為13個。

預期情況:
老闆同意退款後，庫存數量應變更為10個。（7＋３）

**Comment by gameflierHao** [comment]
Fixed

**Comment by anitalo73** [comment]
測試正常

**Comment by anitalo73** [comment]
正式環境確認正常。
