### ISSUE TITLE
[杓文字][退貨][負數訂單]訂購頁面，右上角查詢訂單，查無負數訂單。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1837]
老闆帳號，該分店底下，黑色表頭，消費紀錄，收件訂單，可查到負數訂單。
但，線上訂購，右上角，查詢訂單，沒有查到負數訂單。

客人帳號
線上訂單，右上角，查詢訂單，沒有查到負數訂單。
杓文字這家店，消費記錄，我的訂單，沒有查到負數訂單。

**Comment by gameflierHao** [comment]
fixed

**Comment by anitalo73** [comment]
測試ｏｋ
老闆帳號黑色表頭下，有成立負項訂單。庫存有正常加回去。
（消費者帳號沒有負項訂單），

**Comment by anitalo73** [comment]
老闆帳號會立即產生負項訂單。
客人帳號不會看到負項訂單
