### ISSUE TITLE
[杓文字][點數]訂單金額等於0元，選擇信用卡付款，畫面會卡住，多點幾次信用卡付款，pop up消失，訂單成立，商品庫存顯示售完。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1843]
店號：7828 (杓文字)
商品原庫存10
訂購商品數量2
全額使用點數消費
訂單最後金額0元
選擇付款方式時，選信用卡付款，畫面會卡住，點信用卡付款按鈕多次，選擇付款方式的pop up會消失，接著看到成立訂單的訊息。但該商品會顯示為售完。

預期情況：
1.該商品數量應還有8。
2.0元訂單，選擇付款方式時，系統應要另做處理。

![image](https://user-images.githubusercontent.com/35478230/56730789-5f63c580-678b-11e9-8298-fe9fab31b741.png)
---

![image](https://user-images.githubusercontent.com/35478230/56730827-76a2b300-678b-11e9-8c8c-7eb89b224613.png)

**Comment by gameflierHao** [comment]
Revision: 3457
Author: zhanghaowu
Date: 2019年4月26日 下午 05:47:08
Message:
0元不允許刷卡
----
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by anitalo73** [comment]
debug測試ＯＫ

**Comment by gameflierHao** [comment]
Revision: 3458
Author: zhanghaowu
Date: 2019年4月26日 下午 06:10:22
Message:
0元不能開發票與進入付款選擇
----
Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by anitalo73** [comment]
debug測試ＯＫ

**Comment by anitalo73** [comment]
正式環境測試ＯＫ
