### ISSUE TITLE
[商品管理][menu.html] http（正式與debug）無法新增分類，https的debug也不行，唯https的正式環境正常。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1844]
使用http開啟menu.html時，
正式環境中，無法新增分類，如下圖。
debug，也是無法新增分類。

![image](https://user-images.githubusercontent.com/35478230/56777433-303d6a80-6804-11e9-836f-5422a8566eb9.png)
---
---
使用http「s」開啟menu.html時，
正式環境，可以正常使用。
debug，無法新增分類，如下圖。

![image](https://user-images.githubusercontent.com/35478230/56777518-a346e100-6804-11e9-9a92-e9d29690fb80.png)

**Comment by cmacma7** [comment]
cause by new release use the 3rd parameter of sendDB, however, in the sendDB of menu.html, we enter the 3rd parameter by error. This problem does not happen before because we don't use the 3rd parameter in the past

**Comment by anitalo73** [comment]
測試ＯＫ
