### ISSUE TITLE
[timeline]較晚來訂位的可選擇時間，應要考量前面還有排隊或訂位尚未入座的組數。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1846]
前面有五組排隊，2組預約，都在等座位。
---
![image](https://user-images.githubusercontent.com/35478230/56942728-c0561980-6b4e-11e9-9e05-512a08c440ec.png)
---
---
---
此時再新增一筆新的訂位，15:00的時間有亮起來，服務員可以安排這組新的訂位。
---
![image](https://user-images.githubusercontent.com/35478230/56942757-de237e80-6b4e-11e9-94ff-f03f701cf206.png)
---
---
---
新的訂位被得到安排一個座位，寫入時間軸。
---
![image](https://user-images.githubusercontent.com/35478230/56942762-e5e32300-6b4e-11e9-8c26-3c619afba7c3.png)
---
---
---
前面有五組排隊的預估時間延後了。
---
![image](https://user-images.githubusercontent.com/35478230/56942800-175bee80-6b4f-11e9-9921-aaf0b2b2ce38.png)

---
---
預期情況：
當滿桌時，且前面有其他排隊或訂位未指定位置時，新的訂位，允許可選擇的時間，應該要更晚，不能晚預訂的反而搶先佔位。
---

**Comment by cmacma7** [comment]
Do not allow reservation in the same date. This should be decided by staff of restaurant. 
If Staff just want to insert reservation by intention, then our feature is correct. So Staff can make decision,.
