### ISSUE TITLE
[timeline]做過刪除訂單後，排隊清單中相同人數單，第一組入座後，第二組的建議桌號會與第一組重複。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1848]
做過刪除訂單後
當排隊清單中，有相同人數的訂單時，系統會給不同座位的建議（第一組A4桌、第二組A5桌）。
但當第一組排隊入座（A4桌）後，第二組的系統建議會變成與第一組已入座的桌號（A4桌）相同。
![image](https://user-images.githubusercontent.com/35478230/56956109-cb707000-6b75-11e9-8a82-376ad62b32ec.png)

**Comment by cmacma7** [comment]
Fixed by item.end assign to the correct value. originally .end in updateItem will be invalid date because the diff is NaN

**Comment by anitalo73** [comment]
測試ＯＫ
