### ISSUE TITLE
[timeline]waiting取號後，timeline的排隊清單數量不正確。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1852]
於waiting執行4組新的取號後，
在timeline的排隊清單數量顯示有7組，點開查看，其實只有4組。
---
![image](https://user-images.githubusercontent.com/35478230/57427031-aacea700-7254-11e9-82c3-d7154c17f8f9.png)
---
![image](https://user-images.githubusercontent.com/35478230/57427081-e5384400-7254-11e9-8ac4-1c3ff0287611.png)

**Comment by cmacma7** [comment]
problem cause by bnsubscribe_recover is called at onConnect. This cause the callback of subscribe been called twice. 
We also not to use pendingWaiting, because the itemChange will automatically reflect.

**Comment by anitalo73** [comment]
測試ＯＫ
