### ISSUE TITLE
訂單確認popup，不應自動帶入匿名資訊

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#186]
1. 不登入, 直接體驗
2. 訂位
3. 確認資訊視窗，會自動帶入anonymousxxxxxx

-> 建議空白即可
1. 訂單確認，查看訂位資訊，訂位名字後面會括號(anonymousxxxxxx)
   -> 建議不要加(anonymousxxxxxx)

**Comment by cmacma7** [comment]
Fixed in SVN 697
