### ISSUE TITLE
新報表開發票，日期錯誤，重整頁面後，日期正確。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1885]
開發票，日期是錯誤的
![image](https://user-images.githubusercontent.com/35478230/60499568-4cb9bf80-9ceb-11e9-9171-0e85d2da537b.png)

重整頁面後，日期正確。
![image](https://user-images.githubusercontent.com/35478230/60499510-2e53c400-9ceb-11e9-945c-9e55dad1d9bb.png)

**Comment by cmacma7** [comment]
因為是HTML所以造成沒有辦法顯現
已修正
