### ISSUE TITLE
[new POS] 重新整理後，第三次結帳時，系統會把第二次結帳的品項也帶出來。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1887]
第二次結帳品項是ab兩個品項，結帳完成，跳出到pos主畫面 -> 訂單結束
第三次進入點單，點品項c，結帳會帶出abc三個品項-> 會成立一筆新的訂單

**Comment by huangVic** [comment]
已修正, 結帳後需把點單資料清除
