### ISSUE TITLE
[new POS]點單查詢，且「加點」後，訂單總額「暴」增。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1889]
點單查詢，且「加點」後，訂單總額「暴」增。
![image](https://user-images.githubusercontent.com/35478230/60945908-69737a00-a31f-11e9-8b00-27e258f5c2e0.png)

未加點前
![image](https://user-images.githubusercontent.com/35478230/60945866-52348c80-a31f-11e9-814f-fb346e47effc.png)

**Comment by huangVic** [comment]
已修正
