### ISSUE TITLE
[new POS] 新版pos的商品清單未與menu.html同步。menu.html已將整個分類(序號100)刪除，但pos端仍顯示該分類底下的商品，且可點單結帳喔。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1896]
menu.htmlm已將整個分類(序號100)刪除
![image](https://user-images.githubusercontent.com/35478230/61434747-6143bc00-a969-11e9-8b00-d6f87a6b9fcb.png)

pos端仍顯示該分類底下的商品，且可點單結帳喔。
![image](https://user-images.githubusercontent.com/35478230/61434879-b8499100-a969-11e9-9cce-66ed0d3196ee.png)

**Comment by cmacma7** [comment]
We will not allow user to delete Category unless he delete all items under the category.

**Comment by cmacma7** [comment]
fixed by not allow user delete non-empty category
