### ISSUE TITLE
menu.html需要有全選的功能 （該分類底下有超過千個品項，需要有可以全選刪除的功能。）

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1899]
該分類底下有該分類底下有超過千個品項，需要有可以全選刪除的功能。

![image](https://user-images.githubusercontent.com/35478230/61603610-ca307a00-ac70-11e9-87b7-c389eed9d446.png)

**Comment by cmacma7** [comment]
add select all feature
