### ISSUE TITLE
[new POS]結帳時，快速點結帳按鈕，點數的折扣就會產生多次。

### ISSUE THREAD

**Issue by anitalo73** [cmacma7/bn#1901]
結帳時，選好品項，給好折扣的點數
在結帳的最後一個步驟，快速點[結帳]按鈕，
最後成立的訂單，點數的折扣就會產生多次。

![image](https://user-images.githubusercontent.com/35478230/61702931-2f6c9400-ad73-11e9-8a09-91ee5b804fc8.png)

**Comment by huangVic** [comment]
已將結帳按鈕擋下不能再重複點擊
