### ISSUE TITLE
新的訂位和單品訂單似乎都不被系統認成訂位和訂單，所以在訊息中的訂單類沒被filter 出來。

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#193]
是到下方footer bar, 按訊息，然後右上方，選訂單，就會看到 收到預約，或預約寄件備份。如果進銅盤，預約定位，你將看到預約的兩個widget, 你兩個都訂，然後回到上面描述的地方，看看是不是只見到舊版widget送的單

**Comment by cyen1121** [comment]
fixed
