### ISSUE TITLE
點推播通知開啟app，之後按back的畫面

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#195]
1. 訂單通知: 
   a. 開啟app，打開訂單通知
   b. 按back，回到訂單列表
2. 店家廣告推播:
   a. 開啟app，顯示widget郵件內容
   b. 按back，顯示店家主頁
   若是2b無法達成，引導進店家的ＵＩ需要更加強提示性

**Comment by cmacma7** [comment]
回信息主頁比較合理. 倒是廣告上可加一個＂去商店＂的icon

**Comment by cmacma7** [comment]
fixed in 1.1.730. show shortcut to store at widget level. Click the circle button will show the shortcut
