### ISSUE TITLE
[主頁][新增] 清單後面的商店、頁面圖示不一致

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#214]
[熱門] 與 另外三個 [類別][附近熱門][ID搜尋] 的圖示不一致 

![2015-05-10-23-35-28](https://cloud.githubusercontent.com/assets/10726049/7568400/2cc12f7e-f835-11e4-9f7a-c7fb27124ff6.png)

**Comment by cmacma7** [comment]
fixed in v1.1.709

**Comment by peichingliao** [comment]
[主頁][新增][ID搜尋] 搜尋247，十一街商店後面沒有店舖 icon
[主頁][新增][熱門] 搜尋 "妞媽"，妞媽小鋪後面沒有店舖icon

**Comment by cmacma7** [comment]
These store are not "certified stores", only admin certified store has the store icon.

**Comment by cmacma7** [comment]
If you go to front page, you should notice this difference...
