### ISSUE TITLE
[主頁][新增] 商店、頁面收藏方式不一致

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#215]
[熱門] 與 另外三個 [類別][附近熱門][ID搜尋] 的收藏方式不一致
建議改一樣的方式（都在popup裡面收藏）

![2015-05-10-23-35-28](https://cloud.githubusercontent.com/assets/10726049/7568453/7c3a1e6c-f835-11e4-9bd6-6920c77c80f7.png)

**Comment by cmacma7** [comment]
fix in v1.1.709

**Comment by peichingliao** [comment]
附近熱門沒有一致

**Comment by cmacma7** [comment]
1.1.713 fixed.
