### ISSUE TITLE
[主頁][新增][類別] 搜尋到的頁面，資訊不足

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#217]
醫療->醫院
出現的頁面資訊不足
所屬的商店為？
尤其很多快速創建的商店，名稱重複的頁面很多
![2015-05-10-23-39-31](https://cloud.githubusercontent.com/assets/10726049/7568538/eb6ba7d8-f835-11e4-8e7d-80b26b86d8ed.png)

**Comment by cyen1121** [comment]
現階段已經沒有分類，這部分可能需要讓使用者自己加入關鍵字，方便搜尋

**Comment by peichingliao** [comment]
2016/04/20  現階段已無分類
