### ISSUE TITLE
[主頁][新增][附近熱門] 無法清空地標搜尋的結果

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#219]
1. 輸入地標 “大湖公園"
2. 點擊 "輸入"
3. 顯示兩個項目
4. 清空地標欄位
5. 點擊 "輸入"  ---->  無法清空搜尋結果
   ![2015-05-10-23-44-36](https://cloud.githubusercontent.com/assets/10726049/7568632/61c81628-f836-11e4-87da-e9f563267dc4.png)

**Comment by cyen1121** [comment]
fixed

**Comment by cyen1121** [comment]
不會一直去做搜尋的動作
所以一定要按下Enter才會顯示更新結果
要不然ＤＢ和Google API會被過度使用

**Comment by peichingliao** [comment]
本來是清空後按enter會有問題
但現在清空後按enter OK了 @@
