### ISSUE TITLE
[訊息][訂單][分析] 金額顯示不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#220]
![2015-05-11-14-46-58](https://cloud.githubusercontent.com/assets/10726049/7568664/87a58c18-f836-11e4-9913-c122ef8dbfca.png)

**Comment by cyen1121** [comment]
fixed

**Comment by peichingliao** [comment]
現在chic rose baby蓬裙顯示價格為0

**Comment by cyen1121** [comment]
就的訂單沒有價錢 新產生的訂單才會有
