### ISSUE TITLE
[訊息][訂單][分析] 點擊單項之後，無法返回總項目清單

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#221]
根據Ｄ爸回覆～
按鈕太遠了，不會想到要點擊那個按鈕

![2015-05-11-14-48-03](https://cloud.githubusercontent.com/assets/10726049/7568692/a4454e12-f836-11e4-8895-cf0bd8b50133.png)

**Comment by cyen1121** [comment]
按鍵調整至表單旁
fixed
