### ISSUE TITLE
[訊息][寄件備份] 項目已無內容，清單項目仍然顯示出來

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#222]
![2015-05-11-14-52-02](https://cloud.githubusercontent.com/assets/10726049/7568716/d572c3b6-f836-11e4-8c92-241115cae3de.png)

**Comment by cmacma7** [comment]
suppose 0 will be deleted

**Comment by cmacma7** [comment]
Fixed in 1.1.718, caused by we still show count=0 items.
