### ISSUE TITLE
[訊息][訂單][滿意度調查] 標題與聯絡資料顯示不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#223]
1. 標題應為 "寄件備份: 滿意度調查"
2. 店家資料格式
   ![screenshot_2015-05-10-11-21-50](https://cloud.githubusercontent.com/assets/10726049/7568779/4da08602-f837-11e4-8f06-9c5a493db754.png)
   應和其他widget一樣，放在最上面

**Comment by cyen1121** [comment]
fixed
