### ISSUE TITLE
[收藏] 建議顯示widget的店家資訊

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#224]
建議顯示widget的店家名稱
若無所屬店家，則顯示頁面名稱

--> 因為收藏了，卻看不出來是哪家店的
--> 把店家連結收進menu裡面，比較不直覺，且四個方格建議改為房子圖示

![screenshot_2015-05-10-20-22-16](https://cloud.githubusercontent.com/assets/10726049/7568803/7b43e752-f837-11e4-9a1c-c8e12a6d01f3.png)

**Comment by cmacma7** [comment]
Change to home button at v1.1.718.

**Comment by cmacma7** [comment]
fix in 1.1.727, click the menu, user can see the home link and store name. click the link will go to the store and the station
