### ISSUE TITLE
[Widget][資訊&介紹][1.1.709.2] Bug 整理

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#226]
1.圖文故事 
   a. 設定 店家: 粉絲報 , 連結ID: 沒設id或是id錯誤  將導致前往之後回不來
![1](https://cloud.githubusercontent.com/assets/1106733/7581464/fa41fb38-f8b5-11e4-9915-c37a2d200177.jpg)
   b. 設定完全沒有內容還是能夠建立 之後要修改但是找不到地方修改內容
![2](https://cloud.githubusercontent.com/assets/1106733/7581516/917c958a-f8b6-11e4-8373-f8939012c2d4.jpg)

2.主題圖文
   a. 設定 店家: 粉絲報 , 連結ID: 沒設id或是id錯誤  將導致前往之後回不來(同1.a)
   b. 前往 css 破版
![3](https://cloud.githubusercontent.com/assets/1106733/7581543/dc13bd58-f8b6-11e4-9d96-b01757eee360.jpg)
   c. 由信箱導向粉絲網 要按兩次Back 才會回到信箱
1. Widget 沒有內容 或是 部分欄位沒設內容 還是能夠建立 但是css會破版

**Comment by cyen1121** [comment]
前往商店按鈕修正了

**Comment by gameflierHao** [comment]
設定完全沒有內容還是能夠建立 之後要修改但是找不到地方修改內容
外框設 min-height: 44px; 應該可以解決
這個問題 我把他拉出來另開issue
