### ISSUE TITLE
before create or save the widget need to call the function to validate

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#231]

**Comment by cmacma7** [comment]
in template, add a validate function.
function validate(context, schema)
    Function is called by system when widget store back to server (edit or create new widget). The system call this function to make sure user has enter correct information in the editor. If information is not enough or error, function will return false, otherwise true. If false, the widget will not be created or modified.
The module use context and schema to valid all the fields that user enter. Most of the cases, context is good enough to validate the fields.

**Comment by cmacma7** [comment]
Hi David, the validate has add to BN. Just implement the validate function in template. Document is added.

**Comment by cyen1121** [comment]
fixed
