### ISSUE TITLE
[Widget][優惠][1.1.711] Bug 整理

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#232]
1. 一次性折價券
   a. 折價券取用後同使用者不同裝置下不會sync
   b. 其他使用者目前被用幾張數量不會同步
   c. 領取後同使用者不同裝置畫面不會syc
   d.不同裝置可以重複領取
2. 即時商品促銷
   a. 剩餘張數用途不明

**Comment by gameflierHao** [comment]
建議有要填時間的欄位，預設的時間為當下日期時間

**Comment by cyen1121** [comment]
fixed
