### ISSUE TITLE
無法顯示Widget需要顯示框架提供刪除等操作

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#243]

**Comment by cmacma7** [comment]
widget try failed will not show, so there is no height for these widgets. Need to have minimum height for each wrapper, so that at least user can delete it.

**Comment by cmacma7** [comment]
Fixed by show yellow widget that allow owner to delete it.

**Comment by cyen1121** [comment]
無法刪除
在頁面內做刪除，重新整理還是會出現錯誤的Widget
