### ISSUE TITLE
新增圖文故事 沒有填內容並建立 會導致之後無法編輯與刪除

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#244]
![screenshot_mon_may_25_18 26 32](https://cloud.githubusercontent.com/assets/1106733/7795887/e6d82c6a-030b-11e5-8cca-382893824a45.png)

如圖所示

是否需在widget外框加入min-height呢?

**Comment by cmacma7** [comment]
Use minHeight to div wrapper. Fix in 1.1.728
