### ISSUE TITLE
[Widget][優惠訊息]無法建立

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#250]
新增優惠訊息
建立無法建立

Uncaught TypeError: Cannot read property 'validate' of undefined

function validateWidget() {
    return TemplateAction[global.widget.template].validate ? TemplateAction[global.widget.template].validate(global.widget.context, global.widget.schema) : !0
}

**Comment by cyen1121** [comment]
這個Template完全沒有action

**Comment by cmacma7** [comment]
fix in 1.1.730
