### ISSUE TITLE
新增頁面後，無法立即新增widget

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#251]
在修改商店內，新增頁面後，進入該頁面，無法立即新增widget，要先完成商店編輯，在進入頁面才可編輯。
![screenshot_wed_may_27_11 33 52](https://cloud.githubusercontent.com/assets/1106733/7828301/5a5e28ac-0464-11e5-9f8c-e338c185b6a8.png)
![screenshot_wed_may_27_11 34 26](https://cloud.githubusercontent.com/assets/1106733/7828302/5b70c650-0464-11e5-8f77-11b9456732f9.png)

**Comment by cmacma7** [comment]
fixed inv 1.1.730.
