### ISSUE TITLE
隱藏Widget未同步

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#255]
(1)第一個視窗先點widget（訂單類型）上的歷史紀錄進去訂單頁面後
(2)第二個視窗對相同頁面內的Widget做隱藏動作
(3)第一個視窗離開訂單頁面，被影藏的Widget還是為顯示狀態，重新Refresh後才能看到隱藏狀態

**Comment by cmacma7** [comment]
fix in 1.1.730,

**Comment by cyen1121** [comment]
checked V1.1.731
