### ISSUE TITLE
[Widget][建立菜單] 菜單更新後頁面上內容不會自動更新

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#273]
如題 
步驟如下
1. 建立菜單
2. 修改菜單
3. 菜單更新後頁面上內容不會自動更新，要重整頁面。

**Comment by gameflierHao** [comment]
更新: Fullscreen mode底下有此問題，一般mode則無。

**Comment by cyen1121** [comment]
![screen shot 2015-06-11 at 9 53 37 am](https://cloud.githubusercontent.com/assets/10192854/8098240/e24e91c2-101f-11e5-9618-34fdbf818bc9.png)

**Comment by cyen1121** [comment]
在全畫面情況下編輯會出現此錯誤

**Comment by cmacma7** [comment]
trying.
