### ISSUE TITLE
Refresh造成頁面功能失效

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#275]
# page_editGroup
# page_widgetEditor
# page_editGroupInfo
# page_editStation
# page_widgetSelect
# page_createStation
- 直接refresh後還是可以建立但station不屬於任何一個商店
# page_createGroup
- 直接refresh後還是可以建立商店但裡面都是空的
- 然後這種情況建完後的商店不會跳到商店會跳到sub_category的頁面

**Comment by cyen1121** [comment]
#page_widgetScheduler

**Comment by cmacma7** [comment]
fixed at BN 5/9.
store 1.1.749

**Comment by cyen1121** [comment]
checked
