### ISSUE TITLE
[設定][編輯好友清單] 好友名單不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#279]
我的帳號一直有個 (0) 的帳號在第一個
如果清cache，就會預設有個 (0) 的好友

**Comment by cmacma7** [comment]
Hi PC, I need to login your account to see the problem.
Please go to browser console and give me your
localStorage.loginMyth
It looks like "cmacma7@gmail.com:136:22481cmacma7@gmail.com"
With this, I can login your account without use your user name and password.

**Comment by peichingliao** [comment]
Sylvia Liao:143:21488Sylvia Liao

**Comment by cmacma7** [comment]
This problem caused by no display name and title for this account
