### ISSUE TITLE
[分享] 藉由widget網址開啓的UI畫面問題

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#292]
開啟 http://store.tagfans.com/index.html?noteId=10381&_stationId=896&_storeId=296#page_join
1. 此widget無店家資訊提示
2. 左上的icon與其他畫面不一致
3. 上方標題不應為"標籤"

**Comment by cmacma7** [comment]
Fixed by apply store title and station title to the banner.

**Comment by peichingliao** [comment]
依舊無法直達店家頁面

**Comment by cmacma7** [comment]
You need to click the tagfans logo to go to the page, then go to store.
What is "依舊無法直達店家頁面" means?

**Comment by peichingliao** [comment]
我是指沒有下圖的icon，和訊息的widget樣貌不統一。用習慣了之後會想按 “<" 去連商店
![2015-09-01 10 26 12](https://cloud.githubusercontent.com/assets/10726049/9606938/d2cd27b2-50f8-11e5-8cc6-4036039a2666.png)

**Comment by cmacma7** [comment]
Change the back-arrow button at left-top corner to home button. 
Fixed at BN, and will be deploy after v1.1.812 of store.tagfans.com
example:   http://bn.tagfans.com/node/fb.html?noteId=7214_819_296
