### ISSUE TITLE
[分享] Widget網址無法複製

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#293]
使用macbook air, chrome browser
無法選取網址，只能點到http，如圖

![2015-06-16 10 22 17](https://cloud.githubusercontent.com/assets/10726049/8185496/5c00d484-1477-11e5-91d9-8865589e1bcc.png)

**Comment by cmacma7** [comment]
Fixed by change the <a> link to <textarea>, same solution as youtube.

**Comment by cmacma7** [comment]
Fixed in v1.1.751

**Comment by peichingliao** [comment]
我的mac還是很難選取網址
![2015-06-17 5 20 09](https://cloud.githubusercontent.com/assets/10726049/8203580/5bc55dc0-1515-11e5-989b-8baece0650b5.png)

**Comment by cmacma7** [comment]
Mac seems to be click three times, then whole block will be selected. This is <textarea>, I tried Mac also see the same problem... very strange. Mac does not like mouse selection...

**Comment by cmacma7** [comment]
Fixed by auto select the text area. This is a bug of chrome after version 41. 
But user still can be hard to select partial of the text.
