### ISSUE TITLE
[Widget][Youtube] Youtube網址很難按出複製貼上選單(手機app）

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#294]
Youtube網址很難按出複製貼上選單(手機app）

**Comment by cmacma7** [comment]
Youtube網址很難按出複製貼上選單? Do you mean Android's problem?

**Comment by peichingliao** [comment]
![img_7794](https://cloud.githubusercontent.com/assets/10726049/14662957/f172bb54-06ed-11e6-87d7-2d5dae5bfa08.PNG)

**Comment by peichingliao** [comment]
請看上一張圖
1. 建立youtube widget -> 完成
2. 回到page
3. 編輯已建立的youtube

在editor畫面上，會看到youtube iframe覆蓋在上面 (iPhone app, safari都會發生)
應該在widget > 編輯的時候, 先把iframe隱藏, 或直接刪掉widget div
編輯完成再顯示
