### ISSUE TITLE
[Store]編輯商店頁面刪除按鈕被擋住

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#295]
選取頁面 
上下移動按鈕會擋住刪除按鈕
![screenshot_wed_jun_17_01 11 29](https://cloud.githubusercontent.com/assets/1106733/8190210/e109cfd4-1493-11e5-9bf5-6d21463a85de.png)

**Comment by cmacma7** [comment]
Fixed by move down the button
