### ISSUE TITLE
［Widget］4.1.2 無法直接點選QR Code進入相對應之網頁

### ISSUE THREAD

**Issue by ChihKaiChen** [cmacma7/bn#299]
4.1.2 也可以直接透過點選QR Code打開相對應的網址
測試瀏覽器：Mac版Chrome
問題：於商店分享產生QR Code後，無法直接點選QR Code進入相對應之網頁

**Comment by cyen1121** [comment]
測試的項目是商店分享ＱＲ
並非Widget的QR Code分享
