### ISSUE TITLE
［Widget］7.集點卡 輸入認證號碼後無反應、無法進行集點的動作

### ISSUE THREAD

**Issue by ChihKaiChen** [cmacma7/bn#300]
7.集點卡
測試瀏覽器：Mac版Chrome & Windows版Firefox
問題：在Chrome輸入認證號碼後無反應，也無法於另一裝置進行集點的動作，更新認證碼後重新輸入也毫無反應

**Comment by cyen1121** [comment]
測試無此問題
可以詳細敘述操作步驟
