### ISSUE TITLE
Admin tool for Agent Store

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#306]
User2Stores need extraInfo field to store any extra info.
When request join Agent Store, popup need user enter either password or extra info, then send message to Store owner.
Store owner will receive the message, confirm user, name email and extra info, then modify extra info. Store owner will accept or reject the request by the mailed widget. If agree, then user2stores will be modify to accept the user.

**Comment by cyen1121** [comment]
Store need to add two more field, auth message and auth password. If auth password is empty, the send email for manual auth. Otherwise, use password auth.

**Comment by cmacma7** [comment]
Added to BN

**Comment by cmacma7** [comment]
Store owner can choose use password or admin agree two modes to allow user enter the store.
