### ISSUE TITLE
沒有調整排列順序的箭頭

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#313]
(1)確認頁面可以手動排序
(2)編輯Widget
(3)建立（編輯完成）
(4)對Widget選擇調整位置
(5)原本在Widget上面跟下面的insert 箭頭不見了

**Comment by cmacma7** [comment]
Fixed by item.removed will be splice from the storyBoard.currentArray inside storyBoard.draw().
Problem caused by item has been removed but still count inside the remove() function

**Comment by cmacma7** [comment]
Still see problem in some widgets that has position problem
