### ISSUE TITLE
［widget］地圖地址可輸入經緯度，並可同時顯示地址及經緯度

### ISSUE THREAD

**Issue by ChihKaiChen** [cmacma7/bn#321]
![2015-07-07 3 24 29](https://cloud.githubusercontent.com/assets/10973539/8540906/67768b1a-24bc-11e5-9be7-e5e4b072331f.png)

**Comment by cmacma7** [comment]
No need to display 經緯度. Only need to have input of 經緯度, and if user input 經緯度, then we will ignore the address.

**Comment by cyen1121** [comment]
context新增glc參數去設定座標位置
如果有座標則以座標為地圖定位，沒有才以地址做設定
