### ISSUE TITLE
[Flow] 無法從設定頁面切到別的頁面

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#338]
http://bn.tagfans.com/node/fb.html?noteId=6993_501

開了這頁(Note3, Chrome)，按兩次左上角icon回到tagfans主頁，
再按到設定
就切不回其他分頁了

你們都試不出來喔

**Comment by cmacma7** [comment]
Still cannot reproduce on PC and devices...

**Comment by cmacma7** [comment]
Is there anything very special? Can you try on PC or other devices to see whether you can see the same bug?

**Comment by peichingliao** [comment]
Uncaught TypeError: bnsql.getMailStatus is not a function  jqm.js:15626

**Comment by peichingliao** [comment]
電腦可以複製(Macbook, chrome)
Uncaught TypeError: Cannot read property 'length' of null   template_actions.js:583
登入id: 112 (bn)

**Comment by peichingliao** [comment]
on bn
Sylvia Liao:112:21457Sylvia Liao

**Comment by cmacma7** [comment]
Fixed at BN, it supposed to be the same problem of this account does not have "title" field, which cause js fail. 
Will commit the fix after v1.1.812 at store.tagfans.com.
