### ISSUE TITLE
[Widget] 私人訊息

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#340]
開啟私人訊息 
傳送給店家 
店家會收不到訊息
但是其他客人卻收到

**Comment by Conniehung** [comment]
另外，關於我們推播需客人與飯店都有推播機制比較好，目前只有飯店方有訊息通知聲音，客人這邊沒有

**Comment by cmacma7** [comment]
Fixed at version 1.1.891.
Fix: use "auto" at insertNoteMessage.
