### ISSUE TITLE
[System]在一開始登入畫面，語言替換 香港、大陸 這兩種語言沒有動作

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#342]
使用平台 : PC 
瀏覽器 : Chrome

問題 : 一開始登入畫面(還沒登入的情況下)左上角可以選擇更換語言，但是香港跟大陸這兩種沒有動作。

**Comment by cmacma7** [comment]
Actually, this is because we don't have Hongkong and China language, so we just copy Taiwan language.
