### ISSUE TITLE
[Widget]滿意度調查計數錯誤

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#343]
測試平台:PC

1.新增商店->選擇創立餐廳結束之後，其中選項顧客反應與意見中的滿意度調查任兩個選項快速交錯點擊
   計數量會有負數出現。
2.一樣是滿意度調查"選項輸入"建議可以加入按下Enter即可輸入。

**Comment by chuangshaojung** [comment]
![Uploading bug.png…]()

**Comment by chuangshaojung** [comment]
![bug](https://cloud.githubusercontent.com/assets/13726130/9218712/4661d382-4107-11e5-9f9d-249c3783c1d0.png)

**Comment by cyen1121** [comment]
fixed
