### ISSUE TITLE
[System]在編輯商店時，按下編輯按鈕所跳出的視窗，取消鍵失靈。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#344]
使用平台 : PC 
瀏覽器 : Chrome

![default](https://cloud.githubusercontent.com/assets/13726076/9220499/9a253f96-4115-11e5-92ca-2d7ef66f1cc5.png)

問題 : 上圖為按下編輯按鈕跳出的視窗，此視窗的取消按鈕沒有動作。

**Comment by cmacma7** [comment]
Fixed by attach  onclick=$("#popup_joinMenu").popup('close');
