### ISSUE TITLE
[店面資料]測試資料刪除

### ISSUE THREAD

**Issue by Conniehung** [cmacma7/bn#345]
以下測試資料刪除

漢來 
Store ID : 337
Store ID : 344
Store ID : 350

美麗信
Store ID : 351
Page ID : 1401

君悅
Store ID : 332
Page ID : 1219
Store ID : 353

**Comment by cmacma7** [comment]
store 337  陳栢睿  FB account
store 344 匿名帳號
store 350  ideas0615@gmail.com
store 351 IIIbookSerivice@gmail.com
store 332  Zhang Hao Wu FB account zhanghaowu2@hotmail.com 
store 353 IIIbookSerivice@gmail.com
