### ISSUE TITLE
[widget][style] 需要有橫式的 responsive widget, 因為直式在很多情況下都太長了, 

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#358]

**Comment by cyen1121** [comment]
![2015-08-20 11 11 39](https://cloud.githubusercontent.com/assets/10192854/9376711/4f09a1b2-4743-11e5-8349-bf6a633924f0.png)
![2015-08-20 11 12 15](https://cloud.githubusercontent.com/assets/10192854/9376712/4f0df0fa-4743-11e5-9403-cbbe2bfe5356.png)
![2015-08-20 11 12 47](https://cloud.githubusercontent.com/assets/10192854/9376713/4f0e352e-4743-11e5-8328-ac6f11189963.png)
參考
