### ISSUE TITLE
[widget順序] 在電腦瀏覽器上改widget的順序後，手機上的順序不會同步

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#365]
使用平台 : PC 
瀏覽器 : Chrome

流程 : 在PC上修改widget的順序後，手機上的順序不會同步修改，除非離開頁面再進入一次。

**Comment by cmacma7** [comment]
這個是正常的   擁有者更改順序使用者並不會馬上見到改變直到他下一次再進入頁面

**Comment by cmacma7** [comment]
如果使用者看的時候可以被改變順序, 他一面看, 東西就是會跳來跳去,這是不合理的
