### ISSUE TITLE
[widget] 集點卡功能 若"店家"輸入錯誤認證碼 "客戶"也會顯示認證碼已過期。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#370]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶
使用平台 : iphone4 ios7.1.2

流程
1. 客戶端 點選我要集點按鈕後 產生一組 認證碼 
2. 店家端 輸入錯誤的認證碼 並按下傳送
3. 客戶端 的認證碼條上 會出現已過期的樣式(但是其實此認證碼還能夠使用)

**Comment by cmacma7** [comment]
Verified, it is a bug...

**Comment by cmacma7** [comment]
Hi David, can you check what's the login to show expire? If owner enter the wrong code, all the customers will show expired...

**Comment by cyen1121** [comment]
fixed

**Comment by cmacma7** [comment]
Hi David, when you fix a bug, you might want to describe how you fix, and in the future, the version number of the widget.

**Comment by cmacma7** [comment]
Hello Wade, if you check the bug is fixed, you need to close the bug

**Comment by wade89214** [comment]
ok

**Comment by wade89214** [comment]
這裡網路一直斷掉 可能要花點時間...
