### ISSUE TITLE
[Flow] 點推播通知後, 網頁 automatically get the latest version, 自動更新跳回主頁. 

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#372]
Store app推播波多野的訊息 
我點開android通知
出現訊息一兩秒，結果因為網頁更新，自動跳到主頁去了

**Comment by cmacma7** [comment]
There seems no way to delay auto update of manifest.

**Comment by cmacma7** [comment]
Fixed by not auto update, the update will happen in next time, not current time. As the result, user should still see the message, and the page will not update.

**Comment by peichingliao** [comment]
已修正
