### ISSUE TITLE
[mail][widget][訊息] 點商店icon無作用

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#373]
1. http://store.tagfans.com/#page_station?o=324
2. 點訊息
3. 點本店店長
4. 點(範例)波多野日式烤肉的 <
5. 點 "波多野日式烤肉-新竹店"，無作用，但是折價卷的widget有作用

**Comment by cmacma7** [comment]
Fixed by jump to store front page. Currently fix at BN.
Originally plan to popup window to warn customer that already in store, but it is still confusing.
