### ISSUE TITLE
[sharing][分享] Facebook字太大變Facebool

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#374]
store網站 (Macbook, chrome)
![2015-09-01 11 13 26](https://cloud.githubusercontent.com/assets/10726049/9608137/69e54e6c-50ff-11e5-969d-1f93c74adff1.png)

**Comment by cmacma7** [comment]
Caused by text font size, overflow hidden, the 1em is 16px depends on zoom factor.

**Comment by cmacma7** [comment]
change font-size to 0.85em. It will solve zoom factor 100% , but if user set the zoom larger than 110%, the font will still be truncated.
