### ISSUE TITLE
[widget][全版菜單] Provide one column width to widget 

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#375]
getItemWidth() will give single item width. Or say, if gridLayout does not provide columnWidth, then the gridLayout will automatically assign a reasonable columnWidth to each item. That means caller just need to set columnWidth of gridLayout to null.

**Comment by cmacma7** [comment]
1. GridLayout(itemArray,  rootDiv, horizontalGap, verticalGap, columnWidth), if columnWidth set to null, the system will automatically assign column width. If columnWidth set to a specific value, then the columnWidth will be fixed even the screen size change. Set to null will resize the width if screen size change.
2. global.tagWidth   will get one column width of a widget

**Comment by cmacma7** [comment]
Fixed at BN.
