### ISSUE TITLE
[system][統計頁面]需要讓"統計總結"頁面可以點"訂單編號"查看詳細內容

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#378]
http://store.tagfans.com/#page_join?o=264&id=3130&viewType=station&srcNoteId=23251
這兩個widget需增加
(單一商品訂購，進階商品團購）

**Comment by cmacma7** [comment]
分類不應該是widget, 而應該是[system][統計頁面]

**Comment by peichingliao** [comment]
2016/04/20 已可查看訂單明細
