### ISSUE TITLE
[System] app裡面的input，點了不會自動跳到鍵盤上方

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#382]
Note3, chrome 點了input，會自動跳到鍵盤上方
而tagfans app的input會被跳出來的鍵盤擋住
使用起來不方便

註：fabebook app 點了input，也會自動跳到鍵盤上方

**Comment by cmacma7** [comment]
This is a bug in the Android native browser. By the way, the input scrolls into the view after a character is typed on the soft keyboard.
The following code snippet placed somewhere in the page should help:

if(/Android 4.[0-3]/.test(navigator.appVersion)){
   window.addEventListener("resize", function(){
      if(document.activeElement.tagName=="INPUT"){
         window.setTimeout(function(){
            document.activeElement.scrollIntoViewIfNeeded();
         },0);
      }
   })
}

**Comment by cmacma7** [comment]
http://stackoverflow.com/questions/23757345/android-does-not-correctly-scroll-on-input-focus-if-not-body-element

**Comment by cmacma7** [comment]
加了修正但是好像沒有產生效果

**Comment by peichingliao** [comment]
2016/04/20 NOTE3 app 已無此問題
