### ISSUE TITLE
[widget] 報號與抽號 若"客戶"抽號產生訂單後，"老闆"無法在全部單據內刪除個別的訂單。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#388]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶
使用平台 : iphone4 ios7.1.2

流程
1. 客戶端 點選抽號完成訂單
2. 老闆端 進入全部單據內後，無法對特定的訂單做刪除的動作(只能夠按右上角的"工具"全部刪除)
![default](https://cloud.githubusercontent.com/assets/13726076/9721460/3ea71d84-55cd-11e5-997b-6fef5f1c4a8b.png)

**Comment by cmacma7** [comment]
This is the correct behavior because "order" suppose cannot be deleted.

**Comment by cmacma7** [comment]
If user or merchant can delete order, this order will lost forever.

**Comment by wade89214** [comment]
可是 右上角的工具還是能刪除郵件
