### ISSUE TITLE
[widget] 報號與抽號 編輯頁面 取票模式關閉or開啟不太清楚是什麼意思。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#390]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶
使用平台 : iphone4 ios7.1.2

流程
1. 老闆端 編輯報號與抽號Widget 的第四個選項 "取票模式" 不太清楚是什麼意思。

**Comment by cmacma7** [comment]
should add more description for "取票模式"

**Comment by cyen1121** [comment]
fixed 改名成"模式設定" (1)開啟報號 (2)關閉報號
需要重新加一次Widget才會看到

**Comment by wade89214** [comment]
OK
