### ISSUE TITLE
[widget] [排行榜/列表] 操作行為

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#391]
1. 開啟連結選擇關閉, 但是有輸入地址的話, samsung 手機 or NB chrome 點擊會帶入 google map in tagFans app, 這個是預期的對嗎?
2. 開啟連結選擇外部連結, samsung 手機 or NB chrome 點擊會帶出兩個頁面, 一個是 google map, 一個是外部連結, samsung 手機按上一頁, 會當在內嵌的 google map, 得重啟 app 才行~

可以選"媽媽寶貝團購"->最新消息->裡面的喜好排行榜, 複製出此問題~

**Comment by gameflierHao** [comment]
剛剛與David討論，以下是討論結果。
1. 地址開啟地圖和外部連結為不同行為，因此此情形是正確的。
2. 同1.，由於點取了地址與選項，因此帶出兩個頁面也是正確的。
當機問題要查一下, ASUS 裝置有相同問題。

**Comment by cyen1121** [comment]
修正一下第二點
嘗試操作後發現這樣在APP上會造成錯誤與人不容易發現有兩個頁面的產生

所以合理的修正是點地址要特別處理或是有明確的地方讓人知道可以開啟地圖

**Comment by cyen1121** [comment]
點擊地址只會開啟地圖
點擊電話只會撥打電話
其他區域則是開啟網站或是連結到商店
