### ISSUE TITLE
[widget] [圖文故事] 留言時間顯示問題。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#397]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家 or 客戶[2] 輸入留言。
2. 客戶[1] 在手機上顯示的留言時間都會顯示成年月日 ex : 2015/09/09 00:31:19
    (除非重新進入頁面)。

**Comment by cyen1121** [comment]
這問題跟報號之前一樣的原因
請Howard幫忙確認

**Comment by gameflierHao** [comment]
fixed

**Comment by wade89214** [comment]
OK
