### ISSUE TITLE
[widget] [圖文故事] 留言時間不會隨著時間做更新的動作。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#398]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家 or 客戶[1] or 客戶[2] 輸入留言。
2. 店家 or 客戶[1] or 客戶[2] 留言時間不會隨著時間做更新的動作。
    (除非重新進入頁面)。

**Comment by cyen1121** [comment]
fixed
現在設定幾種情況下會更新時間
(1)當有新的訊息或輸入新的訊息都會對所有訊息的時間欄位做更新
(2)設定interval在每一分鐘都（60秒）自動做一次更新

並對所有牽涉到的Widget都須在destroy時同時清除interval timer

## 修正Message modules

utilityPackage

## 修正Widget modules

customerSatisfacationMail
AStory.White
AStory.White#Vertical
AStory.White#TextFirst
AStory.White#small
TopicStory#cube
TopicStory
MenuOrderListWithCheckBox
FreeStyleCustomerPurchaseForm

**Comment by wade89214** [comment]
OK
