### ISSUE TITLE
[widget] [圖文故事] 選擇圖片用網頁搜尋時，選擇某些圖片會發生image error。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#399]
店家
使用平台 : PC 
瀏覽器 : Chrome

Bug
流程
1. 店家 進到編輯標籤頁面。
2. 按下更換圖片。
3. 選擇"網頁"搜尋。
4. 輸入"櫻花"。(關鍵字改成別的也有可能發生，目前不確定有什麼關聯性)
1. 選擇第一張圖片。
   ![0](https://cloud.githubusercontent.com/assets/13726076/9837756/29d6669a-5a7c-11e5-9bbe-329f28969368.png)
2. 會發生下圖的警告。
   ![000](https://cloud.githubusercontent.com/assets/13726076/9837742/caea57d6-5a7b-11e5-97b9-2ef159a4481b.png)

**Comment by gameflierHao** [comment]
原因：這是由於來源圖片錯誤所導致
解法：當此情況發生時，我會會去使用google search出來的縮圖來做為編輯圖片。
