### ISSUE TITLE
[Widget]一次性折價卷 店家專用意思不太清楚

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#401]
店家
使用平台 : PC 
瀏覽器 : Chrome

流程
1. 店家端 一次性折價卷中按下領取->出現"店家專用"按鈕，是指店家才能按此按鈕? 不太清楚是什麼意 
    思。

**Comment by cyen1121** [comment]
就是給店家看完後才能點掉做兌換的動作

**Comment by chuangshaojung** [comment]
所以客戶端點了"店家專用"店家會收到來自客戶端訊息?

**Comment by cyen1121** [comment]
這部分是客戶出示給老闆做點及兌換的動作
