### ISSUE TITLE
[團購需求] 容易加入 facebook 社團既有成員

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#403]
竹北媽媽希望我們批次幫忙加入目前 facebook 上面的成員 (23,154 位成員) 到竹北媽媽的商店中, 或是提供容易的方法, 讓團員能容易自動加入竹北媽媽的店成為會員.
   點開 https://www.facebook.com/groups/273895059357824/ 右邊有成員清單可以看到目前有的成員

**Comment by ghyu65** [comment]
取得社團成員可以參考 http://stackoverflow.com/questions/4087227/list-the-members-of-a-facebook-group-via-api
好像是 https://graph.facebook.com/[GROUPID]/members?access_token=[ACCESSTOKEN] 可以取得, 不過不確定是否有人數限制, 因為像團購竹北媽媽, 有兩萬多, 應該不太可能一次回傳完才是~

**Comment by cmacma7** [comment]
Use passcode to protect should be OK.
