### ISSUE TITLE
[團購需求] 通知到貨之後, 要自動倒數

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#404]
團主通知客戶到貨到貨之後, client 端會倒數七天, 顯示要取貨的期限, 如果沒有取, 自動取消訂單和通知團主狀態更新~

**Comment by cyen1121** [comment]
再進階團購商品中設定訂單狀態訊息裡面如果有設定過期時間，當選擇到此狀態將會顯示到期時間，並在到期時主動變換訊息為訂單已過期。

**Comment by cyen1121** [comment]
訂單訊息可以設定到期時間
