### ISSUE TITLE
[團購需求] 需要複製商品的功能

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#405]
希望新增商品的流程可以更簡化, 因為他們取貨跟付款方式基本上都固定, 所以不想重新輸入, 商品格式也類似, 希望就是能複製商品 widget, 之後更新商品資訊即可, 能快速建立商品出來

**Comment by cmacma7** [comment]
Only owner has the right to copy, as the result, copy feature will be enabled only he is the owner of the widget.
Will add a "copy" button at the widget menu (the circle one). To paste, user need to go to page menu, then click paste.

**Comment by cmacma7** [comment]
Fixed at store, v1.1.821.4 and after.
Use copy (+) icon at widget menu to copy.  
Paste by click page menu, select paste widget button to paste.

**Comment by ghyu65** [comment]
Great!
