### ISSUE TITLE
[團購需求] 商品上面顯示目前銷售數量

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#406]
希望商品上面圖案能多一個目前銷售數量統計,    類似 17p or groupon 熱銷破千之類,
   e.g. 訂購人數超過五十, 就開始顯示,    因為台灣人是盲目和一窩蜂的,    他們覺得會有吸引更多人購買的效果

**Comment by cyen1121** [comment]
進階團購會將下過多少數量的訂單都顯示在最外層圖片上面
