### ISSUE TITLE
[團購需求] 在商店裡面訂購商品, 要回 facebook 自動 tag 購買者 +1

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#407]
(高優先關乎他營運的獲利)下訂單的同時需要與FB做連動可以讓其他顧客知道有人對商品下單類似+1的概念，以達到宣傳的效果，團購版主認為如果沒這概念會造成大家以為沒什麼人買，而銷售狀況反而變差，類似有人排隊的才好吃的概念。  Moya: 看可否用 Tag 團員的方式來做, David 要研究一下是否有對應的 API

**Comment by ghyu65** [comment]
可參考 http://digitizor.com/2011/01/24/tag-user-facebook-graph/  or http://cythilya.blogspot.tw/2014/09/facebook-graph-api-taggable-friends.html

**Comment by cmacma7** [comment]
Add bn.commentFB({user-id}, {message});  to send comment to a facebook tag.
Example: 
bn.commentFB("489281391241140", "hello world from BN");

**Comment by cmacma7** [comment]
David need to call this function when user put order in widgets.

**Comment by cyen1121** [comment]
放入團購
