### ISSUE TITLE
[團購需求] 對每個商店的分類頁能夠有搜尋或是filter

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#408]
對每個商店的分類頁能夠有搜尋或是filter，因為他希望商品能不做多餘的分類，所以都會放置在同一個頁面裡面，但因為手機瀏覽有限，如果商品很多的時候會很難做找尋，故需要這類的功能

**Comment by cmacma7** [comment]
Will enable page-wide keyword search, sorting, and layout change (change grid width).

**Comment by cmacma7** [comment]
We have category widget, the merchant can use category widget, and that widget has keyword search capability. Please refer to jqm_list module. 
Under such condition, a store has one store page, and several category pages, each category page point to multiple pages.
