### ISSUE TITLE
[團購需求] 一次性通知到貨的功能

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#409]
在統計頁面內需要filter針對特定商品能夠一次變更所有狀態，主要是為了如果某樣商品到貨，那就可以一次性通知這商品購買者來取貨

**Comment by cyen1121** [comment]
## 修改以下Modules

module_showSummary

## 修改以下Widget Templates

FreeStyleCustomerPurchaseForm
MenuOrderListWithCheckBox
BroadcastNumberTicket
MenuOrderList.White
RegisterEventForm
BookingTableListSchedule
BookingTableList.White

**Comment by cyen1121** [comment]
加入功能!

**Comment by cyen1121** [comment]
目前只支援進階團購和進階菜單Widget

**Comment by ghyu65** [comment]
Great!
