### ISSUE TITLE
[widget] [圖文故事] 留言的文字輸入框右邊的輸入按鈕動作怪怪的。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#411]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家 or 客戶[2] 在PC上輸入文字時，"輸入按鈕"不會出現，按下Enter送出留言後才會閃現一下。
2. 客戶[1] 在手機上輸入 一個 "數字" or "字母" 時，"輸入按鈕"不會出現，無法送出。

**Comment by cyen1121** [comment]
fiexd.
原先使用onkeypress會再按下輸入前就trigger造成錯誤
後來改用onkeyup修正問題

特例：
在ios上面如果直接選擇suggestion words則不會trigger onkeyup
除非透過鍵盤輸入才會有效果

**Comment by wade89214** [comment]
測試過後好像還是一樣會有1跟2的問題

**Comment by cyen1121** [comment]
還沒上去到store......
