### ISSUE TITLE
[Widget][單一投票] 在編輯標籤中仍然可以新增重複項目

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#413]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : LG-H440Y Android 5.0.1

客戶[2]
使用平台 : PC 
瀏覽器 : IE

流程:
單一投票->店家端雖然在輸入選項中輸入重複的項目會跳出提示以重複，但店家端仍可在編輯標籤中輸入重複項目
![11111](https://cloud.githubusercontent.com/assets/13726130/9872367/8516c70c-5bcb-11e5-98dd-0d9844a371df.png)

**Comment by gameflierHao** [comment]
原因: 店家編輯資料，儲存時，無驗證項目內容是否重覆。
解法: 當按下儲存時，驗證所有選項內容，如有重覆，跳出警告訊息。

**Comment by chuangshaojung** [comment]
test OK
