### ISSUE TITLE
[Widget][單一投票、多選投票]重新整理後選項名稱被蓋掉

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#415]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : LG-H440Y Android 5.0.1

客戶[2]
使用平台 : PC 
瀏覽器 : IE

流程:
投票Widget中->店家輸入新增選項->客戶端也輸入新增選項->重新整理->店家輸入的新增選項被蓋掉了
![1](https://cloud.githubusercontent.com/assets/13726130/9878142/e177bfb0-5bf3-11e5-8e7c-ab5cc7782acd.png)
![2](https://cloud.githubusercontent.com/assets/13726130/9878151/e932aa76-5bf3-11e5-8203-0fc762205a57.png)
![3](https://cloud.githubusercontent.com/assets/13726130/9878155/ef6f9c50-5bf3-11e5-9fc9-c4e0f4b8f3d2.png)

**Comment by chuangshaojung** [comment]
圖(上)之選項三為店家新增，圖(中)之選項四為客戶新增，圖(下)為重新整理後，原選項三消失了

**Comment by gameflierHao** [comment]
原因: updateDate 沒有更新context
解法: 當updateDate時，檢查並更新context

**Comment by chuangshaojung** [comment]
test OK
