### ISSUE TITLE
購物車要從右上方一到左下方而且一旦有購物置入必須在左下方購物車增加號碼並顯示總金額

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#420]

**Comment by cyen1121** [comment]
這是指全版菜單嗎?

**Comment by cmacma7** [comment]
對全版菜單那個固定位置的購物車目前是在右上方浮起來其他人都是做在左下方

**Comment by cmacma7** [comment]
你也許可以參考一下外賣超人

**Comment by cyen1121** [comment]
底部需要設定padding:100px

**Comment by cyen1121** [comment]
http://bn.tagfans.com/public/jqm.html#page_join?o=281&id=864&viewType=station

參考開發測試
目前裡面有三個全版菜單
新增動畫加入購物車
並在購物車上顯示價錢與數量

**Comment by cmacma7** [comment]
Very good implementation!
