### ISSUE TITLE
[Notification] 由通知開啟App後，導向通知頁面後，無接續動作。

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#421]
1. (App是關起來的狀態) 
2. 由通知開啟App 
3. 導向通知頁面後，無接續動作。

PS:但是如果App是在背景開啟的狀態，通知喚起App後的動作是正確的。

**Comment by cmacma7** [comment]
Bug cause by async call to syncReceived() cause several this function been called before finish.
model_groupList render fail because the redraw=false been overwritten by the second syncReceived.
Solved by make calls after previous complete.

**Comment by cmacma7** [comment]
Fixed at store v1.1.821.4 and after
