### ISSUE TITLE
[widget] [外部資源->資訊介紹] 點選"更多資訊"按鈕後，Tagfans會跳回到商家的主頁面(外部資源->外部連結 這個widget不會)。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#425]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家 or 客戶[1] or 客戶[2] 點選"更多資訊"按鈕後，Tagfans會跳回到商家的主頁面。
    (外部資源->外部連結 這個widget的"更多資訊"按鈕不會)

**Comment by cyen1121** [comment]
fixed 由原先的a tag改成div

**Comment by wade89214** [comment]
測試後還是會跳回主頁

**Comment by cyen1121** [comment]
還沒上去到store......

**Comment by wade89214** [comment]
我錯惹QAQ
