### ISSUE TITLE
Print to printer using Chrome. This is for 印出報號機的號碼

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#427]
Use QZ Tray to print from browser to printer.
Requirement:
1. Need to dynamically load js in the client code. Use loadjscssfile();
2. Need to have basic setup: a. search and set printer with name, b. list all printers, c. use default printer
3. After select the printer from 2, the printer is remembered. The following printings will use the setting.
4. print text and QR Code to POS printer. Need to print Text ( time, number, etc...) and a QR code that point to number widget.  The function is  printToPos(title, message, QRCode_url);

example: loadjscssfile("cordova_ios/cordova.js","js");

function loadjscssfile(filename, filetype){
     if (filetype=="js"){ //if filename is a external JavaScript file
      var fileref=document.createElement('script');
      fileref.setAttribute("type","text/javascript");
      fileref.setAttribute("src", filename);
     }
     else if (filetype=="css"){ //if filename is an external CSS file
      var fileref=document.createElement("link");
      fileref.setAttribute("rel", "stylesheet");
      fileref.setAttribute("type", "text/css");
      fileref.setAttribute("href", filename);
     }
     if (typeof fileref!="undefined")
      document.getElementsByTagName("head")[0].appendChild(fileref);
}   

install driver for POS printer, for example: https://download.epson-biz.com/modules/pos/index.php?page=prod&pcat=3&pid=3495 for POS printer

**Comment by cmacma7** [comment]
To make print without preview and confirm, use
--disable-print-preview // still has confirm
or
--kiosk-printing             // preview popup will auto fade away after one or two second, this is what we want.
add the above option after the target field of property of  Chrome.

Remember stop the all the tasks of Chrome by task manager. Then start a new chrome with above option.

**Comment by cmacma7** [comment]
Please see https://qz.io/   , this is java applet to print to printer.

**Comment by gameflierHao** [comment]
finished
