### ISSUE TITLE
[widget] [外部資源->使用狀態即時顯示] 店家進入編輯內，按"建立新項目"後產生的'分類選項'以及'子項目'與原本有的功能不一樣。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#430]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家進入編輯頁面，按下"建立新項目"。
2. 此時所產生的 分類選項 功能 少了 "是否開啟" 功能。
3. 此時所產生的 項目 功能 多了 "物品圖片" 、 "項目價格" 、 "附加選項代號" 功能。

**Comment by cyen1121** [comment]
修正把多餘項目移除
