### ISSUE TITLE
[widget] [即時功能->即時顯示狀態列表] 店家進入編輯頁面後，少了可以"建立新項目"的紅色按鈕。 

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#431]
店家
使用平台 : PC 
瀏覽器 : Chrome

客戶[1]
使用平台 : iphone4 ios7.1.2

客戶[2]
使用平台 : PC 
瀏覽器 : IE

Bug
流程
1. 店家進入編輯頁面，找不到"建立新項目"的紅色按鈕。
   (除非點選左邊小圖示用複製的方法)

**Comment by cyen1121** [comment]
補其所需要的appendItems
