### ISSUE TITLE
Layout error in groupon widget. The order results format is not correct.

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#434]
http://store.tagfans.com/node/fb.html?noteId=28959_959_279

![bug1](https://cloud.githubusercontent.com/assets/10156054/10413843/8a2016ce-6fec-11e5-8473-e7f80960238f.png)

**Comment by cyen1121** [comment]
調整css樣式讓項目div依照文字長度自由展開高度避免資訊不完全或破版的現象產生
