### ISSUE TITLE
orderform 表單在Editor下編輯Template顯示錯誤

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#435]
(1)選擇團購Widget
(2)編輯團購message裡面的orderform
(3)新增一個text or text input 
(4)修改裡面內容，orderform其他所有項目的Template都會變成相同的值

**Comment by cmacma7** [comment]
It is caused by using parents to get the parent container. but parents return multiple items, which cause problem. change to use jquery closest and problem solved.

**Comment by cyen1121** [comment]
checked 1.1846.3
