### ISSUE TITLE
[Widget][Groupon] 選貨到付款，popup跳出來預設是面交

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#442]
widget 選貨到付款，popup跳出來預設是面交
應預設貨到付款

**Comment by cyen1121** [comment]
這兩部分不是有聯動的預設有錯誤

fixed

**Comment by peichingliao** [comment]
請問這則仍有一樣的問題，是因為舊的widget嗎？
http://store.tagfans.com/node/fb.html?noteId=29906_1488_360

**Comment by cyen1121** [comment]
先關閉，orderform的設定所以造成誤會，已經在預設都拿掉了
