### ISSUE TITLE
[Widget][留言] 打字只按一次enter就會輸入(MAC)

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#445]
我用mac，打到一半按enter（是選字的enter）就會直接輸入
應該要按兩下enter才是輸入

![2015-10-17 12 23 04](https://cloud.githubusercontent.com/assets/10726049/10547491/6e002f04-7467-11e5-9a23-8b6fe6e2df20.png)

**Comment by cmacma7** [comment]
This is the behavior of keyboard, the first enter should be catched by your IME input, if cannot catch by your IME input, then it will send to us....
If your enter give us a enter command, the only thing we can do is "enter", there seems nothing else we can do. Can you address what you expect us to do?

**Comment by cmacma7** [comment]
Fixed for all search bars, use keydown to replace keyup.
The IME is possible to return keyup with code 13 if user use enter to complete the IME. As the result, if we try to detect complete of input, we cannot use keyup 13, instead we need to detect keydown 13.

**Comment by cmacma7** [comment]
David also fixed the chat part of the widget.

**Comment by cyen1121** [comment]
fixed

onkeyup 判斷字串長度 和  enter UI button出現

onkeydown 則是判斷是否有按shift + enter or enter
