### ISSUE TITLE
[widget] [團購] 資料沒有自動帶入

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#446]
如果店主自己新增地址, 電話等欄位, 資料每次都得重新輸入, 需要在新增的時候, 讓店主設定是否為固定資訊, 以讓系統自動記住上次的輸入資訊 ,避免消費者每次都得重新打, 最好也能記住偏好, 例如都是宅配或是自取?

**Comment by cyen1121** [comment]
團購Widget沒辦法做到的地址電話等防呆，因為Orderform列表為自由表單，不會設計成特定對應哪個欄位的作法，避免造成設定更加複雜。

**Comment by ghyu65** [comment]
除了防呆之外, 是說有無辦法自動帶入上次輸入的資料?

**Comment by ghyu65** [comment]
自動帶入只能做在菜單那種舊的表單, 新的團購因為自由度高, 不知用戶怎麼設計所以無法一一對應, 先關閉此issue
