### ISSUE TITLE
顧客反應在平板橫屏狀況，由store 進入 page，page下方留有很大段空間

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#448]
1. 開啟tagfans app
2. 進入 銅盤嚴選韓式烤肉 - 顧客點餐 商店
3. 平板轉成橫屏
4. 進入顧客滿意度page
   下方留有大量橘色背景空白

直屏不會發生此問題，在page頁面內，轉橫屏也不會

**Comment by cmacma7** [comment]
Fixed at v1.1.833.5.
We try to change the height every one seconds, to fit the height of components.

**Comment by gameflierHao** [comment]
check ok
