### ISSUE TITLE
搜尋商店id的搜尋按鈕無作用

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#451]
id搜尋的搜尋鍵壞掉了 但按enter 會搜尋
請參考下圖
![screenshot_thu_oct_22_16](https://cloud.githubusercontent.com/assets/1106733/10668347/769c2ec8-790e-11e5-850d-368120d57f93.jpg)

**Comment by cmacma7** [comment]
Fixed by handle input.

**Comment by gameflierHao** [comment]
Checked
