### ISSUE TITLE
[統計總結] 建議提供“快速過濾”的下拉選單&提示目前過濾狀態

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#452]
1. 目前無法快速過濾出某狀態的訂單，ex. 交易完成
2. 不小心點到交易完成，不知道目前列表示顯示「交易完成」
   （提示目前過濾狀態目前已有提供，位置請調整，不要跟著x軸滑動）

**Comment by cyen1121** [comment]
新版的統計列表除了保留之前的過濾方式以外，也能直接透過下拉選單選擇需要的狀態來過濾，並也可以直接用關鍵字作搜尋。
