### ISSUE TITLE
[頁面] ios9.1 進入頁面時會有 widget 重覆出現的問題

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#459]
可參考以下商店
http://store.tagfans.com/#page_station?o=264
餐點介紹->外帶取餐

**Comment by cmacma7** [comment]
Need to migrate to WKWebview, the UIWebview in iOS9.X has bug on window.location features. window.location.href and window.location.hash become async in iOS 9.x, which cause set the href and hash then read back will be the old value.

Action, wait for WKWebview ready.

**Comment by cmacma7** [comment]
Fixed by hack 100ms delay in pageshow. It is trigger by window.location.href and window.location.hash is async in IOS9.
v1.1.846

**Comment by gameflierHao** [comment]
IOS9.0看起來正常
周一再用IOS9.1測一次

**Comment by gameflierHao** [comment]
ios9.1 fixed
