### ISSUE TITLE
[頁面] ios9.1 無法進入圖片編輯器

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#460]
一但點取圖片編輯器 就被導回首頁

**Comment by cmacma7** [comment]
Need to migrate to WKWebview, the UIWebview in iOS9.X has bug on window.location features. window.location.href and window.location.hash become async in iOS 9.x, which cause set the href and hash then read back will be the old value.

Action, wait for WKWebview ready.

**Comment by cmacma7** [comment]
Fixed by hack 100ms delay in pageshow. It is trigger by window.location.href and window.location.hash is async in IOS9.
v1.1.846

**Comment by gameflierHao** [comment]
IOS9.0看起來正常
周一再用IOS9.1測一次
