### ISSUE TITLE
是否會員加入我們系統, 有個資法保護, 我們要聲明絕對不會販售或提供給公司外的第三者使用, 可能我們要有一個第一次登入系統時的聲明公

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#466]

**Comment by gameflierHao** [comment]
會員須知可參考
https://docs.google.com/document/d/1IPkEcn4q86S4QdM8zHovgfU_2fLCBfRfaIE1uK5l65A/edit
在點擊任一登入時跳出
