### ISSUE TITLE
[行政] 業務獎金所得

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#475]
如果有業務協助成功媒合廠家簽約, 提供一定比例的傭金一年, 這個支付要列入公司薪資支出, 需要開立薪資所得等, 需要有人負責~
每個月提撥多少金額給業務同仁, 也要有人負責~

**Comment by ghyu65** [comment]
可能也需要合約, 需要找人負責草擬~

**Comment by dominic820** [comment]
合約已經有了
