### ISSUE TITLE
[widget] [即時功能->即時顯示狀態列表] 店家進入編輯頁面，點選"建立新項目"後，所產生出的標題皆無法編輯(都無動作)。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#483]
店家
使用平台 : PC 
瀏覽器 : Chrome

Bug
流程
1. 店家 進入編輯頁面，點選"建立新項目"後，所產生出的標題無法編輯(都無動作)。
![default](https://cloud.githubusercontent.com/assets/13726076/11124555/96532bb6-89a0-11e5-9daa-464c5a1df3e1.png)

**Comment by gameflierHao** [comment]
已修復context
請重新新增試看看
