### ISSUE TITLE
[widget] [下單預約服務->全版菜單] option在某些情況下店家無法按"售完"。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#486]
店家
使用平台 : PC 
瀏覽器 : Chrome

Bug
流程
1. 假設附加項目1有2項、附加項目2有3項、附加項目3有4項。
2. 然後某一個菜品的附加項目編輯為 "1,3" 。
3. 則店家 點選此菜品後，想按附加項目3的第4項的"售完"時，會發生error。
(原因 : 貌似 unavailableItems fuction下的 index 只抓到當前菜品的項目順序，即附加項目3其實對應到的是附加項目2，但是附加項目2只有3項，所以發生錯誤)

**Comment by cyen1121** [comment]
已修正bn store
