### ISSUE TITLE
SendMail 需要有選項能夠不發送推播

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#498]
需求:
如題

事由:
顧客滿意度調查表不需要每次收到就發推播
只有不滿意的情況才要發

**Comment by cmacma7** [comment]
function mailOrShare_note(noteId, users, srcId, category, textMessage, storeId, stationId, data, noPushNotification) .
The last parameter set to true, then no push will happen.

**Comment by cmacma7** [comment]
On BN only, need to test on store.
