### ISSUE TITLE
[system] [背景顏色] 設定背景顏色後，按重新整理，此時頁面背景顏色會消失，除非重新再進入頁面。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#502]
店家 or 客戶
使用平台 : PC 
瀏覽器 : Chrome

Bug
流程
1. 進入頁面選擇要設定的背景顏色。
2. 然後按重新整理F5。
3. 則此時頁面背景顏色會消失，除非重新再進入頁面。

**Comment by cmacma7** [comment]
stationInfo.meta is null....
