### ISSUE TITLE
[Widget]特約店家列表 搜尋功能無法搜尋

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#503]
店家 / 客戶
使用平台 : PC 
瀏覽器 : Chrome

流程:
新增店家之後，在搜尋欄位搜尋剛剛新增的店家，無法搜尋到
![1](https://cloud.githubusercontent.com/assets/13726130/11581271/18b6a890-9a7b-11e5-8689-14c5ee9afcd4.png)
![2](https://cloud.githubusercontent.com/assets/13726130/11581273/1d1f2416-9a7b-11e5-8eab-d71745740387.png)

**Comment by cmacma7** [comment]
Hi Wade, please help to take over this widget's bug and new features.
