### ISSUE TITLE
[widget][Feature] [全店購物車] 整併商店內的所有購物widget形成單一購物車

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#513]
需要整併商店內的所有購物widget形成單一購物車
目前分兩部分要修改
1. 
Widget部分需要將購物資要存到某個位置
並提供Function 讓 Platform去Call
2. 
Platform 部分要去將購物車Layout與邏輯加入頁面

**Comment by cyen1121** [comment]
已經完成建置，有請Wade做後續測試回報。
