### ISSUE TITLE
訂單限制改為軟性限制, 筆免商家遺漏訂單

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#521]
把訂單改成軟性限制就是訂單額度可以變成負值，然後根據負值多少來決定下個月要多收多少錢。

**Comment by ghyu65** [comment]
其他參考建議: 
1. 暫時性的遮蔽 等付完款再恢復
2. 上次說要採用浮動計價, 就是看上個月用多少, 自動收費, 不擋筆數
3. 不管多少都不擋, 或是郵件通知對方已經超過進到下一個 level 之類, 或是延遲一天或兩天才生效? 至少有時間可以馬上聯繫店家確認是否要跳一個 level
4. 串了歐付寶之類的立即支付，成功系統就自動解除限制

**Comment by cmacma7** [comment]
On Version v1.1.875, the quota will become negative value.  Will not block user to continue send message, but negative value means store owner need to pay at next month's bill.
