### ISSUE TITLE
[Widget][Groupon] 運送選項無法點文字選取

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#532]
請試試看此HTML
<input type="radio" name="shipping" id="input_shipping" value="60" ship="7-11或是全家">
<label for="input_shipping" >7-11或是全家</label>

**Comment by peichingliao** [comment]
gihub無法貼語法，請搜尋line對話記錄 ^^""

**Comment by cyen1121** [comment]
修正，透過相同index id去對radio btn做點擊動作
