### ISSUE TITLE
orderform自由表單需要能夠可以設定哪些必填，如果沒有參數則都是必填

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#537]
此功能加入後，需要將原先必填的檢查移除(通知David做移除！！！)

**Comment by cmacma7** [comment]
popupForm callback will be checked by system, if callback returns false, then popup will not close.
It is the popupFrom to decide which parameters are necessary. Inside callback, the code should popup necessary information to tell the user which fields are necessary, then return false.
v1.1.882.1 has this feature, please use BN to test.

**Comment by cyen1121** [comment]
以補上如果有空白欄位 則會return false
