### ISSUE TITLE
[Title] 目前網站顯示都沒有 title 配合商店資訊 

### ISSUE THREAD

**Issue by ghyu65** [cmacma7/bn#539]
主要是如果有用戶使用 bookmark, 目前不同商店的 browser title 顯示都會是 "主頁", 會導致加入我的最愛時, 會覆蓋或是 user 需要再特地去改 bookmark name. 比較麻煩, 另外如果有 title, 應該就能讓 google search 到.

**Comment by cmacma7** [comment]
Forget to set title meta in bn.js

**Comment by cmacma7** [comment]
Add title and descriptiions inside <body> tag.

**Comment by cmacma7** [comment]
Add title and description in <body> and <title> tags.
