### ISSUE TITLE
delete the station from station list, but the station is still in the store(cache?)

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#54]

**Comment by cmacma7** [comment]
Delete leaves suppose not to effect the root. Owner need to delete leaves manually

**Comment by cyen1121** [comment]
cannot find the station from store's station list 
(1)create new station into store
(2)delete the station from tagfans my station list
(3)go to the store
(4)the station is still in the store
(5)go edit store
(6)cannot find the station, so there is no way to delete the station

**Comment by cmacma7** [comment]
It is because of the device cache the group info.
Solution, when delete a station, need to find the groups that use this station then tell the server to flush these stations.

**Comment by cmacma7** [comment]
Fixed in SVN 599. Use Sql trigger to update the group lastUpdate number.
