### ISSUE TITLE
希望下方"我的頁面" 能關掉

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#541]
上方也可以點進去編輯，下方也可以點進去編輯。
希望下方"我的頁面" 能關掉。

![temp2](https://cloud.githubusercontent.com/assets/16083361/11950107/5c07f15a-a8c0-11e5-966b-1b269c2b12f1.JPG)

**Comment by cmacma7** [comment]
Corrent at BN, will be release on v1.1.883 and after.
