### ISSUE TITLE
[widget][todo] 要能篩選出 "老闆取消交易" 以及 "惡意取消"

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#544]
目的是統計出黑名單
也可以讓單據總量正確

![temp4](https://cloud.githubusercontent.com/assets/16083361/11950341/8808962c-a8c2-11e5-8461-42581d429f24.JPG)

**Comment by cyen1121** [comment]
已經可以在統計頁面做出過濾，但數量與金額都會設定成0避免造成統計錯誤，如果狀態被改成別的則價錢和數量也會恢復。
