### ISSUE TITLE
iphone Safari 無痕模式 無法進入Tagfans

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#548]
如題
iphone Safari 無痕模式 無法進入Tagfans
(無痕模式無法使用cookie?與localStorage?)

此外 測試chrome的無痕模式
卻是可以進入 並且正常使用的

**Comment by cmacma7** [comment]
Fixed at v1.1.882. 
Caused by localStorage and web sql not supported inside private browsing mode of Safari.
