### ISSUE TITLE
[System] 抓取facebook姓名與實際在facebook上看到的不相同

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#553]

**Comment by cmacma7** [comment]
Please explain what you mean 與實際在facebook上看到的不相同. Can you give an example?

**Comment by cyen1121** [comment]
我們系統顯示的名字 子薰曾
但實際在facebook看到的顯示卻不是這名字
https://www.facebook.com/profile.php?id=100000335952241

**Comment by cmacma7** [comment]
別名是子薰曾
