### ISSUE TITLE
[widget] ID:1096 使用的這一個模板 手機版/PC版 圖型裁切比例不一致 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#554]
(手機版的裁切正確)
![image](https://cloud.githubusercontent.com/assets/16083361/12106842/8a7f89b0-b39e-11e5-9bfb-96a33a7a5b31.png)

**Comment by cyen1121** [comment]
已經修正

**Comment by cyen1121** [comment]
依照圖片大小來顯示，如果螢幕太大則是兩邊留白，螢幕小的情況才會是滿版的狀態，避免圖形被拉的太過瘦長。
