### ISSUE TITLE
[widget][進階團購]商品單價為空或是選項金額為空時 導致訂單金額錯誤

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#556]
![screenshot_tue_jan_05_13 31 21](https://cloud.githubusercontent.com/assets/1106733/12108267/b2fbf470-b3b0-11e5-9c44-6455b60ded7c.png)

**Comment by cyen1121** [comment]
修正！如果價錢不填寫將自動以0元作計算

**Comment by gameflierHao** [comment]
現在如果沒填寫金額 會跳出 警告訊息
讓使用者進行確認
