### ISSUE TITLE
[widget][ui][新增Widget] Popup位置不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#559]
1. 先砍掉tagfans app process
2. 開啟tagfans app，立刻進入商店，進到空白的商品頁
3. 按右上角 +
4. 就會看到popup位置不正確
   iPhone 6s plus, app

![s__2277488](https://cloud.githubusercontent.com/assets/10726049/12118986/eb758124-b403-11e5-9fb7-165a36377067.jpg)

**Comment by cmacma7** [comment]
Only has problem for the first time popup, the second time is fine
