### ISSUE TITLE
[widget] 購物widget 點小圖看大圖 反應不正確

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#572]
![a](https://cloud.githubusercontent.com/assets/16083361/13098901/f924034c-d567-11e5-8603-fa79c7550caf.png)
![b](https://cloud.githubusercontent.com/assets/16083361/13098903/fa7ddc2c-d567-11e5-8ce5-60003af789af.PNG)

大家可以試一下:
http://store.tagfans.com/#page_join?o=1419&id=10344&viewType=station&srcNoteId=133823

**Comment by gameflierHao** [comment]
這種有顯示小圖的都有這個狀況
進階團購  
集單式團購
快速揪團
商品介紹
資訊介紹 

會一併修正

**Comment by gameflierHao** [comment]
all fixed in  bn

**Comment by dominic820** [comment]
Hi Howard, 我可以在哪裡看一下測試結果嗎?
(bn裡面沒有這個widget)
