### ISSUE TITLE
[Widget] 全版菜單在電腦觀看有bug

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#591]
http://store.tagfans.com/#page_join?o=370&id=9502&viewType=station
1. 使用電腦(windows, chrome)觀看時，widget的選擇icon(<)位置不正確, 如圖1
2. 一樣使用windows,chrome, 編輯頁面資料->新tag出現在上方, 儲存後畫面異常, 如圖2
   ![capture image8](https://cloud.githubusercontent.com/assets/10726049/13481765/4eae3870-e123-11e5-8842-8fdb597f3290.png)
   ![capture image6](https://cloud.githubusercontent.com/assets/10726049/13481767/52cf1406-e123-11e5-91d2-82ab49be12d6.png)

**Comment by gameflierHao** [comment]
操作列的設定屬於系統範圍
應該說全版畫面的widget都有這種狀況
