### ISSUE TITLE
訂單狀態的global setting

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#593]
訂單狀態的global setting
1. 縮小訂單記憶體容量、賣家每一筆訂單可以去參考global setting
2. 萬一少加了一個狀態，未來改這個global setting就好，不必每一張訂單都改了

**Comment by dominic820** [comment]
將來使用進階團購(非購物車)的widget 設定都統一在這一個地方(global)
不針對每一個widget去設定

**Comment by cmacma7** [comment]
Change the groupbuy widget to support add to shopping cart or not option, so that owner of the store can use single shopping cart to handle all options.

**Comment by cmacma7** [comment]
But we need to support limit time and limit count widgets also support shopping cart feature.

**Comment by dominic820** [comment]
已經在另一個issue中 追蹤
