### ISSUE TITLE
.訂單上面，要帶出商店名稱 與 商品名稱

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#595]

**Comment by cmacma7** [comment]
Already has 商店名稱.  The title of the order get from original product title, as the result, it is the original product need to have correct title and description. 
At the group buy widget, the merchant in general has a very long description, so it is not a good idea to have description into the order. The order can have store name, and product name already listed in the item list.

**Comment by cmacma7** [comment]
Hi David, can you put product title in order.

**Comment by cyen1121** [comment]
透過getStoreInfo(context, function(data){}) 取的店家名稱，當客人看到會知道訂單來自的店家名稱

**Comment by dominic820** [comment]
ok
