### ISSUE TITLE
訂價規則

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#60]
1，每一用戶可免費建立一個不被認證的商店
2，商店認證 月費2000

**Comment by cyen1121** [comment]
1. 10個免費的 Widgets
2. 其餘的Widgets 有個別的價錢
3. 商店建立時顯示一次性的總價
4. 開放預覽所有可以使用的Widgets

**Comment by cmacma7** [comment]
開放所有可以使用的Widgets,只可以讓製作者的帳號看到. 只有在付費後才能讓更多人看到.
