### ISSUE TITLE
 Widget隱藏 不要用淡出效果，改用斜向banner 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#600]
![image](https://cloud.githubusercontent.com/assets/16083361/13489923/9afdfd6e-e164-11e5-9b68-d4f89bc4c3cc.png)

**Comment by cmacma7** [comment]
In this small widget is reasonable, but for big widget, this is not a good solution.... I can reduce the opacity instead of using the banner.

**Comment by dominic820** [comment]
Ok! 
Reducing opacity will do.
I will inquire with "揪愛買" when it is ready later.

**Comment by cmacma7** [comment]
Enhance opacity to 4 times the original one. Fixed in SVN 930.
