### ISSUE TITLE
VIP價格 (依VIP身分 可以看到對應VIP等級 的價格)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#602]
比方說
一般身分 : 看到市價100元
VIP1 :可以看到市價100元 與VIP1 的90元
VIP2 : 可以看到VIP1看得的之外， VIP2可以看到80元

結帳會帶到最優惠價格

**Comment by cmacma7** [comment]
getUserVip()   can get the VIP number, for example 4.

**Comment by cmacma7** [comment]
Hi David. In your widget, you can provide multiple price, and each price has a vip field. 
If a price has a vip, then only getUserVip()   == your vip, then the price will show up. otherwise the price will show the price does not have vip.

**Comment by cmacma7** [comment]
Fix in SVN 928

**Comment by cyen1121** [comment]
目前在bn實作可以對每個項目做vip價錢1-10的設定

**Comment by cyen1121** [comment]
已經實作完成

**Comment by dominic820** [comment]
done
