### ISSUE TITLE
團購widget，按分享到Facebook 第一次執行，圖片不會出來 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#603]
要關掉重來一次 圖片才會出來

![image](https://cloud.githubusercontent.com/assets/16083361/13562371/eb62bb6c-e472-11e5-810a-c90797571747.png)

![image](https://cloud.githubusercontent.com/assets/16083361/13562377/0d33afda-e473-11e5-8026-eb8f8db62833.png)

**Comment by cmacma7** [comment]
right after your sharing, facebook haven't fetch the image url yet. It will be a delay. Can you make sure this only happen when you publish then see the share right away, comparing with after you share, wait some time then see the result.

**Comment by dominic820** [comment]
yes, indeed.
the picture can still go onto Facebook 社團 correctly.

There's no impact based on the above conclusion.
