### ISSUE TITLE
複製widget / 貼上widget 行為有錯誤

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#604]
請見圖片編號，
1) 頁面內，先有widget A
2) 複製了A，貼上複製的widget，修改完之後按建立，會得到B (到這裡為止都沒問題)
3) 這個時候，不按複製，又按一次貼上，應該要得到widget A，但是跳出來的是 "B" widget !!

![image](https://cloud.githubusercontent.com/assets/16083361/13562556/f2db9a24-e474-11e5-8b0a-bccec24181da.png)

**Comment by cmacma7** [comment]
Is this is good behavior?

**Comment by dominic820** [comment]
No, but in Windows, it's common, right?
Copy "once" and paste "two times" or "three times"....

**Comment by cmacma7** [comment]
Fixed by duplicate the widget before paste to editor. SVN 927

**Comment by dominic820** [comment]
finished
