### ISSUE TITLE
在手機上使用"統計總結" 之後，點選最左邊"訂單號碼"，沒辦法點出單一 這張訂單

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#605]
(改用PC操作可以)

手機會跳出空白畫面，按"取消"，畫面會跳到一個奇怪的地方，再按"上一頁"的箭頭，就跳回我的訂單裡面去了。

![img_6493](https://cloud.githubusercontent.com/assets/16083361/13563629/43e5d8ea-e47e-11e5-88a3-12746be7320b.PNG)

![img_6494](https://cloud.githubusercontent.com/assets/16083361/13563632/4b89bd50-e47e-11e5-9a14-14c6e896d47c.PNG)

![img_6495](https://cloud.githubusercontent.com/assets/16083361/13563634/5133a2c0-e47e-11e5-810e-1ea988798a64.PNG)

![img_6496](https://cloud.githubusercontent.com/assets/16083361/13563638/54832f40-e47e-11e5-9bc2-6e8b72bf5004.PNG)

**Comment by cyen1121** [comment]
幫忙先查詢開啟Dialog後的行為是不是因為不同就造成有誤了
