### ISSUE TITLE
一個店，併存兩個管理帳號 的必要性

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#606]
如果其中一個帳號，被駭客偷走了，

店主勢必會通知我們(Tagfans)擋住駭客 不要被登入了，尤其是facebook帳號
現在很容易被盜。

但商店還是需要管理，沒有第二個帳號，商店停擺的風險很高。

**Comment by cmacma7** [comment]
We can manually change the user from facebook login to email login. Or they can give us another FB account so that we can change for them.
But this must be done by Tagfans. We do not allow user to change account by themselves. If they can change, it is more risky.

**Comment by cmacma7** [comment]
1. We can change by store owner provide his user ID (tagfans ID), email address, and we will generate a password for them.
2. We can change by store owner provide his FB name , and fb id. So that the store will be admin by another FB user account.

**Comment by dominic820** [comment]
ok, so am I right?
1. a store can accept "dual account" through Tagfans team's special help
2. "dual account" means these two account have the same controlability on a single store
