### ISSUE TITLE
需要中英日三種語言界面widget

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#609]
系統介面(store,page)
widget
都需要有三種語言

需要跟著系統的語言設定，呈現不同語言page

**Comment by cmacma7** [comment]
Feature added. SVN #929
Multiple language support has add to BN. Please try to enter the page you want to support multiple language, click the + button at top-right.  select edit page information, then check multiple language support.
How you click + again, you will see the language selection button.
Each language, you can add widgets, and these widgets will only show when the language is selected or your system is set to that widget. If you prepare 3 different languages, but un-check the multiple language checkbox, then all the iwdgets of all languages will show up.

**Comment by cmacma7** [comment]
translate_ja-jp added to translate system language.

**Comment by peichingliao** [comment]
Hi cma,
頁面設定，標題的部分，需要支援 {"en-us":"Store", "ja-jp":"ページ", "zh-tw":"頁面"} 之類的特殊語法

**Comment by peichingliao** [comment]
2016/04/20 已經支援
