### ISSUE TITLE
Back Button issue(cannot go back to Tagfans)

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#61]
Browser: iOS --> Chrome and Safari

**Comment by cmacma7** [comment]
Chrome on iOS only? Right?

**Comment by cyen1121** [comment]
YES only this one, both 7.1.2 and 8.1.1

**Comment by cmacma7** [comment]
It is caused by history.back() not working when appCache is enabled (manifest is enabled). It is a known bug of Safari 7. The only solution is to disable appCache.
Solution suppose to be detect mobile safari version, then disable apache

**Comment by cmacma7** [comment]
confirmed to be iOS 7 problem. Upgrade to iOS 8.1.3 and problem disappeared.
