### ISSUE TITLE
Tagfans回條 需要多一個種類 (超連結)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#610]
用在超商宅配時，會需要填入店號。
這時就需要查詢。

![image](https://cloud.githubusercontent.com/assets/16083361/13597254/78f067f6-e552-11e5-9530-3b414c3eba34.png)

**Comment by cmacma7** [comment]
Suppose add one more field, right?

**Comment by cyen1121** [comment]
ＹＥＳ多一個可以加超連結的
