### ISSUE TITLE
限量的狀態訊息設定 底色不見了(要加回來)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#613]
不正常
![image](https://cloud.githubusercontent.com/assets/16083361/13642698/7e18a9d0-e658-11e5-856e-e539d0926da4.png)

正常
![image](https://cloud.githubusercontent.com/assets/16083361/13642678/69b4d45a-e658-11e5-9915-a381f1816d97.png)

**Comment by cyen1121** [comment]
已經調整context
