### ISSUE TITLE
[Store] 直接在商店加入可開啟外部APP的icon

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#614]
目前開啟外部app都必須在page建立widget
希望可直接在商店首頁找到icon開啟APP

**Comment by cmacma7** [comment]
We already have this feature. Howard has the direct link widget that when enter a page, the first widget of the page will jump to the app directly.
Howard, can you tell PeiChing how to achieve...

**Comment by gameflierHao** [comment]
新增WIDGET -> 外部資源 -> 自動跳轉 用法和排行榜列表一樣
開啟連結 選 外部連結
連結ID 填入 android app id

**Comment by peichingliao** [comment]
非owner才能看到效果
