### ISSUE TITLE
進階團購 下面項目 也有提示 可以上傳圖("物品圖片") 但圖上傳後 不會顯示

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#620]
進階團購 下面項目 也有提示 可以上傳圖("物品圖片") 但圖上傳後 不會顯示

![image](https://cloud.githubusercontent.com/assets/16083361/13660224/dba451b6-e6c2-11e5-9d2d-f4e8cd1abf74.png)

**Comment by cyen1121** [comment]
已經移除了

**Comment by dominic820** [comment]
checked!
