### ISSUE TITLE
統計頁面提供簡易總計並可以快速複製的功能

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#627]
讓團主方便複製貼文給客人知道總共該付的費用，和簡易的物品與訂單細節，最後列出該付的總金額

**Comment by cyen1121** [comment]
bn已經建置完成
在總表下面多加一個textarea來提供快速簡易的統計總結
產生的方式只要總表有變動就會同步更新，目前也不隱藏因為置在下方不會直接造成占畫面所以直接顯示方便做使用。

**Comment by dominic820** [comment]
想問一下，小視窗，能否加個複製鈕? (手機複製，不像電腦複製這麼容易)
對手機型團媽，會很有幫助!

![image](https://cloud.githubusercontent.com/assets/16083361/13723963/18c7339e-e8b0-11e5-8378-6ace37350555.png)

**Comment by cyen1121** [comment]
看起來每個瀏覽器都因為有安全性考量會避免使用這個，所以都需要外掛去做，所以目前暫時不考慮加這功能

**Comment by dominic820** [comment]
ok
