### ISSUE TITLE
[widget] 集單型團購在購物車裡調整購買數量，其數量與購物總數不同

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#632]
測試平台: PC、LG-H440Y Android 5.0.1

流程: 
1. 集單型團購選購-->在購物車裡調整購物數量-->購物總數計算錯誤

![2016-03-13 14 28 00](https://cloud.githubusercontent.com/assets/13726130/13727371/054961fa-e92a-11e5-8ef2-cab81ae2966c.png)
1. 我的訂單中-->各項金額總和與總價不符

![2016-03-13 14 39 53](https://cloud.githubusercontent.com/assets/13726130/13727374/14cea2de-e92a-11e5-9e5e-6c3c024477e3.png)

**Comment by cyen1121** [comment]
ＢＮ目前已經修正，當物品從商品加入時是累加的，但是在購物車裡面改變是取代原本的數量，兩種不同的方式。

**Comment by cyen1121** [comment]
上到store

**Comment by chuangshaojung** [comment]
test OK
