### ISSUE TITLE
[widget] 集單型團購編輯頁面下的訂購後附加資訊填寫後，並未出現在訂單上

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#633]
測試平台: PC、LG-H440Y Android 5.0.1

流程:

集單型團購編輯頁面-->在"訂購後附加資訊"輸入文字-->訂購後在我的訂單中，訂單並未出現原本在"訂購後附加資訊"中所輸入的文字

例如:輸入Hello world
![2016-03-13 14 50 11](https://cloud.githubusercontent.com/assets/13726130/13727415/fb15e62a-e92b-11e5-863c-28a86fe467bc.png)

訂購後在訂單中並未出現剛剛在"訂購後附加資訊"所輸入的Hello world
![2016-03-13 14 50 30](https://cloud.githubusercontent.com/assets/13726130/13727416/feb30e20-e92b-11e5-850b-952dc716bdc0.png)

**Comment by cyen1121** [comment]
store站的團購購物車類型已移除不必要的訂購後資訊欄位

**Comment by chuangshaojung** [comment]
Confirm Removed
