### ISSUE TITLE
未登入的警告視窗，敘述需要更正:

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#634]
敘述需要更正:

請按確定鍵，但沒有確定鍵。
應該是要按"好" 這個鍵喔。

![image](https://cloud.githubusercontent.com/assets/16083361/13729752/73e6a3aa-e977-11e5-9c1a-057af71b9ca4.png)

**Comment by cmacma7** [comment]
This depends on the OS, the wording is depends on OS version to show whatever they want :)
