### ISSUE TITLE
[Widget] 直接開啟集單型團購widget，購物車icon與立即購買按了沒反應

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#635]
即使是登入狀態
直接開啟widget
ex.  http://store.tagfans.com/index.html?noteId=172265&_stationId=897&_storeId=296#page_join

加了商品進購物車後
右上的購物車按鈕&立即購買，按了都沒有反應

**Comment by cyen1121** [comment]
確認沒辦法正確加入到此商店的購物車裡
按 加入購物車 顯示加入成功，右上方的購物車顯示數字與實際商店的購物車數字不同

**Comment by cmacma7** [comment]
Fixed at version 959. It is caused by not handling store ID at shopping cart functions.

**Comment by peichingliao** [comment]
已修正
