### ISSUE TITLE
揪團 issues.  Need to enhance the UI

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#641]
1. Change the owner options from 4 items to 3 items. And when item been selected, need to add a check box.
2. Final Order form need to move from bottom to top of the widget.
3. In summary page, excel style tables. take out the "descript", "count", "price" row for customer tables. But still have this row for total table.

**Comment by cyen1121** [comment]
bn上面修正了
統一在狀態前面加上checkbox (class = status_box)
在showStatus裡面統一將全部checkbox取消只對選擇的做checked
然後checkbox只有當isOwner == true時才會出現。

你的購買清單移動至商品敘述下方，狀態的上方。

背後的excel表單除了全部商品保留標頭的敘述，其他都移除。

**Comment by cmacma7** [comment]
Fixed in BN.
