### ISSUE TITLE
對未登入的帳號，提醒使用者，目前處在未登入狀態

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#642]
1) 對未登入的帳號，提醒使用者，目前處在未登入狀態
2) 讓店家選擇，要不要對未登入的帳號，出現提醒 (建議預設是"要")

![image](https://cloud.githubusercontent.com/assets/16083361/13767776/53b9658a-eaa9-11e5-9ed1-add39565c25c.png)

**Comment by cmacma7** [comment]
Button added, version 941

**Comment by dominic820** [comment]
已經有跳出"這家店有密碼保護"
