### ISSUE TITLE
對購買行為 預先警告"未登入"

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#643]
現在是"選完數量之後" 按送出，才跳出警告"未登入"
要修改成，選數量的瞬間，就跳出警告!

![image](https://cloud.githubusercontent.com/assets/16083361/13767838/15b85538-eaaa-11e5-8ab6-c3201f16cc2d.png)

**Comment by cyen1121** [comment]
牽涉到的Widget為下列
OrderMultipleItemsWidget_groupbuy
one_item_group_buy
OrderMultipleItemsWidget_globalgroupbuy
one_item_group_buy_limit
OrderMultipleItemsWidget_groupbuy_time

在數量改變或是選擇運費的時候都會檢查是不是需要換成FB登入，如果需要就會將所有選擇的商品數量都歸零，並且詢問使用者是否要登入FB。

**Comment by cyen1121** [comment]
放上Store

## 改動的widget

一般團購
限時團購
限量團購
團購（購物車）
單品一般團購（已經不再可以新增的Ｗidget項目內，但有些店家還有使用到）
