### ISSUE TITLE
[改版需求] 3. 我的(My Account)

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#649]
a. 上方的會員資料顯示
- 頭像
- 顯示名稱
- 評價
- 右方設定 - 點擊進入現有設定畫面

b. 我的消費紀錄
- 點擊查看全部 - 換頁顯示
  c.  退款查詢、預約訂位、報名註冊 ... 等
- 點擊換頁顯示
  d. 我的銷售紀錄
- 點擊查看全部 - 換頁顯示
  e. 進帳查詢、預約訂位、報名註冊 ... 等
- 點擊換頁顯示
  ![3](https://cloud.githubusercontent.com/assets/10726049/13800668/47aa805e-eb66-11e5-8de1-204d26c89f68.png)

**Comment by cmacma7** [comment]
I will expose the module to let Peiching to write the module
