### ISSUE TITLE
商店主頁底下有空白

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#65]

**Comment by peichingliao** [comment]
![screenshots_2015-01-27-23-46-24](https://cloud.githubusercontent.com/assets/10726049/5940307/1a5c7212-a745-11e4-9288-a585901f325b.png)

**Comment by cmacma7** [comment]
Need to allow store owner to assign background color. Best way is using widget config to set config, which allow background 2 colors and foreground 2 colors.

**Comment by cmacma7** [comment]
duplicate of #58

**Comment by cmacma7** [comment]
Close because of duplicate for #58
