### ISSUE TITLE
網路不穩定時，不可以讓客戶新增商品widget(以進階團購為例)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#652]
網路不穩定時，不允許讓客戶新增商品widget(以進階團購為例)

故障現象:
客戶新增一個"進階團購"widget，在網路不穩定時，會帶出前一個widget的最終狀態(而不是一個全新的widget)  且依然可以編輯，文字照片都可以換掉。 但一旦按下鍵立，所有個圖片、文字都會失效，而是建立出"前一個widget的最終狀態"

客戶會完全錯亂! 不曉得為什麼新增widget會失效。
所以不可以再讓客戶 進入這樣的狀態了，必須完全清除前一個狀態!

**Comment by cmacma7** [comment]
To reproduce, choose to add a widget, then choose the same widget from templates and add again, you will find we use the last widget as the entry point of the new widget.

**Comment by cmacma7** [comment]
We guess it is caused by we use the instance of widgetSelect widgets instead of clone one. Which cause the following widget created will use the old ones. Fixed at version 952
