### ISSUE TITLE
限量widget 能夠新增多個項目 (目前是1個)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#654]
若單一項 已達上限，則該項不可再下單
但其他項目，需要依然可以下單。

**Comment by wade89214** [comment]
1. 每個品項都加入一個"開啟限量"功能，可選擇開啟or關閉。
2. 限量功能開啟後，需要填寫"限量數目"才能夠建置(如未填寫or填寫不是數字會跳出視窗，並不給建置)。
3. 限量功能開啟後，開啟品項之品名下方會有剩餘數量(若為店家則會再多一個重置按鈕)。
4. 由於是使用hashcode做編碼，所以要求各品名不得重複(重複會跳出視窗，並不給建置)。
5. 進入頁面後會有個setInterval，每秒更新一次各品項的限量數目，若品項剩餘數量為0，則該品項會顯示"售完"，並使用者如果有該品項在購物車，將自動從購物車中刪除。
6. 若品項剩餘數量為0 或 品項更改限量數目，店家可按品名下方的"重置"按鈕，達到初始狀態(一個品項一個)。
7. 若夠買品項超出能購買的數目，則不給購買，並自動從購物車刪除(利用 getObject 去偵測)。
8. 若已到填寫資料階段，不過卻超出能購買的數目(表示有其他人也在購買此項)，則不給購買(利用 incObject 跟 getObject 去搭配，並且加回購買數量)。

測試 Widget : http://bn.tagfans.com/node/fb.html?noteId=9764_948_294

**Comment by cmacma8** [comment]
Hi
Wede，關於每秒更新一次數量請問你指的是到伺服器去拿數量嗎？那這樣子伺服器會太忙的。應該是說在購買下單的時候，才去檢查數量，看是不是已經賣完了，如果賣完了要提醒顧客已經賣完請他重新下訂單。如果你想更新售完應該每三十秒一次就可以了。

wade89214 notifications@github.com 於 2016年3月29日 星期二寫道：

**Comment by wade89214** [comment]
好的，那我再修改一下。

**Comment by wade89214** [comment]
已更改為30秒更新一次，並且在購買下單、重置時，才去檢查數量。

**Comment by dominic820** [comment]
ok
