### ISSUE TITLE
進入統計總結 點選單一一張訂單 暫缺的標記 會失效

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#656]
進入過統計總結，再把單一一張訂單，點出來
這時候 暫缺的標記 會失效
(金額有扣，綠色的暫缺 沒有跳出來)

![image](https://cloud.githubusercontent.com/assets/16083361/13853514/fffaee14-eca1-11e5-9b8f-cf57385ee56f.png)

**Comment by cyen1121** [comment]
已修正
如果點checkbox會比點標題要多往parent找一層才能找到售完的div
