### ISSUE TITLE
FAQ 內容調整

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#657]
能否分成兩部份:

1) 賣家如何確定 訂單是否成立
2) 買家如何確定 訂單是否成立

![image](https://cloud.githubusercontent.com/assets/16083361/13867106/b9b6cafe-ecf6-11e5-9eb0-8264626757c8.png)

**Comment by gameflierHao** [comment]
![screenshot_tue_mar_22_00 25 17](https://cloud.githubusercontent.com/assets/1106733/13925768/9448fc26-efc4-11e5-9c5e-205e5553b7d4.png)

已更新

**Comment by dominic820** [comment]
good
