### ISSUE TITLE
FAQ (關於三層架構的部份)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#658]
Hi, 這張圖右邊cut到了　

![image](https://cloud.githubusercontent.com/assets/16083361/13867207/ce07cfac-ecf7-11e5-845a-b8cd96e242ec.png)

**Comment by dominic820** [comment]
(確認一下 目前圖片上到一半對嗎)

**Comment by gameflierHao** [comment]
FAQ還在更改
好了會通知大家
預計這週會有個版本出來

**Comment by gameflierHao** [comment]
FAQ已更新
