### ISSUE TITLE
[widget] [團購->快速揪團] 圖片展示如果Size不一樣的話，會突然伸縮怪怪的。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#659]
店家 or 客戶
使用平台 : PC / iphone4
瀏覽器 : Chrome

Bug
流程
測試 Widget : http://store.tagfans.com/node/fb.html?noteId=205942_2677_527
1. 圖片如果Size不一樣會突然伸縮位移。

**Comment by cmacma7** [comment]
David, last time we talk about this item, I think the decision is to use animation and fix the size of the picture.

**Comment by cyen1121** [comment]
全部改用background-size = > cover統一大小避免變大變小跳動的問題
