### ISSUE TITLE
[widget] [團購->快速揪團] 客戶也能新增商品。

### ISSUE THREAD

**Issue by wade89214** [cmacma7/bn#660]
店家 or 客戶
使用平台 : PC / iphone4
瀏覽器 : Chrome

Bug

1.客戶也能夠新增商品。

**Comment by cmacma7** [comment]
Is this a bug? Or it is actually a feature that is controlled by the owner to allow user to add product or not.

**Comment by wade89214** [comment]
抱歉 沒看到可以關閉><
