### ISSUE TITLE
消費紀錄 這個紅色小框框 能不能在商店首頁也出現

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#662]
消費紀錄 這個紅色小框框 
能不能在商店首頁就出現 (更容易查詢)

![image](https://cloud.githubusercontent.com/assets/16083361/13875157/2d30fbea-ed37-11e5-8af5-4a238cc6658d.png)

![image](https://cloud.githubusercontent.com/assets/16083361/13875168/40a6c8a8-ed37-11e5-98ec-e2bf17bb4b7a.png)

**Comment by cmacma7** [comment]
The 此店訊息 change to 信息與記錄, then user can click to see the 消費紀錄

**Comment by cmacma7** [comment]
And focus already move to 消費紀錄 when user click 此店訊息, so I think change the wording is good enough.
