### ISSUE TITLE
商品名稱的文字不明原因錯亂 造成無法篩選

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#664]
(此widget在商店1518裡面)

![messageimage_1458575791141](https://cloud.githubusercontent.com/assets/16083361/13925248/a1208d1c-efc2-11e5-94c4-dcfd6f4121a4.jpg)

![messageimage_1458575523831](https://cloud.githubusercontent.com/assets/16083361/13925241/96d55996-efc2-11e5-9048-dec0e1f901ce.jpg)

篩不到東西 : 
![messageimage_1458575640948](https://cloud.githubusercontent.com/assets/16083361/13925262/acc8b11c-efc2-11e5-929f-c804b8d858a6.jpg)

**Comment by cyen1121** [comment]
這問題與上次遇到<>一樣的問題原先透過html()取字造成編碼轉換的問題，後來改用text()修正

**Comment by dominic820** [comment]
ok
