### ISSUE TITLE
從店首頁點選"此店訊息"，預設要進入"消費紀錄"  (目前是"收件夾")

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#665]
目的是"查詢"的人，應該是多過看訊息的人。
有助於查詢訂單!

![image](https://cloud.githubusercontent.com/assets/16083361/13954853/7d1094d8-f07d-11e5-8543-4776156c2440.png)

**Comment by cmacma7** [comment]
fixed in version 944. set focus to model_categoryList
