### ISSUE TITLE
客戶希望統計總表，篩選後出現的筆數，能調高到500筆。 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#666]
客戶希望統計總表，篩選後出現的筆數，能調高到500筆。 
可以用設定的方式設定上去，
客戶可接受 此"設定"可以跟著機器走，換機器必須重新設定。

**Comment by cyen1121** [comment]
bn的統計列表 
1. 會記錄之前選擇的筆數，
2. 最多可以到400筆，
3. 進來會抓設定好的筆數，不會再只有今天的單子，方便客人進來一定有單子
4. 滿意度調查表的換頁修好了
5. 修正過濾條件再重新進來的時候還會存在且沒顯示的bug
