### ISSUE TITLE
[widget] [快速揪團] 刪除某項團購商品後，在購買統計中仍然存有該商品的紀錄

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#668]
測試平台: PC

流程:
1. 進入編輯->刪除下圖中的牛舌餅
![01](https://cloud.githubusercontent.com/assets/13726130/13980374/398f22e6-f119-11e5-910a-ba13d5595516.png)
2. 在購買統計中，牛舌餅卻沒有被刪除，除非選購另外的商品才會被蓋掉
![02](https://cloud.githubusercontent.com/assets/13726130/13980385/435a1376-f119-11e5-84a3-594a60e0d861.png)

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
