### ISSUE TITLE
widget可以排列組合方式 選擇商品規格 並訂購

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#671]
範例 : 
7種顏色 配 6種尺寸, 42種排列組合。
可用下拉選單 或 按鍵 來讓客人選購!

![image](https://cloud.githubusercontent.com/assets/16083361/14007720/417e3668-f1b4-11e5-9762-ceca6752b8bb.png)

**Comment by dominic820** [comment]
對應"衣服"的上架，高度需求

**Comment by cmacma7** [comment]
maybe duplicated bug.

**Comment by peichingliao** [comment]
已實作完畢
