### ISSUE TITLE
在Tagfans登入第二個 facebook帳戶 流程能否更簡單?

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#672]
現行 
1. 瀏覽器 : 需先登出facebook視窗 再登出Tagfans軟體
2. APP : 需移除App 重新下載

**Comment by cmacma7** [comment]
Yes, we can logout for user. But most of the people will forget password and user name, if we logout for them, the possibility will be disaster.

**Comment by cmacma7** [comment]
Text modified, Fixed on version 950. Go to advance setting and choose Go to facebook and Logout.

**Comment by dominic820** [comment]
突然有個想法，覺得我們還是要協助登出facebook，因為:
1. 客人不能順利切換faceboook帳號，會一直怪Tagfans不好用。
2. 客人忘記密碼，不會怪Tagfans有問題，只會怪自己，而且會想辦法找到答案。

但我想，最重要，不能被犧牲的功能是，瀏覽器只要是登入中，Tagfans舊不必重新輸入。

**Comment by cmacma7** [comment]
I have made the change in advance setting. Please see my comments above.

**Comment by cmacma7** [comment]
1. 客人不能順利切換faceboook帳號，會一直怪Tagfans不好用。 This is not normal case, this is advance user's case. So they should use advance setting, instead of waste 99% of people's time to remember the password. Facebook is doing this way, why we want to change it?
