### ISSUE TITLE
要進入某社團，在等待店主審核期間，需要系統提醒

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#674]
需要系統提醒 : 你正在等待店主審核
因為有客人以為系統故障，所以一直登不進去。
其實是在等店主。

**Comment by cmacma7** [comment]
prompted user to wait when they reply the answer. But we never know when the store owner allow, so cannot reject customer to send request once again. 
prompt add in BN.

**Comment by cmacma7** [comment]
Fixed at store in version 949
