### ISSUE TITLE
需要進快修正關於 "進入商店限制" 的描述

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#677]
dominic有提供參考文案
(紅色箭頭)

![image](https://cloud.githubusercontent.com/assets/16083361/14041548/e6583a14-f2ac-11e5-8c29-5e92d33ca3b6.png)

![image](https://cloud.githubusercontent.com/assets/16083361/14041550/edd56938-f2ac-11e5-8808-6b9ca5f28052.png)

**Comment by cmacma7** [comment]
在下面的文框中，你應該輸入進店提示給客戶。 (1) 如果你選擇 "使用密碼" ，請提示客戶他們如何能得到密碼。一般情況下，您的客戶可以通過提示推斷密碼，或通過電子郵件或即時通訊軟體收到您的密碼。 (2) 如果你選擇 "由管理員確認" ，請輸入您需要客戶回答的問題。 當客人進入您的商店時，會看到您的提問。客人需要正確的回覆您的問題,才可以獲得入店許可。您的留言箱裡將收到他們的進店請求。 您可以根據他們的答案跟身分, 決定是否接受他們進店。

**Comment by cmacma7** [comment]
Text modified,  Fixed on version 950

**Comment by dominic820** [comment]
so good!

**Comment by dominic820** [comment]
馬兄
這個"輸入密碼"，可以多寫一點嗎?
比方說"請輸入你指定的密碼"

![image](https://cloud.githubusercontent.com/assets/16083361/14101324/631f6e7a-f5c6-11e5-9f95-980f2faeb840.png)

**Comment by cmacma7** [comment]
Changed the wording at version 955.1
