### ISSUE TITLE
[統計總結] 單品的統計總結UI修正

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#678]
1. 上方header bar請提示該widget標題
2. 原本的header bar有提示起訖日期，但下方選擇新的日期，header bar未更新
   ![12](https://cloud.githubusercontent.com/assets/10726049/14069033/48318e50-f4c6-11e5-80a7-3d74aeb48004.png)

**Comment by cmacma7** [comment]
This is two issues. Second one belong to David. So I will open another issue for 上方header bar請提示該widget標題

**Comment by cyen1121** [comment]
日期顯示不正確的問題已經修正了，因為更新日期後沒把正確的title資料帶進去取代原本舊的，只有在init summary的時候才有去換。

**Comment by cmacma7** [comment]
showSummary and showSummaryBeta both support (gid, title) with the complete title text.

**Comment by cyen1121** [comment]
已將title放入header裡面，在手機畫面較小的時候，因title在前面後方時間範圍會變成點點點被藏起來，但因為下方input就有時間區段的提示，所以提示上面是沒問題的。大畫面的時候則可以完整呈現。
