### ISSUE TITLE
[Widget] 聯絡我們的category_id未指定

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#679]
因為有對話功能
須指定category_id=99
![13](https://cloud.githubusercontent.com/assets/10726049/14069044/8d279342-f4c6-11e5-8485-b3022f0a65e7.png)

**Comment by cyen1121** [comment]
已修正上store和bn將原先設定的type 105換成99

**Comment by cmacma7** [comment]
Hi David, if you fix the issue, please remember to add fixed label.
