### ISSUE TITLE
We need to provide discount rule, for example buy 3 get 10 dollars off.

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#681]

**Comment by dominic820** [comment]
Tagfans客人給的簡單的例子是 : 各賣一個， 多少錢。
期望 : 各買一個(買一組)，後台要能計算 總共幾個，而不是只記得 買一組。

**Comment by cmacma7** [comment]
Widget inner scripting
The widget inner scripting gets the script from widget.context, then execute the script.
Price script:  it is used to calculate the final price of the items inside a widget. It can be used to calculate the discount, for example.
Context.script : this is the sample script that you can put under widget.context.script through widget json editor
    var A=0; 
for (var i=0; i<arguments.length; i++){     
A+=arguments[i].p*arguments[i].count;
}  
if (arguments.length > 3) { 
return A-10;
}
else {
    return A;
}
At the sample above, we assume the widget has items in the format of {count:3, p:40} for each item, and items collected to an array then pass into the script. arguments is the predefined input, which is passed from the caller as parameter. You can use arguments this variable to access the objects that the caller has. The result should return to the caller. Please note, this script is behaving like inside function functionX(arguments){ Your_Script_Here };
In your template, to calculate the price basing on the above script, you use
var priceFunction = new Function(script);
var price = priceFunction.apply(this, context.items);
Here script is the script you get from widget context. Context.items is the items array that you used to record the product items information. Context.items becomes the arguments in your script. this can be passed to the script, and becomes this in your script. Please note, you can pass any object as this to the script. For example, if you pass {token:2133} as this to the script, then inside script, this.token will be 2133.

**Comment by cmacma7** [comment]
Hi Peiching, this issue assign to you for practice.
Please see the Widget inner scripting above, to create the pricing rule.

**Comment by peichingliao** [comment]
已完成 一般團購 - 優惠模組
