### ISSUE TITLE
靠左對齊的需要

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#685]
靠左對齊的需要
(同一類商品 可更容易判讀)

![image](https://cloud.githubusercontent.com/assets/16083361/14082662/dcdf22c4-f543-11e5-9a66-ed9df29fd7a0.png)

**Comment by cyen1121** [comment]
已修正上bn和store
只對商品名稱設定css --> text-align: left;padding: 0 5px;
讓文字靠左並且左右間隔都有5px

**Comment by dominic820** [comment]
Hi David, 
下面的商品統記表格
"名稱" 也需要靠左對齊喔。

![image](https://cloud.githubusercontent.com/assets/16083361/14101228/9c207a62-f5c5-11e5-8ca7-6e9896e18f42.png)

**Comment by cyen1121** [comment]
已完成，上面style皆修正
