### ISSUE TITLE
開發預購專用widget 能依數量更換狀態

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#686]
![image](https://cloud.githubusercontent.com/assets/16083361/14082927/5c14b058-f545-11e5-9657-af7386d56f2e.png)

![image](https://cloud.githubusercontent.com/assets/16083361/14082953/89955492-f545-11e5-8f13-2b24671ea0b1.png)

**Comment by cmacma7** [comment]
This widget will change state depends on a rule, for example, the purchased count.
We need to implement the rule just like price rule. As the result, user can input script to define the rules. Please refer to the below price rule example code.

**Comment by cmacma7** [comment]
Widget inner scripting
The widget inner scripting gets the script from widget.context, then execute the script.
Price script:  it is used to calculate the final price of the items inside a widget. It can be used to calculate the discount, for example.
Context.script : this is the sample script that you can put under widget.context.script through widget json editor
    var A=0; 
for (var i=0; i<arguments.length; i++){     
A+=arguments[i].p*arguments[i].count;
}  
if (arguments.length > 3) { 
return A-10;
}
else {
    return A;
}
At the sample above, we assume the widget has items in the format of {count:3, p:40} for each item, and items collected to an array then pass into the script. arguments is the predefined input, which is passed from the caller as parameter. You can use arguments this variable to access the objects that the caller has. The result should return to the caller. Please note, this script is behaving like inside function functionX(arguments){ Your_Script_Here };
In your template, to calculate the price basing on the above script, you use
var priceFunction = new Function(script);
var price = priceFunction.apply(this, context.items);
Here script is the script you get from widget context. Context.items is the items array that you used to record the product items information. Context.items becomes the arguments in your script. this can be passed to the script, and becomes this in your script. Please note, you can pass any object as this to the script. For example, if you pass {token:2133} as this to the script, then inside script, this.token will be 2133.
