### ISSUE TITLE
widget名稱與位置的調整、調動 (功能不需改變)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#687]
1. 圖文故事可以當做"公開留言"來使用，請複製一個到"意見收集"的分類裡面，名稱也可以改成"公眾留言板"
2. 連絡我們，請改名成"私密留言"

**Comment by cmacma7** [comment]
Howard please help to change the widget select. We need to change the 留言 to have two entry, one is public and one is private. All under "意見收集"的分類裡面. Public 留言 please copy the 圖文故事 with message default to enable.

**Comment by gameflierHao** [comment]
Done
