### ISSUE TITLE
[統計總結] 用手機看統計總結，點選訂單號碼，畫面空白

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#689]
1. 用chrome模擬 iPhone 6 plus
2. 進入商店 -> 消費記錄 -> 收到 訂單 -> 統計總結 -> 點選訂單列表上任一個訂單號碼
3. 出現空白畫面

![22](https://cloud.githubusercontent.com/assets/10726049/14101937/488c536c-f5ca-11e5-8901-999810258ec9.png)

**Comment by cyen1121** [comment]
在手機頁面因畫面太小，jQuery Mobile 再開dialog的時候會把前一頁執行pagehide
所以會造成執行summary的destroy，再回來就會整個頁面被殺掉。

點選單號叫出訂單在關閉也有相同情況

**Comment by cmacma7** [comment]
Fixed at version 960. It is caused by summary page destroy is been called when change page to popupForm in mobile==true case.

**Comment by peichingliao** [comment]
chrome模擬ok了
用ios app，popup內容有出現，可是close要點兩下才能關閉
而且關了就直接跳回查詢訂單畫面，而非停留在統計總結 
右上角也沒有統計總結可以按了
