### ISSUE TITLE
編輯tag，選了照片後，說明文字跑版

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#69]
![screenshot_2015-01-27-20-02-22](https://cloud.githubusercontent.com/assets/10726049/5940548/9102861c-a746-11e4-98b1-92f39408ceac.png)

**Comment by cmacma7** [comment]
Fixed in SVN 603
setTimeout(function(){modifySimpleEditor();}, 20); not been called if return from photo editor.
