### ISSUE TITLE
In the chat area of all the widgets, when user type a sentence, the sentence at local device will not show right away, but delay for seconds.

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#692]
It is because the implementation show the user typed message until echo back from server. If network is slow, it will delay for a long time.

**Comment by cyen1121** [comment]
fixed
修改以下三項
(1)文字會馬上出現並閃爍，直到收到post api確認完成發送，則將閃爍取消。
(2)並對過長文字做修正，初始化顯示最多三行
(3)留言直接放在姓名後方，減少空間的浪費

修改module
utilityPackage
針對留言module做修正
