### ISSUE TITLE
[Widget] 團購widget購買完成, 重新整理兩次, 會回到原本的購買畫面

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#699]
這是bug

OrderMultipleItemsWidget_groupbuy

 if(data && data.orderNumber > 0){

訂單號碼字串 "9863-00098" > 0 會是false, 就跳進else, 把之前的訂單給清掉

**Comment by cyen1121** [comment]
將原先判斷的方式改成判斷string的長度是否正確
避免造成錯誤

OrderMultipleItemsWidget_groupbuy_time_limit_w
OrderMultipleItemsWidget_globalgroupbuy
OrderMultipleItemsWidget_groupbuy
OrderMultipleItemsWidget_groupbuy_time
OrderMultipleItemsWidget

fixed
