### ISSUE TITLE
訂單合併流程建立

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#700]
the two functions are ready on BN. However, the id you store to object is "index" of each item instead of "id". It is because in the future we might want to re-use the noteId for all the mails. As the result, the only unique one is mail index, which is currentArray[i].index for item i.

function get the items from the storyBoard of mails basing on input index array. Here index is the mail index, not the note Id. Each order has index (mail index) and (noteId) id, here we use index to identify the mails.
function getMailItemsByIndex(indexes)

// function remove the items from the storyBoard of mails basing on input index array. Here index is the mail index, not the note Id. Each order has index (mail index) and (noteId) id, here we use index to identify the mails.
function removeMailItemsByIndex(indexes)

**Comment by dominic820** [comment]
能併 能拆
拆單最小還原單位 : 還原到原始訂單即可
(PS : 若原始訂單有多項目，不需要連每一個項目都拆散)

**Comment by cyen1121** [comment]
SVN 1026

**Comment by dominic820** [comment]
ok

**Comment by cyen1121** [comment]
可以讓使用者進行訂單合併
但條件限制
1. 需要是團購widget下的訂單
2. 同一個使用者的訂單
3. 當品項名稱相同但價錢不同則會分成不同的商品
4. 會以最新的一張單子當作基準，並使用其運送方式
