### ISSUE TITLE
錯字訂正 (團購can)

### ISSUE THREAD

**Issue by MollyTsai** [cmacma7/bn#701]
![image](https://cloud.githubusercontent.com/assets/18318048/14336983/381efaba-fc9c-11e5-9028-fbba5b2d9748.png)

**Comment by cmacma7** [comment]
What's this means. where is the error?

**Comment by MollyTsai** [comment]
it's supposed to be 真實"帳"戶, not 真實"賬"戶...

**Comment by gameflierHao** [comment]
DONE
