### ISSUE TITLE
<團購Can> 畫面黑條

### ISSUE THREAD

**Issue by MollyTsai** [cmacma7/bn#702]
往下拉scroll bar會出現黑條.. (從"親友小揪團"進去不會發生此現象, 但如果是從"類型"一路往下選就會看得到) 

![image](https://cloud.githubusercontent.com/assets/18318048/14337054/f8255cc8-fc9c-11e5-8720-b10bc0d3fd9c.png)
![image](https://cloud.githubusercontent.com/assets/18318048/14337064/0736ba22-fc9d-11e5-896d-478deea8eb4b.png)

**Comment by gameflierHao** [comment]
Done

**Comment by MollyTsai** [comment]
確認okay.
