### ISSUE TITLE
列表排行榜widget 故障

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#707]
無法刪除"地址" "電話"
刪除之後 按 右上角建立 
"地址" "電話"又會跑出來

![image](https://cloud.githubusercontent.com/assets/16083361/14419458/8591d02e-fff8-11e5-8344-e44414f2035f.png)

**Comment by gameflierHao** [comment]
備註:
Editor的 X  不 work
如果利用backspace刪除的話 
context內容會被刪掉 - 正確
但利用 X 快速清除內容時
context內容時記上還是會存在 - 錯誤

是否是input旁的刪除btn動做出了問題?

**Comment by cmacma7** [comment]
fixed by switch back to handleKeyup() on all input.
