### ISSUE TITLE
模版分類 文字說明

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#708]
揪團後面 請加上 (限3件商品)
![image](https://cloud.githubusercontent.com/assets/16083361/14420045/563171a0-fffc-11e5-9d29-249b74526b9d.png)

專業團購裡面 請把"簡易開團" 移除　
![image](https://cloud.githubusercontent.com/assets/16083361/14420074/8589362c-fffc-11e5-94a5-e6c6cb9559f8.png)

**Comment by gameflierHao** [comment]
DONE
