### ISSUE TITLE
圖片tag引導性不佳

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#71]
即日起~2015/1/15享預購價$1688元/組年菜提貨時間◆ 2/16(一)、2/17(二) 11:30~22:00◆ 2/18(三)除夕 11:30~16:00春節營業時間◆ 2/18(三)除夕、2/19(四)初一    ◇ 中山北殿、吉林殿、大興西殿、中美殿、光明殿      殿休(除夕僅提供外帶及年菜提貨服務)    ◇ 朝富殿、崇德殿 11:30~22:00◆ 2/20(五)初二~2/23(一)初五 11:30~22:00
http://store.tagfans.com/?noteId=4811

我遇到一個困難，我想訂這個年菜，可是我看不清楚圖片上的電話

**Comment by cmacma7** [comment]
How to solve it?

**Comment by cyen1121** [comment]
這其實跟原本上的圖不夠大張有點關係，我覺得可以增加檢舉系統讓user反映給店家，就像訂單的選擇幾個選項可以給他選  然後選完直接透過系統寄給店家Owner和我們service@tagfans.com的帳號.
選項可以有
(1)資訊不清楚
(2)圖片不清楚
(3)含有暴力及色情文字
(4)內容已經過期
(5)分類錯誤
(6)操作困難<--反映給我們自己
目前想到是這樣

**Comment by cyen1121** [comment]
是不是Apple 再過APP審核也要有檢舉機制?

**Comment by peichingliao** [comment]
我以前提過上傳圖片好慢->因為是傳原始檔+顯示原始檔
後來改成上傳前即縮圖 (?!)

可否改成
上傳原始檔+顯示縮小圖
tag預設也是顯示縮小圖
點擊全螢幕可看原始圖檔, user就可以自行放大觀看

**Comment by cyen1121** [comment]
歸類為老闆自己上圖要上好一點跟好閱讀的圖
不能算是bug

close
