### ISSUE TITLE
十一街 需要把訂單介面修正 (ex : 訂單的 地址, email 要拿掉) 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#710]

**Comment by gameflierHao** [comment]
全版菜單部分:店家未讀改訂單成立

**Comment by gameflierHao** [comment]
更新全版菜單顧客填寫資訊選項

![screenshot_wed_apr_13_15 39 12](https://cloud.githubusercontent.com/assets/1106733/14486109/ce2f3d26-018d-11e6-9097-35e14f33be4b.png)

**Comment by dominic820** [comment]
ok
