### ISSUE TITLE
付費團購excel 跟 widget 新增第二個備註欄位 目前一個已經不夠用了

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#711]

**Comment by dominic820** [comment]
需要再一個欄位
有人是寫流水號 有人是寫上游廠商名字 或更多備註資料.....
![image](https://cloud.githubusercontent.com/assets/16083361/14483709/4f1a1f44-017c-11e6-85fe-baed685fe016.png)

**Comment by cyen1121** [comment]
已經增加備註2的欄位 
並可以對欄位做過濾
目前支援所有團購widget

module_name : 
OrderMultipleItemsWidget_groupbuy_time_limit_w
OrderMultipleItemsWidget_globalgroupbuy
GeneralShoppingCart
OrderMultipleItemsWidget_groupbuy
one_item_group_buy
one_item_group_buy_limit
OrderMultipleItemsWidget_groupbuy_time
module_showSummaryBeta

**Comment by dominic820** [comment]
ok
