### ISSUE TITLE
iOS app會把訂單號碼辨認為電話號碼

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#713]
iOS app會把訂單號碼辨認為電話號碼
1. widget訂購完成的畫面 (各種不同widget)
2. 查詢訂單 (各種不同查詢紀錄)

不小心按到訂單號碼，就會問是否進行通話，有點惱人

查詢有以下幾種做法
http://stackoverflow.com/questions/226131/how-to-disable-phone-number-linking-in-mobile-safari

---- 此方法是可行的 ---
.element { pointer-events: none; }
## .element > a { text-decoration:none; color:inherit; }

但是要改的widget實在是太多了
可否直接由jqm.html，或是ios app修改呢？

**Comment by cmacma7** [comment]
add the meta at verison 973.1

**Comment by peichingliao** [comment]
已修正
