### ISSUE TITLE
客戶商店的版型 可以重新選擇

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#714]
情境:

客戶選了"揪團"，但是他其實是要蓋"專業團購"
一人有兩家店的上限，所以版型需要開放重選。

![image](https://cloud.githubusercontent.com/assets/16083361/14592243/1a35656e-054f-11e6-8db3-abaf95ab7f90.png)

**Comment by cmacma7** [comment]
Enable delete Store at front page manage:delete. Then user can add new store.
Version 1.1.978

**Comment by dominic820** [comment]
可否關閉客人自刪權限，
以後sales(目前dominic)來把關也好
順便建立客戶關係

**Comment by dominic820** [comment]
close
