### ISSUE TITLE
在設計問券的時候 只寫"問題描述" 不寫"標題"   由買方填入的資料，會無法紀錄

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#715]
在設計問券的時候
只寫"問題描述" 不寫"標題" 一樣可以完成問題
下單後也依然可以帶出回條

但是問券由買方填入的資料，會無法紀錄
需要設計成 不需兩行都填寫 
因為客戶不知道 兩行都要填

![default](https://cloud.githubusercontent.com/assets/16083361/14604015/00a71c28-05a4-11e6-9933-9bcccdd79ed8.PNG)

**Comment by cmacma7** [comment]
fixed by use description as name.

**Comment by dominic820** [comment]
ok
