### ISSUE TITLE
團購widget標題出現 #號，會造成該widget無法"查詢訂單"

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#717]
(4/21 客戶反映 特別某一個widget 無法查到訂單)

![image](https://cloud.githubusercontent.com/assets/16083361/14703623/605a9c08-07e3-11e6-873a-37317f391348.png)

**Comment by cmacma7** [comment]
It is caused by # sign is re-assign to url by jquery mobile dataurl. It is jquery mobile's bug that if dataurl is encodeURIComponent, but still show # in url.
Fixed in v987

**Comment by dominic820** [comment]
closed
