### ISSUE TITLE
[Widget] 在新的頁面，新增團購can，再新增一般團購，回到頁面會發生error

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#719]
在新的頁面，新增團購can，再新增一般團購，回到頁面會發生error

因為團購can
context.slideImageTimer = setInterval(function(){
裡面的context.rootDiv，變成了一般團購的div
所以呼叫了一般團購的showImage，發生error

![2016-04-21 10 38 46](https://cloud.githubusercontent.com/assets/10726049/14712931/ae67f80e-0811-11e6-9d7c-71c2c8bf9391.png)

**Comment by cyen1121** [comment]
在開啟editor後會造成原先佔存在context底下的image dom變成editor裡的widget dom，造成setInterval在執行時出錯，直接在setInterval裡面去find dom不在原先的init裡面find。
