### ISSUE TITLE
撰寫新郵件給店家，不應有多種widget可選擇

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#72]
![screenshots_2015-01-28-23-52-59](https://cloud.githubusercontent.com/assets/10726049/5940948/f727cd06-a748-11e4-872a-cf700529d948.png)

**Comment by cmacma7** [comment]
Should disable compose feature for now, until we find a good way to use it

**Comment by cmacma7** [comment]
Please help on define the rules.
1. When in a store, which templates that owner can use.
2. When in a store, which templates that user can use.
3. When not inside store (at our main page), which templates user can use.

**Comment by cyen1121** [comment]
我覺得可以做以下的分類方式
in store各種widget都可以做使用

但不是在store的情況下
只有資訊類型(除了留言放大內部頁面跳業外沒有其他功能)和投票這種
其他使用都很奇怪
外部連結有可能很容易變成拿來寄送病毒或詐欺的widget
點菜定位都不是單獨發郵件需要的

**Comment by peichingliao** [comment]
我覺得
1. user寄給店家: 只有文字
2. user寄給user: 只有文字 (有這一路嗎?)
3. user分享給user: 不限 (因為分享的是店家發布的tag)

**Comment by cmacma7** [comment]
How about
1. user寄給店家: not allowed. Because the store can have message widget in the customer feedback page. 
2. user寄給user:  Allow non-commercial widgets, and social widgets. 
3. user分享給user: 不限 (因為分享的是店家發布的tag). Yes already this way.

**Comment by peichingliao** [comment]
1. ok
2. 還是覺得僅限圖文功能就好，有其他適合的widget嗎？投票若是對象只有一個也沒意義

**Comment by cmacma7** [comment]
Currently mail can only send to friends.
