### ISSUE TITLE
購買行為的Widget在項目名稱如果有 < > ，在訂單產生時會有亂碼出現

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#720]

**Comment by cyen1121** [comment]
將原先抓html()做法改為text()

一般菜單
OrderMultipleItemsWidget

團購購買
OrderMultipleItemsWidget_groupbuy_time_limit_w
OrderMultipleItemsWidget_groupbuy
one_item_group_buy_limit
OrderMultipleItemsWidget_groupbuy_time
OrderMultipleItemsWidget_globalgroupbuy
one_item_group_buy

**Comment by dominic820** [comment]
ok
