### ISSUE TITLE
widget上架 - 集中訂單狀態設定 的 購物widget

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#721]
採勾選方式
![image](https://cloud.githubusercontent.com/assets/16083361/14806729/18ff6dd4-0ba8-11e6-9d65-82d8f83527be.png)

widget成立之後， 不可重選

**Comment by cyen1121** [comment]
![2017-02-09 2 40 25](https://cloud.githubusercontent.com/assets/10192854/22772109/b44d326a-eed5-11e6-8dec-f93da738d89c.png)

**Comment by cyen1121** [comment]
系統須提供get shoppingCart context的做法
