### ISSUE TITLE
變更文字說明(購物車狀態設定)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#722]
商店首頁 --> 管理裡面

![image](https://cloud.githubusercontent.com/assets/16083361/14806753/595b0e60-0ba8-11e6-8de5-be7d9a1378d7.png)

"編輯購物車" 改成 "訂單狀態， 統一設定處"

**Comment by cmacma7** [comment]
fixed at version 992.

**Comment by dominic820** [comment]
ok
