### ISSUE TITLE
開發facebook "切換狀態 啟動自動推播功能"

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#725]
可輔助Tagfans的推播(有時收不到)  

ex : 賣家切換到 "請來取貨" 的狀態， 自動啟動FB對話視窗  "請取貨-訂單號碼NO.166122-00001(超連結)" 團主按送出即可。

**Comment by cmacma7** [comment]
add sendFBMessage function to enable summary page to deliver private message to client
example: sendFBMessage(100000210796533, "管理者已讀，請靜待通知", "CMA STORE1 : ✨香茅油精✨ #限時團~4/21 中午收單", getLinkId(storyBoard.currentArray[3]));
sendFBMessage(receiverId, title, description, linkId); Here linkId is the 23143_2311_280 format. You can use gtLinkId() to get the linkId from either itemData, or obj of your Div. As the result.   sendFBMessage(100000210796533, "管理者已讀，請靜待通知", "CMA STORE1 : ✨香茅油精✨ #限時團~4/21 中午收單", getLinkId(storyBoard.currentArray[3].wrapper.rootDiv)); will get the same result

getLinkId(storyBoard.currentArray[3])  will return the same result as getLinkId(storyBoard.currentArray[3].wrapper.rootDiv), this function accept itemData or obj, both.

**Comment by dominic820** [comment]
ok
