### ISSUE TITLE
訂單跳號問題 - 更改訂單生成流程

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#727]
未來將由Server執行以下三個步驟 :
 a) 取得新號碼
 b) 訂單寫入成立
 c) facebook +1 推文

 案例 :某商品某單品 :
 widget顯示三人訂購， 但確實只有兩張訂單，也確定老闆沒有刪單， 中間確實跳了一號。

**Comment by cyen1121** [comment]
一般團購修正在發出訂單後就一起透過server對fb做留言，避免分成兩次發送造成的遺失發生

**Comment by dominic820** [comment]
closed?

**Comment by cyen1121** [comment]
已修正sendMail和fb post合併已無此問題
