### ISSUE TITLE
訊息按鈕，按兩次的畫面不正確

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#729]
訊息toggle的時候
上方的foucs設置不正確

![image](https://cloud.githubusercontent.com/assets/10726049/14823585/a90d3d72-0c05-11e6-92f9-f32842599010.jpeg)

**Comment by cmacma7** [comment]
resolve by take out the click event of the bottom button.
Fixed on BN.

**Comment by peichingliao** [comment]
2015/5/5 驗證ok
