### ISSUE TITLE
[Editor] 限量團購widget, 新增項目再刪除, 項目錯亂

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#734]
1. 新增限量團購widget
2. 在物品項目 建立新項目
3. 在 "建立新項目" 底下會出現 "分類選項" & "項目"
4. 依序將Step3新增的"分類選項" & "項目" 按刪除
5. save
6. widget 項目順序亂掉

![55](https://cloud.githubusercontent.com/assets/10726049/14976450/6b69f990-113e-11e6-8cba-9164e7dcc8ed.png)
![56](https://cloud.githubusercontent.com/assets/10726049/14976456/6f5aa2e8-113e-11e6-9a9b-61bdcb62db1c.png)

**Comment by cyen1121** [comment]
一般團購有類似情形
