### ISSUE TITLE
[widget] 規格組合團購  第一個商品項目無法點擊 "售完"

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#743]
測試平台: PC

測試流程:
新增規格組合團購->無法點選第一個商品項目"售完"功能，而其他幾個項目皆可以點選
![00](https://cloud.githubusercontent.com/assets/13726130/15383018/2547c0f6-1dc2-11e6-9e46-70cfa970109e.png)

**Comment by cyen1121** [comment]
fixed.

Type : Widget Module
Template : OrderMultipleItemsWidget_groupbuy
Solution : The first item's index is 0. In the function unavailableItems, if  index is undefined or 0, function would return false. The solution is to change the if-else condition to check the undefined and index is not 0.

**Comment by chuangshaojung** [comment]
test OK
