### ISSUE TITLE
[Widget][一般團購] 訊息狀態新增欄位無用

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#749]
一般團購 的訊息狀態
「請匯款」的表單新增「收件人姓名」、「收件人電話」、「收件地址」
1. 顧客回覆之後，賣家的畫面，狀態有立即改變，但是展開細項資料卻沒有及時呈現
2. 新增的 「收件人姓名」、「收件人電話」、「收件地址」 ，內容沒有顯示出來

**Comment by cyen1121** [comment]
fixed

orderform沒有name時，需要用Description去代表name，避免造成找不到資料就不會回存的問題

**Comment by peichingliao** [comment]
目前沒有此問題
