### ISSUE TITLE
首頁引導文字 需要調整(二)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#753]
前往商店街=>搜尋商店
(三個人中 有兩個客人 不知道要在首頁哪裡搜尋XX街麵食館 來點餐)

搜尋商店 希望加一個"放大鏡符號"

![image](https://cloud.githubusercontent.com/assets/16083361/15661221/31c2667e-2718-11e6-8c8e-1adce363e89e.png)

![image](https://cloud.githubusercontent.com/assets/16083361/15661149/a17b8014-2717-11e6-81c2-7a00252bfa0a.png)

**Comment by cmacma7** [comment]
changed.
