### ISSUE TITLE
[widget] 規格團購編輯頁面的庫存管理選擇"售完"功能，建立之後售完並沒有顯示出來

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#755]
測試平台: PC

測試流程:
新增規格團購->進入編輯頁面->點擊某一項目->庫存管理改成"售完"，如下圖
![01](https://cloud.githubusercontent.com/assets/13726130/15737714/2540f7da-28da-11e6-84a3-6c2874142dc2.png)

建立之後widget無法顯示"售完"功能，如下圖
![02](https://cloud.githubusercontent.com/assets/13726130/15737865/f93d699c-28da-11e6-9a5e-30fa03dd100d.png)

只有規格團購才有此問題，其他都能正常運作

**Comment by chuangshaojung** [comment]
規格團購只能從widget左方點擊方形框框才能改成"售完"，無法從編輯頁面理做更改

**Comment by peichingliao** [comment]
r.1487 已修正
bn 已更新

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
