### ISSUE TITLE
[Widget] 訂便當widget訂購完成的畫面沒有sync訂單狀態

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#759]
![s__4325482](https://cloud.githubusercontent.com/assets/10726049/15767386/133a2cc8-297a-11e6-864a-0f3a914534d6.jpg)
![s__4325483](https://cloud.githubusercontent.com/assets/10726049/15767393/1c798c34-297a-11e6-8704-7aebca25fdb3.jpg)

**Comment by cyen1121** [comment]
已經都修正完成，因為抓的mail有問題
所以改成走localstorage去存note_id，每次進來直接拿來用

**Comment by peichingliao** [comment]
目前已有sync
