### ISSUE TITLE
收到的email，左上角沒有全螢幕模式

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#76]
![screenshot_2015-02-02-10-50-45](https://cloud.githubusercontent.com/assets/10726049/5995264/832adebe-aac9-11e4-96fc-000b003617c7.png)

**Comment by cyen1121** [comment]
新機制在手機會太小螢幕上顯示會將放大縮小功能隱藏

避免放大結果跟實際widget差不多大小
