### ISSUE TITLE
製作撿貨單 

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#762]
統計總結
列印輸出 撿貨單
資訊可參考

![image](https://cloud.githubusercontent.com/assets/16083361/15767650/6a5e59d2-297c-11e6-9f18-1d2effc9d741.png)

**Comment by Iris926** [comment]
[Test Site] bn
[Result] 已將"金額"欄位移除
![image](https://cloud.githubusercontent.com/assets/22789907/23192664/b1359400-f8df-11e6-9051-274b4448c67b.png)

**Comment by Iris926** [comment]
需增加的功能：
1. 讓user可自行勾選要印出的欄位
2. 讓user可以撿貨後直接包貨+貼寄送資訊：填匯資料中的 收件姓名、電話、地址 也要納入1.中的可勾選欄位
3. 建議寄送資訊獨立放在方便剪裁的區塊
