### ISSUE TITLE
[訂單合併功能] 將兩張訂單合併之後，在與一張較新的訂單合併之後，再按下"回到併單前"，則原來先合併的訂單無法回到原始狀態

### ISSUE THREAD

**Issue by chuangshaojung** [cmacma7/bn#766]
測試平台:PC

測試流程:
進到統計總結畫面->先將兩張較舊的訂單合併->再與一張較新的訂單合併->選擇"回到併單前"
->則先合併的訂單無法還原成原來的狀態

**Comment by chuangshaojung** [comment]
如果重新整理過後，就會恢復正常狀態

**Comment by cyen1121** [comment]
修正在合併單如果要與更新的單子做合併時會先將物品數量恢復再進行合併

**Comment by chuangshaojung** [comment]
6/7 test ok
