### ISSUE TITLE
從統計總結點進去，被合併單過後的"子訂單" 來不及消失 出現在統計總結，造成統計總結數量，不正確(多了一筆)

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#767]
這一筆(345589-00003)
其實應該要消失
後續重新整理，會不見(345589-00003已經合併到別張訂單了)

![image](https://cloud.githubusercontent.com/assets/16083361/15814525/b930793a-2bf9-11e6-8b40-3f36b63fa797.png)

**Comment by cyen1121** [comment]
已修正，主單在被init時會先移除子單

**Comment by dominic820** [comment]
ok
