### ISSUE TITLE
"單一widget查詢訂單" 與 "合併訂單" 的影響

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#768]
客戶反映 即使訂單有合併
也需要在單一widget入口
1)能查詢 單一品項總訂購量
2)能查看 原始留言

建議能依照客戶需求
原因1: 從單一品項 查詢單一品項總訂購量 是直覺 且很多人有用到的功能
原因2: 原始留言能露出，解決了 合併訂單時 留言的管理問題(即:回到單一widget去查就好)

**Comment by cyen1121** [comment]
以後從個別商品進去查看歷史紀錄，將不再顯示合併單結果，會顯示最原始的單子，也禁止在這種情況下做合併單的動作

合併單只允許透過總表查詢和建立

**Comment by cyen1121** [comment]
bn上了

**Comment by dominic820** [comment]
ok
