### ISSUE TITLE
下單畫面中止、卡住

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#770]
需要能自動跳開到別的畫面 
且提醒下單可能不成功 請重新查詢
(客人不敢切走)

![image](https://cloud.githubusercontent.com/assets/16083361/16106214/2e0f78dc-33c5-11e6-9e52-89791325af9e.png)

**Comment by cyen1121** [comment]
以修正上bn和store

會請他重新確認訂單，如果完成會直接顯示最新訂單資訊
