### ISSUE TITLE
目前統計總結，沒有針對user ID作區分，同一姓名，會被集中在一起

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#771]
需要針對user ID 做區別

![image](https://cloud.githubusercontent.com/assets/16083361/16106325/0f97f3c4-33c6-11e6-9ae5-5d7d31a9ef8d.png)

**Comment by cyen1121** [comment]
對於相同名字都會找出來，是否有必要透過user_id來過濾，可以列入討論
各有各的好處，一般相同名字的人並不多應該還是能分辨得出來

**Comment by dominic820** [comment]
ok!
目前不同人 不會被合併起來!
