### ISSUE TITLE
Tagfans的換頁邏輯 需要有一致性

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#772]
(或標示清楚) 1-400, 401-800之類

舉例:
排序 : 只能排本頁
篩選 : 可以跨到下一頁篩選
統計金額 : 只有本頁的總金額 (遇到跨頁，不顯示反而好，以免錯亂。  最後一頁有總結金額就好)

**Comment by cyen1121** [comment]
需要討論一下要怎麼解決或是有比較好的呈現方式

列入討論

**Comment by cyen1121** [comment]
因為資料是依照過濾條件一路搜尋下去，如果達到一頁上限會停止在找下去，直到按下一頁才會再往下找，所以無法清楚列出實際有多少頁面，但可以做成第幾頁，然後不知道總共有多少頁面，除非整個完整資料都走過一次．

**Comment by cyen1121** [comment]
bn加入頁次但下方依然顯示訂單順序的相關性，讓人有多一個參考性的數字
