### ISSUE TITLE
 excel顧客回覆每列都有，造成對帳錯誤，可否只印一列

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#775]

**Comment by cyen1121** [comment]
需要討論一下要怎麼解決或是有比較好的呈現方式

列入討論

**Comment by cyen1121** [comment]
新修改的統計頁面下載的excel不會有這個問題發生了，但如果需要就的格式則需要改變閱讀模式

**Comment by cyen1121** [comment]
目前以上到bn

**Comment by cyen1121** [comment]
格式一格式二暫時隱藏
避免團媽造成誤會不懂資料哪些有重複或不重複

如果需要可以打開但excel要調整回來
