### ISSUE TITLE
點大頭像 不會連到FB裡面 特定的人

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#777]
case 1 : ID被誤用到posts ID
自己不能點自己:

![image](https://cloud.githubusercontent.com/assets/16083361/16219620/31a9e0a6-37ba-11e6-9257-d088dd89becf.png)
跳到不相關畫面
https://www.facebook.com/janette.rowley/posts/10207764904141548

case 2 : https://www.facebook.com/10205581044995076

**Comment by cyen1121** [comment]
已修正加入profile字樣避免搗成錯誤的位置，如果還有錯誤應該是帳號的id問題

**Comment by dominic820** [comment]
但是現在這樣
連Sylvia也是錯的耶(Sylvia本來可以點的到嗎?)

![image](https://cloud.githubusercontent.com/assets/16083361/16611751/d8dbd366-4395-11e6-9ce3-679f3a50d65c.png)

![image](https://cloud.githubusercontent.com/assets/16083361/16611756/e4021e80-4395-11e6-8a3c-076363ab8bff.png)

**Comment by peichingliao** [comment]
那個uid是 app_scoped_uid
D爸你的連結改一下
改成 https://www.facebook.com/app_scoped_uid
就可以了!

**Comment by cyen1121** [comment]
已修正
