### ISSUE TITLE
下載excel 需要能下載出VIP等級

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#778]
為了管理VIP客戶
(現在有客人 已經加購VIP價格分層widget)

**Comment by cyen1121** [comment]
bn完成，訂單會記錄下單時候使用者的VIP等級，事後在變化，訂單紀錄的也還是下單時的等級避免造成糾紛。在統計頁面下載的Excel內野可以看到VIP等級

**Comment by dominic820** [comment]
ok
