### ISSUE TITLE
團購widget按售完，但仍會被超買

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#780]
若客戶網路不通，可能無法被即時更新到"售完"
依然可以超買。
需要在下單時，比對售完，以免超下。
本周客戶反映兩次(兩個商品、不同人 出現 超買)

![image](https://cloud.githubusercontent.com/assets/16083361/16439468/54d2c6ce-3deb-11e6-8419-01bc163fea5f.png)

**Comment by cyen1121** [comment]
getUserVip需要再進入store時就設定到local才行

**Comment by cmacma7** [comment]
Got it!

**Comment by cyen1121** [comment]
bn store此問題已修正，因為當商品沒有category沒有設定時index為0造成判斷傳送錯誤，修正後以可以
