### ISSUE TITLE
揪團加入自然語言

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#781]
透過自然語言爬文，快速統計人數，團購也能在不想成立訂單的時候，使用揪團來確定濳在的買家

**Comment by cyen1121** [comment]
BN  getDictionary完成

需要能夠透過fb的uid來對upsertObject做insert的動作，因為爬文的時候需要將資料存成不同使用者下的單子。

**Comment by peichingliao** [comment]
2016.06.30 已上線
