### ISSUE TITLE
優惠(買N送M) widget 客製化調整

### ISSUE THREAD

**Issue by dominic820** [cmacma7/bn#789]
1. 需要補一個 "買N個 送M元"
   ![image](https://cloud.githubusercontent.com/assets/16083361/16757134/983142f0-483c-11e6-86df-7c314e12b345.png)
2.  因為可以舉行 多重優惠活動
    需要限制觸發條件  
   ![image](https://cloud.githubusercontent.com/assets/16083361/16757375/2acdc2d6-483e-11e6-86fd-aeb6d20fe43c.png)

**Comment by peichingliao** [comment]
Hi Iris,
請幫忙測試傳送到你店舖的優惠活動widget唷

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] 未發現錯誤現象
1. 優惠功能OK
2. 設定優先順序OK
3. 能否套用多次OK
4. 是否套用同個優先順序的其他優惠活動OK
