### ISSUE TITLE
[併單] 貨品狀態要帶進新合併訂單

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#791]
as title

**Comment by dominic820** [comment]
原本兩個項目都有設"貨品狀態"
合併完 下面那一個的項目的"貨品狀態"不見囉

![image](https://cloud.githubusercontent.com/assets/16083361/16863321/f6764c54-4a83-11e6-9320-101ab3a03d9e.png)

**Comment by Iris926** [comment]
[10/21補充] 目前併單後，**"品項為純數字"**的單一商品狀態都沒有被帶進併單後的訂單裡
1. 統計表單哩，有將單一商品狀態保留
2. 展開併單後的訂單，則單一商品狀態被清空

![image](https://cloud.githubusercontent.com/assets/22789907/19588974/dee94bf8-979b-11e6-8349-7a8cd89207ff.png)

**Comment by cyen1121** [comment]
已修正會帶入其他副單的貨品狀態

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
