### ISSUE TITLE
掃描出重複訂單

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#796]
[Scenario]
1. 客戶到FB社團留一筆辨識錯誤的留言，接著再留一筆可以辨識正確的留言
2. 老闆 scan FB=>先把辨識錯誤的按"略過"，再把辨識正確的按"成立訂單"
3. 老闆 直接再按最上方的"再掃描一次"=>剛剛已經成立訂單的，又被scan出來，所以又可以按一次成立訂單

[Result] 同一筆FB社團留言，會產生兩筆訂單的回覆

![image](https://cloud.githubusercontent.com/assets/22789907/19342716/8c092782-9165-11e6-88e2-de4e3c0cc124.png)

![image](https://cloud.githubusercontent.com/assets/22789907/19342741/aec9bca0-9165-11e6-9856-22ad39e22fb9.png)

**Comment by peichingliao** [comment]
與另一個bug重複

https://github.com/cmacma7/bn/issues/805
