### ISSUE TITLE
【限量-團購】 widget，名稱修正

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#800]
store.tagfans.com==>新增widget==>團購==>【限量-團購】
此 widget已可涵蓋「限時 and/or 限量」的需求。widget title建議修正為【限時、限量-團購】。

**Comment by cyen1121** [comment]
store已修正

修改名稱

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1550
[Result] Fixed
