### ISSUE TITLE
從FB留言下單，商品品項為數字，與數量混淆，造成scan FB時，訂購數量有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#803]
[Scenario]
0. 商品網址：http://store.tagfans.com/node/fb.html?noteId=878495_20660_3722
1. 客戶至FB社團留言下單：綠25+1 紅 23+1
2. 老闆 scan FB並成立訂單，至FB社團查看

[Result] 
[紅] 25 x 23 - 4830元
[紅] 25 x 1 - 210元
[綠] 25 x 1 - 210元

![image](https://cloud.githubusercontent.com/assets/22789907/19424503/4a2504c2-945c-11e6-8d62-467c7c55c798.png)

**Comment by cmacma7** [comment]
綠25+1 紅 23+1 is not a legal order because 紅 23 does not exist.  As the result, the answer is correct

**Comment by Iris926** [comment]
下單下錯，沒有"紅23"這個商品項目，故23被當成是數量。
