### ISSUE TITLE
從FB留言下單，當客戶夾雜錯誤資訊時，將造成 scan FB後，訂購數量有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#804]
[Scenario]
0. 商品網址：http://store.tagfans.com/node/fb.html?noteId=916241_20867_3722
1. 客戶至FB留言下單：A+1 +1 H+1 B*1
2. 老闆scan FB並成立訂單，回FB社團查看結果

[Result]
A x 1 - 50元
B x 1 - 50元
B x 1 - 50元
H x 1 - 50元

![image](https://cloud.githubusercontent.com/assets/22789907/19424990/9ddaf398-9460-11e6-9c09-0cdd4a1745cd.png)

**Comment by cmacma7** [comment]
The order is not complete, A+1 +1 H+1 B*1  , the +1 does not have item name, so assign to B is not unreasonable.

**Comment by Iris926** [comment]
不是bug，故關閉。
