### ISSUE TITLE
FB留言下單，已成功成立訂單，在統計及商品購買紀錄都看不到訂單；重新scan FB後，又再次scan到這張單

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#805]
[Scenario]
0. 商品網址：http://store.tagfans.com/node/fb.html?noteId=916241_20867_3722
1. 先去FB社團連續留言兩筆訂單
2. scan FB 後，同時將兩筆訂單都成立好(FB那邊也有看到訂單成立的回覆了，圖1)
3. 點統計，發現剛剛兩筆訂單中的第二筆，沒有被列進來統計的表格
4. 直接前往該商品，查看該商品的訂單紀錄，也沒有看到訂單紀錄
5. 再回到FB社團，再下兩筆訂單並scan FB=>剛剛沒出現的訂單又被scan到了，連同最新的兩筆訂單，總共掃出3筆訂單(圖2)

**[Note] 目前僅能在此商品複製出錯誤現象，其他商品尚無法複製出來**

![01](https://cloud.githubusercontent.com/assets/22789907/19425319/987c3544-9463-11e6-88ec-72a405e0079e.PNG)
![02](https://cloud.githubusercontent.com/assets/22789907/19425320/987d8124-9463-11e6-9d5a-6dfa6903e341.PNG)

**Comment by peichingliao** [comment]
D爸未處理第二張訂單的error dirty write

**Comment by cyen1121** [comment]
bn上已修正

檢查是否已經在actions裡面有設置過dirtyCheck和incObject
如果已經有了就更新裡面的內容
如果沒有就push進去

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed(沒有再複製出錯誤現象)
