### ISSUE TITLE
[FB匯入]從FB匯入商品，都會被貼上"限量"的標籤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#806]
[Scenario]
0. 參考商品網址：http://store.tagfans.com/node/fb.html?noteId=918296_20660_3722
1. 老闆先將商品PO在FB社團
2. 老闆到系統，點選 設定/Scan FB/管理/匯入Facebook社團文章
3. 編輯商品時，要確認每個商品項目都是"關閉限量"
4. 成功建立商品

[Result] 查看商品，發現有顯示"限量"標籤

![image](https://cloud.githubusercontent.com/assets/22789907/19429895/a3938c7c-9484-11e6-9efa-865d1e70eb1e.png)

**Comment by cyen1121** [comment]
bn修正
檢查是否有商品的限量是被打開的

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
