### ISSUE TITLE
[消費紀錄][併單] 併單過程中，若切換頁數，則勾選框格會消失+上方的"合併所選訂單"button仍存在

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#807]
[Scenario]
1. 老闆點選 消費紀錄/收件訂單/統計/統計總結/管理/修改。刪除。併單
2. 先在第一頁勾選訂單(圖1)，接著點選 **>** 切換至下一頁

[Result] 勾選框格已消失，但上方與"修改。刪除。併單"相關的功能button仍存在

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19431026/39741e74-9489-11e6-8387-04813a3d6787.png)
　　　
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19431031/4a4595b6-9489-11e6-99af-01a50c1c232f.png)

**Comment by Iris926** [comment]
[補充] 
1. 老闆點選 消費紀錄/收件訂單/統計/統計總結/管理/修改。刪除。併單
2. 接著點擊某一欄位作排序=>勾選框格一樣會消失

**Comment by cyen1121** [comment]
bn已修正
再重新製表的時候會讓使用者確認是不是在合單狀況如果是彈出警告

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
