### ISSUE TITLE
[建議][消費紀錄][統計]能有"商品名稱"的欄位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#808]
[Scenario]
1. 老闆點選 消費紀錄/收件訂單/統計/統計總結
=>此處的"物品名稱"欄位，顯示的是商品的"項目"
=>當老闆想要針對特定商品的某一項目來做狀態的修改，可能會不好辨認

[建議]
1. 在統計表單裡多一個"商品名稱"的欄位(可辨識不同商品，也可直接以該商品作filter)
2. 原來的"物品名稱"欄位，改成"項目"

　　　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19433304/b2710c5c-9492-11e6-97e6-0e19e5012f72.png)

**Comment by cyen1121** [comment]
bn已更新

加入標題欄並將物品名稱改成項目

標題也能過濾和搜尋

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1550
[Result] 統計頁面裡的"商品統計" 也需要顯示標題欄
![image](https://cloud.githubusercontent.com/assets/22789907/20416839/43cb6754-ad7c-11e6-8310-f85320088fc5.png)

**Comment by cyen1121** [comment]
修正

**Comment by VanessaHsu** [comment]
已上線
