### ISSUE TITLE
[消費紀錄][併單]併單後，將所有商品狀態改成一樣都是A，再將其他項目改成不是A，則商品狀態沒有真正被改成功

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#809]
[Scenario]
1. 老闆進行併單
2. 併單後，更改商品狀態，**全部**改成A(ex. 已出貨，圖1)
3. 將某幾個商品改成不是A(ex. 空白，圖2)
4. 連點兩次back，回到"消費紀錄"(此動作按F5重整頁面也可以)
5. 重新進入訂單統計頁面，查看剛剛修改的商品狀態(圖3)

[Result] 全部都變回A(圖1)

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19462674/262bd10c-9521-11e6-8c51-26c6022cfb9b.png)

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19462689/45de80e4-9521-11e6-9be1-30ad4377c4a1.png)

**Comment by cyen1121** [comment]
bn, store已修正
記錄在context.itemStatus有重複的問題所以記錄到DB會讓下一次進來init資料比對出錯

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
