### ISSUE TITLE
從FB留言下單，商品品項為數字，與數量混淆，造成scan FB時，訂購數量有誤(確認user下單正確)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#811]
[Scenario]
0. 商品網址：http://bn.tagfans.com/node/fb.html?noteId=14821_1171_351
1. 客戶至FB留言下單 "粉15+1 粉5+1 粉13+1 米杏11+1 米杏8+1"
2. 老闆 scan FB

[Result]
粉-5 x 1 - 100元
粉-13 x 1 - 100元
粉-15 x 1 - 100元
米杏-11 x 1 - 100元
**米杏-11 x 8 - 800元
米杏-11 x 1 - 100元**

![image](https://cloud.githubusercontent.com/assets/22789907/19465570/d30b3e7e-9537-11e6-9f2d-3bafa717b09e.png)

**Comment by cmacma7** [comment]
Fixed on BN at svn version 1401. 
Cause by "6".score("6", 0.98) is 0.449, smaller than limit 0.5, cause test fail.

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
