### ISSUE TITLE
[Feature]輸入商品分類時，能提供auto complete功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#814]
[Scenario]
1. 老闆點選 shop icon/新增商品
2. 在"商品分類"的欄位，輸入分類名稱
3. 在編輯"分類列表"時，輸入分類名稱

[Expected Result] 當老闆輸入分類名稱的第一個字時，就能自動顯示相關的分類名稱，供老闆直接點選套用

**Comment by VanessaHsu** [comment]
已上架
