### ISSUE TITLE
[改量改價]修改 商品單價/數量/運費後，表示方式不一致

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#816]
[Scenario]
0. 老闆已擁有改量改價權限
1. 老闆至 收件訂單 or 收件訂單/統計/統計總結
2. 展開任一訂單，點擊商品單價/數量/運費，在對話視窗修改

[Result]
1. 商品單價修改後，原單價直接被新單價取代；且該項數量沒有被修改，卻被畫刪除線(NG)
2. 數量修改後，原數量會被畫刪除線 & 標上新數量
3. 運費修改後，原運費直接被新運費取代，且會另外顯示一行有刪除線的字"原始運費n元"(NG)

[Expected Result] 建議所有修改後的顯示方式，都統一跟目前的"修改數量"的方式一樣

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19510754/18641600-9617-11e6-9902-e6e27c174fb8.png)

**Comment by gameflierHao** [comment]
Revision: 1416
Modified : /nodejs/bn/widgets/Widget/Groupbuy/OrderForm/FreeStyleCustomerPurchaseForm.js

修正商品單價修改後顯示問題
