### ISSUE TITLE
[改量改價]修改商品單價後，統計表格裡的商品狀態沒有馬上同步更新為空白

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#817]
[Scenario]
0. 老闆已擁有改量改價權限
1. 老闆至 收件訂單 or 收件訂單/統計/統計總結
2. 展開任一訂單，更動商品項目的狀態(ex. 缺貨中)
3. 修改商品單價=>該商品項目的狀態，會馬上清為空白

[Result] 統計表格裡的同一個商品項目，商品狀態沒有同步更新

[Expected Result]
1. 修改前後，商品的狀態皆不應被改變
2. 若修改後，商品狀態固定會被清空，則建議展開訂單&統計表格都應同步

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19511391/a81e20e0-9619-11e6-8ead-9007de5b5b9e.png)

**Comment by gameflierHao** [comment]
Revision: 1418
Modified : /nodejs/bn/widgets/Widget/Groupbuy/OrderForm/FreeStyleCustomerPurchaseForm.js

**Comment by gameflierHao** [comment]
當物品修改價格後將 context 內的 itemStatusIndex 與 itemStatusMessage 初始化, 並 call checkItemFinish(更新項目狀態)

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
