### ISSUE TITLE
[Scan FB]從FB留言下單"兩件"，scan FB 會判讀為數量1

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#818]
[Scenario]
1. 客戶在FB留言 "A兩件"
2. 老闆 Scan FB

[Result] A x1

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19511708/f357fc9c-961a-11e6-8d1a-63312fcf4d75.png)
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19511751/2ee2a2c6-961b-11e6-82e7-f29610f4d440.png)

**Comment by cmacma7** [comment]
We don't recognize "兩"
