### ISSUE TITLE
[FB匯入]連續點擊"列出文章"n次，會同時列出n次結果

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#819]
[Scenario]
1.  至 設定/Scan FB
2. 選社團&輸入日期區間/連續按n次"列出文章"

[Result] 會直接秀出n次結果

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19543540/f34fb3b2-96aa-11e6-89f8-c56ce4192102.png)

**Comment by peichingliao** [comment]
svn r.1406已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
