### ISSUE TITLE
[十一街][外帶點餐]客戶將商品加入購物車後、結帳前，若商品剛好售完了，則結帳時應提醒客戶&該項目應從訂單移除

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#820]
[Scenario]
0. 店家菜單連結 http://store.tagfans.com/#page_join?o=2907&id=16494&viewType=station
1. 客戶至 店家首頁/外帶點餐/點擊商品並輸入購買數量/加入購物車(ex. 買了A_3+B_5)
2. 老闆將A標記為"售完"
3. 客戶點擊 購物車/前往結帳/輸入姓名&電話/發送，訂單成立！

[Expected Result] 客戶點擊"前往結帳"時，應提醒客戶
1. A商品已售完，要繼續結帳 or 購買其他商品
2. A商品要從訂單中被移除

**Comment by cyen1121** [comment]
bn上加入提示詢問是否要繼續購買

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result]
1. 建議將wording改為：
確定 - 直接前往結帳(刪除已售完商品)  
取消 - 繼續購買其他商品
1. 建議行為：
   確定 =>刪除已售完商品、自動導至結帳頁面(已OK)
   取消 =>刪除已售完商品、自動導回外帶點餐菜單

**Comment by cyen1121** [comment]
已在store和bn修正
如果商品已售完

在購物車的地方不管按確定或是取消都會移除售完的商品

然後取消會同時關閉購物車回到購買頁面

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
