### ISSUE TITLE
[十一街][外帶點餐][外帶冷凍水餃專區]結帳頁面不一致

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#821]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_station?o=2907
1. 客戶至 店家首頁/外帶點餐/外帶生鮮水餃/選購後進入結帳頁面(填寫個人資料，圖1)
2. 客戶至 店家首頁/外帶冷凍水餃專區/選購後進入結帳頁面(填寫個人資料，圖2)

[Result] 圖2多了"信箱" & "地址"的欄位，會讓客戶以為這是可以宅配的

[Expected Result] 如果確定都是由客戶親自取貨付款，建議兩邊的結帳頁面要一致

[圖1]
![image](https://cloud.githubusercontent.com/assets/22789907/19546077/f70cee84-96be-11e6-8380-de6a92c2cd1c.png)

　　
[圖2]　
![image](https://cloud.githubusercontent.com/assets/22789907/19546064/ce5b5e6c-96be-11e6-9089-2ebc8adec29c.png)

**Comment by cyen1121** [comment]
bn已修正

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
