### ISSUE TITLE
[Tagfans Sync]以email登入的客戶在系統下單，Tagfans Sync在FB留言訂單記錄時，應隱藏部分email字元

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#822]
[Scenario]
0. 商品網址 http://store.tagfans.com/node/fb.html?noteId=939308_20867_3722
1. 以email 登入的客戶，在tagfans系統下單
2. Tagfans Sync在FB社團回覆下單紀錄

[Result] Tagfans Sync 會直接將完整的客戶email 顯示出來
[Expected Result] 應隱藏部分email 字元，ex. vatil***@gmai.com

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19547717/8aa940ea-96cc-11e6-92eb-41e8fa088c80.png)

**Comment by cyen1121** [comment]
bn已修正
會移除email後面的domain

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed

![image](https://cloud.githubusercontent.com/assets/22789907/20418463/916f575c-ad88-11e6-8f92-372529201f53.png)
