### ISSUE TITLE
[十一街][外帶點餐]當購物車為空時，點擊"購物車"，應popup提示視窗，不須導進結帳頁面

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#823]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_station?o=2907
1. 客戶至 店家首頁/外帶點餐
2. 先不要點擊任何商品，直接點擊左下的"空的購物車"=>導進結帳頁面(NG)
3. 在結帳頁面，點擊"前往結帳"=>popup"請選擇商品數量"(NG，結帳頁面是空白的，沒有任何商品可以選擇)
4. 在結帳頁面，點擊header左側的back=>回到店家首頁(NG，預期應回到外帶點餐菜單

[Expected Result] 當購物車為空時，點擊購物車=>應留在外帶點餐菜單的頁面，並直接popup"購物車目前沒有任何商品喔！"

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19548048/9873faba-96ce-11e6-8ce7-cd09bb9a5915.png)

**Comment by cyen1121** [comment]
bn上修正
空的購物車沒有辦法打開

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
