### ISSUE TITLE
[十一街][外帶點餐][外帶冷凍水餃專區]未登入的客戶下單，成立訂單後的客戶名稱有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#824]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_station?o=2907
1. 客戶未登入，直接在"外帶點餐" or "外帶冷凍水餃專區" 下單/輸入姓名&電話/訂單成立
2. 連續成立多張訂單，每次輸入的名字都不同，ex. A、B、C、D
3. 老闆查看訂單

[Result] 訂單的客戶名稱會錯亂，ex. D(C)

[Expected Result] 訂單的客戶名稱，應直接以客戶輸入的名稱顯示，不應重複顯示前次輸入的名稱於( )內

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19555203/6be94e9e-96ee-11e6-9625-af25268ae0b6.png)

**Comment by gameflierHao** [comment]
Revision: 1428
Author: zhanghaowu
Date: 2016年10月24日 下午 04:35:40
Message:
修正: git #824

[十一街][外帶點餐][外帶冷凍水餃專區]未登入的客戶下單，成立訂單後的客戶名稱有誤

方法:

使用 getMyInfo 確認是否為體驗帳號,如果為體驗帳號則備註體驗帳號(備註不使用前一個設定的暱稱)

---

Modified : /nodejs/bn/widgets/Modules/informationForm.js

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] 有相同問題

![image](https://cloud.githubusercontent.com/assets/22789907/19653777/56896054-9a48-11e6-86ae-8539b7c5aad2.png)

**Comment by gameflierHao** [comment]
store version : 1.1.1439
更新 informationForm.menusuperman

方法同 informationForm

Revision: 1446
Author: zhanghaowu
Date: 2016年10月27日 上午 10:49:34
Message:

## informationForm.menusuperman

Added : /nodejs/bn/widgets/Widget/Menu/informationForm.menusuperman.js

**Comment by Iris926** [comment]
[Store version] v1.1.1439
[Result] Fixed
1. 外帶訂單成立，一定要填入姓名/電話
2. 客人填單時，姓名欄位看到"你的姓名"
3. 老闆收單時，姓名欄位看到：
　未登入：客人輸入的名稱(體驗帳號)
　有登入：客人輸入的名稱(帳號名稱/email address) or 帳號名稱/email address(帳號名稱/email address)
