### ISSUE TITLE
[十一街][外帶點餐]紅色< button的點擊範圍，很容易與菜單第一項商品的售完checkbox重疊

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#826]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_join?o=2907&id=16494&viewType=station
1. 老闆進入"外帶點餐"的頁面

[Result] 某些視窗比例，會讓紅色<button的點擊範圍，跟售完checkbox重疊

![image](https://cloud.githubusercontent.com/assets/22789907/19583702/a24a89a2-9771-11e6-8a9f-64e1fe9a9d3a.png)

**Comment by cyen1121** [comment]
bn store已修正 將開關移動至最左邊，因為只有老闆看到所以不會影響客人看圖的問題

**Comment by Iris926** [comment]
[Store version] v1.1.1486
[Result] Fixed(售完checkbox只有老闆會看到，不影響顧客)
