### ISSUE TITLE
[十一街][外帶點餐]客人點餐時，"數量&細項選則"的文字有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#827]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_join?o=2907&id=16494&viewType=station
1. 客人至外帶點餐頁面，點擊任一商品

[Result] popup的"數量&細項選則"，文字有誤
[Expected Result] 應為"擇"

![image](https://cloud.githubusercontent.com/assets/22789907/19583892/d1d9e0e0-9772-11e6-94ea-32d0437ae52e.png)

**Comment by cyen1121** [comment]
bn已修正

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
