### ISSUE TITLE
[Scan FB] 當商品品項有顏文字or特殊符號時，會造成scan失敗

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#835]
[Scenario]
1. 老闆刊登商品，並在品項中輸入顏文字or特殊符號(附圖)
2. 客戶在FB社團留言下單，老闆Scan FB(結果請見附圖)

![image](https://cloud.githubusercontent.com/assets/22789907/19589497/052a8d74-979f-11e6-84b4-b77b915d7e6d.png)

![image](https://cloud.githubusercontent.com/assets/22789907/19589503/09f18d4e-979f-11e6-987d-f54d4d5110b2.png)

![image](https://cloud.githubusercontent.com/assets/22789907/19589562/6ed3d992-979f-11e6-838d-6740c794cfa9.png)

![image](https://cloud.githubusercontent.com/assets/22789907/19589556/5ab31c66-979f-11e6-9f4b-12bb45a73afd.png)

**Comment by peichingliao** [comment]
原因是因為 項目 「90""」，造成JSON parse failed
![messageimage_1477039740890](https://cloud.githubusercontent.com/assets/10726049/19592761/c5470d70-97af-11e6-97cb-b5186bfea810.jpg)

**Comment by cmacma7** [comment]
!!!
