### ISSUE TITLE
[連續購買]當商品數量很多，連續購買頁面最下方的商品，則商品頁上方會多出一大塊空白

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#838]
[Scenario]
0. http://store.tagfans.com/node/fb.html?noteId=957029_15842_221
1. 點進商品頁，購買商品，完成第一次訂單
2. 點"繼續購買"=>會再次進入商品頁

[Result] 商品頁上方會多出一大塊空白(附圖)
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19631513/0484c1d6-99d0-11e6-97e2-98287bcd714c.png)

**Comment by cyen1121** [comment]
bn已修正
因為返回購物狀態會叫redrawPanel造成div的top計算錯誤

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
