### ISSUE TITLE
[貨品狀態]統計總表裡的貨品狀態，與展開訂單時看到的貨品狀態，顯示風格不一致

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#840]
[建議] 讓貨品狀態統一都以"有不同底色"的風格顯示
[圖片]
1. 統計總表的貨品狀態
2. 展開訂單的貨品狀態

![image](https://cloud.githubusercontent.com/assets/22789907/19631657/acbe93ee-99d1-11e6-81a1-1ac334f5b370.png)
　　
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19631643/9afe0c3e-99d1-11e6-845c-6ca5973ea5ad.png)

**Comment by cyen1121** [comment]
bn已修正
貨品狀態加入顏色

**Comment by Iris926** [comment]
[Store version] v1.1.1402
[Result] Fixed
