### ISSUE TITLE
[十一街][訂位預約]訂位預約單的狀態是"資料錯誤，訂位失敗"，應將此訂位額度釋出

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#841]
[Scenario]
0. 店家網址 http://store.tagfans.com/#page_join?o=2907&id=16497&viewType=station
1. 老闆設定每個時段都有5張桌可以訂位預約
2. 客人將15:30時段的桌數全部訂光
3. 老闆將這些訂單的狀態全部改成"資料錯誤，訂位失敗"
4. 客人再次前往訂位頁面

[Result] 15:30無法訂位

**Comment by cyen1121** [comment]
請CMA先幫忙確認訂位API是不是有提供把數字恢復的方法

**Comment by cyen1121** [comment]
已修正上bn store

訂位後可以取消後釋放座位

並且不會重複釋放

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1529.1
[Result] Fixed (無法訂位/資料錯誤，訂位失敗/惡意取消，這三個狀態都會將訂位額度釋出)
