### ISSUE TITLE
[FB匯入]選擇日期區間時，叫出月曆但不選擇日期，會讓日期欄位變成亂碼

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#842]
[Scenario]
1. 老闆點 設定/Scan FB/管理/匯入Facebook社團文章
2. 選擇社團
3. 點選日期欄位=>叫出月曆
4. 不選擇日期，點擊其他空白處，把月曆收起來

[Result] 日期欄位會變成亂碼

　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19636988/2fdcc7fa-99ff-11e6-8711-81f9f3828798.png)

**Comment by peichingliao** [comment]
*: 修正日曆顯示問題(#842)
+: 記憶之前選擇的日期
+: 自動代入分類標題

r.1483 已修正，並增加另外兩個功能

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed
1. 修正日曆顯示問題
2. 記憶之前選擇的日期
3. 此項目移除：自動代入分類標題(因統計頁面已加上"商品名稱"的欄位)
