### ISSUE TITLE
[VIP價格][天使屋]不是VIP客人，下單時卻顯示VIP價格，並成功下單

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#845]
[店主回報]
0. 商品網址 http://store.tagfans.com/node/fb.html?noteId=863582_15153_2291
1. 店主回報：某位初次購物的user，沒有VIP資格，卻以VIP價格成功下單
2. 店主提供圖檔：
![image](https://cloud.githubusercontent.com/assets/22789907/19710059/103cf6f8-9b5e-11e6-9a79-25e4f9ee52e1.png)
![image](https://cloud.githubusercontent.com/assets/22789907/19710062/17146664-9b5e-11e6-9148-9cb9637581b4.png)

　　　
[QA Scenario]
0. 商品網址 http://store.tagfans.com/node/fb.html?noteId=960194_20612_3722
1. 商店須設定為"需要通過管理員確認"
2. 從沒進過商店的user，發出進店詢問/店家審核通過
3. user將商店加入常用列表/店家確認**未**設定user為VIP
4. user至有設定VIP價格分層的商品下單

[Result]
1. 看到的商品價格為一般客戶的價格
2. 下單時卻變成VIP價格
![image](https://cloud.githubusercontent.com/assets/22789907/19710170/0cd3de2c-9b5f-11e6-9252-d84167db9d95.png)

[註]目前只複製出一次

**Comment by cyen1121** [comment]
將所有getUserVip使用統一數值，避免造成價錢不統一

皆會存到context.userVip

**Comment by cyen1121** [comment]
bn store皆已修正

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed(沒有複製出錯誤現象)
