### ISSUE TITLE
[入店審核]從iOS FB app點擊商品連結，若該商品所屬的商店需要入店審核，則點開連結後，會跳到tagfans首頁

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#846]
[Scenario]
0. 需要入店審核的店家網址 http://store.tagfans.com/index.html#page_station?o=2306
　在FB社團的商品網址 http://store.tagfans.com/node/fb.html?noteId=910115_18839_2306
1. 分別使用iOS、Andriod、PC，從FB社團裡點擊商品連結

[Result]
**1. iOS FB app：直接跳回tagfans首頁(NG)**
![image](https://cloud.githubusercontent.com/assets/22789907/19711076/b3dedb94-9b65-11e6-9880-ff05fa71b873.png)
　　　
**2. iOS Safari：跳出"需要登入真實帳戶"的提示視窗(NG)**
![image](https://cloud.githubusercontent.com/assets/22789907/19711079/bd9e85ee-9b65-11e6-8824-9a0d10957776.png)
　　　
3. Android FB app：入店審核的說明視窗+店家問題，都有正確顯示
![image](https://cloud.githubusercontent.com/assets/22789907/19711090/ce0e8af0-9b65-11e6-864b-2d5e0ed85e53.png)
　　　
**4. Android Chrome：跳出"需要登入真實帳戶"的提示視窗(NG)**
![image](https://cloud.githubusercontent.com/assets/22789907/19711085/c72781e2-9b65-11e6-9457-85c64e6d8724.png)
　　　
5. PC Chrome：入店審核的說明視窗+店家問題，都有正確顯示
![image](https://cloud.githubusercontent.com/assets/22789907/19711169/44d99dd2-9b66-11e6-994f-cd74cbca44d3.png)

**Comment by peichingliao** [comment]
現在ios點商品會變空白
