### ISSUE TITLE
[iOS app]背景移除app，點訂單通知進入app，再點左上角back，則白畫面

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#849]
[Scenario]
0. Version v1.1.1434 / iOS app
1. 店主背景移除app
2. 收到新訂單，直接點訂單通知，進入app
3. 成功進入"收件訂單"的畫面，點左上角Back

[Result] app白畫面

**Comment by gameflierHao** [comment]
在新版 ios app 1.1.5 上面
左上角Back將會回到 Tagfans 首頁畫面

**Comment by Iris926** [comment]
[App version] 1.1.10
[Test Site] store
[Version] v1.1.1803.1
[Result] Fixed
