### ISSUE TITLE
點常用商店的大頭貼，出現不正確的popup

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#85]
![screenshot_2015-02-10-18-09-04](https://cloud.githubusercontent.com/assets/10726049/6125352/1c361772-b150-11e4-883d-71d65c23e3a9.png)

**Comment by cmacma8** [comment]
This is the editing popup, suppose see the store details. Please try other store to see whether this is this store bug, or all happen in the same way.

**Comment by peichingliao** [comment]
今天測又正常了耶
可能昨晚在捷運上玩，網路狀況不太好
不過現在還是會先出現那個白畫面0.5~2秒，才出現商店簡介。
看有沒有要改善讀取中的畫面呢？

**Comment by peichingliao** [comment]
沒有再出現了
