### ISSUE TITLE
[Android app]背景移除app，點訂單通知進入app，再點左上角back，則閃過白畫面後，直接離開app

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#850]
[Scenario]
0. Version v1.1.1434 / Android app
1. 店主背景移除app
2. 收到新訂單，直接點訂單通知，進入app
3. 成功進入"收件訂單"的畫面，點左上角Back

[Result] 閃過白畫面後，直接離開app

[Expected Result] 回到上一層畫面：消費紀錄

**Comment by gameflierHao** [comment]
在新版 andoird app 1.1.5 上面
左上角Back將會回到 Tagfans 首頁畫面

**Comment by Iris926** [comment]
[App version] debug_1.1.5
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
