### ISSUE TITLE
[消費紀錄][併單]併單時，選擇"訂單狀態不同的"訂單來併，卻會出現提示視窗；點"確定"後還是有合併成功

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#851]
[Scenario]
0. Version v1.1.1434
　確認要併單的訂單，都在同一頁 & 要併單的訂單狀態不同
![image](https://cloud.githubusercontent.com/assets/22789907/19714635/5e234ac4-9b82-11e6-9ecc-95a3e02c670b.png)
　　　
1. 點擊客人姓名A，filter出A的所有訂單
![image](https://cloud.githubusercontent.com/assets/22789907/19714646/70a51970-9b82-11e6-9362-c46b3200f6ea.png)
　　　
2. 點選"我要併單"，將這兩張訂單狀態不同的單做合併=>跳出提示視窗(NG)
![image](https://cloud.githubusercontent.com/assets/22789907/19714357/0eafd068-9b80-11e6-962f-19b0e50b747c.png)
　　　
[Expected Result] 不應跳出提示視窗，訂單應直接合併成功

**Comment by cyen1121** [comment]
bn已修正
因為訂單的變化執行了gotNoteUpdate所以顯示跳出錯誤的視窗

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed (訂單狀態不同時，會直接套用主單的狀態)
