### ISSUE TITLE
[消費紀錄][併單]將已併單的訂單，再併單一次，則第一次併單的副單的商品狀態，會被清空

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#852]
[Scenario]
0. Version v1.1.1434
1. 老闆至收件訂單頁面，先執行一次併單
![image](https://cloud.githubusercontent.com/assets/22789907/19714780/6573b4ca-9b83-11e6-8b89-903449e0cbdc.png)
　　　
2. 老闆再次將步驟1的併單，跟其他訂單再合併一次
![image](https://cloud.githubusercontent.com/assets/22789907/19714803/86fc8590-9b83-11e6-9233-59bf32b8fea7.png)
　　　
[Result] 
1. 步驟1的併單，副單的商品狀態都被清空(展開訂單也一樣是被清空狀態)
2. 主單 & 步驟2的副單，商品狀態顯示正常
![image](https://cloud.githubusercontent.com/assets/22789907/19714880/15eb8d96-9b84-11e6-9d9a-d794240eb3c8.png)
![image](https://cloud.githubusercontent.com/assets/22789907/19714857/eba36ed2-9b83-11e6-9c24-ba67c14618a9.png)

**Comment by cyen1121** [comment]
bn已修正

因為在合併單中的檢查沒有把比較的名稱加入source id一起比

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
