### ISSUE TITLE
[消費紀錄][併單]將有單一商品狀態的訂單合併，再拆開，則部分商品狀態會被清空

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#853]
[Scenario]
1. 將欲合併訂單，設定好每一項商品的商品狀態 & 訂單狀態
![image](https://cloud.githubusercontent.com/assets/22789907/19715745/e0f6da2c-9b89-11e6-8d04-725693bba616.png)
　　　
2. 合併訂單
![image](https://cloud.githubusercontent.com/assets/22789907/19715755/f7fe86e8-9b89-11e6-8078-9bf0fbf3b573.png)
　　　
3. 拆單

[Result] 尚未找到明確規則，但每次併單拆單後，都有部分單一商品狀態被清空
![image](https://cloud.githubusercontent.com/assets/22789907/19716557/0289430a-9b8f-11e6-98cb-ee2dfd3ef472.png)

**Comment by cyen1121** [comment]
store已更新，修改貨品狀態時沒有sid也能正確判斷出是哪一個貨品的
並在新的修改貨品狀態都是sid+name+price

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
