### ISSUE TITLE
[VIP價格][芳誼筱云] VIP客人從自己的訂單紀錄點回商店(重複2次)，則VIP價格會變回原價

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#854]
[Scenario]
0. 客人有下單VIP商品的紀錄
1. 客人點開 我的訂單，從任一商品點 < ，再點商店名稱，查看商品
2. 點左上角 Back，回到我的訂單
3. 再重複一次步驟1，查看商品

[Result] 客人會看到所有價格都變成原價

**Comment by cmacma7** [comment]
Fixed, problem cause by global.groupinfo is not ready before getuservip. and global.groupinfo is not ready because of global.gid not filled in if _storeId in place instead of o=

**Comment by cmacma7** [comment]
svn 1461 fixed.

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
