### ISSUE TITLE
[金音獎][螢光棒]在網頁上不應該左右撐開

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#855]
[Result]
![image](https://cloud.githubusercontent.com/assets/22789907/19721057/437ca01e-9ba3-11e6-8492-b203a6dc2ff6.png)

**Comment by gameflierHao** [comment]
store version : 1.1.1439

參考網址 : http://store.tagfans.com/#page_join?o=3305&id=18959&viewType=station

Revision: 1445
Author: zhanghaowu
Date: 2016年10月27日 上午 09:52:40
Message:
[金音獎][螢光棒]在網頁上不應該左右撐開#855

## 解決方式 : 當螢幕寬度大於800px時 顯示原圖大小

Added : /nodejs/bn/widgets/Widget/Simple Widgets/GlowSticks.js

**Comment by Iris926** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/22789907/19751963/0a42f5bc-9c2c-11e6-8043-bf3e9316a1fb.png)
