### ISSUE TITLE
[Android app]剛下載完測試版app，第一次開啟，會顯示錯誤訊息"Wrong User Email or Password"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#857]
[Scenario]
0. Android手機安裝測試版apk
1. 安裝完成，開啟app

[Result]
1. 畫面顯示"Wrong User Email or Password"
2. 在此訊息點"確定"，則畫面一直停留在tagfans歡迎畫面
![image](https://cloud.githubusercontent.com/assets/22789907/19762705/929489c6-9c6d-11e6-824a-060273ac9dfd.png)

**Comment by cmacma7** [comment]
Same as clear browser cache

**Comment by cmacma7** [comment]
Nop, clear browser cache cannot reproduce.... and delete APP from android then re-install still cannot reproduce.... why?

**Comment by cmacma7** [comment]
The user name and password is correct as the printed out, but login fail.... Should be timing issue from create the anonymous account to login again.

**Comment by cmacma7** [comment]
Try fixed. When it is new user and auth fail, just sleep 500ms then reload. Fixed on BN.

**Comment by Iris926** [comment]
[App version] Tagfans-debug-1.1.5
[Result] 沒有再發生錯誤現象
