### ISSUE TITLE
In Summary page, when user input a keyword to filter, there is no way to clear the filter at the top.

### ISSUE THREAD

**Issue by cmacma7** [cmacma7/bn#858]
The only way to clear the keyword filter is go to keyword field and clear manually. The keyword suppose to become a filter button at top just like name/item name filter.

**Comment by cyen1121** [comment]
bn已修正

加入可以直接去掉搜尋條件的地方

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed (過濾條件會變成可移除的btn，列在統計總表上方)
![image](https://cloud.githubusercontent.com/assets/22789907/20421058/a135e69c-ad9c-11e6-8669-c313a22542a3.png)
