### ISSUE TITLE
設定-好友 的bug

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#86]
![screenshot_2015-02-11-13-42-55](https://cloud.githubusercontent.com/assets/10726049/6142585/29065148-b1f4-11e4-9547-2720a8da4a34.png)

**Comment by peichingliao** [comment]
1. 左下新增好友的icon與按鈕顏色
2. 新增好友->跳出popup->直接按確定，出現空白好友
3. 匯入facebook好友-> 出現2個david
4. 把所有好友都刪掉 (誤刪)，無處可重新匯入fb好友

以上4個bug

**Comment by cmacma7** [comment]
Fix 1, 2, 3.
Number 3 is there are actually two David, one is google account and one is Facebook account

**Comment by cmacma7** [comment]
item 4. Fixed by support multiple account using the same facebook ID. And support reload the facebook friends.
