### ISSUE TITLE
[統計總結] 貨品狀態、付款狀態 表頭需顯示下拉選單

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#860]
1. 貨品狀態表頭需顯示下拉選單
2. 付款狀態表頭需顯示下拉選單 (選項為設定進去的iname)

**Comment by cyen1121** [comment]
bn已修正

加入貨品狀態和付款狀態的下拉箭頭

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
