### ISSUE TITLE
[團購widget][關閉運費] 在系統新增商品再發佈到FB，則仍顯示運費資訊

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#863]
[Scenario]
0. 商品網址 http://store.tagfans.com/node/fb.html?noteId=984842_21269_3722
　　　
1. 老闆在系統裡先新增任一團購widget：**關閉運費**![image](https://cloud.githubusercontent.com/assets/22789907/19838494/6289fca2-9f0b-11e6-973c-4b4fe7930da2.png)
　　　
2. 發佈到FB，並至FB查看該商品
　　　

[Result] 發佈到FB，仍可看到運費資訊
![image](https://cloud.githubusercontent.com/assets/22789907/19838509/97f24a5c-9f0b-11e6-9d3d-95c46cb93d61.png)

**Comment by peichingliao** [comment]
r.1474已更新
bn已更新

**Comment by Iris926** [comment]
[Store version] v1.1.1474
[Result] Fixed(一般團購&VIP價格widget)
