### ISSUE TITLE
開啟單一物品檢視訂單時，開啟的是寄件備份而不是收件

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#864]
1. 放置widget的分享連結(包含fb/note.html?xxxxx)到google document的excel
2. 再從excel導去tagfans的單一商品連結，會先跳轉至google的外部網站檢查
3. 在單一物品的狀態底下，storyBoard.itemArray[0].isAdmin會在網頁開啟時就被設定為false
4. 點選查詢此商品記錄時會判斷isAdmin(obj)(isAdmin會去判斷isOwner(obj)，isOwner會去看itemData.isAdmin)，因為isAdmin一開始就錯了，所以就開起了寄件備份而不是收件

此問題在慢的電腦上百分之百命中

**Comment by cmacma7** [comment]
It is caused by model_favoriteList is fetched after the isAdmin() is called. Fixed by mobile.initialize() is called inside model_favoriteList complete callback.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
1. 老闆從google excel裡，點開商品連結
2. 點 查詢本商品購買紀錄
3. 看到的是"收件"
