### ISSUE TITLE
orderform只有資訊欄位的時候不需要有確定的按鈕

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#865]
在訂單orderform只有資訊欄位的時候不需要有確定的按鈕

**Comment by cmacma7** [comment]
Fixed by popupForm(rootDiv, formContext, callback, forcePopup, sendButtonText), set sendButtonText to false will hide the send button.
Transfer to David to complete.

**Comment by cyen1121** [comment]
bn上已修正
存文字或是存圖片都不會有確定按鈕

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
