### ISSUE TITLE
[十一街]從店家首頁點擊右上角的"分享"，建議將popup內的小人圖案移除

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#866]
[Scnario]
0. 店家網址 http://store.tagfans.com/index.html#page_station?o=2907
1. 進入店家首頁，點擊右上角的"分享"
2. 查看popup內文

[Result] popup內的小人圖案，目前無明確功能，建議先移除
[註] 三合院也有相同情形，建議一併移除
![image](https://cloud.githubusercontent.com/assets/22789907/19878555/16f53d0e-a025-11e6-9e6b-0bbbe0fd1a5a.png)

**Comment by cmacma7** [comment]
OK, will remove this one.
