### ISSUE TITLE
[刪訂單] 刪除併單後的主單，副單也應該被刪除

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#877]
1. 刪除此頁面所有訂單
2. 直接刪主單

兩個都應該要可以刪掉副單
如果副單是scan的，也要可以刪掉修正前的舊訂單

**Comment by cyen1121** [comment]
BN上訂單加入getChildNotes提供相關index array
 function getChildNotes(context){}

**Comment by cyen1121** [comment]
bn已修正
在統計頁面刪除全部訂單時，也會一併把副單刪除

透過getChildNotes取得相關副單

**Comment by peichingliao** [comment]
今天客戶反應，從統計總結批次刪除訂單
副單仍然存在

**Comment by cyen1121** [comment]
deleteAllMails 會去檢查是否在currentArray裡面，如果沒有則不會刪除，導致刪除不完整
