### ISSUE TITLE
[店內點餐][銅盤] 結帳單明細中有遺漏點餐細項

### ISSUE THREAD

**Issue by huangVic** [cmacma7/bn#881]
[Scenario]
1. 選擇BBQ豬 or BBQ雞 or 韓式鬼椒豬 or 黑蒜牛 (不選口味情況下)
2. 點餐明細畫面送出點菜單
3. 前往帳單明細(Bill) 看不到前述這幾樣點過的商品

![1](https://cloud.githubusercontent.com/assets/5910437/19919615/ec4fe0be-a10e-11e6-9c5d-625ac4aa5e44.png)

**Comment by gameflierHao** [comment]
已修正
測試網址 : https://service.tagfans.com/public/jqm.html#page_station?o=344

重製銅盤測試POS SERVER資料
更新傳送餐點語法

Revision: 1469
Author: zhanghaowu
Date: 2016年11月2日 下午 05:57:40
Message:
店內點餐: 點餐時,加入口味資料

## 並修正: [店內點餐][銅盤] 結帳單明細中有遺漏點餐細項 #881

Modified : /nodejs/bn/POS/pos_porting.js

**Comment by huangVic** [comment]
結帳單明細已修正。
經連入銅盤POS 系統確認，平版拿到結帳單明細與POS系統中相同。
