### ISSUE TITLE
[店內點餐] 需要一個點餐APP 可以讓店家設定 POS IP

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#886]
如題
可以讓店家自由輸入店內點餐系統ip
並開啟點餐系統

**Comment by gameflierHao** [comment]
點餐系統開啟APP

http://service.tagfans.com/public/order/

提供以下設定 : 

server ip 
port
store id 
page id

**Comment by Iris926** [comment]
已驗證無誤。
