### ISSUE TITLE
[店家首頁][我的頁面] 點擊EDIT會直接進入頁面，未開啟編輯功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#888]
[Scenario]
1. 老闆進入商店首頁，點擊下方的"點擊以顯示 我的頁面"
2. 點擊任一頁面的"Edit"

[Result] 直接進入該頁面，未開啟編輯功能
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19953652/6bb851b4-a1ab-11e6-9653-3374ad52b4a1.png)

**Comment by cmacma7** [comment]
The Edit icon is telling the user that this station you can edit, not press to edit the page. The edit icon onlly tell user you can edit.

**Comment by Iris926** [comment]
[建議]
1. 當user點了此處的"Edit"，可以直接導至 "管理"頁面
2. 此處的頁面入口失效，不要讓user可以點進頁面(要點的話，上方就已經可以點了)
