### ISSUE TITLE
[商店街][附近熱門] 找不到位置，無法列出附近商家

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#891]
[Scenario]
1. 進入tagfans/商店街/附近熱門

[Result] 找不到位置，無法列出附近商家
![image](https://cloud.githubusercontent.com/assets/22789907/19955704/c804ae1e-a1be-11e6-94bd-b9b7e3678f12.png)

**Comment by peichingliao** [comment]
getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by cyen1121** [comment]
這部分需要HTTPS才能取得位置資訊，這部分轉給VIC作銜接使用新的架構

**Comment by huangVic** [comment]
預計將 Cliotu 功能整合進 Tagfans

**Comment by peichingliao** [comment]
這部分無解決方法
只能使用https網址
