### ISSUE TITLE
[通知][收件夾]新增"系統通知"、"交易通知"，移除"所有收到的郵件"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#893]
[Scenario]
1. 進入商店街/訊息 or 進入任一商店/消費紀錄
2. 進入"通知"(原本叫做收件夾)

[Expected Result]
1. 新增"系統通知"
2. 將"交易通知"從右上角移進來
3. 移除"所有收到的郵件"
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19960198/4072d66a-a1e6-11e6-86cd-d35fa8d8c900.png)

**Comment by cmacma7** [comment]
Fixed in version 1486

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
1. 交易通知保留在右上角、list中再多增加一次 交易通知 進來
2. "所有收到的郵件"保留
