### ISSUE TITLE
[店內點餐][銅盤] 口味項目濾掉空字串的部分

### ISSUE THREAD

**Issue by huangVic** [cmacma7/bn#894]
POSMenu 裡面的口味項目有許多空字串, 請 @gameflierHao 過濾一下這些用不到的選項

![default](https://cloud.githubusercontent.com/assets/5910437/19960934/dcdcf3ce-a1ea-11e6-890e-52e7dcb8eac0.png)

**Comment by gameflierHao** [comment]
已利用trim()去排除空字符口味

測試網址 : https://service.tagfans.com/public/jqm.html#page_station?o=344

Revision: 1477
Author: zhanghaowu
Date: 2016年11月3日 下午 06:31:55
Message:

## 新增口味資料與行動模式

Modified : /nodejs/bn/widgets/Modules/POSMenu.js

**Comment by huangVic** [comment]
經測試後，已修正此問題
