### ISSUE TITLE
[取號報號][三合院] 老闆將目前報號值輸入文字，則造成顯示錯誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#898]
[Scenario]

0. 三合院老闆登入
1. 進入"現場報號"
2. 點擊任一報號顯示區域，直接輸入文字，按"確定"
　　　

[Result] 造成號碼顯示錯誤(附圖)
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/19992511/86d0447e-a279-11e6-9a7f-8763e350f8af.png)
![image](https://cloud.githubusercontent.com/assets/22789907/19992539/c7daeae6-a279-11e6-82aa-d1e845c8ad6f.png)
![image](https://cloud.githubusercontent.com/assets/22789907/19992556/e492d86a-a279-11e6-9dfd-7dec9e172f1d.png)
![image](https://cloud.githubusercontent.com/assets/22789907/19992553/ddfadf52-a279-11e6-818f-f30774834106.png)

**Comment by cmacma7** [comment]
Need to check whether input is a number, and number >0. Otherwise number becomes 0.

**Comment by cyen1121** [comment]
確認是否為數字，不是的話會提示老闆做修改

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
1. 純數字OK
2. 字串開頭為數字，則自動擷取數字部分
3. 一般字串都會跳出提示視窗，要求重新填寫
