### ISSUE TITLE
[取號報號][三合院] 老闆欲設定"候位取號"的號碼，顯示的號碼與輸入框的值不sync

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#900]
[Scenario]
1. 老闆登入，進入"候位取號"的頁面
2. 點擊任一欄位，會有popup讓老闆設定下一取號號碼

[Result] popup內的數字，跟欄位顯示的數字不一樣
![image](https://cloud.githubusercontent.com/assets/22789907/19993184/ba6dbe24-a27e-11e6-991e-93383bca4c33.png)

**Comment by cyen1121** [comment]
以修正   會依照點選的數字欄位做顯示

**Comment by Iris926** [comment]
[Store version] v1.1.1465
[Result] Fixed
