### ISSUE TITLE
[取號報號][三合院] 客人誤輸入>30的人數，造成點選"取號"無作用

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#901]
[Scenario]
1. 客人至取號機，輸入電話與人數
2. 誤輸入人數為55
3. 按"取號"

[Result] 無作用
[Expected Result] 建議要有提示視窗"已超過可訂位人數" or "請重新輸入訂位人數"
![image](https://cloud.githubusercontent.com/assets/22789907/19994016/1508dba6-a285-11e6-927a-a7fde80eeb3f.png)

**Comment by cmacma7** [comment]
Need to popup window to let user know the number exceed maximum

**Comment by cyen1121** [comment]
bn store已修正 會跳出警告視窗已超過最大訂位人數

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result] Fixed (會popup "已超過可訂位人數")
