### ISSUE TITLE
[取號報號][三合院][建議] 取號時，要檢查客人的電話號碼是否為09開頭 & 共有10碼

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#902]
[Scenario]
1. 客人輸入電話號碼&人數
2. 電話號碼格式錯誤

[Expected Result] 建議要有提示視窗"請確認電話號碼是否正確"

**Comment by cyen1121** [comment]
bn store已修正只能輸入純數字的電話號碼

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result] Fixed(一定要輸入10位數的手機號碼)
