### ISSUE TITLE
[取號報號][三合院] 候位取號的輸入欄位 & 已取到的號碼，需要適度放大

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#905]
[Scenario]
1. 客人到候位取號頁面，輸入電話號碼 & 人數
2. 客人完成取號

[Expected Result]
1. 輸入電話號碼 & 人數的欄位，需要放大
2. "取號"的btn，需要放大
3. 拿到的號碼紙，上方的"最新一筆"要移除
4. 頁面下方顯示的"下一號"，老闆可以看到、客人不用看到
5. 取到號碼後，整張號碼紙需要放大；號碼相對於整張號碼紙的比例，也需要放大

**Comment by cyen1121** [comment]
bn store修正

字體放大兩倍，號碼原先使用24px改成40px

下方號碼隱藏給老闆看而已

最新一筆字樣移除

**Comment by Iris926** [comment]
[Store version] v1.1.1486
[Result] Fixed
[註]    取號畫面會出一個"小鍵盤"的版本，之後會再驗證( #931 )
