### ISSUE TITLE
[報號取號][三合院] 每次取號完 30秒 後，畫面自動回到輸入電話號碼&人數

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#906]
[Scenario]
1. A客人取號，畫面已顯示A拿到的號碼牌
2. B客人要取號，需要先點"確認受理號碼/下一位"btn，才能回到輸入電話號碼&人數的頁面

[Expected Result] A客人取號 30秒 後，畫面自動回到 輸入電話號碼&人數，B客人即可直接輸入取號

**Comment by cyen1121** [comment]
bn store 修正

 30秒後自動返回取號介面關閉單據模式

**Comment by Iris926** [comment]
[Store version] v1.1.1486
[Result] Fixed (下一位客人可以自己點"確認受理號碼/下一位"，or 30秒後會自動回到取號頁面)
