### ISSUE TITLE
[報號取號][三合院] 使用手機進入"現場報號"頁面，則上方三合院LOGO部分，不易滑動

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#907]
[Scenario]
1. 使用手機進入三合院的店家畫面/現場報號
2. 滑動頁面 or 查詢後再滑動頁面

[Result] 
1. 當下方報號區已經滑到底了，還是無法將三合院LOGO部分滑動(需要直接去滑三合院LOGO部分，才能滑動)
2. 當下方報號區已經滑到底了，部分報號顯示會被截斷

**Comment by cyen1121** [comment]
bn store已修正 css設定造成無法滑動跟高度限制修正

**Comment by Iris926** [comment]
[Store version] v1.1.1486
[Result] Fixed
