### ISSUE TITLE
[報號取號][三合院] 使用pad(豎屏)，進入"現場報號"畫面，，則報號區跑版

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#908]
[Scenario]
1. 客人使用pad(豎屏)，進入"現場報號"頁面

[Result] 報號區跑版
![image](https://cloud.githubusercontent.com/assets/22789907/19998395/8d936e20-a2a7-11e6-8833-9ecfa9cb7e87.png)

![image](https://cloud.githubusercontent.com/assets/22789907/19998400/923dc33a-a2a7-11e6-9182-a7368cfee839.png)

**Comment by cyen1121** [comment]
bn store已修正

將ＵＩ轉換改成968px

低於968則轉換成流水式閱讀
高於968則用大版顯示

**Comment by Iris926** [comment]
[test site] store
[Result] Fixed
