### ISSUE TITLE
[報號取號][三合院] 建議查詢取號的結果，人數的地方不要只顯示數字

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#909]
[Scenario]
1. 客人完成取號
![image](https://cloud.githubusercontent.com/assets/22789907/19998600/a5af4aaa-a2a8-11e6-9331-85f8fcd252a8.png)
　　　
2. 客人至"現場報號"頁面，輸入電話號碼，查詢取號紀錄
![image](https://cloud.githubusercontent.com/assets/22789907/19998716/4f6bb38a-a2a9-11e6-80be-a10c4414b79c.png)
　　　
**[Expected Result] 建議在客人的查詢紀錄裡，人數的地方也要顯示"人數：5"，or "5位"**

**Comment by cyen1121** [comment]
bn store已修正補上人數字樣

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result] Fixed
