### ISSUE TITLE
《分享頁面》的bug

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#91]
![screenshots_2015-02-11-14-18-19](https://cloud.githubusercontent.com/assets/10726049/6142833/3bcf64c2-b1f9-11e4-864f-7eeb04774aab.png)
![screenshots_2015-02-11-14-19-05](https://cloud.githubusercontent.com/assets/10726049/6142834/45f035f8-b1f9-11e4-8e31-e7ea7503757a.png)

**Comment by peichingliao** [comment]
1. 左下角不應有 《新增好友》
2. 選擇郵寄給朋友 -> 沒有顯示我的朋友
3. 此畫面所有按鈕都失效，手機的back按了也沒反應

**Comment by cmacma7** [comment]
Fixed the UI, and fix item 3. item 2 seems still exist.

**Comment by peichingliao** [comment]
此畫面已不存在
