### ISSUE TITLE
[消費紀錄][併單][李味鎂] 併單後，部分商品狀態顯示錯誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#910]
[Scenario]
1. 老闆至 消費紀錄/收件訂單/統計/統計總結
2. 管理/修改.刪除.併單
3. 欲合併的訂單中，有些單一商品狀態修改2次以上 & 是較久以前的訂單(約2~3周前)
4. 進行併單

[Result] 併單後，單一商品狀態並非最新一次的紀錄(跳回初始值)

[註]從line群組回報，有影片可查看操作過程

**Comment by cyen1121** [comment]
bn已修正，以前在合併單會把舊的貨品狀態方式(name+price)當作繼承帶入主單
現在修改成都統一用新的格式(sid+name+price)

**Comment by Iris926** [comment]
[Test Site] bn
[Result] 尚有相同問題

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed (併單時若讀到舊的商品狀態方式，則須繼續跑完loop；若讀到新的商品狀態方式，則loop中止)
