### ISSUE TITLE
[報號取號][三合院] 老闆查看預約訂位的訂單紀錄時，修改狀態的icon點擊無作用

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#911]
[Scenario]
1. 老闆進入"候位取號"頁面
2. 點 查詢號碼紀錄/統計/統計總結
3. 在任一筆訂單，點修改狀態的icon

[Result] 無作用
![image](https://cloud.githubusercontent.com/assets/22789907/20001179/f2544812-a2b5-11e6-805f-5bc6abbcc846.png)

**Comment by cyen1121** [comment]
bn已修正
點選問題修正，點了會展開狀態做選擇圖示必須要有鉛筆

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed

---

[Test Site] store
[Version] v1.1.1498
[Result] Fixed
