### ISSUE TITLE
[取號報號][三合院] 老闆查看預約取號的紀錄時，建議點擊"備註"欄做filter

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#912]
[Scenario]
1. 老闆進入"候位取號"頁面
2. 點 查詢號碼紀錄/統計/統計總結
3. 點備註欄的任一內容，ex. 3-4人

[Expected Result] 建議可以過濾出所有 3-4人 的取號紀錄
![image](https://cloud.githubusercontent.com/assets/22789907/20001364/c7e502fa-a2b6-11e6-9247-98c280e82d1e.png)

**Comment by cyen1121** [comment]
bn 修正

可以過濾備註

需要同時驗證訂單得備註是否都正確

**Comment by Iris926** [comment]
[Test site] bn
[Result] Fixed (both 狀態 & 備註 都可以過濾)

---

[Test Site] store
[Version] v1.1.1498
[Result] Fixed (both 狀態 & 備註 都可以過濾)
