### ISSUE TITLE
[取號報號][三合院] 建議修改查詢訂位號碼欄位裡的預設文字

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#914]
[Scenario]
1. 進入 三合院/現場報號
2. 查詢訂位號碼

[目前行為] 該欄位的預設文字為"透過電話，查詢你的號碼"

[建議改成] "透過電話，查詢你的**候位**號碼"
![image](https://cloud.githubusercontent.com/assets/22789907/20043701/0f43aff4-a4cc-11e6-8b6f-37d887c243a3.png)

**Comment by cyen1121** [comment]
BN store已修正

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result] Fixed
