### ISSUE TITLE
[取號報號][三合院] 老闆or客人 點擊取號紀錄裡的電話號碼，帶起手機的撥號功能後，應可直接帶入該電話號碼

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#915]
[Scenario]
0. 使用手機browser or app
1. 老闆進入"候位取號"頁面
2. 點 查詢號碼紀錄/統計/統計總結
3. 點 任一電話連結

[Result] 會直接喚起手機的電話撥打功能
![image](https://cloud.githubusercontent.com/assets/22789907/20044030/d5bf7688-a4cf-11e6-97ac-434caf6dd06f.png)
![image](https://cloud.githubusercontent.com/assets/22789907/20044031/dcfbd1d0-a4cf-11e6-836b-89346abf74ed.png)

[Expected Result] 喚醒電話功能之外，還可以將剛剛點的電話號碼，直接帶入(將附圖中的999999直接帶入)

**Comment by cyen1121** [comment]
可以直接帶起電話

**Comment by Iris926** [comment]
[Test site] bn
[Result] Fixed (在預約訂位、統計總結，都可以成功帶入電話)

---

[Test Site] store
[Version] v1.1.1498
[Result] Fixed
