### ISSUE TITLE
[取號報號][三合院][建議] 將客人取號的號碼，統一叫做"候位號碼"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#917]
[Scenario]
1. 客人至候位取號頁面/取號 =>會看到"受理號碼"
![image](https://cloud.githubusercontent.com/assets/22789907/20044456/2392c00a-a4d4-11e6-8d92-d3ad1bba0d54.png)
　　　
2. 客人至現場報號頁面/查詢 =>會看到"受理號碼"
![image](https://cloud.githubusercontent.com/assets/22789907/20044463/30345b7a-a4d4-11e6-9b0a-fcad9c1486b4.png)
　　　
3. 老闆/客人至訂位列表頁面 =>會看到"訂單號碼"
![image](https://cloud.githubusercontent.com/assets/22789907/20044470/38ca3aac-a4d4-11e6-95f1-fc26f873942a.png)
　　　
**[建議] 統一叫做"候位號碼"**

**Comment by cyen1121** [comment]
bn store修正
報取號統一文字為 後位號碼

但是統計表單還是訂位號碼因為與訂位使用共通表格，所以不作變動，這頁也主要給老闆做使用不會造成客人混淆

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result]
1. 候位取號：已取號，下方的btn的字樣也需要改
![image](https://cloud.githubusercontent.com/assets/22789907/20048585/ad117a64-a4f8-11e6-93d2-b133b6c62f60.png)
　　　
2. 現場報號 OK
3. 訂單列表的部分不做更動 OK

**Comment by cyen1121** [comment]
bn store已修正

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Result] Fixed
