### ISSUE TITLE
[取號報號][三合院]  未登入的客人至"我的預約訂位"查看，在訂單列表會多出一個空白欄位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#918]
[Scenario]
0. 客人未登入
1. 客人至 候位取號/輸入電話及人數/完成取號
2. 客人至 消費紀錄/我的預約訂位/統計/統計總結

[Result] 會看到一個空白的欄位
![image](https://cloud.githubusercontent.com/assets/22789907/20044701/f58b5896-a4d5-11e6-8b3a-12a3e3f65929.png)

**Comment by cyen1121** [comment]
如果不能改會顯示tagfans logo

**Comment by cyen1121** [comment]
bn修正

**Comment by Iris926** [comment]
[Test Site] bn
[Result] Fixed (both 預約訂位 & 外帶訂單)
![image](https://cloud.githubusercontent.com/assets/22789907/20125927/1ae0c616-a66c-11e6-81fb-6480cdeedc98.png)
　　　
![image](https://cloud.githubusercontent.com/assets/22789907/20125968/60b24732-a66c-11e6-8936-859c13d98b31.png)

---

[Test Site] store
[Version] v1.1.1498
[Result] Fixed (both 預約訂位 & 外帶訂單)
