### ISSUE TITLE
[取號報號][三合院] firefox輸入管理者密碼，卻無法成功進入候位取號

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#919]
[Scenario]
0. 使用firefox開啟三合院首頁
1. 進入 候位取號/點擊"請洽管理者/服務人員"，並輸入密碼/enter

[Result] 無作用

**Comment by cyen1121** [comment]
bn store已修正
抓取event不正確
firefox不支援直接抓取window.event的參數，必須onclick時帶入

**Comment by Iris926** [comment]
[Version] v1.1.1486
[Browser] Firefox
[Result] Fixed
