### ISSUE TITLE
編輯tag的《開啟/關閉留言》會造成順序改變

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#92]
設定為新tag在上方

![screenshots_2015-02-11-14-44-11](https://cloud.githubusercontent.com/assets/10726049/6143066/e3b5c75a-b1fc-11e4-8bc1-c99ec50884cf.png)

原本沒有留言的tag在最上方
![screenshot_2015-02-11-14-43-04](https://cloud.githubusercontent.com/assets/10726049/6143081/1e38dab6-b1fd-11e4-9daa-6c6e0a61bc53.png)

開啟留言功能後，跑到第二則
![screenshot_2015-02-11-14-43-46](https://cloud.githubusercontent.com/assets/10726049/6143095/542e0bdc-b1fd-11e4-9874-522c972da18c.png)

**Comment by cmacma7** [comment]
Tried, but cannot reproduce. Any specific procedure?
I create a widget at top, and initially comment off. Then turn on the comment, the widget still at top.
Test at bn.tagfans.com
