### ISSUE TITLE
[取號報號][三合院] 取號時，建議阻擋 +- . e這四個符號，不要讓user輸入

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#920]
[Scenario]
1. 客人進入候位取號的頁面
2. 輸入 電話號碼 & 人數

[Result] 大部分的符號/字母都無法輸入，但是還可以輸入 + - . e

[建議] 這四個符號/字母 也不要讓user有機會輸入

**Comment by cyen1121** [comment]
使用自訂鍵盤已無此問題

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1498
[Result] Fixed
