### ISSUE TITLE
[取號報號][三合院] 老闆使用app進候位取號頁面，則"查詢號碼紀錄"btn & < btn，點選範圍重疊

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#924]
[Scenario]
1. 老闆使用app登入
2. 進入 候位取號 頁面
3. 點 查詢號碼紀錄 btn

[Result] 很容易點出<的MENU
![image](https://cloud.githubusercontent.com/assets/22789907/20084140/7dcd3bb4-a59b-11e6-8bc4-49ceca5004aa.png)
![image](https://cloud.githubusercontent.com/assets/22789907/20084212/c8ea3872-a59b-11e6-81d4-8f372f2243a1.png)

**Comment by cyen1121** [comment]
bn store修正
將整體視覺往下移45px(padding-top:45px)

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1498
[Result] Fixed
