### ISSUE TITLE
[店內點餐][銅盤]填寫客戶滿意度調查表，點擊需要輸入文字的欄位，則畫面自動捲到"手機號碼"的欄位

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#926]
[Scenario]
1. 填寫客戶滿意度調查表
2. 點擊"其他建議" or "姓名" 的欄位

[Result] 畫面自動捲到"手機號碼"的欄位
![image](https://cloud.githubusercontent.com/assets/22789907/20088597/4675c908-a5bc-11e6-8d5c-5d9de46b598c.png)

**Comment by gameflierHao** [comment]
相關 TO 
[店內點餐][問券調查] 鍵盤輸入導致INPUT位置被推開 #903

**Comment by gameflierHao** [comment]
Fixed in : http://store.tagfans.com/
Version : 1.1.1522

參考測試位置 : http://store.tagfans.com/#page_join?o=1145&id=9173&viewType=station

**Comment by Iris926** [comment]
已驗證無誤。
