### ISSUE TITLE
[店內點餐][銅盤][mobile] 點餐後輸入未開桌桌號，建議保留點餐紀錄，可以直接再次輸入桌號

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#927]
[Scenario]
　0. 點餐平板的設備欄位，設定為 mobile
1. 服務人員進行點餐/送出/輸入錯誤or未開桌的桌號/確認
![image](https://cloud.githubusercontent.com/assets/22789907/20089455/0c5530a0-a5c2-11e6-8afc-836ebe47a2fd.png)

2. popup提示訊息/關閉　
![image](https://cloud.githubusercontent.com/assets/22789907/20089467/15853e4a-a5c2-11e6-9e5b-23b23f048eca.png)
　　　

[Result] 點餐紀錄自動清除

[建議] 保留點餐紀錄，服務人員可以再次輸入正確桌號；避免重複點餐，造成客人觀感不佳

**Comment by huangVic** [comment]
當成功送出點餐單時才會清空購物車內容

**Comment by Iris926** [comment]
已驗證無誤。
