### ISSUE TITLE
[店內點餐][銅盤] 尚未點餐就點擊"送出"，建議直接以popup顯示提示訊息

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#929]
[Scenario]
1. 客人完全沒有點餐
2. 點"送出"

[Result]
1. 進入"點菜單"畫面
2. 顯示提示訊息：您尚未點餐唷。。。
3. 沒有"送出點菜單"的btn
![image](https://cloud.githubusercontent.com/assets/22789907/20091718/33d110f6-a5cf-11e6-9ca9-a52f43a00b56.png)

[建議] 直接在MENU頁就popup提示訊息：
1. 過10秒讓popup自動關閉，客人可以繼續從菜單點餐
2. popup裡的btn顯示"繼續點餐"，點了btn後，客人可以繼續從菜單點餐

**Comment by huangVic** [comment]
點"送出"時新增判斷購物車裡面是否有資料, 若沒有就跳出 popup訊息提示

![default](https://cloud.githubusercontent.com/assets/5910437/20146519/291df79e-a6df-11e6-86a2-2366fb2c3e2d.png)

**Comment by huangVic** [comment]
因此方式要是沒有點選任何品項將無法進入帳單查看, 故先取消此功能

**Comment by Iris926** [comment]
此功能暫不做更動，維持原行為。
