### ISSUE TITLE
[店內點餐][銅盤] 進入點菜單後，將餐點全部刪光，其行為應與"未點餐就點擊送出"一致

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#930]
[Scenario]
1. 客人開始點餐
2. 點"送出"，進入點菜單畫面
3. 將點菜單裡的餐點全部刪除清空

[Result]
1. 沒有顯示提示訊息"您尚未點餐唷。。。"
2. 下方的"送出點菜單"btn還在
3. 如果點擊"送出點菜單"，則會popup"喔喔...您尚未點餐，請先進行點餐作業！"
![image](https://cloud.githubusercontent.com/assets/22789907/20091873/fc5f5c94-a5cf-11e6-96c9-ed52ddab993d.png)
　　　

**[建議] 行為應與 #929 一致**

**Comment by huangVic** [comment]
行為改為與 #929 一致

**Comment by Iris926** [comment]
已驗證無誤。
