### ISSUE TITLE
[取號報號][三合院] 候位取號介面，改成"有小鍵盤"的版本

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#931]
[Request]
1. 頁面直接顯示數字小鍵盤
2. 不須點擊input欄位，就可以直接輸入電話&人數
3. 老闆可以看到"下一號"的部分，版面也需要調整(附圖)
![image](https://cloud.githubusercontent.com/assets/22789907/20092573/dc923c02-a5d3-11e6-8f09-c6856d604bde.png)

**Comment by cyen1121** [comment]
已完成
已放到bn store
密碼輸入不提供鍵盤

電話和人數會有數字鍵盤
完全人性化自動對應欄位和完成

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1498
[Result] Fixed
