### ISSUE TITLE
db query當需要狀態key的時候只使用第一組key當參照組去拿，造成其他資料不完整

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#932]
問題
當訂單頁面比數較多還沒讀取完成就進入統計頁面，會造成部分資料只有訂單狀態出現，其他資料不完整

討論結果
在queryArrayPush時檢查進來的key是否都相同，不是的話就將指令發出，重新累積相同key的query

**Comment by cmacma7** [comment]
Need to check the keys in continue sequence, if the same, you can accumulate, otherwise send out right away.
