### ISSUE TITLE
[店內點餐][銅盤] 送出點菜單後，查看帳單，則帳單明細有誤

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#935]
[Scenario]
1. 客人點餐/送出點菜單
2. 客人點 送出/帳單明細icon

[Result] 帳單明細有誤：數量加總是對的，但是品項錯誤
![image](https://cloud.githubusercontent.com/assets/22789907/20162216/6c53a7da-a72e-11e6-80b2-e27db3bb9f85.png)
　　　
[註]POS機顯示正確
![image](https://cloud.githubusercontent.com/assets/22789907/20162248/abe0dd5a-a72e-11e6-81db-64c2c7a4eca6.png)

**Comment by huangVic** [comment]
因新品牌"北村" 無設定品項 itemcode 所以在做資料合併時會略過不處理。將改用 TypeNo & ItemName 的組合規則

**Comment by Iris926** [comment]
已驗證。
