### ISSUE TITLE
[店內點餐][銅盤] 用餐時間&提醒時間皆清空，開桌後不應計數用餐時間

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#936]
[Scenario]
1. 老闆進 點餐系統/編輯
2. 將 用餐時間 & 提醒時間 清空
![image](https://cloud.githubusercontent.com/assets/22789907/20162324/34556c3c-a72f-11e6-9e30-5cafd32cf97d.png)
　　　

[Result] 開桌後，畫面下方的用餐時間仍在計數
![image](https://cloud.githubusercontent.com/assets/22789907/20162343/661e1642-a72f-11e6-85f7-7a5a7d9519e9.png)

**Comment by huangVic** [comment]
當沒有填入"用餐時間"&"提醒時間" 將不會啟動計時功能, 及畫面上的計時也會一併隱藏

**Comment by Iris926** [comment]
已驗證無誤。
