### ISSUE TITLE
[店內點餐][銅盤] 使用7吋平板，豎屏點餐，則口味tag會顯示在數量下方、上下排列

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#939]
[Scenario]
0. 老闆設定"顯示帳單金額"為否
1. 平板以豎屏顯示/點餐/送出
2. 查看點菜單

[Result] 豎屏顯示，則口味tag會顯示在數量下方，並上下排列

![image](https://cloud.githubusercontent.com/assets/22789907/20167867/4fcc2206-a759-11e6-8670-e55983b65eb9.png)
![image](https://cloud.githubusercontent.com/assets/22789907/20167942/e2b50d9e-a759-11e6-93b0-3f5188659f9e.png)
　　　
[Expected Result] 口味tag顯示在品項名稱下方，並左右排列(目前橫屏顯示已是此行為)
![image](https://cloud.githubusercontent.com/assets/22789907/20167871/54628a1c-a759-11e6-8652-0de51151906b.png)
![image](https://cloud.githubusercontent.com/assets/22789907/20167971/05e9d3c6-a75a-11e6-943d-7bb3a332c603.png)

**Comment by huangVic** [comment]
已修正跑板問題

![default](https://cloud.githubusercontent.com/assets/5910437/20168593/ff787b88-a75d-11e6-8b37-d4e57af9643f.png)

**Comment by Iris926** [comment]
已驗證無誤。
