### ISSUE TITLE
[店內點餐][銅盤] 帳單明細的標題列，建議與下方清單一樣寬

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#940]
[Scenario]
0. 老闆設定 "顯示購買清單=是"
1. 客人成功送出點菜單
2. 客人點擊帳單明細icon

[Result] 帳單明細的標題列，左右稍短
[Expected Result] 標題列也跟下方清單一樣寬
![001](https://cloud.githubusercontent.com/assets/22789907/20169215/2e9b7dc2-a761-11e6-9c21-75a77907fd32.png)
![002](https://cloud.githubusercontent.com/assets/22789907/20169216/2e9c5170-a761-11e6-9516-abe4c5ae5f31.png)

**Comment by huangVic** [comment]
已修正

**Comment by Iris926** [comment]
已驗證無誤。
