### ISSUE TITLE
[店內點餐] 請協助提供"可模擬尖峰時刻大量使用"的自動測試

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#942]

**Comment by gameflierHao** [comment]
餐廳系統 壓力測試
測試環境
![image](https://cloud.githubusercontent.com/assets/1106733/20549927/8d52a07a-b16b-11e6-8dc5-21e3a565367a.png)

測試動作
取得開桌資料 每100-300ms 15台
取菜單資料流程 每300-1000ms 10台
點餐裝置每300-1000ms 送出六樣餐點 5台
裝置短暫斷線後(3S)續連 (OK)

持續時間24小時

結果 : 通過


![20161123121021](https://cloud.githubusercontent.com/assets/1106733/20550924/ddef18e2-b175-11e6-8464-4a9fff7b2f20.jpg)
![6fdca91f42ed843caeca872618478afd](https://cloud.githubusercontent.com/assets/1106733/20550925/e0b64e24-b175-11e6-877e-4fd1e7ba55ba.jpg)
