### ISSUE TITLE
[店內點餐][銅盤] 當要送單時 POS當掉  連按送出  當POS恢復時 不會跳出點餐成功或是失敗

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#944]

**Comment by gameflierHao** [comment]
POSMenu FIFO 在 init時 要清空

Menu會擋不可以連續送出

當發生POS資料等候時間發生 timeout(15S)

會去清空 POSMenu FIFO

**Comment by Iris926** [comment]
已驗證無誤。
1. 送出點菜單前，POS斷線
2. 送出點菜單(如果是mobile就要進入輸入桌號的popup)
3. POS重新連線，再次送出點菜單(mobile則是在輸入桌號的popup按確認)=>可成功送出
