### ISSUE TITLE
新版商店介面，沒有地方可看到商店id

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#949]
點目錄區的【管理】後，直接進去編輯商店畫面，跳過原本有id那一頁。

**Comment by cmacma7** [comment]
Fixed on #SVN 1522
You can see store ID at bottom of left-top menu.
You can also share the store by QA code/Line/Facebook by click Share button in the left-top menu

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1522
[Result] Fixed (在左上角MENU可以查看)
