### ISSUE TITLE
老闆可以隱藏Widget或是顯示Widget的功能

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#95]

**Comment by cmacma7** [comment]
This feature will allow user hide prepared widget but do not want to show to users yet. The final solution can be time set to show time.

**Comment by cmacma7** [comment]
need to use optBit in noteinfo to have a hidden bit. If hidden bit is 1, the note will be hidden. update optbit of a note will cause station been touched, and a hideNote message will broadcast out.

**Comment by cmacma7** [comment]
Done is version 662
