### ISSUE TITLE
[店內點餐][銅盤] 客戶滿意度調查表的頁面，title名稱應統一

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#954]
[Scenario]
1. 客人點進 客戶滿意度調查表
2. header & title的名稱不一致，建議都要改成 "客戶滿意度調查表"
![image](https://cloud.githubusercontent.com/assets/22789907/20260155/5ac22a06-aa93-11e6-9ab6-5f3d79c1721c.png)

**Comment by gameflierHao** [comment]
"滿意度調查表" 是頁面名稱 使用者可以自己修改
"顧客意度調查表" 是WIDGET CONTEXT 使用者也可以任意修改

**Comment by Iris926** [comment]
這屬於可修改的內容，不需修正。
