### ISSUE TITLE
[新版商店介面] 編輯商品分類表，會讓購物車設定返回預設值(反之也會發生)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#958]
[Scenario]
1. 老闆已編輯過商品分類表
2. 老闆至左上MENU 管理/設定購物車/訂單狀態設定(統一設定處)/編輯/建立
3. 回到商品，查看商品分類表 =>直接回復為預設值(NG)

4. 再次編輯商品分類表
5. 至左上MENU 管理/設定購物車/訂單狀態設定(統一設定處) =>直接回復為預設值(NG)

**Comment by cmacma7** [comment]
Fixed in version 1537
problem caused by we always clean up the shoppingCarInfo before save to it, so clean up each other if save one.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
