### ISSUE TITLE
[預約訂位][十一街] 客人填寫資料的格式，需與外帶點餐一致(移除信箱、地址)

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#959]
[Scenario]
1. 客人至 十一街/訂位預約/輸入人數&選擇時段
2. 填寫個人資料
![image](https://cloud.githubusercontent.com/assets/22789907/20292182/8502ea4c-ab26-11e6-9233-eee44c35ef1d.png)

　　　
　　　
[Expected Result] 格式需與"外帶點餐"一樣
![image](https://cloud.githubusercontent.com/assets/22789907/20292191/97e1a04a-ab26-11e6-8c5b-ce9feb401028.png)

**Comment by cyen1121** [comment]
已修正上bn store

統一表格填寫樣式

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
