### ISSUE TITLE
[預約訂位][十一街] 在填寫個人資料的popup點XX，該訂位額度仍被計數

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#960]
[Scenario]
1. 客人至 十一街/訂位預約/輸入人數&選取時段/在popup填寫個人資料
2. 在填寫個人資料的popup按XX
3. 重新搜尋可定位時段

[Result] 該訂位額度已經被計數
[Expected Result] 成功送出個人資料後，才算是真正訂位成功(用掉訂位額度)

**Comment by cyen1121** [comment]
bn store已修正
如果取消則會將位置釋放出來

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1537
[Result] Fixed
