### ISSUE TITLE
[新版商店介面][匯入FB社團文章] 新版商店的店主已沒有page概念，需移除"選擇匯入頁面"的項目

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#961]
[Scenario]
1. 老闆已建立一家新版商店
2. 老闆進入商店/左上MENU/Scan FB/右上管理/匯入Facebook社團文章
3. 選擇社團、日期/點 匯入

![image](https://cloud.githubusercontent.com/assets/22789907/20298260/d5e79056-ab4f-11e6-8915-d6f06aca877a.png)
　　　

**[Expected Result]  新版商店，不需"選擇匯入頁面"的項目**

**Comment by cmacma7** [comment]
Use global.inECMode can detect whether it is the new EC page. 
But I think we still need the page selection because even inside EC mode, user can still have pages. That means, in EC mode, user can choose "not to have a page"

**Comment by peichingliao** [comment]
r.1540已修正
bn已更新，store尚未更新

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed
![image](https://cloud.githubusercontent.com/assets/22789907/20417167/7b3b759c-ad7e-11e6-812c-0f8c00e26fb0.png)
