### ISSUE TITLE
[新版商店介面] 開啟"消費紀錄"後，會看不到店號

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#964]
[Scenario]
1. 至 左上MENU/管理/設定購物車/勾選 顯示購物紀錄
2. 回到新版商店/左上MENU

[Result] 當分頁較多的時候，店號會被消費紀錄擋住
![image](https://cloud.githubusercontent.com/assets/22789907/20332664/5cc7ebaa-abe8-11e6-8bfa-0fa677cb51c5.png)

**Comment by cmacma7** [comment]
fixed by add padding bottom 60px. 
fix in BN. version 1549.2

**Comment by Iris926** [comment]
[Test Site] bn
[Result] FIxed

![image](https://cloud.githubusercontent.com/assets/22789907/20399083/a0482154-ad2a-11e6-86e3-95d63f26abd7.png)
