### ISSUE TITLE
[iOS app] 訂閱"本丸麻麻"並購買商品，則訂單狀態改變時，有時會收不到推播

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#968]
[Scenario]
1. 訂閱"本丸麻麻"/購買商品/成立訂單/將app退至背景
2. 店主修改訂單狀態

[Result] 有一段時間都收不到推播；但過不到半小時，就可以正常收到推播了

**Comment by gameflierHao** [comment]
目前發現一個狀況
在APP內 使用FB登入後
導回的uri會失去cordova=X_X
因此會無法使用推播功能

不過這個狀況再使用者關閉APP
下次在啟動時就會恢復正常(因為已經登入)

老馬會將isphonegap的判斷利用localstorage存下來
避免FB導回後 無法判斷是APP

**Comment by gameflierHao** [comment]
登入後
第一次 call gotStationsForGroup 時
因為 sns push notification 還沒有 init 完成
因此沒有call subscribe channel

**Comment by gameflierHao** [comment]
已修正
store v1.1.1786

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1788.2
[Result] 下載APP後第一次登入/APP背景執行/老闆修改訂單狀態=>客人可以收到推播
