### ISSUE TITLE
[Android app][iOS app] A帳號從手機登出後，還是能繼續收到推播

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#974]
[Scenario]
1. 從android/iOS app登出
2. 背景移除app
3. 發推播給A帳號

[Result] 手機可收到推播
[Expected Result] 登出後，不應再收到推播

**Comment by gameflierHao** [comment]
修正推播問題無法收到後
無法重現問題

[iOS app] 訂閱"本丸麻麻"並購買商品，則訂單狀態改變時，有時會收不到推播 #968 fixed
