### ISSUE TITLE
[Service][HTTPS] single widget share url is incorrect

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#977]
https模式下
single widget share url's  protocol should be https, not http

**Comment by cmacma7** [comment]
Fixed on version 1.1.1607.20. On bn and store/debug.  Service.tagfans.com need to update to latest version.

**Comment by cmacma7** [comment]
You can verify on https://store.tagfans.com/debug/index.html

**Comment by peichingliao** [comment]
store (1894) 驗証OK
