### ISSUE TITLE
[導覽商店] handleWatchStation跳轉商店之後，無法返回原先的導覽商店

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#979]
handleWatchStation跳轉商店之後，無法返回原先的導覽商店
需特殊處理導覽商店case

**Comment by cmacma7** [comment]
Fixed in version 1549.1.
Please use lockstore=1 in URL to lock the initial store. As the result, when it jump to other store and back, the original store will show.

**Comment by peichingliao** [comment]
fixed
