### ISSUE TITLE
[新版商店介面] 點擊single tag url後，回到自己商店編輯商品，再回tagfans首頁，造成頁面錯亂

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#983]
[Scenario]
1. 老闆已登入tagfans
2. 點擊別店的商品連結，ex. http://store.tagfans.com/node/fb.html?noteId=1081253_x_221
3. 點左上"瀏覽更多"/再點左上MENU/點tagfans首頁
4. 進入自己的商店/右上MENU任選一tag/任選一商品進編輯/取消編輯
5. 左上MENU/點tagfans首頁

[Result] 又回到步驟2的商品頁
[Expected Result] 應回到tagfans首頁

**Comment by cmacma7** [comment]
problem caused by history.go() go to the wrong steps.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
