### ISSUE TITLE
[新版商品介面][updateWidgetContext 被cache住] 發布商品到FB並勾選機器人留言，但沒有成功被寫入

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#985]
[Scenario]
1. 老闆在新板商店建立商品
2. 點進商品頁，點選左上角的"發佈商品到facebook"btn
3. 這兩個選項都打勾：啟用機器人留言(Tagfans Sync) [?] /  啟用Tagfans Easy+留言自動成立訂單 [?]
4. 再次點擊商品入口，打開商品頁 =>"發佈商品到facebook"btn文字是白色(NG)
5. 點擊"發佈商品到facebook"btn，進入查看 =>啟用機器人留言(Tagfans Sync) [?] 沒有勾選(NG)

**Comment by cmacma7** [comment]
The bug has fixed in version 1549.1 , svn 1550.
It is cause by the note updateWidgetContext does not update the version of the note.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1550
[Result] Fixed
