### ISSUE TITLE
[新版商品介面][tag] 輸入有關 ㄝ 的tag，還沒輸入完就變成藍色tag

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#986]
[Scenario]
1. 編輯商品，輸入tag：
欲輸入"鞋"，則會變成 ㄒ一ㄝ
欲輸入"專業"，則會變成 專一ㄝ
![image](https://cloud.githubusercontent.com/assets/22789907/20380442/0bb91afe-acdd-11e6-8d4a-02a24afe24a9.png)

**Comment by peichingliao** [comment]
r.1544
移除逗號分隔tag功能 (僅能enter分隔)
