### ISSUE TITLE
[新版商店介面] 在商店裡操作，有時會遇到 Error Loading Page 的訊息

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#987]
[目前較容易看到此訊息的操作]
1. 進入此tag畫面：http://store.tagfans.com/#page_join?o=3842&tag=%E5%AF%B6%E5%AF%B6%E8%A1%A3%E9%A3%BE_$%E9%9E%8B/%E8%A5%AA&viewType=station&mode=ec
2. 點擊商品後再退出
3. 開啟console看到的訊息：
![image](https://cloud.githubusercontent.com/assets/22789907/20380545/b4a096ec-acdd-11e6-9f5a-d84eb6af970e.png)

![image](https://cloud.githubusercontent.com/assets/22789907/20380546/b8991f80-acdd-11e6-9c3e-199e70c37d8e.png)

**Comment by cmacma7** [comment]
jquery mobile bug, so we need to filter the tag again at page_join begin.

**Comment by cmacma7** [comment]
version 1607 and after is fixed.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1759
[Result] Fixed
