### ISSUE TITLE
[統計總表][下載excel] 建議將"總金額"改成"本頁總計"

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#988]
[Scenario]
1. 老闆進入訂單的統計頁面
2. 點選右上MENU管理/下載。列印/下載本頁商品excel
3. 開啟excel

[Result] "總金額"應改成"本頁總計"(跟統計總表用的詞一樣)
![image](https://cloud.githubusercontent.com/assets/22789907/20382152/8d75eefc-ace5-11e6-8511-77b0582c9e12.png)

![image](https://cloud.githubusercontent.com/assets/22789907/20382281/3356448e-ace6-11e6-8ef4-52bf026aba00.png)

**Comment by cyen1121** [comment]
bn已修正，更改名稱了

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed
