### ISSUE TITLE
[新版商店介面] 需增加 global search 功能

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#989]
[Expected Result] 客人進入新版商店的任一tag下，都可以全站搜尋商品

[目前行為] 僅能搜尋該tag下的商品

**Comment by cmacma7** [comment]
Sure, big search!

**Comment by cmacma7** [comment]
added in version 1607.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1705.2
[Result] Fixed
