### ISSUE TITLE
[新版商店介面] 在tag A裡，新增一個有tag A的商品，則新增完成後，商品沒有即時顯示出來

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#990]
[Scenario]
1. 老闆先從分類表裡，點 tag A =>目前畫面就顯示tag A 的所有商品
2. 新增一個有tag A的商品/建立
3. 畫面回到tag A 的所有商品

[Result] 剛剛建立的商品，沒有即時顯示出來 (畫面refresh後才有)

**Comment by cmacma7** [comment]
Please try version 1549.1 and after. I cannot reproduce.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1550
[Result] cannot reproduce
