### ISSUE TITLE
使用不完整的access token後，造成網頁失效，停留在空白畫面

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#993]
[Test Site] store
[Version] v1.1.1550

[Scenario]
1. 至 設定/進階設定/輸入一組不完整的access token/確定

[Result] 
1. 網頁失效，畫面空白
2. 畫面重整/關掉分頁再重開，還是畫面空白
3. 必須清cache後，網頁才能恢復正常

**Comment by cmacma7** [comment]
Fixed on BN and version 1560. Not put on store yet. Will put on store on next release.
Problem caused by setUid fail without knowing the fail in client side. Now setUid fail will cause client side clean the cache and reload.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1607.2
[Result] Fixed (popup"Wrong AccessToken"，然後回到store.tagfans.com首頁)
