### ISSUE TITLE
Tag system: Tag list，未收錄【編輯分類表】時，裡面新建的tag

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#995]
有些使用者會先到【編輯分類表】功能，建立好分類架構(tag)，再回頭建立商品。
使用者會預期，剛才輸入過的tag，可以在「商品widget建立」時的「tag下拉式選單」找到，但並未找到。

使用者會誤認為: 他建立的分類名稱(tag)，沒有生效==>客服再度增加一次訪問量。

action: 
1. 應該把【編輯分類表】輸入的tag，也加入下拉選單裡。
2. 在【編輯分類表】時，不知道能否也支援auto-complete。這樣可以減少使用者輸入的loading。

**Comment by cmacma7** [comment]
implemented in svn and version 1559

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1559
[Result] Fixed
1. 編輯商品時建立的tag & 編輯分類列表時建立的tag，都會被列入auto complete
2. 編輯分類表時，目前不考慮加上auto complete功能
