### ISSUE TITLE
[分享] 分享頁面/widget，將"複製網址"的部分清空，退出分享功能再進來，該欄位仍是空的

### ISSUE THREAD

**Issue by Iris926** [cmacma7/bn#997]
[Scenario]
1. 至任一頁面or任一widget點"分享"
2. 將"複製網址"的欄位清空，點左上"完成"
3. 再次進入"分享"

[Result] "複製網址"的欄位仍為空白
[Expected Result] 退出分享功能並再次進入，"複製網址"欄位應可恢復顯示

[註] 畫面重整後可恢復正常

![image](https://cloud.githubusercontent.com/assets/22789907/20468080/9e3a2b50-afcd-11e6-9bc0-cf82c60a4955.png)

**Comment by cmacma7** [comment]
Fixed in BN.  wait next release to put on store.
problem is $("#urlShare").text() is not working correctly, should use $("#urlShare").val() to set the text inside textarea tag.

**Comment by Iris926** [comment]
[Test Site] store
[Version] v1.1.1565
[Result] Fixed
